### ISSUE TITLE
Share and ... popup from buttons facing the wrong way!

### ISSUE THREAD

**Issue by LawlyPopz** [FrankerFaceZ/FrankerFaceZ#10]
**Web Browser**: Chrome

**Do you use BetterTTV**: No
**Do you use other Twitch extensions**: BTTV 4 FFZ
**Do you use PrivacyBadger**: No

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: wont help with this issue

**Bug / Idea**: 
![Image of Bug](http://pushzz.xyz/img/33ab9.png)

These buttons should be switched back to the same way the default twitch uses!

`.balloon--up.balloon--right, .balloon--down.balloon--right {
    top: auto;
    /* left: auto; */
    right: 0;
}`

This fixes it but then u also need to do 

`.balloon--up.balloon--right:after, .balloon--down.balloon--right:after {
    top: 100%;
    /* left: 50%; */
    margin-left: 6px;
}`

![Image of Normal Twitch](http://pushzz.xyz/img/4564c.png)

**Steps to Reproduce (if Applicable)**: Just view any channel

**Comment by Lordmau5** [comment]
Can reproduce.

**Comment by LawlyPopz** [comment]
This is what it use to be before the addon which the addond's css messes it up on the lines i posted above
![Image of Bug](http://pushzz.xyz/img/2c5b6.png)
