### ISSUE TITLE
Remove seconds from uptime display

### ISSUE THREAD

**Issue by Zoooook** [FrankerFaceZ/FrankerFaceZ#1002]
**Is your feature request related to a problem? Please describe.**
Stream uptime just started displaying with seconds.

**Describe the solution you'd like**
Only show hours / minutes in uptime

**Describe alternatives you've considered**
Tried to turn off uptime display and just use Twitch's, can't find an option, and Twitch is displaying seconds as well

**Comment by SirStendec** [comment]
The setting already has an option to not show seconds.

**Comment by Zoooook** [comment]
It has that setting for the directory page, not on channel pages, as far as I can tell. If such a setting exists, it doesn't show up when searching the settings for "uptime".
