### ISSUE TITLE
Highlight users with mod comment

### ISSUE THREAD

**Issue by simon-crsshr** [FrankerFaceZ/FrankerFaceZ#1007]
For quick moderating it's really slow to always check if a user already has a mod comment.

It would be nice if the moderators see the users with a mod comment highlighted just like it is with the "New User Highlighter" add-on.

**Comment by SirStendec** [comment]
Not feasible. To determine if a user has any mod comments, you need to run a GQL query. Running a query for every user in chat is excessive.

The `New User Highlighter` add-on is in a unique position, in that it's able to avoid running per-user queries by using the sequential nature of user IDs to identify possible creation dates.
