### ISSUE TITLE
Text permanently stuck on high contrast

### ISSUE THREAD

**Issue by cucco1** [FrankerFaceZ/FrankerFaceZ#101]
**Web Browser**: Google Chrome

**Do you use BetterTTV or other Twitch extensions**: The FFZ Add-On Pack

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: N/A

**Bug / Idea**: The chat text is permanently stuck on high contrast. I've tried playing around with different high contrast settings but no matter what high contrast text stays active. Very minor issue, but it's there.

**Comment by SirStendec** [comment]
I am unable to reproduce this bug at all. Do you still get it? Are you sure you don't have another CSS theme or some other extension that could be causing the issue?

**Comment by SirStendec** [comment]
Still haven't seen any issues like this, nor received any other reports. I'm closing this due to lack of response.
