### ISSUE TITLE
Implement Random PogChamp

### ISSUE THREAD

**Issue by deefdragon** [FrankerFaceZ/FrankerFaceZ#1010]
**Is your feature request related to a problem? Please describe.**
I understand and support the removal of the original PogChamp, however I am disappointed at twitch's choice to set a constant emote over implementing Day9's original replacement Idea, or continuing the daily random emotes. This request is to implement an option to use random emotes for pogChamp again.

**Describe the solution you'd like**
The ability to set pogChamp to one of. 
- Current Emote
- Daily Random
- Each Emote Random

Emotes could be pulled from either the full emote set as fetch-able via the old API, or from FFZ's emote list.

**Additional context**
A best case scenario would be the inclusion of the hover over to show the origin of the emote like other emotes do now.

The emote list (assuming the twitch emote list is used) would likely best be done via pulling the entire set from https://dev.twitch.tv/docs/v5/reference/chat#get-all-chat-emoticons , parsing it, and including the list of emote ids in the extension "hard coded". This means that the endpoint only needs to be checked once instead of requiring every user to do this on their own, stressing twitch's api, and the user's internet connection.

**Comment by SirStendec** [comment]
I don't want to override any global Twitch emotes. That would create inconsistent behavior between different clients, more than add-on emotes already cause. If anything, I would implement emotes that change daily as a FFZ global emote but there are currently no plans for that. There's just a lot of work to do and it's not a high priority.
