### ISSUE TITLE
Emotes do not load images& FFZ sometimes does not load

### ISSUE THREAD

**Issue by robuhde** [FrankerFaceZ/FrankerFaceZ#1011]
Starting about a week or so ago, upon opening a stream, about 85% of the BTTV emotes, some FFZ global emotes, and random twitch emotes do not resolve to images and are only displayed as text in the emote display menu and in chat. Opening the emote menu does sometimes partially resolve it. Refreshing sometimes solves it however it also sometimes runs into the issue of removing stuff like BTTV core entirely so that they aren't shown at all. Refreshing can partially fix this,. Occasionally refreshing causes FFZ to not load what-so-ever and I get Twitch page like it is as if the add-on wasn't installed at all. 

1. Go to any twitch channel
2. Open the emote menu to view enabled/available emotes
2a. See Error that FFZ has not loaded at all
3. See error

**Expected behavior**
Emotes should be loaded on page load, the

https://i.imgur.com/WAEX6ks.png
https://i.imgur.com/KdDiu7S.png
https://i.imgur.com/R5gkDZS.png

**Environment:**
 - Windows 10 Home 20H2 64-bit, build 19042.844, experience pack 120.2212.551.0
 - Firefox Nightly 88.0a1 (2021-03-20) (64-bit)
 - Extensions: FrankerFacez (Addon Core and BTTV HTTPS Everywhere, minerBlock, Old Reddit Redirect, Open image in new tab, Stylus (it does not have a twitch or global style enabled), Twitch Adblock, uBlock Origin

**FFZ Logs - https://pastebin.com/Wri2pv0C
The built-in upload has been "Uploading..." for 5 minutes.

This has only started recently within the past week or so and as of trying this right now I've cleared localStorage, uninstalled, and reinstalled FFZ without restoring my settings and it is still doing both of these things. I had to close firefox and reopen it before to get the logs link above because FFZ encountered an error and would not load the settings menu.

**Comment by SirStendec** [comment]
Please check the Network tab of your browser's developer tools to see which resources are failing to load and why when you have a loading issue. (I assume, since you're using a developer-targeted browser, that you know how.) This sounds more like networking issues. FFZ and BTTV both make use of Cloudflare, so if you're having intermittent connection issues to Cloudflare that would explain things.

**Comment by robuhde** [comment]
I changed my DNS and have not encountered this issue since.
