### ISSUE TITLE
BTTV Gif emotes not working with FFZ AP 

### ISSUE THREAD

**Issue by Ukosrs** [FrankerFaceZ/FrankerFaceZ#1012]
Please submit bugs related to add-ons to the repository:
Since of today any of the bttv gif emotes don't work unless I uninstall FFZ-AP. Its not a problem with bttv setting as I tried everything. And also if I uninstall FFZ-AP I don't see bttv emotes anymore (I have bttv and ffz installed).  Maybe I'm just stupid and don't know how to fix it

**Comment by Ukosrs** [comment]
I think its more of a bttv emotes add on thing then ffz ap it self.

**Comment by Lordmau5** [comment]
There was a new change in FFZ to animated emotes.

You now have to enable this specific setting to see them:
![image](https://user-images.githubusercontent.com/1345036/111904656-48e24980-8a48-11eb-8f4c-89f2c93563cc.png)

**Comment by Ukosrs** [comment]
oh, well then. never realized to just type animated emotes

**Comment by Lordmau5** [comment]
The change is relatively new, a bit over 12h old from what I can tell, so it would make sense that not many people are aware of it yet 😁
