### ISSUE TITLE
Case Sensitive for Filtering > Blocked > Terms doesn't work

### ISSUE THREAD

**Issue by guniu** [FrankerFaceZ/FrankerFaceZ#1013]
**Describe the bug**
Case Sensitive setting for Filtering > Block > Terms doesn't work as it should. It filters both, lower case and upper case.
(It does work for Highlight > Terms though)

**To Reproduce**
1. Go to Filtering > Block and add a new Term "Test" with Case Sensitive enabled ("Aa" button)
2. Go to Filtering > General > Behavior and enable "Filter your own messages."
3. Go to your channel and type the term with different casings, eg. "test", "TEST", "Test", etc.
4. Notice they all get blocked.

**Expected behavior**
With above example, only term "Test" should be blocked.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Version: 89
 - FFZ Version 4.20.83 a8b28b2
 - Other Extensions: BetterTTV, uBlock Origin

**Comment by SirStendec** [comment]
Fixed in 1cdff0ec6755c3a8d6f2530bfd9afce659324bb7
