### ISSUE TITLE
Post compressor volume control

### ISSUE THREAD

**Issue by 3941** [FrankerFaceZ/FrankerFaceZ#1022]
While the player volume control is a nice way to control the input levels for the compressor (which basically allows you to adjust the dynamic range), you don't have any way to control the output levels.
Ideally I'd like to see an additional slider, maybe to the right of the compressor on/off switch.

So far I've resorted to controlling the browser volume in the Windows mixer, which isn't fun when you use it to watch anything else but Twitch.

**Comment by SirStendec** [comment]
Sounds like a browser bug to me. What browser are you using? (Also, this is why you should fill out issue templates to an extent.)

**Comment by 3941** [comment]
What exactly sounds like a bug to you?
Seems like extended behavior to me, unless you're saying the player volume control is supposed to change to control compressor output levels? It doesn't. I've tested that in several browsers. I use Edge, but it's the same on Chrome or Firefox.

Granted, I'm running pretty extreme compressor settings, which will make it a lot more noticeable that the player volume controls input, not output levels.

Threshold -45, Knee 1, Ratio 20, Attack 0, Release 0.1

Give that a try and you'll see.

**Comment by SirStendec** [comment]
It makes more sense now. I've never encountered someone with such extreme settings, and more moderate settings maintain the behavior of the volume slider to a large degree.

A second volume slider controlling a gain node would probably be the best solution. No ETA on when one might be added.

**Comment by 3941** [comment]
Yeah I use those to tame the all over the place dynamics of GTARP streams, where every player has potentially different volume levels to begin with, and where distance also affects volume. I just like to be able to understand as many people in any given scene as possible.

Thanks for considering my proposal! 🥰

**Comment by SirStendec** [comment]
This is implemented as of b3c3c8130d515c259c57d255c4d679fa009d042c
