### ISSUE TITLE
FFZ blocks uBlock filter for chat

### ISSUE THREAD

**Issue by Osahashi** [FrankerFaceZ/FrankerFaceZ#1023]
I want to remove the ":" after the usernames in chat and leave a space between the username and message, the code works but FFZ blocks it. 

```
twitch.tv##[data-test-selector="chat-message-separator"]
twitch.tv##.chat-line__username-container:style(padding-right:5px!important;)
```

The code only works with FFZ deactivated in the main window, and it works in pop out chat with FFZ active (I guess because FFZ not working in pop out?) 

Why and what blocks the uBlock filter? Can I do something?

**Comment by SirStendec** [comment]
FrankerFaceZ changes how chat is rendered. You can still use a uBlock rule, but you'll need to change the rule.
