### ISSUE TITLE
Improve workarounds for #763 Playback Speed Not Working on Firefox

### ISSUE THREAD

**Issue by hoffmc3** [FrankerFaceZ/FrankerFaceZ#1024]
**Is your feature request related to a problem? Please describe.**
#763 describes an issue in which playback speed on VODs does not work when using the audio compressor on Firefox.  I understand that this cannot be fixed by FFZ.  However, as a user that would like to use the compressor and also watches VODs with playback speed increased (on Firefox), I would like to propose some alternate solutions to this issue.

**Describe alternatives you've considered**
Right now, the only way I can use both these features is to keep the compressor off by default.  This means I need to toggle it on every single time I load a livestream or VOD that I don't intend to speed up.

If I try to keep in on by default, I cannot toggle it off and adjust playback speed on a VOD.  The speed does not change when toggled off, and if I refresh the player or browser, the compressor turns back on.  

**Describe the solution you'd like**
I propose 3 solutions:

1. When the compressor is toggled off, refresh the player (or the audio component) so that playback speed will then begin to work immediately.  Alternately, if a user adjusts playback speed on a VOD (and the browser is identified as Firefox), disable the compressor + refresh automatically.
2. If that is not possible / too much work, I propose that the compressor toggled setting is maintained when the player is refreshed.  Right now, it toggles back to the default on both live and VODs.  This way, users can keep it on by default and toggle it off manually, refresh, and change playback speed when needed.
3. If that is still not possible, please provide an option in the settings to disable the compressor by default only on VODs, while leaving it on for livestreams.

Thanks!

**Comment by hoffmc3** [comment]
Thank you for the quick fix!

**Comment by DragRedSim** [comment]
The underlying browser bug discussed in #763 was fixed with the release of Firefox 91, so that it is no longer necessary to have a workaround for VODs to allow the use of both the compressor and playback speed.
