### ISSUE TITLE
Chat identity button

### ISSUE THREAD

**Issue by halarus** [FrankerFaceZ/FrankerFaceZ#1025]
Previously there was an option in the experiments to hide that annoying identity button in the chat input box.
Not so long ago it seem to have disappeared.
Am I missing something here?

**Comment by Lego6245** [comment]
Concur. Tried a couple of experiments but none of them seemed to get rid of it. As mentioned in #986 this would be considered for implementation when the experiment went way, so hopefully this means it'll get picked up :)

**Comment by halarus** [comment]
@Lego6245 Saw your comment on the closed issue and I thought I'd make a new one.

**Comment by halarus** [comment]
@SirStendec thank you 🙏
