### ISSUE TITLE
DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'FFZ:setting:p:0:chat.filtering.highlight-basic-blocked' exceeded the quota.

### ISSUE THREAD

**Issue by vibosxD** [FrankerFaceZ/FrankerFaceZ#1026]
**Describe the bug**
Cannot restore settings with many blocked message filters (250106 length).

**To Reproduce**
1. Restore backup with a large amount of message filters via: `p:0:chat.filtering.highlight-basic-blocked`

**Expected behavior**
Permit this action?

**Screenshots**
None
**Environment (please complete the following information):**
 - OS:  Windows
 - Browser chrome
 - Version 89.0.4389.128 (Official Build) (64-bit)
 - Other Extensions: [BetterTTV, Privacy Badger, AdBlock]

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:

**Additional context**

**Comment by SirStendec** [comment]
You have too much in your local storage. Please switch to a different settings provider (IndexedDB specifically) in Data Management > Storage >> Provider.

There's nothing I can do about the localStorage quota. I do have plans to better alert users when their quota is used up, but not sure when that'll be arriving and it still doesn't prevent the quota being an issue in the first place.
