### ISSUE TITLE
FFZ Supporter badge not dislayed on chat

### ISSUE THREAD

**Issue by CauzYolo** [FrankerFaceZ/FrankerFaceZ#1032]
The FFZ Supporter badge is not dislayed on chat.
The developper console report a 404 not found.

**Screenshots**

![image](https://user-images.githubusercontent.com/10593700/116001552-42219600-a5f5-11eb-828c-e3dcc2172506.png)

**Environment (please complete the following information):**
 - OS: Windows
 - Browser Mozilla Firefox
 - Version  88.0

**Comment by SirStendec** [comment]
Resolved in 2f41f520af3fad08cea4415ae4e50389239e7e0a
