### ISSUE TITLE
Automatically use highest avaiable video quality / source

### ISSUE THREAD

**Issue by darthphallus** [FrankerFaceZ/FrankerFaceZ#1034]
**Is your feature request related to a problem? Please describe.**Occasionally my streams will switch to a lower quality if I have not been on the page for a while. I have to manually go to Settings>Video Quality>Highest Quality/Source, close, close

**Describe the solution you'd like**
A setting to force player behaviour to select the highest available or source quality option

**Describe alternatives you've considered**
Tried to use the Auto quality feature but it defaults to 480p when not in focus. 

**Additional context**
![image_2021-05-04_141545](https://user-images.githubusercontent.com/43572890/117009020-3748be80-ace3-11eb-9d7e-3b1d6a366716.png)

**Comment by SirStendec** [comment]
Twitch reduces the video quality when you aren't watching to save bandwidth. There is a legitimate reason. Not dealing with this.
