### ISSUE TITLE
Potential memory leak/bug

### ISSUE THREAD

**Issue by ItMeSarah** [FrankerFaceZ/FrankerFaceZ#1037]
**Describe the bug**
Twitch randomly skyrocketing to 2.5-3.5 gig of ram from 400-450 mb of ram with FFZ enabled.

**To Reproduce**
1. Go to 'twitch
2. Click on a channel
3. wait a few minutes and it will skyrocket to 2.5 gig of ram and freeze that entire page, no other pages affected, and only happens with FFZ enabled. 

**Expected behavior**
Expect it to not freeze and die. 

**Screenshots**
Chrome task manager where it says it's using 104+% of the cpu??: https://i.imgur.com/ZW2ZFS7.png

Windows task manager where it says it's using 2.6 gig of ram+: before https://i.imgur.com/WL6WzaK.png After https://i.imgur.com/1ZOCXk1.png

**Environment (please complete the following information):**
 - OS: Windows 10.
 - Browser Chrome
  - Version  90.0.4430.212 
 - Other Extensions: a few but I have disabled them all to test if it was just FFZ and it is.

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**: Cannot get it because FFZ just freezes with twitch. and it shows normal things upon getting a new tab with twitch loaded cause I have to close the entire tab when it freezes, cannot reload.

**Comment by SirStendec** [comment]
Could you please export your FFZ settings (Control Center. Data Management > Backup and Restore) and attach them to this issue?

**Comment by ItMeSarah** [comment]
> Could you please export your FFZ settings (Control Center. Data Management > Backup and Restore) and attach them to this issue?

Sure, 
[ffz-settings.txt](https://github.com/FrankerFaceZ/FrankerFaceZ/files/6496725/ffz-settings.txt)

Also now today it's showing the things you usually see when you hover over the ffz icons like this 
![image](https://user-images.githubusercontent.com/67713330/118552550-b34ff700-b724-11eb-832d-057981a2bc3d.png)
 with no way to get rid of them

**Comment by ItMeSarah** [comment]
> I think it's the same for Firefox, my twitch tab freeze, ram going to 100%. It happens for few days now.
> ![image](https://user-images.githubusercontent.com/23707269/118939789-5b95d380-b950-11eb-9c27-ca46b3d2d341.png)
> 
> Look like it's random, sometimes i get freeze every 10min, sometime after few hours.

Exactly this, sometimes 1-10 minutes, sometimes a few hours.

**Comment by ItMeSarah** [comment]
Seems like this is all resolved now, for me.

**Comment by ItMeSarah** [comment]
Prematurely closed, since it's still happening, just not as often.
