### ISSUE TITLE
Kaspersky AV hates this url for some reason

### ISSUE THREAD

**Issue by OmegaBlurz** [FrankerFaceZ/FrankerFaceZ#1039]
see here: https://i.imgur.com/0lheNI1.png

**Comment by OmegaBlurz** [comment]
https://i.imgur.com/jxZtFtJ.png this too

**Comment by OmegaBlurz** [comment]
and yes both of these have already been added to exclusions before

**Comment by SirStendec** [comment]
Those server are having networking issues that lead to connections failing. Without Kaspersky, visiting one of those URLs would show something like this:
![image](https://user-images.githubusercontent.com/14036657/118541361-949b3180-b71f-11eb-9cd2-7cf310ff4429.png)

Your antivirus software is handling the situation badly, and we have no control over that failing.

You can disable the behavior that tries connecting to the pubsub edge by opening the FrankerFaceZ Control Center, going to `Debugging > Socket` at the bottom, and changing the Server Cluster to `Disabled`.
