### ISSUE TITLE
Tooltips always showing as text in player and site

### ISSUE THREAD

**Issue by plastic-fork** [FrankerFaceZ/FrankerFaceZ#1040]
**Describe the bug**
Some tooltips seem to always show as text in the player and on the site.

**To Reproduce**
No clue, just started happening since the newest update, happens on all my browsers.

**Expected behavior**
That text to not show

**Screenshots**
https://i.imgur.com/i9YblKH.jpg
Marked it with red squares

**Environment (please complete the following information):**
 - OS: Pop!_Os 20.10 (linux, based on ubuntu)
 - Browser Brave
 - Version 1.24.85
 - Other Extensions: None
 
Happens on firefox 88.0.1 aswell.

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:
https://pastebin.com/DwTrDLzG

**Additional context**
Happened after latest update.

**Comment by joshuax8** [comment]
I'm also facing this problem on Windows 10 (20H2) with Chrome 90.0.4430.212
One thing I noticed is that this also seems to happen with the Twitch Chat Pronounce extension. Maybe something changed over at Twitch which affects both extensions.

**Comment by cbftw** [comment]
Also seeing this issue in Firefox 88.0.1 on Win10 20H2.

**Comment by Stepan-H** [comment]
I have the same problem. 
[https://ibb.co/zbjxp78](url)

**Comment by steffhelbling** [comment]
It seems that Twitch has made some changes affecting tooltips behaviour.
Vivaldi 3.9.2289.3 arm (Chromium 91.0.4472.33), macOS 11.3.1

**Comment by Taizunz** [comment]
It's being worked on.
https://twitter.com/SirStendec/status/1394386384207687683

**Comment by SirStendec** [comment]
Fixed in 89941d2ee5b48c4af35cb34d087d73736b62a4f9
