### ISSUE TITLE
Gain Control Slider appears to be broken on Firefox

### ISSUE THREAD

**Issue by DoraTheExploder** [FrankerFaceZ/FrankerFaceZ#1041]
**Describe the bug**
The gain control slider that replaces the volume slider if Audio Compression is enabled and the option is set to do so appears to have had some change made approx. two days ago that caused the feature to stop working. What caused me to notice the issue is that it is no longer themed along with the rest of the controls but instead is using the browser default aesthetic for a sliding control. After attempting to adjust the gain control either direction it appears to have no effect whilst held, additionally it automatically returns to the 100% (default) position after releasing the control.

**To Reproduce**
1. Open any livestream with the Gain Control option enabled.
2. Notice the missing aesthetic match (cause of suspicion)
3. Attempt to adjust the gain control in either direction.
4. See bug description

**Expected behavior**
Expected behavior would be for the slider to be themed along with the rest of the controls (of minor importance) and for it to adjust the gain value of the audio compressor (this would, in effect, adjust the overall volume of the stream audio).

**Screenshots**
https://i.imgur.com/m5a9OfH.jpeg

**Environment (please complete the following information):**
 - OS: Windows 10 Home ver. 20H2
 - Browser Firefox 64-bit ver. 88.0.1
 - Version 4.0 (as reported by Firefox)
 - Other Extensions: uBlock Origin, Purple Adblock

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:
N/A

**Comment by SirStendec** [comment]
Released an update today that fixes the styling, and I did tests in Firefox. I was unable to reproduce an issue with the gain control being reset to 100%.

Can you confirm that you're still seeing that issue?

**Comment by DoraTheExploder** [comment]
Can confirm that the issue seems to be resolved, curious what exactly I did to make it behave like that. I'll re-open if it reoccurs.
