### ISSUE TITLE
Disabled animated emotes don't show in chat

### ISSUE THREAD

**Issue by guniu** [FrankerFaceZ/FrankerFaceZ#1047]
**Describe the bug**
After setting "Animated Emotes" to Disabled the emote doesn't display the still image. It displays a broken icon image plus the emote name. After checking the source link for the emote it turns out the server cache.ffzap.com is timing out for me. It was working fine like 2 days ago.

**Screenshots**
![image](https://user-images.githubusercontent.com/19828894/119395721-3ac4d980-bcd4-11eb-8741-823b6ba762b6.png)

Trying to access cache.ffzap.com:
![image](https://user-images.githubusercontent.com/19828894/119395971-8aa3a080-bcd4-11eb-89a6-07200d5e7f54.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 90.0.4430.212
 - Other Extensions: BetterTTV, uBlock Origin

**Comment by Lordmau5** [comment]
This is due to the FFZ:AP server being offline as of the time being.
It doesn't want to boot up anymore and I've put in a support ticket to my provider to see if they can somehow get it fixed by an on-site technician.
No response yet though...

**Comment by Lordmau5** [comment]
Seeing as the FFZ:AP server is now back up this issue should be resolved.
