### ISSUE TITLE
Highlight User Messages with Viewer Card Open not working

### ISSUE THREAD

**Issue by DoraTheExploder** [FrankerFaceZ/FrankerFaceZ#1048]
**Describe the bug**
Issue is a duplicate of #785 , which was closed in April 2020. It seems that the issue has reoccurred, though I'm not sure when/where the issue was reintroduced.

**To Reproduce**
1. Go to "Chat -> Viewer Cards"
2. Turn on "Highlight Messages from users with open viewer cards"
3. (Optional) Select a non-default highlight color (In my case it seemed that the default color was the same as the default chat background color, so I chose one that was more vibrant.)
4. Open a user card in chat by clicking someone's name
5. See description, refer #785 

**Expected behavior**
When opening a user card, all messages from that user in chat are to be highlighted.

**Screenshots**
None available at this time. An applicable screenshot is accessible in issue #785. Let me know if you'd like me to create a newer image.

**Environment (please complete the following information):**
 - OS: Windows 10 Home ver. 20H2
 - Browser: Firefox 64-bit ver. 88.0.1
 - Version 4.0 (as reported by Firefox)
 - Other Extensions: uBlock Origin, Purple Adblock

**Additional context**
Refer to issue #785 for duplicate issue that was closed previously.

**Comment by DoraTheExploder** [comment]
Also, let me know if you'd prefer to re-open the prior issue and remove this for issue management preference.

**Comment by SirStendec** [comment]
This is working fine for me. Are you using popout chat, moderation chat, dashboard chat, etc?

**Comment by DoraTheExploder** [comment]
Issue appears to have resolved itself after a restart. Not certain what caused the issue, as I was not using any special form of chat except that I was in Theater Mode.
