### ISSUE TITLE
Anonymous chat mode

### ISSUE THREAD

**Issue by alefbeo** [FrankerFaceZ/FrankerFaceZ#1052]
**Is your feature request related to a problem? Please describe.**
I dislike being pinged in chat or being seen as "available" when I simply want to lurk and view a stream sometimes.

**Describe the solution you'd like**
An option to not appear in the viewer list, AKA anonymous mode. Perhaps along with a button or chat command to enable/disable.

**Describe alternatives you've considered**
Although there are other extensions that can achieve the same goal, it would be very nice if it was packaged into FFZ. Anonymous mode would integrate well with the profile & rules feature existing in FFZ. (say you don't want to be in the viewer list when you're in a particular channel, or maybe in the hottub section) 

**Additional context**
The last issue concerning this was closed almost 2 years ago, I hope this feature may be reconsidered as I believe a lot of users would find this useful.

(English is not my native language, please let me know if something can be clarified)

**Comment by Kurzdor** [comment]
Hottub section... dude/
You can use Anon Chat in Better TTV as solution.

**Comment by bottleblue** [comment]
Is there any update on this feature request? I just installed FFZ and don't see an option for anonymous chat. This is the only thing missing from FFZ for me to completely ditch BTTV since it does everything else BTTV can and much more.

**Comment by Lordmau5** [comment]
Closed in favor of #301 (Since that is still the most up-to-date information I have about this feature request)
