### ISSUE TITLE
Badge highlighting: Mod+Bot badges inconsistent

### ISSUE THREAD

**Issue by ReggX** [FrankerFaceZ/FrankerFaceZ#1053]
**Describe the bug**
I have set up badge highlighting in FFZ.
* Bot, Prio 90, Color grey
* Mod, Prio 80, Color green

With this setup, bots should get a less noticable grey message background compared to more noticable green for mods, even if the bots have mod privileges on the channel (Nightbot, etc.)

This usually works, but sometimes it doesn't.

**To Reproduce**
Encountered on Twitch channel https://www.twitch.tv/leonbratt with the two bots @FriendlyMusician @Fossabot (both have combined Mod+Bot badges), but Fossabot is highlighted grey while FriendlyMusician is highlighted green.

**Expected behavior**
Both bots should be highlighted grey.

**Screenshots**
![image](https://user-images.githubusercontent.com/1953510/120906847-229e7400-c65d-11eb-80e9-fc2904f837ea.png)

**Environment (please complete the following information):**
 - OS: Windows 10 2004
 - Browser Google Chrome
 - Version 91.0.4472.77

**Comment by SirStendec** [comment]
Fixed in 2a57ecb8a730c1cff018bdf3684014065cfec388
