### ISSUE TITLE
Highlight for badges only work if badge is visible

### ISSUE THREAD

**Issue by flonou** [FrankerFaceZ/FrankerFaceZ#1058]
for example, if I set a highlight color for VIPs, if they do not show their badge (maybe because another badge has taken priority), the highlight is not working.
I understand it's not a "role" highlight, but I would exepect it to work as such

**Comment by SirStendec** [comment]
It would not and does not work that way.

Clients do not receive information for badges that are not visible. FrankerFaceZ cannot highlight users based on badges they have that are not visible.
