### ISSUE TITLE
Twitch animated emotes toggle is ignored

### ISSUE THREAD

**Issue by codl** [FrankerFaceZ/FrankerFaceZ#1064]
**Is your feature request related to a problem? Please describe.**
Twitch chat settings have a toggle for animated emotes now, but it is ignored when FFZ is running, which is confusing. Only the similar setting inside of FFZ is respected.

**Describe the solution you'd like**
Would be neat if that option took you to the FFZ setting for animated emotes.

**Describe alternatives you've considered**
The setting in FFZ could have a "Use twitch setting" default like pause chat does, though that would mean the FFZ exclusive option to animate emotes on hover would be less discoverable.

**Comment by codl** [comment]
...why was this closed?

**Comment by SirStendec** [comment]
Because it was fixed.

**Comment by codl** [comment]
Oh I see now, I didn't notice because it only gets taken into account on a reload. Thanks!
