### ISSUE TITLE
Hiding thumbnail: more styles

### ISSUE THREAD

**Issue by robbai** [FrankerFaceZ/FrankerFaceZ#1075]
**Is your feature request related to a problem? Please describe.**
Thumbnail hiding styles only allows for hiding of the thumbnail, and title.

**Describe the solution you'd like**
Allow the user to blur the profile picture, username, category, tags, stream uptime, live badge, and viewer count.

**Describe alternatives you've considered**
Allow blurring of the entire entry.

**Additional context**
Replace the dropdown with checkboxes for each of these options.

Thanks

**Comment by SirStendec** [comment]
The point of hiding the thumbnail and the title is to block spoilers while still showing you that the person is live and broadcasting in a category.

Hiding the other information would just make the entry a waste of space, and better hid entirely. Not interested in implementing this.
