### ISSUE TITLE
[Feature Request] Please give us the ability to completely hide the entire "Engage your community with panel extensions" section when you are editing the panels, by using a FrankerFaceZ toggle option.  (see picture)  Thank you.

### ISSUE THREAD

**Issue by idgas01** [FrankerFaceZ/FrankerFaceZ#1087]
![Panel Extensions](https://user-images.githubusercontent.com/75463665/127380596-f654ea9c-a45a-4e65-a646-4b1879bdb334.png)

I tried accomplishing this by creating my own userscript, but the div class name keeps changing.  Right now, it is div.gIjbiC.  But last week it was something else.  I had tried div.channel-panels > div:nth-class(2) > div:nth-class(1), but it didn't work for some reason.

**Comment by SirStendec** [comment]
Looked into this. As you pointed out, there is no stable class name for matching this element because of Twitch's growing reliance on styled-components.

I won't be adding this. The complexity is too high for something that you don't see unless you're editing your panels.
