### ISSUE TITLE
Display Subscriber Loyalty Badges "Off Switch" doesn't work

### ISSUE THREAD

**Issue by Rmac524** [FrankerFaceZ/FrankerFaceZ#109]
**Web Browser**:
Chrome 54.0.2840.99 (64-bit)
**Do you use BetterTTV or other Twitch extensions**:
just ffz
**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:
http://putco.de/NTU0Mw.log

**Bug / Idea**:
Display Subscriber Loyalty Badges "Off Switch" doesn't work

**Steps to Reproduce (if Applicable)**:
just turn the setting off

**Comment by SirStendec** [comment]
I can't reproduce the problem. Can you right click a badge in chat with the feature on, click Inspect, and show me what it shows you?

(Here's an example of what I see for reference...)
![image](https://cloud.githubusercontent.com/assets/14036657/23337235/171b8244-fbb4-11e6-9458-6ede711b56c4.png)

**Comment by SirStendec** [comment]
I'm assuming from the lack of further correspondence that this was a one time issue and isn't happening anymore. Closed.
