### ISSUE TITLE
Toggleable bio panel extension iframes

### ISSUE THREAD

**Issue by int22** [FrankerFaceZ/FrankerFaceZ#1091]
**Is your feature request related to a problem? Please describe.**
Trolls and malicious actors have been using harvest user information when you visit their channel.

**Describe the solution you'd like**
Add a toggleable setting to block/show iframes so they don't load? Possible blacklist for extensions?

**Describe alternatives you've considered**
I've tried userscripts, noscript extension, and blocking domains in HOSTS file.

**Additional context**
Sketchy people go around mass following streamers to generate traffic to their own channel to harvest viewer information through player extensions and/or bio panels.

**Comment by SirStendec** [comment]
FrankerFaceZ is not able to reliably block extensions from loading due to the order in which it's loaded into the page. Please use an adblocker to block extensions you don't like. Also please send feedback to Twitch asking for more user control over extensions.
