### ISSUE TITLE
[Feature Request] Tab Completion Emote Priority

### ISSUE THREAD

**Issue by NickAbc423** [FrankerFaceZ/FrankerFaceZ#11]
**Web Browser**: Chrome

**Do you use BetterTTV**: Recently started using only FFZ
**Do you use other Twitch extensions**: BTTV 4 FFZ
**Do you use PrivacyBadger**: No

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**: I recently started using FFZ exclusively and it bothered me that when using tab completion I would end up sending messages to users instead of using emotes. 
In BTTV there's an option to allow emotes to have priority when using tab completion and I was wondering if it would be possible to implement that into FFZ. 
What you could do is make it so you tag users only when using the @ sign and only use emotes without. 
This is a minor issue but it would be a small quality of life improvement especially for people making the switch from BTTV.

**Steps to Reproduce (if Applicable)**:

**Comment by LawlyPopz** [comment]
> What you could do is make it so you tag users only when using the @ sign and only use emotes without. 

I kind of disagree with this cus then its going back to the default twitch i really like being able to not HAVE to put the @ when i type somones name
