### ISSUE TITLE
Volume control not being hidden when 100% volume force setting is enabled

### ISSUE THREAD

**Issue by PrgmrAtHrt** [FrankerFaceZ/FrankerFaceZ#1100]
**Describe the bug**
When "Force built-in volume to 100% when the audio compressor is enabled." setting is active, the volume control is not being hidden.

**To Reproduce**
1. Open FrankerFaceZ settings
2. Go to Player > Compressor
3. Enable "Force built-in volume to 100% when the audio compressor is enabled." setting

**Expected behavior**
The volume control should be hidden.

**Screenshots**
![Compressor Bug](https://user-images.githubusercontent.com/38510213/129416198-4b34c913-02f2-4c22-be85-3420894d3f08.jpg)
![Compressor Bug 2](https://user-images.githubusercontent.com/38510213/129416205-fd5ccb0b-d7c8-4211-9d9c-af91ee9067bb.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser: Microsoft Edge
 - Version: 92.0.902.73

**Comment by SirStendec** [comment]
Closed by 207fda2b36059d1fe74154280ccb61fe4cf188c5
