### ISSUE TITLE
Notification for thread messages

### ISSUE THREAD

**Issue by nazsol** [FrankerFaceZ/FrankerFaceZ#1101]
Currently the only sound notification is when someone mentions you using @ but never when directly replying to your message as a thread via the arrow icon, i miss a lot of messages because of this.

**Comment by jakb27** [comment]
Hey, 
what do you mean by "notification"? Do you mean that the message, which mentioned you is colored? Because that is working for @ and replies as a thread.  Or is there a special notification-message-setting that i'm missing?

**Comment by nazsol** [comment]
I meant sound notification, i edited my post.

**Comment by jakb27** [comment]
is this sound notification for @-mentions a feature by FrankerFaceZ?

**Comment by nazsol** [comment]
I'm pretty sure that it used to be a feature of FFZ but they seemed to have removed it, maybe because of constant changes by Twitch.

However i did look at the settings from that addon and yes that does allow me to hear a sound for @ as well as threads, thanks for pointing this out to me :)
