### ISSUE TITLE
"Mod View" chat color change

### ISSUE THREAD

**Issue by d3athcricket** [FrankerFaceZ/FrankerFaceZ#1107]
**Describe the bug**
Set custom colors to change the look of twitch to how I liked it in a stream window. Went to mod view later on for a streamer I mod for and the text chat was the wrong color. Under "Theme" I have text color set as #00ff00 and chat text color set as #aaaaaa. This appears correctly in a normal stream view (non mod view) but the text chat color override does not function in mod view, and all of the text chat is showing as #00ff00

**To Reproduce**
1. set text color to #00ff00
2. set chat text color to #aaaaaa
3. confirm correct colors via "normal" stream view
4. enter mod view and see text chat color appearing as wrong color

**Expected behavior**
Expected chat color to stay the same through all views of twitch, standard and mod view

**Screenshots**
![correct](https://user-images.githubusercontent.com/89757544/131275273-637405ee-0e54-45a8-b09c-5cbea5ed5e29.PNG)
![incorrect](https://user-images.githubusercontent.com/89757544/131275274-e6a641b1-b06f-4bec-85c3-68de217203ce.PNG)

**Environment (please complete the following information):**
 - OS: Windows 10 Home
 - Browser Chrome
 - Version 92.0.4515.131 (Official Build)
 - Other Extensions: BetterTTV, AdBlock
 
**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:
initialization
-------------------------------------------------------------------------------
[21:31:57] info | core: FrankerFaceZ v4.28.5 (build 552a00ea69f47d790f46 - commit c1fba86dc93b67566de6ab5a82ca7362999d0ab9) (initial https://www.twitch.tv/moderator/jerhymgames)
[21:31:57] info | site: Using: Twilight
[21:31:57] info | site.web_munch: Found and wrapped webpack's loader after 0ms.
[21:31:57] info | settings: Using Provider: LocalStorageProvider
[21:31:57] info | core: Loaded descriptions of 0 modules.
[21:31:57] info | settings: Initialization complete after 12.10000ms -- Values: 64 -- Profiles: 2
[21:31:57] info | site.fine: Installing MutationObserver.
[21:31:57] info | site.switchboard: Found Route and Switch with 16 routes.
[21:31:57] info | site: Loaded descriptions of 17 modules.
[21:31:57] info | site.elemental: Installing MutationObserver.
[21:31:57] info | site.web_munch: require() grabbed in 248.20000ms.
[21:31:58] info | main_menu: Built Tree in 12.10000ms with 151 structure nodes and 253 settings nodes.
[21:31:58] info | experiments: Loaded information on 2 experiments.
[21:31:58] info | socket: Using Server: wss://lilz.frankerfacez.com/
[21:31:58] info | core: Initialization complete in 573.70000ms.

settings
-------------------------------------------------------------------------------
i18n.debug.capture: false
i18n.format.date: "default"
i18n.format.time: "short"
i18n.format.datetime: "medium"
i18n.debug.transform: null
i18n.locale: "en"
addons.dev.server: false
socket.use-cluster: "Production"
metadata.modview.hide-info: false
layout.side-nav.hide-viewers: false
metadata.uptime: 2
metadata.uptime.no-native: true
metadata.viewers: false
metadata.viewers.no-native: false
layout.swap-sidebars: false
layout.portrait: false
layout.portrait-threshold: 1.25
layout.use-portrait: false
chat.width: null
chat.use-width: false
layout.use-chat-fix: false
layout.theatre-navigation: false
layout.minimal-navigation: false
layout.side-nav.show-avatars: true
layout.side-nav.show: 1
layout.side-nav.hide-offline: true
layout.prime-offers: true
layout.discover: true
channel.hide-unfollow: false
channel.round-avatars: true
channel.hide-live-indicator: false
layout.side-nav.rerun-style: 1
layout.side-nav.show-rec-channels: 1
layout.side-nav.show-friends: 1
whispers.show: true
channel.show-celebrations: true
layout.theme.global-font: ""
layout.portrait-invert: false
layout.portrait-min-chat: false
layout.inject-portrait: false
layout.use-portrait-swapped: false
player.theatre.metadata: false
layout.use-portrait-meta: false
layout.use-portrait-meta-top: false
layout.portrait-extra-width: 24
player.theatre.no-whispers: false
layout.portrait-extra-height: 14
theme.can-dark: true
theme.is-dark: true
theme.color.background: "#000000"
theme.color.text: "#00ff00"
theme.color.accent: "#00ff00"
theme.color.tooltip.background: "#000000"
theme.color.tooltip.text: "#00ff00"
theme.color.chat-background: ""
theme.color.chat-text: "#aaaaaa"
theme.color.chat-accent: "#00ee00"
theme.font.size: 13
directory.show-channel-avatars: undefined
directory.hide-live: false
directory.hidden.reveal: false
directory.hidden.style: 2
channel.panel-tips: false
channel.auto-click-chat: false
player.gain.enable: false
player.gain.no-volume: false
player.volume-always-shown: false
player.ext-interaction: true
player.hide-mouse: true
player.ext-hide: 0
player.captions.font-size: ""
player.captions.font-family: ""
player.compressor.enable: true
player.compressor.shortcut: null
player.no-autoplay: false
player.home.autoplay: true
player.button.pip: true
player.button.reset: true
player.gain.min: 0
player.gain.max: 2
player.compressor.default: false
player.allow-catchup: true
player.hide-event-bar: false
metadata.host-button: true
player.force-visible: undefined
ffz.show-new-settings: true
metadata.featured-follow: true
metadata.player-stats: true
channel.hosting.enable: true
metadata.stream-delay-warning: 0
player.volume-scroll: false
player.gain.scroll: false
player.mute-click: false
player.compressor.threshold: -50
player.compressor.knee: 40
player.compressor.ratio: 12
player.compressor.attack: 0
player.compressor.release: 0.25
ffz.search.matches-only: true
debug.link-resolver.source: null

experiments
-------------------------------------------------------------------------------
Unique ID: ktVIZgUcBXTAP8J2z4jNDWm1tUh9hJPx

FFZ | API-Based Link Lookups: false (r:0.7)
Twitch | stream_manager_new_panels_upsell: control (r:0.05, t:user_id)
Twitch | vx_disco_search_suggestions_v1: control (r:0.25, t:device_id)
Twitch | extensions_installation_optimization: test (r:0.33, t:channel_id, c:jerhymgames)
Twitch | Devsite_create_apps_form_recaptcha: control (r:0.5, t:user_id)
Twitch | VP09 Web: control (r:0.5, t:device_id)
Twitch | bits_top_nav_explanation : experiment (r:0.5, t:user_id)
Twitch | cf_wp_new_onboarding: variant (r:0.5, t:channel_id, c:jerhymgames)
Twitch | gifting_themed_user_notice: experiment (r:0.5, t:channel_id, c:jerhymgames)
Twitch | happening_now_by_user: control (r:0.5, t:user_id)
Twitch | jcb_icon_jp: control (r:0.5, t:user_id)
Twitch | reduce_subs_confusion: control (r:0.5, t:device_id)
Twitch | subs_pif: thank_first (r:0.5, t:user_id)
Twitch | twitch_studio_go_live_social_share: variant (r:0.5, t:user_id)
Twitch | vx_disco_signup_nudge: variant (r:0.5, t:device_id)
Twitch | vx_vert: control (r:0.55, t:device_id)
Twitch | vxp_left_nav_hover_logged_in: control (r:0.75, t:user_id)
Twitch | player_warp: treatment (r:0.9, t:device_id)
Twitch | idplat_randor: variant_1 (r:0.94, t:device_id)
Twitch | bits_card_simplified_cheermote_selection: control (r:0.95, t:user_id)
Twitch | bits_skus_reduction: control (r:0.95, t:user_id)
Twitch | chat_history: control (r:0.95, t:user_id)
Twitch | chat_pause_hover_default: control (r:0.95, t:user_id)
Twitch | expressions_popular_emotes: off (r:0.95, t:user_id)
Twitch | gifting_user_notice_standardization: control (r:0.95, t:user_id)
Twitch | multimonth_evergreen_discount: variant (r:0.95, t:user_id)
Twitch | take_the_leaderboard: TakeTop10Spot (r:0.95, t:user_id)
Twitch | vxp_hide_miniplayer: control (r:0.95, t:device_id)
Twitch | liverecs_holdout_device: control (r:0.98, t:device_id)
Twitch | liverecs_holdout_v2: control (r:0.98, t:user_id)
Twitch | TWILIGHT_CAROUSEL_HOLDBACK: control (r:0.99, t:device_id)
Twitch | community_insights: treatment (r:0.99, t:channel_id, c:jerhymgames)

addons
-------------------------------------------------------------------------------
Known
7tv-emotes | disabled | 7TV v1.1.0
brcm | disabled | brcm v1.0.0
deck | disabled | Deck v1.4.0
ffzap-bttv | disabled | FFZ:AP BTTV v3.2.6
ffzap-core | disabled | FFZ:AP Core v3.3.6
ffzap-liriklive | disabled | FFZ:AP LirikLIVE v3.2.2
fs-chat | disabled | fs-chat v1.4.3
inline-tab-completion | disabled | Inline Tab v1.2.2
ModTools | disabled | Mod Tools v1.0.1
new-account-highlighter | disabled | New Account Highlighter v1.1.1
poll-shim | disabled | poll_shim v0.2.2
pronouns | disabled | pronouns v1.0.2
repetition-detector | disabled | repetition_detector v1.1.0
smokemotes | disabled | smokeys_utils v1.1.3

Modules
loaded   | enabled  | 
loaded   | enabled  | core
loaded   | enabled  | settings
loaded   | enabled  | experiments
loaded   | enabled  | i18n
loaded   | enabled  | socket
loaded   | enabled  | site.web_munch
loaded   | enabled  | site.fine
loaded   | enabled  | site.elemental
loaded   | enabled  | site.router
loaded   | enabled  | site.apollo
loaded   | enabled  | site.twitch_data
loaded   | enabled  | site.switchboard
loaded   | enabled  | site.subpump
loaded   | enabled  | site
loaded   | enabled  | addons
loaded   | enabled  | vue
loaded   | enabled  | tooltips
loaded   | disabled | chat/actions
loaded   | enabled  | chat.badges
loaded   | enabled  | chat.emotes
loaded   | enabled  | chat.emoji
loaded   | enabled  | chat.actions
loaded   | enabled  | chat.overrides
loaded   | enabled  | chat
loaded   | enabled  | main_menu
loaded   | enabled  | metadata
loaded   | enabled  | site.bits_button
loaded   | enabled  | site.bttv_compat
unloaded | disabled | translation_ui
loaded   | enabled  | site.css_tweaks
loaded   | enabled  | site.channel
loaded   | enabled  | site.chat.scroller
loaded   | enabled  | site.chat.chat_line.rich_content
loaded   | enabled  | site.chat.chat_line
loaded   | enabled  | site.chat.settings_menu
loaded   | enabled  | site.chat.emote_menu
loaded   | enabled  | site.chat.input
loaded   | enabled  | site.chat.viewer_cards
loaded   | enabled  | site.chat
loaded   | enabled  | site.compat_emote_menu
loaded   | enabled  | site.dashboard
loaded   | enabled  | site.directory.game
loaded   | enabled  | site.directory
loaded   | enabled  | site.featured_follow
loaded   | enabled  | site.host_button
loaded   | enabled  | site.layout
loaded   | enabled  | site.menu_button
loaded   | enabled  | site.mod-view
loaded   | enabled  | site.player
loaded   | enabled  | site.sub_button
loaded   | enabled  | site.theme
loaded   | enabled  | site.video_chat

chat
-------------------------------------------------------------------------------
chat settings
-------------------------------------------------------------------------------
chat.badges.fix-colors: false
chat.badges.style: 6
theme.can-dark: true
theme.is-dark: true
chat.badges.clickable: true
chat.badges.version: 2
chat.filtering.color-mentions: true
chat.actions.inline: [{"action":"ban","appearance":{"type":"icon","icon":"ffz-i-block"},"options":{},"display":{"mod":true,"mod_icons":true,"deleted":false}},{"action":"unban","appearance":{"type":"icon","icon":"ffz-i-ok"},"options":{},"display":{"mod":true,"mod_icons":true,"deleted":true}},{"action":"timeout","appearance":{"type":"icon","icon":"ffz-i-clock"},"display":{"mod":true,"mod_icons":true}},{"action":"msg_delete","appearance":{"type":"icon","icon":"ffz-i-trash"},"options":{},"display":{"mod":true,"mod_icons":true}},{"action":"reply","appearance":{"type":"icon","icon":"ffz-i-reply"},"options":{},"display":{}}]
chat.scroller.freeze-requires-hover: true
chat.scroller.hover-delay: 750
chat.scroller.freeze: 0
chat.scroller.smooth-scroll: 0
chat.input.hide-identity: true
chat.emote-menu.enabled: true
chat.emote-menu.icon: false
chat.emoji.style: "twitter"
chat.actions.room-above: false
chat.tab-complete.emotes-without-colon: false
chat.input.show-mod-view: true
chat.filtering.deleted-style: 1
chat.filtering.clickable-mentions: false
chat.filtering.bold-mentions: true
chat.hide-community-highlights: false
chat.bits.show: true
chat.bits.show-pinned: false
chat.lines.alternate: true
chat.lines.padding: true
chat.adjustment-mode: 0
chat.adjustment-contrast: 4.5
theme.color.chat-background: ""
theme.color.background: "#000000"
theme.color.chat-text: "#aaaaaa"
chat.filtering.highlight-mentions: true
chat.filtering.highlight-tokens: false
chat.filtering.mention-color: ""
chat.lines.borders: 0
chat.subs.gift-banner: true
chat.banners.hype-train: true
chat.banners.prediction: true
chat.banners.polls: true
chat.width: null
chat.effective-width: 340
chat.actions.size: 16
chat.timestamp-size: 10
chat.font-size: 13
chat.lines.emote-alignment: 0
chat.font-family: ""
chat.delay: -1
chat.scrollback-length: 150
chat.filtering.remove-deleted: 1
chat.actions.room: []
chat.bits.animated: true
theme.tooltips-dark: false
chat.emotes.animated: 1
chat.filtering.blocked-types: {}
chat.replies.style: 1
chat.filtering.display-deleted: false
chat.points.allow-highlight: 2
chat.filtering.debug: false
chat.filtering.highlight-basic-users-blocked: []
__filter:block-users: null
chat.filtering.highlight-basic-blocked: []
__filter:block-terms: null
chat.filtering.highlight-basic-badges: []
__filter:highlight-badges: null
chat.filtering.highlight-basic-badges-blocked: []
__filter:block-badges: null
chat.filtering.highlight-basic-users: []
__filter:highlight-users: null
chat.filtering.highlight-basic-terms: []
__filter:highlight-terms: null
chat.emotes.enabled: 2
chat.emotes.2x: false
chat.fix-bad-emotes: true
chat.filtering.mention-priority: 0
chat.rich.enabled: true
chat.rich.minimum-level: 0
chat.rich.all-links: false
chat.name-format: 0
chat.badges.hidden: {}
chat.badges.custom-mod: true
chat.badges.custom-vip: true
chat.timestamp-format: "H:mm"
layout.portrait: false
layout.portrait-threshold: 1.25
layout.use-portrait: false
layout.portrait-min-chat: false
chat.points.show-rewards: true
chat.points.show-button: true
chat.emote-menu.combine-tabs: true
chat.emote-menu.stay-loaded: true
chat.emote-menu.show-quick-nav: true
chat.emote-menu.show-heading: 1
chat.emote-menu.tall: true
chat.emote-menu.reduced-padding: true
chat.emote-menu.show-search: true
chat.emote-menu.sort-emotes: 4
chat.emote-menu.sort-tiers-last: true
chat.emote-menu.show-emoji: true
chat.emote-menu.shortcut: false
chat.mru.enabled: true
chat.filtering.process-own: false
tooltip.images: true
tooltip.badge-images: true
tooltip.emote-images: true
tooltip.emote-sources: true
chat.points.auto-rewards: true
tooltip.rich-links: true
tooltip.link-images: true
tooltip.link-nsfw-images: false
tooltip.link-interaction: true

**Additional context**
Apologies for the wall of log, the "upload" button didn't seem to do anything...
I'd like to be able to keep the text color for the rest of the UI at #00ff00 and maintain the #aaaaaa of text chat. Hopefully this is something simple! Thanks!

**Comment by SirStendec** [comment]
Closed by a529e7fd279757393b9500b4d59ec28d96d4b1db
