### ISSUE TITLE
Is it possible to use in other chats

### ISSUE THREAD

**Issue by AquaBae** [FrankerFaceZ/FrankerFaceZ#111]
**Web Browser**: Google Chrome

**Do you use BetterTTV or other Twitch extensions**: No

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: N/A

**Bug / Idea**: Can you make this available to use in any chat? I saw that I could use other subscribers emotes in Twitch in any stream. That's what I assumed this was like.

**Steps to Reproduce (if Applicable)**:

**Comment by SirStendec** [comment]
FrankerFaceZ's emoticon system is about allowing individual channels to customize their experience and add new content for their communities to enjoy. It's all about the channel and its community.

We don't think that letting users set their own global emotes is a good idea and it isn't something we're going to support now or in the future.
