### ISSUE TITLE
7TV Tab Completion

### ISSUE THREAD

**Issue by xSlyDolphin** [FrankerFaceZ/FrankerFaceZ#1111]
After enabling 7TV in FFZ Settings, it seems like the Tab Completion doesn't apply to the emotes from that app.

I think having a feature that lets you enable tab completion for 7TV emotes would be awesome as it's just necessary for more convenient usage.

**Comment by SirStendec** [comment]
Any emotes added via FFZ's API, which the add-on uses, are tab-completed the same as any other emotes.

**Comment by xSlyDolphin** [comment]
well it's not the case for me... i enabled 7tv and still cant tab complete

**Comment by gempir** [comment]
@xSlyDolphin FFZ uses colon : to complete emotes. Just starting to type an emote and to tab is a chatterino and bttv feature. Not ffz

**Comment by gorro123** [comment]
Same issue on me
refreshing (F5) stream works for me - annoying tho

**Comment by Lordmau5** [comment]
> Same issue on me refreshing (F5) stream works for me - annoying tho

How are you trying to tab-complete the emotes? Just by typing their name and pressing tab, or are you using a colon `:` infront?

**Comment by gorro123** [comment]
Just the first letters and tab

if its not working refreshing fixes that

**Comment by TheGha** [comment]
seems like there is a setting for that in ffz
Chat » Input
Allow tab-completion of emotes without typing a colon. (:)

for some reason ffz emotes could be tab autocompleted with this off for me, while 7tv didn't. so check that.

**Comment by ReidHub** [comment]
Still an issue in 2025. Can this get more priority, it's a big problem imo

**Comment by idiota73** [comment]
still an issue.. refreshing stream fixes it for a while

**Comment by de1337ro** [comment]
refreshing only fixes it sometimes though
