### ISSUE TITLE
Giant Emojis

### ISSUE THREAD

**Issue by gempir** [FrankerFaceZ/FrankerFaceZ#1112]
**Describe the bug**
Emojis are a lot bigger than they should be

**To Reproduce**
1. Install FrankerFaceZ
2. Read a chat with emojis

**Expected behavior**
They should be normal sized

**Screenshots**
![image](https://user-images.githubusercontent.com/9765622/132912067-2753972d-d94e-4cf4-819c-4dd06a17ae90.png)

**Environment (please complete the following information):**
 - OS: Arch Linux
 - Browser Chrome
 - Version 91
 - Other Extensions: Ublock, Bitwarden, Notion, Nothing Twitch related, Bttv disabled
 
**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:
https://pastebin.com/raw/gjQQb62s (Your upload took too long)

**Additional context**
Version 4.29.0
04cfbe6

**Comment by gempir** [comment]
From @yobson1
Using "Emoji Style" Native in FFZ Settings fixes this issue

**Comment by Void48** [comment]
Fixed! 
![image](https://user-images.githubusercontent.com/85196642/132913768-4b262573-48a2-4743-8bab-34a61c402c97.png)

**Comment by gempir** [comment]
Seems to be fixed by 35c99df8aac1caca4142b2fb580f80fae9e8b9fc
