### ISSUE TITLE
Huge emoji

### ISSUE THREAD

**Issue by yobson1** [FrankerFaceZ/FrankerFaceZ#1113]
**Describe the bug**
Emojis in chat are huge with FFZ enabled.

**To Reproduce**
View any chat and emojis entered in chat will be huge.

**Expected behavior**
They should be normal sized.

**Screenshots**
https://i.imgur.com/jHszKfL.png

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version  93.0.4577.63
 - Other Extensions: uBlock Origin, Video Ad-block for Twitch

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:
https://hastebin.com/raw/ciqibuheda

**Comment by gempir** [comment]
Duplicate of https://github.com/FrankerFaceZ/FrankerFaceZ/issues/1112

**Comment by yobson1** [comment]
> Duplicate of #1112

I posted it right after my bad.
Also changing emoji rendering to native in FFZ settings fixes the issue.
