### ISSUE TITLE
[Feature] Re-enable or replace auto-host system

### ISSUE THREAD

**Issue by Gamertech** [FrankerFaceZ/FrankerFaceZ#1114]
**Is your feature request related to a problem? Please describe.**
Twitch stated that they've only stopped showing auto-hosts in the live view, yet the FFZ host button always reports I'm hosting 'None' unless I manually host someone, showing they've completely disabled it and are talking out of an alternative orifice yet again.

**Describe the solution you'd like**
Any chance of FFZ reading the configured auto-host list and doing Twitch's job for them? ie. re-enabling the auto-host system, or automatically hosting a live channel on the list 'manually'? At least while the user is online and their browser is connected to Twitch?

**Describe alternatives you've considered**
Appeal to Twitch's better sensibilities and...lol...yea no. The community already tried that, it was instantly declined with a PR answer: https://twitch.uservoice.com/forums/923383-creators-and-stream-features/suggestions/44104500-return-auto-host-to-live-view

**Additional context**
Not really much else needed to say here. Please rescue us from Twitch!

**Comment by SirStendec** [comment]
This isn't something I'm interested in implementing. Someone else can try if they want, but it won't be me.
