### ISSUE TITLE
FFZ Extension for iPadOS 15

### ISSUE THREAD

**Issue by michael-gram** [FrankerFaceZ/FrankerFaceZ#1117]
**Is your feature request related to a problem? Please describe.**
n/a

**Describe the solution you'd like**
iPadOS 15 recently introduced browser extension support in Safari. Does this make it possible to bring FFZ to iPad?

https://www.macrumors.com/guide/ios-15-safari-extensions/?Bibblio_source=true
https://developer.apple.com/safari/extensions/

**Describe alternatives you've considered**
FFZ is not available officially on iPad that I'm aware of, only on desktop browsers. The Twitch mobile app is fine but does not support extensions.

**Additional context**
I primarily watch Twitch from an iPad and it would be great to bring FFZ to the platform. Thanks for your consideration.

**Comment by SirStendec** [comment]
We will not be releasing any official extensions for Apple.

1. Apple charges a yearly fee to release extensions on their platform.
2. We don't have any Apple hardware to perform testing.
3. Apple has invented their own non-standard way of making extensions that I don't want to have to think about.

If you want FFZ on Apple products, please find a way to use userscripts and just use our user script.
