### ISSUE TITLE
Missing Stream Uptime on the directory page thumbnails

### ISSUE THREAD

**Issue by Morten79** [FrankerFaceZ/FrankerFaceZ#1135]
**Describe the bug**
Since yesterday the stream uptime indicator, have been missing from the Directory page thumbnails.

**To Reproduce**
1. Go to - Directory > Channels > Stream Uptime: Enabled.

**Expected behavior**
The aforementioned setting should by default show the stream uptime (hour, minutes).

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version 92
 - Other Extensions: None only uBlock Origin.

**Additional context**
Have tried to see if it works with a clean chrome profile without uBlock Origin, but with the same result.

Hope you'll be able to fix this soon.
Thanks for making such a great extension :+1:

**Comment by bithub2** [comment]
I think Twitch changed something again... but the last update was almost 2 months ago... PLEASE COME BACK AND FIX THIS SOON 🤬

**Comment by Morten79** [comment]
I'm now able to see the thumbnails uptime  - This issue can now me closed for now

**Comment by Lordmau5** [comment]
Closing this issue as it was resolved in version 4.29.3.

If the issue comes up again please open up a new issue 😁
