### ISSUE TITLE
Add websites/domains to apply FFZ and BTTV emotes

### ISSUE THREAD

**Issue by yontekh** [FrankerFaceZ/FrankerFaceZ#1136]
**Is your feature request related to a problem?** no

**Describe the solution you'd like**
I would like FrankerFacez and LirikLive emotes to work on the [chitchat.ma.pe](https://chitchat.ma.pe/lirik) website/domain as well.
Or have an option to manually whitelist domains in the settings.

**Comment by SirStendec** [comment]
That isn't how the extension works. A custom extension specifically for use with chitchat.ma.pe would need to be created.

I am slowly working on a FFZ add-on for filtering chat in a similar way to that website. Not sure when it will be done.
