### ISSUE TITLE
Please bring back OMGScoots

### ISSUE THREAD

**Issue by Rowibl** [FrankerFaceZ/FrankerFaceZ#114]
**Web Browser**: Google Chrome

**Do you use BetterTTV or other Twitch extensions**: BTTV

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: NA

**Bug / Idea**:
Please add the emote OMGScoots like you did with SoonerLater. OMGScoots is a big part of my twitch experience and if I can't have it I'm afraid I might have to leave the website forever. If you could save this emote and bring it back as a FrankerFaceZ emote I would be incredibly grateful :-).

**Steps to Reproduce (if Applicable)**:
1. Find OMGScoots
2. Put a gun to his head.
3. Change his name to ScootsOMG.
4. Bring him back in his full glory.

**Comment by SirStendec** [comment]
SirScoots, the person pictured in the former OMGScoots emoticon, does not want anyone to do that so we're refraining from making a global OMGScoots emote with FFZ and we are not allowing anyone to submit it to the service.
