### ISSUE TITLE
eyes converts to a broken discord svg emoji

### ISSUE THREAD

**Issue by Tiffys** [FrankerFaceZ/FrankerFaceZ#1143]
Whenever I type eyes in chat it attempts to convert it to an emoji but it's a broken image icon and the word eyes like so: https://i.imgur.com/eAbDoPs.png

The image with inspect source seems to direct here: https://discord.com/assets/4c5a77a89716352686f590a6f014770c.svg

It seems somewhat obvious the reason the image doesn't load is because cloudflare says access is denied to that image, you can see it if you access it from discord. It's the 👀 emoji, or should be. But it's not actually `:eyes:` or `:eye:` it's just the word eyes. Though it's a little weird for it to autoconvert such a common word as eyes into an emoji to begin with.

I'm not sure which add-on is doing it, or if it's the core. I don't think it's BetterTTV Emotes because I tried disabling every option in Add-Ons » BetterTTV Emotes and none of them fixed it. Disabling that add-on and refreshing didn't fix it either. Disabling Mod Tools and The FrankerFaceZ Add-On Pack - Core and refreshing also didn't fix it. And if it's not any of those then it must be FFZ itself? I dunno.

Here's a link to the feedback log: https://pastebin.com/HwvHeHzN

**Comment by SirStendec** [comment]
FrankerFaceZ never references Discord assets. We host our own emoji assets. If you post 👀 with the emoji style set to twitter, which you have given your debug logs, it should be using the URL: https://cdn.frankerfacez.com/static/emoji/images/twemoji/1f440.png

You likely have another extension, unrelated to FFZ, that is causing problems.

**Comment by Tiffys** [comment]
> FrankerFaceZ never references Discord assets. We host our own emoji assets. If you post 👀 with the emoji style set to twitter, which you have given your debug logs, it should be using the URL: https://cdn.frankerfacez.com/static/emoji/images/twemoji/1f440.png
> 
> You likely have another extension, unrelated to FFZ, that is causing problems.

I probably only used the actual emojis for testing. But this problem occurs when literally typing "eyes" in chat. Is there some way to actually track down what could be causing it? Cause it's really annoying.
