### ISSUE TITLE
Workaround for posting combined emoji

### ISSUE THREAD

**Issue by Mm2PL** [FrankerFaceZ/FrankerFaceZ#1147]
**Additional context**

I've created an RFC for this: https://gist.github.com/Mm2PL/982c76964fe53f80fcf6b6963bba049f. Rendered LaTeX PDF: https://mm2pl.github.io/emoji_rfc.pdf. This is a workaround for https://github.com/twitchdev/issues/issues/307.

**Is your feature request related to a problem? Please describe.**

Yes, but it's a TMI issue, the chat server removes the **ZERO WIDTH JOINER** character which makes posting and receiving combined emoji (like 👨‍🌾) impossible. They just get turned into their parts, in this case 👨🌾. 

![2021-12-04_20-53](https://user-images.githubusercontent.com/25011746/144722855-b629b2c3-1856-4179-b005-9f7bace1b518.png)

**Describe the solution you'd like**

I'd like for FFZ to replace **U+200D** (ZERO WIDTH JOINER) with **U+E0002** (no official name) when sending/receiving messages as I've described in the RFC.

**Describe alternatives you've considered**

Not doing it and bothering Twitch to fix it and having them probably ignore us.

**Comment by leon-richardt** [comment]
Just a little update, this workaround has now been implemented in Chatterino (https://github.com/Chatterino/chatterino2/pull/3469) and DankChat (https://github.com/flex3r/DankChat/commit/d5303b9f7659b19e18427bc22c56efb44d9f9df9).

**Comment by Felanbird** [comment]
This workaround has been implemented into Chatsen (chatsen/chatsen@0350eb5) as well.

**Comment by ErisApps** [comment]
This workaround is no longer needed as of March 22, 2022 (see https://github.com/twitchdev/issues/issues/307#issuecomment-1080604383).
It would be neat if this workaround could be removed/reverted as it the usage of this breaks the correct rendering of combined emojis on vanilla clients.

**Comment by leon-richardt** [comment]
> This workaround is no longer needed as of March 22, 2022 (see [twitchdev/issues#307 (comment)](https://github.com/twitchdev/issues/issues/307#issuecomment-1080604383)). It would be neat if this workaround could be removed/reverted as it the usage of this breaks the correct rendering of combined emojis on vanilla clients.

Good point! For reference, Chatterino recently (last week) removed its sending side of the implementation as well: https://github.com/Chatterino/chatterino2/pull/4361

**Comment by Felanbird** [comment]
It would be preferred if only the sending side is removed and the reading side is kept, that way it won't cause any conflicts with people still using old versions of chatterino/chatty/chatsen that still send them with the workaround.

**Comment by ErisApps** [comment]
I'm completely fine with that approach, that would at least allow you all to phase out the workaround altogether in due time 🙂

**Comment by Felanbird** [comment]
> that would at least allow you all to phase out the workaround altogether in due time

Well no, we don't force the user to update, I'm just trying to make sure FFZ users don't see broken emojis from those users
