### ISSUE TITLE
[Suggestion] A way to save the settings.

### ISSUE THREAD

**Issue by XsFrozdY** [FrankerFaceZ/FrankerFaceZ#1155]
**Is your feature request related to a problem? Please describe.**
Every time I reinstall windows, Franker resets, personally I don't like the franker way of showing emotes, I like the standard the best.

So a way to save the settings would be appreciated, there are tons of ways this could be done.

**Describe the solution you'd like**
The most annoying of all the solutions I can come up with is to import/export a .xml file to and from the PC, BUT, it's MUCH better than having everything reset and you have to go through setting it up the way you want every time, or preferably synced between all my devices.

**Describe alternatives you've considered**
Better TTV but I'm running both, sooo... there's not really any other alternatives.

**Additional context**
I think I covered all I can.

**Comment by Lordmau5** [comment]
FFZ actually already has a backup & restore functionality that saves / loads a `.json` file
![image](https://user-images.githubusercontent.com/1345036/146407143-17104674-4589-431c-916a-bdb6a7c2ada3.png)

As for synced / cloud storage settings, that'd only work for certain browsers that would support it, so it's not really something Stendec was looking into from what I remember

**Comment by XsFrozdY** [comment]
So blind I am... nevermind then :P
