### ISSUE TITLE
Support for 7TV nickname paints

### ISSUE THREAD

**Issue by TomasTokaMrazek** [FrankerFaceZ/FrankerFaceZ#1157]
7TV.app added new functionality called Nametag Paints. There are few (currently three) multi-color variations available. Support through FFZ would be in line with other 7TV features already implemented like animated avatars and zero-width emotes.

**Comment by SirStendec** [comment]
Requests regarding add-ons should be submitted to the add-ons issue repository. That said, the 7tv developers already submitted an updated for their FFZ add-on that does this.
