### ISSUE TITLE
FFZ is pausing youtube videos and ads and there's no setting to undo this.

### ISSUE THREAD

**Issue by whaaaley** [FrankerFaceZ/FrankerFaceZ#1162]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g. chrome, firefox]
 - Version [e.g. 70]
 - Other Extensions: [e.g. BetterTTV, Privacy Badger, AdBlock, etc.]

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:

**Additional context**

**Comment by SirStendec** [comment]
FrankerFaceZ's browser extension is incapable of affecting YouTube, nor is it designed to do so. Please ensure that whichever version of FrankerFaceZ you are using, it is the official version linked on our website.

In the future we might support YouTube, but currently the extension only works on Twitch and only runs on *.twitch.tv domains.

**Comment by whaaaley** [comment]
Hm. Gotcha. I'm not sure what the issue I'm having is then. I don't have any other extensions installed in Firefox. When FFZ is enabled Youtube videos are automatically pause. Disabling FFZ and refreshing Youtube stops the auto-pausing. Fwiw I'm running the latest Firefox version on Windows 11.
