### ISSUE TITLE
[Bug] cannot collapse/expand chat in theater mode

### ISSUE THREAD

**Issue by schmarrn** [FrankerFaceZ/FrankerFaceZ#117]
**Web Browser**: Firefox

**Do you use BetterTTV or other Twitch extensions**: BTTV for FFZ

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: http://putco.de/NTYyNA.log

**Bug**: I can't collapse or expand the chat in theater mode anymore. The arrow buttons disappear when I enter theater mode.

**Comment by SirStendec** [comment]
I cannot reproduce this behavior. The button appears as expected when I mouse over the player in theater mode. Please make sure you aren't using any other extensions that might be interfering.

You might also want to test with no extensions at all to see if it's there. You might be subject to A/B testing from Twitch.

**Comment by schmarrn** [comment]
I just noticed that it works normal when I don't have the "Swap sidebar position" option active. When I activate the setting (to place chat on the left) the buttons disappear in theater mode.
