### ISSUE TITLE
Support for new Twitch Feature: Moments

### ISSUE THREAD

**Issue by ReggX** [FrankerFaceZ/FrankerFaceZ#1172]
Twitch recently announced a new feature called Moments, as a beta available to a limited amount of partners and affiliates.
https://help.twitch.tv/s/article/moments?language=en_US

Moments add new (time-limited) prompt to claim them and new badges for the users who did.

Since moments are limited to 5 a month and only a few streamers, research and test opportunities may be few and far between.

**Describe the solution you'd like**
* Add the Moments badges to Badge Visibility, Highlight, Block settings.
* Add an option to auto-claim the Moment when the prompt appears for the people who like the feature.
* Add an option to hide the Moments prompt for people who don't like it and want their chat free of distractions.

**Comment by pointydev** [comment]
Would love to see auto-claim and prompt visibility settings implemented. [ESL_CSGO](https://www.twitch.tv/esl_csgo) make relatively frequent use of this feature, so [ESL/IEM events](https://www.hltv.org/events) may be good testing grounds.

**Comment by DoraTheExploder** [comment]
> Would love to see auto-claim and prompt visibility settings implemented. [ESL_CSGO](https://www.twitch.tv/esl_csgo) make relatively frequent use of this feature, so [ESL/IEM events](https://www.hltv.org/events) may be good testing grounds.

I would also like to see this feature implemented. Bump.

**Comment by ReggX** [comment]
I'm closing this issue since Moments are dead.
