### ISSUE TITLE
Dismiss User Menu when clicking in player not behaving as expected

### ISSUE THREAD

**Issue by Taizunz** [FrankerFaceZ/FrankerFaceZ#1174]
**Describe the bug**
**EDIT: After a quick reproduction test on more channels, I have narrowed it down to only being an issue on channels that have active overlay extensions.**

Behavior without browser (Chrome in this case) extensions enabled: When you click your avatar in the top-right corner of the site, the user menu opens. Clicking anywhere on the site (but outside of the user menu) closes it.
Behavior with FFZ enabled: When the user menu is open, clicking anywhere outside of the menu closes it, except for when you click in the player area. With FFZ's default settings applied, clicking in the player area does not dismiss/close the user menu.

I found that the setting "Allow mouse interaction with overlay extensions." seems to be the culprit here. It's enabled by default in FFZ, but something about it is different enough from Twitch's native behavior that it prevents the user menu from closing when this is on.

**To Reproduce**
1. Open any live channel (**EDIT: Has to be a channel with active overlay extensions**)
2. Click your avatar in the top right corner of the site to open the user menu
3. Click in the player area to attempt to dismiss/close the user menu
4. Menu doesn't close. (And if it does, you have probably disabled the setting "Allow mouse interaction with overlay extensions.")

**Expected behavior**
Close the user menu when clicking in the player area.

**Environment (please complete the following information):**
 - OS: Win10
 - Browser: Chrome Version 97.0.4692.99
 - Other Extensions: Lots, but none that seems to have an influence other than FFZ.

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:
https://gist.github.com/Taizunz/9c87da68b1d750f6526b3c9774720480

**Comment by SirStendec** [comment]
Vanilla Twitch does not close the user menu if you click over the player while an overlay extension is present. FrankerFaceZ isn't doing anything different there. The setting you're talking about does absolutely nothing when in its default state.

Simple fact is that your page will not receive click events if the user clicks on an iframe. It's a security thing. Extensions run in an iframe, and overlay extensions cover almost the entire player with their iframe, so the base page can't receive click events for that area.
