### ISSUE TITLE
Disabling animated emotes not working with 7TV

### ISSUE THREAD

**Issue by gae28** [FrankerFaceZ/FrankerFaceZ#1175]
**Describe the bug**
When disabling animated emotes and having 7tv emotes enabled, the animated emotes from 7tv do not display as static images as expected.

**To Reproduce**
1. Go to Frankerfacez control center
2. Enable 7TV add-on
3. Disable animated emotes in Chat -> Appearance -> Emotes
4. 7TV emotes still animate.

**Expected behavior**
Animated emotes from 7TV should display as static images.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 97.0
 - Version 4.32.1 
 - Other Extensions: 

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:
Uploading logs did not work but can be provided if needed.

**Comment by SirStendec** [comment]
This is a data problem, and not something that can or should be addressed by the main FFZ extension. I don't think 7tv even serves static versions of their animated emotes, though I may be mistaken. In either case:

Please submit bugs related to add-ons to the repository:

https://github.com/FrankerFaceZ/Add-Ons/issues

Any issues opened on this main repository for add-ons will be closed, as this repository is for the main client specifically and not add-ons.
