### ISSUE TITLE
Profiles, Current Category Rule not matching

### ISSUE THREAD

**Issue by aoitrix** [FrankerFaceZ/FrankerFaceZ#1178]
**Describe the bug**
The "Current Category" rule doesn't match

**To Reproduce**
0. Go to a live stream
1. Go to Profiles, Select Lower Priority Profile
2. Click on Add new Rule, Current Category, Select current category of streamer, save rule
3. See error (Red x rule doesnt match) 

**Expected behavior**
The rule should match.

**Screenshots**
Chrome:
![2022-02-24 13_51_05-Sleepypan - Twitch](https://user-images.githubusercontent.com/48161323/155530290-6f0349b6-e3aa-49d4-9dc6-3946efd3ec40.png)

Firefox:
![2022-02-24 14_14_32-BiberBros - Twitch](https://user-images.githubusercontent.com/48161323/155531005-64f2f4d3-bbb1-4590-b919-4358330c78d0.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome /  Firefox 
 - Version 98.0.4758.102  (Chrome) / 97.0.1 (Firefox)
 - Other Extensions: ublock origin, disabled on twich.tv

**Additional context**
Tested with different categories, reaching from just chatting, Marbles on Stream, Dark Souls III.
Tested with "Current Streamer" - that rule matches.

**Comment by Lordmau5** [comment]
**Extra dev notes:**

https://github.com/FrankerFaceZ/FrankerFaceZ/blob/master/src/settings/filters.js#L315 utilizes `ctx.categoryID` and `ctx.category` respectively to check if the category is valid.

Upon inspection, those variables aren't present on the `ctx` object anymore.
Not sure if it's still present somewhere, but this is all I managed to find from a quick look at the code.

**Comment by SirStendec** [comment]
Fixed in 155938f584d16efe39f5c348ce96389fbf02658a
