### ISSUE TITLE
Chat loads but new messages never appear

### ISSUE THREAD

**Issue by alex-gonz** [FrankerFaceZ/FrankerFaceZ#118]
**Web Browser**:
FF 52.0.1

**Do you use BetterTTV or other Twitch extensions**:
I'm using BetterTTV v6.8R55 but no other twitch extensions.

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:
http://putco.de/NTY0NA.log

**Bug / Idea**:
When I enter a twitch stream, chat "loads", showing messages that were posted just before I joined chat, but I don't see any new messages, and if I send a message it doesn't appear. I do, however, see timeouts.

I'm not sure if this happens every time or if it's just very often. Refreshing doesn't seem to make this bug go away.

This bug seems to go away if I disable either of FFZ or BTTV, and sometimes stops happening for a bit if I refresh just after I re-enable them together.

**Steps to Reproduce (if Applicable)**:
Go to http://www.twitch.tv/directory/following.
Click on a channel.

**Comment by SirStendec** [comment]
This is a BetterTTV issue and not related to FrankerFaceZ. As I understand it, they're working on rewriting their extension currently in order to fix instability like this. You shouldn't encounter any issues like that using FFZ by itself.
