### ISSUE TITLE
Emotes doesn't show after the colon (:) when the colon not at the first ?

### ISSUE THREAD

**Issue by hxmo69** [FrankerFaceZ/FrankerFaceZ#1180]
yesterday I was messing around in frankerface setting so much and after that this happened ... when type colon (:) to search for emote it appears only when the colon at the first of the message like this (:lul message) but when I go like this ( message :lul) the emote doesn't show up .. I displayed frankerface extension and still the same problem .

any help ?

**Comment by Codelefant** [comment]
Most likely related to #1179

**Comment by Lordmau5** [comment]
Yeah, duplicate of #1179
