### ISSUE TITLE
"Swap Sidebars" + "Theater Mode" | CSS Error when chat wraps under video.

### ISSUE THREAD

**Issue by duckyb** [FrankerFaceZ/FrankerFaceZ#1182]
**Describe the bug**
When using theater mode in a narrow window the chat doesn't fill the width of the page.

**To Reproduce**
1. Enable "FFZ Control Center > Layout > Swap Sidebars"
2. Go to any stream
3. Click on "Enable theater mode" (alt + t)
4. Reduce the window width until the chat wraps under the video*
5. See error

*Note: This issue does not appear when resizing using chrome dev-tools

**Expected behavior**
The chat should fill the window width.

**Screenshots**
<details>
<summary> Open Screenshot </summary>

![Screenshot 2022-03-01 115059](https://user-images.githubusercontent.com/27895007/156157713-a0ced2e8-bb8b-4ba0-b431-5327e0e7ab22.png)

</details>

**Environment (please complete the following information):**
 - OS: Windows
 - Chrome
 - Version 98.0.4758.102 (Official Build) (64-bit)
 - Other Extensions: BetterTTV, UblockOrigin

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**: 
[View Logs](https://gist.githubusercontent.com/duckyb/00035b719ce29db9a1d0f36236e31e63/raw/280edbd941d1eed4076727f9c7a9bd616eb3ff66/FFZ%2520Logs)

**Comment by SirStendec** [comment]
Fixed in 155938f584d16efe39f5c348ce96389fbf02658a
