### ISSUE TITLE
Typing in twitch chat is randomly reversed / backwards

### ISSUE THREAD

**Issue by TBloop** [FrankerFaceZ/FrankerFaceZ#1187]
**Describe the bug**
Seemingly randomly, the text I type in the chat box will display (and be sent as) backwards. For instance, if I type "hi guys", it will come out as "syug ih". 

I thought I might've been alone in this, but I've started seeing people typing sentences backwards in chat. Today, I found two people that said they had the same issue, and they also use FFZ. I asked if they had any add-ons enabled, they said no. 

I have 7TV, BTTV, Fullscreen chat, Inline tab completion, Smokey's utilities, and FFZ add-on pack enabled.

This bug started approximately a month ago.

**To Reproduce**
Unfortunately I haven't been able to reproduce. The only possible thing I've noticed is that it seems to happen if i haven't typed anything in a minute or two. In other words, the first thing I type for a little while is the thing that is backwards. It never happens if I type many messages in a row. 

When it does happen, simply deleting the text and then clicking on the text box with the mouse will fix it. 

**Expected behavior**
Text should always show up and be sent in the order the keys are pressed

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 99.0.4844.51
 - Other Extensions: 
 Bypass Paywalls
Authenticator
Checker plus for gmail
Dark reader
Gmail Mod
Google docs offline
Join
Pay by privacy.com
Rakuten cashback for shopping
Reddit enhancement suite
Return youtube dislike
reveddit real-time
Reviewmeta.com review analyzer
Smile always
Sponsorblock for youtube
The camelizer
Thumbnail rating for youtube
Typio form recovery 
uBlock Origin
Video ad-block for twitch
FFZ

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:
https://www.pastery.net/qwdnak/

**Additional context**
One of the other people that said they had the problem was also on Windows 10 with Chrome.

**Comment by duke1102** [comment]
Just wanting to let you know that I also encounter this issue and know of at least one other person where this is happening.

**Comment by TBloop** [comment]
Hm. Just commenting that I saw a reddit thread of people having this issue, and one person said it still happened when they were in incognito mode which should disable extensions. Could it just be twitch itself with this issue?

**Comment by ttvDanjio** [comment]
It seems to be an FFZ Issue. It appears after losing focus in the chat bar (e.g. hovering above with your mouse on a stream you follow) it turns grey and the moment you unhover chat gets its focus back BUT throws you to the beginning and not at the point you stopped typing.

**Comment by TBloop** [comment]
I spoke to several people on reddit that said they had this issue and didnt have FFZ or similar extensions. I also havent had this happen to me in several weeks. My thought was that it was a twitch issue and they may have fixed it recently.

However, I do notice some strange behavior with the cursor. Sometimes it will remain at the beginning of the text box even though I've typed past it , which would normally be a sign it would be typing backwards like before. However my text types normally. It seems it's been mostly fixed except for that cursor behavior.

**Comment by FactionRed** [comment]
I too have this issue; it happens when i alt-tab in and out of the window a bunch but hard to replicate; it's very hit and miss
