### ISSUE TITLE
Playback statistics not showing

### ISSUE THREAD

**Issue by SpartanD** [FrankerFaceZ/FrankerFaceZ#1192]
Playback statistics not showing

![Yhb6081](https://user-images.githubusercontent.com/102737936/161054487-b4af9b50-16b2-4eb5-acbe-9fcb6929a973.png)

Environment:
 - OS: Windows 10 Home
 - Browser: Chrome
 - Version: 21H2
 - Other Extensions: BetterTTV, UBlock Origin, Dark Reader, Shazam

**Comment by PvtSimpson** [comment]
Experiencing the same thing.
