### ISSUE TITLE
Ability to extract specific word/array from chat message

### ISSUE THREAD

**Issue by bel57** [FrankerFaceZ/FrankerFaceZ#1199]
Hello!
Variables are a bit limited, I'd like FFZ to extract a username from a bot message to do a quick shoutout

Technical context/  Taizun said this on Discord:
You may want to submit a feature request for something like the ability to extract a specific word out of an array in a message, as that's the closest we'd feasibly get to what you initially wanted. There's no feasible way to extract a "username" from a message unless it's prefixed with an @, and that's not always the case in bot messages. 
There's already a {{message.text}} variable, so a possible request could be for a {{message.<number>}} variable, where you replace <number> with the what the number for that word would be in an array, i.e. the first word in a message would have number 0, so to extract the first word, you'd use the variable {{message.0}}

bot message:  
StreamElements: _**user** just raided the channel with x viewers PogChamp_

So, the way it's formatted, username is the first word of raid messages. I'd like the username extracted so I can make use of this kind of action: _!so **{{message.0}}**_ which would allow a quick macro for a shoutout.

Thanks :)

**Comment by WaterBoiledPizza** [comment]
I see this being closed as completed and format added, but is there documentation on how to use the formatters?

**Comment by bel57** [comment]
> SirStendec — 2022-04-19 11:00PM
> Right... that would've been helpful to include lmao
> Like {{ message.text | word(3) }}
> You can also chain formatters like {{ message.text | word(-3,) | slugify }} (And no I don't expect slugify/snakecase to ever be useful but they were test methods and meh)

join the discord for any help and questions
