### ISSUE TITLE
Twitch HTML5 Player?

### ISSUE THREAD

**Issue by HiroiSekai** [FrankerFaceZ/FrankerFaceZ#1201]
**Is your feature request related to a problem? Please describe.**
This isn't an FFZ problem, but it does refer to a Twitch problem. It's 2022, and Twitch still uses an antiquated video player that stutters randomly for no reason, even on the highest of connection speeds.

**Describe the solution you'd like**
A Chrome plugin called Twitch HTML5 Player has already been developed to replace the slow vanilla Twitch player with a much more up to date HTML5 one. However, the interface itself for the plugin is outdated and missing features, like the ability to see your sidebar of followed streams, for just one example.

The solution I'd like is if possible, I'd love if FFZ could incorporate a replacement video player of sorts that is actually customizable. The aforementioned plugin does vastly improve the stability of watching streams, but the interface is old, restrictive and non-customizable. FFZ always offered very finite editing with great detail, I'd love to know if the team would be able to implement a replacement player that isn't painful to use.

**Describe alternatives you've considered**
As mentioned, the only really decent known plugin alternative is Twitch HTML5 Player on the Chrome Extensions Web Store. It fixes the laggy Twitch player, but has its own problems with user experience with its very limited interface.

**Additional context**
Just for context, I am certain it is not my internet connection causing the slowdown in the Twitch player. My own streams maintain the highest connection stability possible, and my speeds are always near or at 1Gbps up/down through Ethernet. Regardless of this, I still have to use FFZ's reload video player option many times per stream I watch because it'll randomly just lag for several seconds and put me further and further behind live chat speed.

**Comment by SirStendec** [comment]
Implementing a replacement player would be a lot of work and it isn't something I'm interested in at this time. Additionally to the work, that sort of project would create unnecessary friction with Twitch due to issues with handling ads. It's just not something I'd like to introduce to FrankerFaceZ.
