### ISSUE TITLE
(BUG) Message dissapears upon opening emote menu

### ISSUE THREAD

**Issue by CrazySaft** [FrankerFaceZ/FrankerFaceZ#1203]
**Describe the bug**
If i enter a message in the chat box then open the emote menu message will get deleted

**To Reproduce**
1. Type a message
2. Open emote menu
3. Message is gone also replys or so

**Expected behavior**
Message should still be there

**Environment (please complete the following information):**
 - Windows
 - Chrome
 - 4.33.0 FFZ 
 - Newest Chrome
 - BTTV, FFZ. FFZ-Addon, Twitch-Ad block, 7TV

I removed all extensions still doesn't work also reloading the page(i did indeed work for 2 minutes then again the bug startet) won't work.

I think this i a huge bug and should be fixed quickly.

Cause the upload log button get's stuck and nothing happens i add it here manually  ;(

initialization
-------------------------------------------------------------------------------
[17:26:24] info | core: FrankerFaceZ v4.33.0 (s:twitch f:main b:416e11000ab3c06de5f8 c:2af7d5618b865ecdb6eff29443b9c58f029d7c42)
[17:26:24] info | core: Initial URL: https://www.twitch.tv/colaway
[17:26:24] info | site: Using: Twilight
[17:26:24] info | site.web_munch: Found and wrapped webpack's loader after 0ms.
[17:26:24] info | settings: Using Provider: LocalStorageProvider
[17:26:24] info | core: Loaded descriptions of 0 modules.
[17:26:24] info | settings: Initialization complete after 12.90000ms -- Values: 95 -- Profiles: 2
[17:26:24] info | site.fine: Installing MutationObserver.
[17:26:24] info | site.switchboard: Found Route and Switch with 12 routes.
[17:26:24] info | site: Loaded descriptions of 17 modules.
[17:26:24] info | site.elemental: Installing MutationObserver.
[17:26:24] info | main_menu: Built Tree in 14.40000ms with 153 structure nodes and 260 settings nodes.
[17:26:25] info | site.web_munch: require() grabbed in 1059.80000ms.
[17:26:25] info | experiments: Loaded information on 2 experiments.
[17:26:25] warn | site.player: Unable to install document visibility hook. TypeError: Cannot redefine property: hidden
[17:26:25] info | site.chat: Chat Types have changed from static mappings for categories: CHAT_TYPES
[17:26:25] info | core: Initialization complete in 1628.00000ms.

settings
-------------------------------------------------------------------------------
i18n.debug.capture: false
i18n.format.date: "short"
i18n.format.time: "medium"
i18n.format.datetime: "medium"
i18n.debug.transform: null
i18n.locale: "de"
addons.dev.server: false
ffzenhancing.focus_input_area_after_emote_select: true
ffzenhancing.keep_delay_low: true
ffzenhancing.keep_delay_low_delay: 8.5
ffzenhancing.keep_delay_low_delay_low_latency: 5
ffzenhancing.keep_delay_low_rate: 1.05
ffzenhancing.fix_tooltips: true
ffzenhancing.doubleclick_username_paste_in_chat: true
ffzenhancing.move_users_in_chat_to_bottom: false
ffzenhancing.hide_rooms_header: false
ffzenhancing.auto_reload_on_error_2000: true
ffzenhancing.auto_reload_on_hanged_video: true
ffzenhancing.auto_reload_on_hanged_video_after: 10
ffzenhancing.auto_check_player_quality: false
ffzenhancing.auto_check_player_compressor: true
ffzenhancing.pin_mentions: true
ffzenhancing.reset_after_delay: true
ffzenhancing.reset_after_delay_delay: 30
ffzenhancing.animate_static_gif_emotes_on_mouse_hover: true
ffzenhancing.auto_click_claim_bonus_points: true
ffzenhancing.fix_emote_select: false
ffzenhancing.highlight_user_messages: false
ffzenhancing.visibility_hook_time: 5
ffzenhancing.fix_addon_load: false
ffzenhancing.fix_video_freeze_on_tab_change: true
player.theatre.auto-enter: false
chat.bits.show: false
layout.display-bits-button: false
metadata.modview.hide-info: false
layout.side-nav.hide-viewers: false
metadata.uptime: 2
metadata.uptime.no-native: true
metadata.viewers: false
metadata.viewers.no-native: false
layout.swap-sidebars: false
layout.portrait: true
layout.portrait-threshold: 1.25
layout.use-portrait: false
chat.width: null
chat.use-width: false
layout.use-chat-fix: false
layout.theatre-navigation: false
layout.minimal-navigation: true
layout.side-nav.show-avatars: true
layout.side-nav.show: 1
layout.side-nav.hide-offline: false
layout.hide-discover-luna: false
layout.prime-offers: false
layout.discover: true
channel.hide-unfollow: false
channel.round-avatars: true
channel.hide-live-indicator: false
layout.side-nav.rerun-style: 1
layout.side-nav.show-rec-channels: 0
layout.side-nav.show-friends: 1
whispers.show: true
channel.show-celebrations: true
layout.theme.global-font: ""
layout.portrait-invert: false
layout.portrait-min-chat: false
layout.inject-portrait: false
layout.use-portrait-swapped: false
player.theatre.metadata: false
layout.use-portrait-meta: false
layout.use-portrait-meta-top: false
layout.portrait-extra-width: 5
player.theatre.no-whispers: false
layout.portrait-extra-height: 10
theme.disable-auto-dark: false
theme.can-dark: true
theme.is-dark: true
theme.color.background: ""
theme.color.text: ""
theme.color.accent: ""
theme.color.tooltip.background: ""
theme.color.tooltip.text: ""
theme.color.chat-background: ""
theme.color.chat-text: ""
theme.color.chat-accent: ""
theme.font.size: 13
directory.show-channel-avatars: undefined
directory.hide-live: false
directory.hidden.reveal: false
directory.hidden.style: 2
channel.panel-tips: false
channel.auto-click-chat: true
player.gain.enable: false
player.gain.no-volume: false
player.volume-always-shown: false
player.ext-interaction: true
player.hide-mouse: true
player.ext-hide: 0
player.captions.font-size: ""
player.captions.font-family: ""
player.compressor.enable: true
player.compressor.shortcut: null
player.no-autoplay: false
player.home.autoplay: true
player.button.pip: false
player.button.reset: true
player.gain.min: 0
player.gain.max: 2
player.compressor.default: false
player.allow-catchup: true
player.hide-event-bar: false
metadata.host-button: false
ffz.show-new-settings: true
channel.extra-links: false
sub-button.prime-notice: false
channel.hosting.enable: false
ffz.search.matches-only: false

experiments
-------------------------------------------------------------------------------
Unique ID: UgP0DXe4rNxHdc57qPZoc2IW3DldEa3y

FFZ | API-Based Link Lookups: true (r:0.3)
Twitch | mse_in_workers: holdback (r:0.07, t:device_id)
Twitch | simplified_gifting_offer_presentment: custom_bottom_goals_anon_tiers (r:0.125, t:user_id)
Twitch | vxp_left_nav_hover_logged_in: treatment (r:0.25, t:user_id)
Twitch | creator_features_and_tools_creator_home_upsell: variant1 (r:0.33, t:user_id)
Twitch | extensions_installation_optimization: test (r:0.33, t:channel_id, c:colaway)
Twitch | Devsite_create_apps_form_recaptcha: variant1 (r:0.5, t:user_id)
Twitch | Twilight Player Core NPM Distribution (Public): variant-b (r:0.5, t:device_id)
Twitch | bits_top_nav_explanation : experiment (r:0.5, t:user_id)
Twitch | cf_wp_new_onboarding: variant (r:0.5, t:channel_id, c:colaway)
Twitch | giftcard_redemption_in_checkout: experiment (r:0.5, t:device_id)
Twitch | prime_gaming_crown_filter_menu: control (r:0.5, t:user_id)
Twitch | reduce_subs_confusion: control (r:0.5, t:device_id)
Twitch | sda_post_fill_drop: control (r:0.5, t:device_id)
Twitch | seamless_subscription_upgrades: control (r:0.5, t:user_id)
Twitch | subs_pif: thank_first (r:0.5, t:user_id)
Twitch | sunlight_broadcast_page_experiment: variant (r:0.5, t:user_id)
Twitch | v6s_versions: control (r:0.5, t:device_id)
Twitch | the_sill: control (r:0.6, t:user_id)
Twitch | upcoming_schedules_directory_page: active (r:0.8, t:device_id)
Twitch | better_onsite_gift_notifications: control (r:0.9, t:user_id)
Twitch | bits_skus_reduction: control (r:0.95, t:user_id)
Twitch | chat_history: control (r:0.95, t:user_id)
Twitch | sidenav_active_gift: control (r:0.95, t:user_id)
Twitch | vxp_hide_miniplayer: control (r:0.95, t:device_id)
Twitch | liverecs_holdout_device: control (r:0.98, t:device_id)
Twitch | liverecs_holdout_v2: control (r:0.98, t:user_id)
Twitch | TWILIGHT_CAROUSEL_HOLDBACK: control (r:0.99, t:device_id)
Twitch | community_insights: treatment (r:0.99, t:channel_id, c:colaway)
Twitch | warp_web_prod: control (r:0.99, t:device_id)

addons
-------------------------------------------------------------------------------
Known
7tv-emotes | enabled | external | undefined v2.2.1
brcm | disabled | brcm v1.0.0
chatterino-badges | disabled | Chatterino v1.0.0
deck | disabled | Deck v2.0.1
ffzap-bttv | enabled | external | FFZ:AP BTTV v3.2.10
ffzap-core | enabled | FFZ:AP Core v3.3.6
ffzap-liriklive | disabled | FFZ:AP LirikLIVE v3.2.2
first-message-highlighter | disabled | first_msg_highlight v1.0.0
fs-chat | disabled | fs-chat v1.4.4
inline-tab-completion | disabled | Inline Tab v1.2.4
ModTools | disabled | Mod Tools v1.0.1
new-account-highlighter | disabled | New Account Highlighter v1.1.1
poll-shim | disabled | poll_shim v0.2.2
pronouns | disabled | pronouns v1.1.0
repetition-detector | disabled | repetition_detector v1.1.0
smokemotes | disabled | smokeys_utils v1.1.5

Modules
loaded   | enabled  | 
loaded   | enabled  | core
loaded   | enabled  | settings
loaded   | enabled  | experiments
loaded   | enabled  | i18n
loaded   | enabled  | socket
loaded   | enabled  | site.web_munch
loaded   | enabled  | site.fine
loaded   | enabled  | site.elemental
loaded   | enabled  | site.router
loaded   | enabled  | site.apollo
loaded   | enabled  | site.twitch_data
loaded   | enabled  | site.switchboard
loaded   | enabled  | site.subpump
loaded   | enabled  | site
loaded   | enabled  | addons
loaded   | enabled  | vue
loaded   | enabled  | tooltips
loaded   | disabled | chat/actions
loaded   | enabled  | chat.badges
loaded   | enabled  | chat.emotes
loaded   | enabled  | chat.emoji
loaded   | enabled  | chat.actions
loaded   | enabled  | chat.overrides
loaded   | enabled  | chat
loaded   | enabling | main_menu
loaded   | enabled  | metadata
loaded   | enabled  | site.bits_button
loaded   | enabled  | site.bttv_compat
unloaded | disabled | translation_ui
loaded   | enabled  | site.css_tweaks
loaded   | enabled  | site.channel
loaded   | enabled  | site.chat.scroller
loaded   | enabled  | site.chat.chat_line.rich_content
loaded   | enabled  | site.chat.chat_line
loaded   | enabled  | site.chat.settings_menu
loaded   | enabled  | site.chat.emote_menu
loaded   | enabled  | site.chat.input
loaded   | enabled  | site.chat.viewer_cards
loaded   | enabled  | site.chat
loaded   | enabled  | site.compat_emote_menu
loaded   | enabled  | site.dashboard
loaded   | enabled  | site.directory.game
loaded   | enabled  | site.directory
loaded   | enabled  | site.featured_follow
loaded   | enabled  | site.host_button
loaded   | enabled  | site.layout
loaded   | enabled  | site.menu_button
loaded   | enabled  | site.mod-view
loaded   | enabled  | site.player
loaded   | enabled  | site.sub_button
loaded   | enabled  | site.theme
loaded   | enabled  | site.video_chat
loaded   | enabled  | addon.ffz-enhancing-addon
loaded   | enabled  | addon.7tv-emotes
loaded   | enabled  | addon.ffzap-core
loaded   | enabled  | addon.ffzap-bttv

chat
-------------------------------------------------------------------------------
chat settings
-------------------------------------------------------------------------------
chat.badges.fix-colors: true
theme.can-dark: true
theme.is-dark: true
chat.badges.style: 1
chat.badges.clickable: 0
chat.badges.version: 2
chat.filtering.color-mentions: false
chat.actions.inline: [{"action":"ban","appearance":{"type":"icon","icon":"ffz-i-block"},"options":{},"display":{"mod":true,"mod_icons":true,"deleted":false}},{"action":"unban","appearance":{"type":"icon","icon":"ffz-i-ok"},"options":{},"display":{"mod":true,"mod_icons":true,"deleted":true}},{"action":"timeout","appearance":{"type":"icon","icon":"ffz-i-clock"},"display":{"mod":true,"mod_icons":true}},{"action":"msg_delete","appearance":{"type":"icon","icon":"ffz-i-trash"},"options":{},"display":{"mod":true,"mod_icons":true}},{"action":"reply","appearance":{"type":"icon","icon":"ffz-i-reply"},"options":{},"display":{}}]
chat.scroller.freeze-requires-hover: false
chat.scroller.hover-delay: 750
chat.scroller.freeze: 2
chat.scroller.smooth-scroll: 0
chat.input.hide-identity: true
chat.emote-menu.enabled: true
chat.emote-menu.icon: true
chat.emoji.style: "twitter"
chat.actions.room-above: false
chat.actions.room: []
chat.tab-complete.emotes-without-colon: true
chat.emotes.2x: 0
chat.emotes.limit-size: true
chat.input.show-mod-view: true
chat.lines.padding: true
chat.bits.show: false
chat.bits.show-pinned: true
chat.filtering.deleted-style: 0
chat.filtering.clickable-mentions: false
chat.filtering.bold-mentions: true
chat.hide-community-highlights: false
chat.lines.alternate: true
chat.filtering.highlight-mentions: true
chat.filtering.highlight-tokens: false
chat.filtering.mention-color: "#356205"
chat.adjustment-mode: 1
chat.adjustment-contrast: 4.5
theme.color.chat-background: ""
theme.color.background: ""
theme.color.chat-text: ""
theme.color.text: ""
chat.lines.borders: 0
chat.bits.animated: true
theme.tooltips-dark: false
chat.width: null
chat.effective-width: 340
chat.actions.size: 16
chat.timestamp-size: null
chat.font-size: 13
chat.lines.emote-alignment: 0
chat.font-family: ""
chat.delay: 0
chat.scrollback-length: 500
chat.filtering.remove-deleted: 0
addon.7tv_emotes.global_emotes: true
addon.7tv_emotes.channel_emotes: true
ffzap.core.highlight_sound: "https://cdn.ffzap.com/sounds/default_wet.mp3"
ffzap.core.highlight_sound_types: ["badge","mention","term","user"]
ffzap.core.enable_highlight_sound: false
ffzap.core.message_deletion: 0
ffzap.core.highlight_sound_volume: 50
ffzap.betterttv.global_emoticons: true
ffzap.betterttv.pro_emoticons: true
ffzap.betterttv.channel_emoticons: true
chat.subs.gift-banner: true
chat.banners.hype-train: true
chat.banners.prediction: true
chat.banners.polls: true
chat.banners.drops: true
ffzap.betterttv.arbitrary_emoticons: true
chat.filtering.blocked-types: {}
chat.filtering.debug: false
chat.filtering.highlight-basic-users-blocked: []
__filter:block-users: null
chat.filtering.highlight-basic-blocked: []
__filter:block-terms: null
chat.filtering.highlight-basic-badges: []
__filter:highlight-badges: null
chat.filtering.highlight-basic-badges-blocked: []
__filter:block-badges: null
chat.filtering.highlight-basic-users: []
__filter:highlight-users: null
chat.filtering.highlight-basic-terms: [{"v":"@Crazy_Wolf_Ahuuu","t":"text","c":"#186305","s":false,"h":false,"w":true,"p":0,"remove":false},{"v":"@crazy_wolf_ahuuu","t":"text","c":"#185B07","s":false,"h":false,"w":true,"p":0,"remove":false}]
__filter:highlight-terms: {"hl":null,"non":[[0,"#186305",[null,{}]],[0,"#185B07",[null,{}]]]}
chat.emotes.enabled: 2
chat.emotes.animated: 1
chat.fix-bad-emotes: true
chat.emoji.replace-joiner: 2
chat.filtering.mention-priority: 0
ffzap.core.remove_spaces: false
chat.replies.style: 1
chat.filtering.display-deleted: "DETAILED"
chat.points.allow-highlight: 2
chat.rich.enabled: true
chat.rich.minimum-level: 0
chat.rich.want-mid: false
chat.rich.all-links: false
chat.name-format: 0
chat.badges.hidden: {"m-tcon":false,"m-other":false,"m-game":false,"m-addon":false,"m-owl":false,"premium":true,"moderator":false}
chat.badges.custom-mod: true
chat.badges.custom-vip: true
chat.timestamp-format: "H:mm"
layout.portrait: true
layout.portrait-threshold: 1.25
layout.use-portrait: false
layout.portrait-min-chat: false
chat.points.show-rewards: true
chat.points.show-button: true
chat.emote-menu.combine-tabs: true
chat.emote-menu.stay-loaded: true
chat.emote-menu.show-quick-nav: true
chat.emote-menu.show-heading: 1
chat.emote-menu.tall: false
chat.emote-menu.reduced-padding: true
chat.emote-menu.show-search: false
chat.emote-menu.sort-emotes: 4
chat.emote-menu.sort-tiers-last: true
chat.emote-menu.show-emoji: true

**Comment by SirStendec** [comment]
This is an issue with Twitch's chat input component and something they need to fix, it's unrelated to FFZ.

**Comment by CrazySaft** [comment]
Oh okay thanks i just thought ist caused by your (FFZ)Emote menu not twitchs main emote menu

**Comment by CrazySaft** [comment]
> This is an issue with Twitch's chat input component and something they need to fix, it's unrelated to FFZ.

Thanks for quick response
