### ISSUE TITLE
Video tools are currently simply missing

### ISSUE THREAD

**Issue by jandraelune** [FrankerFaceZ/FrankerFaceZ#1209]
**Describe the bug**
Audio Compressor and Video Refresh being a couple

**To Reproduce**
Just open a stream

**Expected behavior**
The buttons for the features are simply missing

**Screenshots**

**Environment (please complete the following information):**
 - OS: Win10
 - Browser: Chrome
 - Version: 101.0.4951.54
 - Other Extensions: 

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:

**Additional context**

**Comment by Caittus** [comment]
Per issue #1210, blocking ##.stream-display-ad__wrapper restored Audio Compressor and Reset Player.
