### ISSUE TITLE
chat

### ISSUE THREAD

**Issue by fox112** [FrankerFaceZ/FrankerFaceZ#121]
faling out of chat when i use frankerfacez i have try disabel frankerfacez and the chat works normaly some times i need to refresh 3-5 times before video load have try to disabel frankerfacez and everything works normaly again with out frankerfacez this issues i have for over 5 months now why is it fix?

**Comment by SirStendec** [comment]
You need to use the issue template if you want help. It prompts you to provide information that I need to help diagnose problems and help people.

That said, I'm going to assume that you are a BetterTTV user as there is a known problem with it that causes loading problems. If you aren't, please open a new issue and use the template.
