### ISSUE TITLE
custom speed for "Allow the player to speed up to reduce delay"

### ISSUE THREAD

**Issue by Chat-mots** [FrankerFaceZ/FrankerFaceZ#1212]
**Problem :**
When you have too much delay on a stream, the speed of the video player became 1,03.
Sometimes you have a lot of delay and you still want to watch what happens (not refreshing the player). 

**Enhancement :**
Adding a custom speed would be useful. 
For exemple : having the player going at a speed of 1,30 or 1,80 or even 5 when you have a big delay to catch up is a good alternative if you don't want to refresh the player. And the video would go back at a normal speed once the delay has been reduced.

**an (imperfect) alternative :**
I use an application that can change the speed of any video, however the acceleration and slowing of the video has to be done manually. And if you catch up the stream and still go too fast, the video will be paused and recharged (while ffz stops at the right moment, and puts the video at a normal speed)

**Comment by SirStendec** [comment]
Speeding up in that way is an internal feature to Twitch's player and not something FFZ implements. There is no API for FFZ to use to change the catch-up playback speed and the actual playback rate is being set within web assembly and isn't something FFZ can somehow reflect into and change.

While I could probably set a playback rate on the `<video>` element and it might work, I would rather just not deal with it. There's less data available to FFZ about the state of buffered content than I would prefer for doing something like that.
