### ISSUE TITLE
viewer list auto refresh +bots check

### ISSUE THREAD

**Issue by bel57** [FrankerFaceZ/FrankerFaceZ#1213]
Hello, I don't know if feasible, perhaps too complex?

Feature request to have FFZ auto refresh viewers/users list on the right pane from time to time and check if listed nicknames are known to be bots (can check against https://www.twitchbots.info/api or https://twitchinsights.net/bots API/database). If true, highlight username/pop an alert.

Additional/alternative feature request: whitelist system, chat and right pane: have some UI for users management, the end result would be to display a checkmark symbol/icon or highlight in a specific color the name of known/regulars/approved users who aren't bots. Or the other way, display a cross symbol/ red color for suspicious users.

As of now I'm doing the checking process manually. Would be a great help as a mod to have FFZ handle that so I can focus more on the stream. Might be too ambitious/too much? Thanks for reading me.

**Comment by SirStendec** [comment]
If someone is being a problematic chatter, there are already moderation tools for dealing with that. If someone isn't being a problematic chatter and is just in the viewer list, then what's the problem?

I'm not interested in implementing any features that interact with the viewer list in any way.
