### ISSUE TITLE
[Feature Request] Forced vertical mode

### ISSUE THREAD

**Issue by duckyb** [FrankerFaceZ/FrankerFaceZ#1217]
**Is your feature request related to a problem? Please describe.**

I hate when I'm using theater mode, make the window as large as my screen and the chat goes to the side of the video making it much smaller.

**Describe the solution you'd like**

I would like to have the large window and the chat below at the same time.

**Describe alternatives you've considered**

An alternative is making the video full screen but then I completely lose access to the chat and my OS taskbar

**Additional context**

| Small window | Full-width |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/27895007/169568802-e4cce3c1-9d54-40f3-b835-f8bfb941240b.png) | ![image](https://user-images.githubusercontent.com/27895007/169568853-4a1a6ec4-daa9-48fd-8f62-f3bffaaf2c19.png) |

**Comment by SirStendec** [comment]
Just change the portrait mode threshold to a value that makes it behave how you want. Even `1.26` is probably enough for the aspect ratio in the second picture.

**Comment by duckyb** [comment]
Awesome, I didn't know of this setting. Thank you so much!
