### ISSUE TITLE
[Feature request] Double click « @nickname, »

### ISSUE THREAD

**Issue by imzxc** [FrankerFaceZ/FrankerFaceZ#122]
**Web Browser**: Chrome.

**Do you use BetterTTV or other Twitch extensions**: FFZ.

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: -.

**Bug / Idea**: Double click to paste @ and nickname in chat bar. « @nickname, »

**Steps to Reproduce (if Applicable)**: -.

**Comment by SirStendec** [comment]
I don't plan on implementing a feature like this. Aside from feeling that it isn't a very intuitive form of input, detecting double-click events properly would create input lag for single-click events in chat and I'm really not satisfied with that.
