### ISSUE TITLE
Option to hide channel point suggetion pop-up in chat.

### ISSUE THREAD

**Issue by Fjara-h** [FrankerFaceZ/FrankerFaceZ#1225]
I like a relatively uncluttered chat, I want to read what people say and not see random things I don't really care about. Upon earning enough channel points to use a channel point reward, there is a popup/fake chat message box thing that pops up saying "Spend your points on <channel reward>" with a button to do so.

A switch to toggle display of the unique element class. I don't think there are alternatives.

![image](https://user-images.githubusercontent.com/22579764/172962831-4da70824-966d-49af-9f07-f6add7fc00de.png)

**Comment by SirStendec** [comment]
You should be able to hide messages like that by hiding the message type "InlinePrivateCallout" within Chat > Filtering > Block. I don't plan on a specific feature to hide those otherwise.
