### ISSUE TITLE
Sidebar Hover Over to Expand

### ISSUE THREAD

**Issue by alkaris2** [FrankerFaceZ/FrankerFaceZ#1229]
**Is your feature request related to a problem? Please describe.**
Twitch has done something to their side where the sidebar no longer expands the sidebar when you hover your mouse over the sidebar.

**Describe the solution you'd like**
Just to have the ability to hover mouse cursor over the sidebar again to expand it.

**Describe alternatives you've considered**
Nothing, this is Twitch doing weird changes to the site.

**Additional context**
none.

**Comment by Tassader** [comment]
Try changing Debugging->Experiments->Twitch Experiments
vxp_left_nav_hover_logged_in from control (weight:100) to treatment (weight:0)

I have no idea what it is supposed to do, but it seems to help :D

**Comment by alkaris2** [comment]
it was a little buggy at first, but that certainly worked.

**Comment by Tassader** [comment]
Hm while it works, you need to do it again after every browser restart as the experiments don't get saved apparently :-(
