### ISSUE TITLE
Stop certain emotes from being suggested via tab autocomplete

### ISSUE THREAD

**Issue by TBloop** [FrankerFaceZ/FrankerFaceZ#1246]
**Is your feature request related to a problem? Please describe.**

There are several emotes that I will *never* use, and they constantly get in the way when I try to type other emotes. I would like to put them on a blacklist so that they will never be suggested. 

For example, some channels have OMEGALICK enabled and it always shows up first when I try to type OMEGALUL instead. It's so annoying. 

**Describe the solution you'd like**

An emote blacklist that enables you to add (and remove) certain emotes that will never be suggested when you use tab autocomplete. I would still be able to see them in chat if someone else typed them or if I typed it out manually, but it would not be suggested when I press tab to autocomplete the emote. 

**Describe alternatives you've considered**

I cannot think of any alternative. I looked through all the settings and cant see a workaround.

**Comment by SirStendec** [comment]
If you hide an emote from the FFZ Emote Menu using the provided visibility controls, FFZ will also prevent those emotes from appearing in auto-complete.

**Comment by TBloop** [comment]
Hi,

Thanks for the reply. 

I'm pulling my hair out. I've literally spent over 30 minutes trying to find the visibility controls for the emotes. I know I've done it before but that may have been in BTTV. 

Not even google could help me. I clicked on everything I could find. Help, please!
