### ISSUE TITLE
[Feature Request] Real time chat translations

### ISSUE THREAD

**Issue by TheRightScript** [FrankerFaceZ/FrankerFaceZ#1256]
**Is your feature request related to a problem? Please describe.**
Often times when watching a stream in another language the chat will be in the streamers native language. It would be amazing if the messages that are going through the chat can be run through google translate in real time.

This would help bridge the gap caused by the language barrier. Often times even if you can't fully understand the streamer, you can understand enough based off of the context clues given from chat. It would also decrease toxicity in chats where users simply do not understand each other. Having this feature would also massively help in situations where a translation would allow viewers to understand the stream rules or any automatic messages from stream bots/mods.

**Describe the solution you'd like**
A button, setting or addon that can be toggled to auto translate all chat messages using google translate to your target language in real time. 

**Describe alternatives you've considered**
Currently if I right click the page and use google translate to translate the page it will translate everything including whatever was typed in chat, however this doesn't apply to new chat messages. In order to translate those messages as well I have to turn off the full page translation and then do it again. This isn't really an issue in a slow moving chat but any chat where people are constantly talking it's just not feasible. 

Perhaps there is a script that can just refresh the google full page translation. About half a year to a year ago the full page google translation would keep translating all the new chat messages on the page, but at some point this functionality stopped. 

There is a youtube extension called LiveTL/HyperChat that performs this exact function, so perhaps doing whatever they did may help streamline your own process.

**Comment by SirStendec** [comment]
There are no cost effective translation APIs. BetterTTV used to provide a translation feature, but they had to stop and as far as I know it was because of cost.

It's unfortunate, but it's not a feature we can afford to offer. I might try looking into why Chrome's native translation feature isn't properly handling dynamic content, though.
