### ISSUE TITLE
Experiment keeps un-toggling itself

### ISSUE THREAD

**Issue by Zoooook** [FrankerFaceZ/FrankerFaceZ#1259]
I have the wysiwyg editor disabled, via the wysiwyg_chat_input_user_id experiment. Every so often, maybe once a week or so, it re-enables itself, the experiment resets to default. I notice because emotes start displaying themselves in the chat box again, and then I go disable it again. When I do this, it's always a different word I have to type to access experiments, which makes me think FFZ updated itself. The experiment should stay off once I've turned it off.

 - OS: Windows 8.1
 - Browser: Chromium Version 102.0.5005.115 (Developer Build, ungoogled-chromium) (64-bit)
 - Other Extensions: uBlock Origin, DarkReader

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:

initialization
-------------------------------------------------------------------------------
[15:35:57] info | core: FrankerFaceZ v4.36.1 (s:twitch f:main b:7f63fc1f0b55e82fbc87 c:39abc9df4893f02bb554110d5c13947ab00b5f94)
[15:35:57] info | core: Initial URL: https://www.twitch.tv/
[15:35:57] info | site: Using: Twilight
[15:35:57] info | site.web_munch: Found and wrapped webpack's loader after 0ms.
[15:35:57] info | settings: Using Provider: LocalStorageProvider
[15:35:57] info | core: Loaded descriptions of 0 modules.
[15:35:57] info | settings: Initialization complete after 32.00000ms -- Values: 108 -- Profiles: 2
[15:35:57] info | site.fine: Installing MutationObserver.
[15:35:57] info | site.switchboard: Found Route and Switch with 13 routes.
[15:35:57] info | site: Loaded descriptions of 17 modules.
[15:35:57] info | site.elemental: Installing MutationObserver.
[15:35:57] info | site.web_munch: require() grabbed in 262.30000ms.
[15:35:57] info | experiments: Loaded information on 2 experiments.
[15:35:57] info | socket: Using Server: wss://yoohoo.frankerfacez.com/
[15:35:58] info | core: Initialization complete in 367.10000ms.

settings
-------------------------------------------------------------------------------
i18n.debug.capture: false
i18n.format.date: "default"
i18n.format.time: "short"
i18n.format.datetime: "medium"
i18n.debug.transform: null
i18n.locale: "en"
addons.dev.server: false
socket.use-cluster: "Production"
chat.bits.show: true
layout.display-bits-button: false
metadata.modview.hide-info: false
layout.side-nav.hide-viewers: false
metadata.uptime: 1
metadata.uptime.no-native: true
metadata.viewers: true
metadata.viewers.no-native: true
layout.swap-sidebars: false
layout.portrait: false
layout.portrait-threshold: 1.25
layout.use-portrait: false
chat.width: null
chat.use-width: false
layout.use-chat-fix: false
layout.theatre-navigation: false
layout.minimal-navigation: false
layout.side-nav.show-avatars: false
layout.side-nav.show: true
layout.side-nav.hide-offline: true
layout.hide-discover-luna: false
layout.prime-offers: false
layout.discover: false
channel.hide-unfollow: false
channel.round-avatars: true
channel.hide-live-indicator: true
layout.side-nav.rerun-style: 2
layout.side-nav.show-rec-channels: 0
layout.side-nav.show-friends: 1
whispers.show: true
channel.show-celebrations: true
layout.theme.global-font: ""
layout.portrait-invert: false
layout.portrait-min-chat: false
layout.inject-portrait: false
layout.use-portrait-swapped: false
player.theatre.metadata: false
layout.use-portrait-meta: false
layout.use-portrait-meta-top: false
layout.portrait-extra-width: 24
player.theatre.no-whispers: false
layout.portrait-extra-height: 14
theme.disable-auto-dark: false
theme.can-dark: true
theme.is-dark: true
theme.color.background: "#0B0F0F"
theme.color.text: "#9FDFDF"
theme.color.accent: ""
theme.color.tooltip.background: ""
theme.color.tooltip.text: ""
theme.color.chat-background: ""
theme.color.chat-text: ""
theme.color.chat-accent: ""
theme.font.size: 13
directory.show-channel-avatars: false
directory.hide-live: true
directory.hidden.reveal: false
directory.hidden.style: 2
channel.panel-tips: false
channel.auto-click-chat: false
player.gain.enable: false
player.gain.no-volume: false
player.volume-always-shown: true
player.ext-interaction: true
player.hide-mouse: true
player.ext-hide: 2
player.captions.font-size: ""
player.captions.font-family: ""
player.compressor.enable: true
player.compressor.shortcut: null
player.hide-event-bar: false
addon.fs-chat.bg.blur: 0
addon.fs-chat.height: null
addon.fs-chat.width: null
addon.fs-chat.bg.color: "rgba(0,0,0,0.50)"
addon.fs-chat.automatic: false
addon.fs-chat.shortcut: "alt+c"
directory.hide-recommended: true
directory.block-titles: []
__filter:directory.block-titles: null
directory.uptime: 1
directory.hide-vodcasts: true
player.force-visible: undefined
channel.hosting.enable: true
player.no-autoplay: false
player.home.autoplay: false
player.button.pip: false
player.button.reset: false
player.gain.min: 0
player.gain.max: 2
player.compressor.default: false
player.allow-catchup: false
ffz.show-new-settings: true
channel.extra-links: true
player.theatre.auto-enter: false
metadata.host-button: false
sub-button.prime-notice: true
player.volume-scroll: true
player.gain.scroll: false
player.volume-scroll-steps: 0.01
metadata.clip-download: true
metadata.featured-follow: true
metadata.player-stats: true
metadata.stream-delay-warning: 10
player.mute-click: false
debug.link-resolver.source: null
channel.raids.no-autojoin: false
ffz.search.matches-only: true

experiments
-------------------------------------------------------------------------------
Unique ID: qKsUKi9XTvzzCrchqvoMUBEXkOCrkjOB

FFZ | API-Based Link Lookups: false (r:0.7)
Twitch | one_click: variant_1 (r:0, t:device_id)
Twitch | wysiwyg_chat_input_user_id: control (Override) (r:0, t:user_id)
Twitch | warp_web_prod: treatment (r:0.01, t:device_id)
Twitch | sidenav_active_gift: variant (r:0.05, t:user_id)
Twitch | consent_tool_headline: control (r:0.16, t:device_id)
Twitch | extensions_installation_optimization: control (r:0.34, t:channel_id, c:zoasty)
Twitch | Devsite_create_apps_form_recaptcha: variant1 (r:0.5, t:user_id)
Twitch | Twilight Player Core NPM Distribution (Public): variant-b (r:0.5, t:device_id)
Twitch | bits_top_nav_explanation : control (r:0.5, t:user_id)
Twitch | cf_wp_new_onboarding: control (r:0.5, t:channel_id, c:zoasty)
Twitch | giftcard_redemption_in_checkout: experiment (r:0.5, t:device_id)
Twitch | k_p: treatment (r:0.5, t:device_id)
Twitch | last_x_events_user_level: events (r:0.5, t:user_id)
Twitch | reduce_subs_confusion: experiment (r:0.5, t:device_id)
Twitch | sda_post_fill_drop: control (r:0.5, t:device_id)
Twitch | spotlight_to_dashboard_entry: variant (r:0.5, t:user_id)
Twitch | studio_default_layout_change: control (r:0.5, t:user_id)
Twitch | studio_transition_ui: variant (r:0.5, t:device_id)
Twitch | subs_pif: thank_first (r:0.5, t:user_id)
Twitch | subscriber_recap: variant 1 (r:0.5, t:channel_id, c:zoasty)
Twitch | v6s_versions: treatment (r:0.5, t:device_id)
Twitch | v8_turbo: treatment (r:0.5, t:user_id)
Twitch | xsolla_back_button_checkout: control (r:0.5, t:user_id)
Twitch | com30_ssoln: control (r:0.8, t:user_id)
Twitch | second_pincer_manuever_jackie_chan: control (r:0.8, t:user_id)
Twitch | bits_skus_reduction: control (r:0.95, t:user_id)
Twitch | chat_history: control (r:0.95, t:user_id)
Twitch | simplify_support_panel_resub: control (r:0.95, t:user_id)
Twitch | vxp_hide_miniplayer: control (r:0.95, t:device_id)
Twitch | liverecs_holdout_device: control (r:0.98, t:device_id)
Twitch | liverecs_holdout_v2: control (r:0.98, t:user_id)
Twitch | TWILIGHT_CAROUSEL_HOLDBACK: control (r:0.99, t:device_id)
Twitch | community_insights: treatment (r:0.99, t:channel_id, c:zoasty)

addons
-------------------------------------------------------------------------------
Known
7tv-emotes | disabled | 7TV v1.3.0
aplatypuss-emotes | disabled | Aplatypuss Emotes v1.0.0
ffzap-core | enabled | FFZ:AP Core v3.3.6
brcm | disabled | brcm v1.0.0
chatterino-badges | disabled | Chatterino v1.0.0
deck | disabled | Deck v2.2.1
emoteless | disabled | emote_less_chat v1.0.5
ffzap-bttv | enabled | FFZ:AP BTTV v3.2.10
ffzap-liriklive | enabled | FFZ:AP LirikLIVE v3.2.2
first-message-highlighter | disabled | first_msg_highlight v1.0.0
fs-chat | enabled | fs-chat v1.5.0
inline-tab-completion | disabled | Inline Tab v1.2.4
ModTools | disabled | Mod Tools v1.0.1
new-account-highlighter | disabled | New Account Highlighter v1.1.1
poll-shim | disabled | poll_shim v0.2.2
prattlenot | disabled | PrattleNot v0.5.0
pronouns | disabled | pronouns v1.1.0
repetition-detector | disabled | repetition_detector v1.1.0
smokemotes | disabled | smokeys_utils v1.1.5

Modules
loaded   | enabled  | 
loaded   | enabled  | core
loaded   | enabled  | settings
loaded   | enabled  | experiments
loaded   | enabled  | i18n
loaded   | enabled  | socket
loaded   | enabled  | site.web_munch
loaded   | enabled  | site.fine
loaded   | enabled  | site.elemental
loaded   | enabled  | site.router
loaded   | enabled  | site.apollo
loaded   | enabled  | site.twitch_data
loaded   | enabled  | site.switchboard
loaded   | enabled  | site.subpump
loaded   | enabled  | site
loaded   | enabled  | addons
loaded   | enabled  | vue
loaded   | enabled  | tooltips
loaded   | disabled | chat/actions
loaded   | enabled  | chat.badges
loaded   | enabled  | chat.emotes
loaded   | enabled  | chat.emoji
loaded   | enabled  | chat.actions
loaded   | enabled  | chat.overrides
loaded   | enabled  | chat
loaded   | enabled  | main_menu
loaded   | enabled  | metadata
loaded   | enabled  | site.bits_button
loaded   | enabled  | site.bttv_compat
unloaded | disabled | translation_ui
loaded   | enabled  | site.css_tweaks
loaded   | enabled  | site.channel
loaded   | enabled  | site.chat.scroller
loaded   | enabled  | site.chat.chat_line.rich_content
loaded   | enabled  | site.chat.chat_line
loaded   | enabled  | site.chat.settings_menu
loaded   | enabled  | site.chat.emote_menu
loaded   | enabled  | site.chat.input
loaded   | enabled  | site.chat.viewer_cards
loaded   | enabled  | site.chat
loaded   | enabled  | site.compat_emote_menu
loaded   | enabled  | site.dashboard
loaded   | enabled  | site.directory.game
loaded   | enabled  | site.directory
loaded   | enabled  | site.featured_follow
loaded   | enabled  | site.host_button
loaded   | enabled  | site.layout
loaded   | enabled  | site.menu_button
loaded   | enabled  | site.mod-view
loaded   | enabled  | site.player
loaded   | enabled  | site.sub_button
loaded   | enabled  | site.theme
loaded   | enabled  | site.video_chat
loaded   | enabled  | addon.ffzap-core
loaded   | enabled  | addon.ffzap-bttv
loaded   | enabled  | addon.ffzap-liriklive
loaded   | enabled  | addon.fs-chat

chat
-------------------------------------------------------------------------------
chat settings
-------------------------------------------------------------------------------
chat.badges.fix-colors: true
theme.can-dark: true
theme.is-dark: true
chat.badges.style: 1
chat.badges.clickable: 0
chat.badges.version: 2
chat.filtering.color-mentions: true
chat.actions.inline: [{"action":"ban","appearance":{"type":"icon","icon":"ffz-i-block"},"options":{},"display":{"mod":true,"mod_icons":true,"deleted":false}},{"action":"unban","appearance":{"type":"icon","icon":"ffz-i-ok"},"options":{},"display":{"mod":true,"mod_icons":true,"deleted":true}},{"action":"timeout","appearance":{"type":"icon","icon":"ffz-i-clock"},"display":{"mod":true,"mod_icons":true}},{"action":"msg_delete","appearance":{"type":"icon","icon":"ffz-i-trash"},"options":{},"display":{"mod":true,"mod_icons":true}},{"action":"reply","appearance":{"type":"icon","icon":"ffz-i-reply"},"options":{},"display":{}}]
chat.scroller.freeze-requires-hover: true
chat.scroller.hover-delay: 750
chat.scroller.freeze: 0
chat.scroller.smooth-scroll: 0
chat.input.hide-identity: false
chat.emote-menu.enabled: true
chat.emote-menu.icon: false
chat.emoji.style: 0
chat.emotes.2x: 1
chat.emotes.limit-size: false
chat.banners.last-events: true
chat.input.show-mod-view: true
chat.lines.padding: true
chat.bits.show: true
chat.bits.show-pinned: true
chat.filtering.deleted-style: 0
chat.filtering.clickable-mentions: true
chat.filtering.bold-mentions: true
chat.hide-community-highlights: false
chat.lines.alternate: false
chat.filtering.highlight-mentions: true
chat.filtering.highlight-tokens: true
chat.filtering.mention-color: ""
chat.adjustment-mode: 1
chat.adjustment-contrast: 4.5
theme.color.chat-background: ""
theme.color.background: "#0B0F0F"
theme.color.chat-text: ""
theme.color.text: "#9FDFDF"
chat.lines.borders: 0
ffzap.core.highlight_sound: "https://cdn.ffzap.com/sounds/default_wet.mp3"
ffzap.core.highlight_sound_types: ["badge","mention","term","user"]
ffzap.core.enable_highlight_sound: false
ffzap.core.message_deletion: 0
ffzap.core.highlight_sound_volume: 50
ffzap.betterttv.global_emoticons: true
ffzap.betterttv.pro_emoticons: true
ffzap.liriklive.global_emoticons: true
ffzap.liriklive.sub_emoticons: true
ffzap.betterttv.arbitrary_emoticons: true
chat.width: null
chat.effective-width: 340
chat.actions.size: 16
chat.timestamp-size: null
chat.font-size: 13
chat.lines.emote-alignment: 0
chat.font-family: ""
chat.subs.gift-banner: true
chat.banners.hype-train: true
chat.banners.prediction: true
chat.banners.polls: true
chat.banners.drops: true
chat.tab-complete.emotes-without-colon: false
chat.actions.room-above: true
chat.delay: 0
chat.scrollback-length: 9999
chat.filtering.remove-deleted: 0
chat.filtering.blocked-types: {}
chat.actions.room: []
ffzap.betterttv.channel_emoticons: true
chat.bits.animated: true
theme.tooltips-dark: false
layout.portrait: false
layout.portrait-threshold: 1.25
layout.use-portrait: false
layout.portrait-min-chat: false
chat.points.show-rewards: true
chat.points.show-button: true
chat.emote-menu.combine-tabs: true
chat.emote-menu.stay-loaded: true
chat.emote-menu.show-quick-nav: true
chat.emotes.animated: 1
chat.emote-menu.show-heading: 1
chat.emote-menu.tall: false
chat.emote-menu.reduced-padding: false
chat.emote-menu.show-search: true
chat.emote-menu.sort-emotes: 4
chat.emote-menu.sort-tiers-last: true
chat.emote-menu.modifiers: 0
chat.fix-bad-emotes: true
chat.emotes.enabled: 2
chat.emote-menu.show-emoji: false
chat.filtering.debug: false
chat.filtering.highlight-basic-users-blocked: []
__filter:block-users: null
chat.filtering.highlight-basic-blocked: []
__filter:block-terms: null
chat.filtering.highlight-basic-badges: []
__filter:highlight-badges: null
chat.filtering.highlight-basic-badges-blocked: []
__filter:block-badges: null
chat.filtering.highlight-basic-users: []
__filter:highlight-users: null
chat.filtering.highlight-basic-terms: [{"remove":false,"v":"z+o+k+","t":"regex","c":"#00B0FF","w":true,"h":true,"p":0}]
__filter:highlight-terms: {"hl":[[0,"#00B0FF",[null,{}]]],"non":null}
chat.emoji.replace-joiner: 2
chat.filtering.mention-priority: 0
ffzap.core.remove_spaces: true
chat.replies.style: 0
chat.filtering.display-deleted: "DETAILED"
chat.points.allow-highlight: false
chat.rich.enabled: true
chat.rich.minimum-level: 0
chat.rich.want-mid: false
chat.rich.all-links: true
chat.name-format: 0
chat.badges.hidden: {}
chat.badges.custom-mod: true
chat.badges.custom-vip: true
chat.timestamp-format: "h:mm"
chat.filtering.hidden-tokens: {}
chat.subs.show: 3
chat.extra-timestamps: true
chat.subs.compact: false
chat.rich.hide-tokens: false
tooltip.images: true
tooltip.link-images: true
tooltip.link-nsfw-images: true
tooltip.emote-images.animated: true
tooltip.emote-images: true
tooltip.emote-sources: true
chat.click-emotes: true
chat.sub-emotes: true
chat.emote-dialogs: true
chat.mru.enabled: true
chat.filtering.process-own: false
tooltip.badge-images: true
chat.emote-menu.shortcut: true
chat.points.auto-rewards: false
chat.bits.stack: 0
chat.bits.cheer-notice: false
chat.me-style: 1
chat.points.show-callouts: false
chat.subs.merge-gifts: 0
chat.subs.merge-gifts-visibility: true
tooltip.rich-links: true
tooltip.link-interaction: true
chat.automod.run-as-mod: false

**Comment by Tassader** [comment]
For me the experiments reset like every 2 days, with no update of FFZ (or change the word to type)

**Comment by SirStendec** [comment]
This is intended behavior. Experiment controls are a developer feature, and I won't be making changes to how they function.
