### ISSUE TITLE
Option to copy a message without selection

### ISSUE THREAD

**Issue by x9136** [FrankerFaceZ/FrankerFaceZ#1265]
![Example](https://user-images.githubusercontent.com/60105060/184688427-b1b9253c-64b8-455d-9e30-01bf63a7079f.png)

**Comment by SirStendec** [comment]
Added in 8cd6545556fbfaaf663b7c383552dc0f77b655bf

**Comment by dpthegrey** [comment]
hi @SirStendec, I tried searching for "copy" in the Control Center but I am not able to see the option to enable copy message.

![image](https://github.com/FrankerFaceZ/FrankerFaceZ/assets/49444980/3c19d1c7-0014-4b16-bed7-cac10baff6b4)

the chat message also does not show a button to copy
![image](https://github.com/FrankerFaceZ/FrankerFaceZ/assets/49444980/2ee8b800-f793-4d86-845b-e661e356f242)

**Comment by x9136** [comment]
@dpthegrey 
<img width="965" alt="Screenshot 2023-11-28 at 02 23 30" src="https://github.com/FrankerFaceZ/FrankerFaceZ/assets/60105060/791b9164-5c9d-4fff-9001-97fcedfc314b">
