### ISSUE TITLE
Option to enable claiming of channel points on raid without following it

### ISSUE THREAD

**Issue by pointydev** [FrankerFaceZ/FrankerFaceZ#1270]
**Is your feature request related to a problem? Please describe.**
When a raid to another channel takes place, you are given the incentive that by following it you will be awarded with channel points in the source channel. Often I will join raids simply to gain these channel points, followed by returning to the previous channel or closing the tab entirely.

**Describe the solution you'd like**
Similar to the `Automatically claim bonus rewards.` option, I think a way to claim the reward while not following the raid to content that may not be of interest and/or be annoying to the viewer would be beneficial for users. If this were to be implemented, perhaps a way for users to manually rejoin raids if they are interested in following it may be useful, alongside the point claim.

**Describe alternatives you've considered**
There is already a feature to automatically leave/not join raids, however this does not grant the channel point incentive and therefore defeats my point.
![Autoleave](https://the.yog.zone/6qRzpgK.png)

Thanks,
Elliott

**Comment by SirStendec** [comment]
You don't deserve rewards for following a raid if you don't actually follow a raid.
