### ISSUE TITLE
Give Chatuser a specific own (nick/user)name

### ISSUE THREAD

**Issue by silez** [FrankerFaceZ/FrankerFaceZ#1272]
**Is your feature request related to a problem? Please describe.**
No there is no problem, everything is fine!

**Describe the solution you'd like**
I would like to have an option to change the username in chat to my own specific (user)name.

**Describe alternatives you've considered**
In bttv add-on you can do it by clicking chat usersname and then change it - but my workspace is with FFZ, imo the best add-on for twitch!

**Additional context**
Personally, I would just wish for a function where I can set the names in the twitch chat for myself. As already described above, this is possible with bttv. For me personally, that would be the only function that is "missing" to round off the package completely. As a twitch-mod even more extremely awesome!
Thanks for your great work!

**Comment by SirStendec** [comment]
Already a feature. You need to add a custom chat action, either as an in-line action or a user context action, to "Change Name & Color".
![image](https://user-images.githubusercontent.com/14036657/194631083-277e67f1-94fb-467e-b8e5-e58e73c22480.png)

**Comment by silez** [comment]
Oh wow... i did some custom chat actions already but i never read this user context action. Thank you so much. Now, FFZ is "more" perfect for me. The last thing i searched for 👍
