### ISSUE TITLE
Option to clear emote menu search on close

### ISSUE THREAD

**Issue by pointydev** [FrankerFaceZ/FrankerFaceZ#1273]
**Is your feature request related to a problem? Please describe.**
When I reopen the emote menu after a previous search, I usually want to search for a different emote, meaning I have to clear the search bar each time, adding extra keypresses.

**Describe the solution you'd like**
An option to clear the search box each time the emote menu is closed and/or a message is sent.

**Describe alternatives you've considered**
Disabling `Stay loaded after opening`, however not only would this decrease performance, it also doesn't seem to work.

**Additional context**
In the case that this isn't intended behaviour, here's my [current settings](https://the.yog.zone/7cfzpkX.png).

Thanks,
Elliott

**Comment by SirStendec** [comment]
Added in 8cd6545556fbfaaf663b7c383552dc0f77b655bf
