### ISSUE TITLE
[QoL] Show the hosting component despite disabling Show Channel Hosting

### ISSUE THREAD

**Issue by Infinitay** [FrankerFaceZ/FrankerFaceZ#1274]
**Is your feature request related to a problem? Please describe.**
I disable channel hosting because some streamers host a channel before they end their stream and still stream for a few more minutes. However, as a result, the div that displays which channel is being hosted is removed.

**Describe the solution you'd like**
I would like for the "hosting <channel>" div to appear under a streamer's title despite having disabled "Show Channel Hosting" option within FFZ.

**Describe alternatives you've considered**
N/A

**Additional context**
_With Show Channel Hosting disabled_
![image](https://user-images.githubusercontent.com/6964154/190474118-86de7c32-9388-415e-a5c7-b2dcddb36176.png)

_With Show Channel Hosting enabled_
![image](https://user-images.githubusercontent.com/6964154/190474285-fad52412-0a1a-4310-93da-5dfc55399d8f.png)

**Comment by SirStendec** [comment]
Irrelevant now that hosting has been removed.
