### ISSUE TITLE
Can't hide the Bits Leaderboards

### ISSUE THREAD

**Issue by TsukiZero** [FrankerFaceZ/FrankerFaceZ#1275]
Even after disabling the "Display Leaderboards" and Bits related UI, it still shows.

Had to make a new stylebot rule to hide it:
`[data-test-selector^="channel-leaderboard"] {
  display: none;
}`

**Comment by SirStendec** [comment]
Added in 8cd6545556fbfaaf663b7c383552dc0f77b655bf
