### ISSUE TITLE
Emote and Mention Autocompletion does not appear in Popout and Embedded Chats

### ISSUE THREAD

**Issue by Mitsunee** [FrankerFaceZ/FrankerFaceZ#1278]
**Describe the bug**

The autocompletion for emotes and mentions does not appear anymore at all. Pressing tab will focus the next element as per browser default.

**To Reproduce**

1. Go to any stream chat
2. Type `:Kap`
3. Press Tab
4. No autocompletion happens, bits button is focused by browser.

**Expected behavior**

Autocompletion should show up (or be already visible since a `:` was used to start emote autocompletion) and offer to complete the emote

**Screenshots**

Can't do a screenshot of something that's not there :\

**Environment (please complete the following information):**

 - OS: Fedora KDE Spin x86_64
 - Browser: Ungoogled Chromium (flatpak)
 - Version: Version 105.0.5195.125 (Official Build, ungoogled-chromium) (64-bit)
 - Other Extensions: ublock origin is active, nothing else is

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:

https://pastebin.com/raw/qphSzftD

**Additional context**

Tested emotes were twitch defaults and sub emotes of both myself and the channel whose chat I was in. Popout chat was used since I watch twitch through streamlink.

Edit: It has been confirmed below that this issue exists in chat embeds, as well as Popout chat.

**Comment by Gambloide** [comment]
This started happening in the last 24 hours.

The problem does not appear in the default chat embedded on a normal stream page.

As soon as the chat is embedded somewhere else or popped out `:`, `@` or `tab` autocompletion do not work anymore.
Neither suggestions are shown, nor is anything completed.

Examples where it does not work:
- chat popout
- chat in modview
- chat in OBS

Scope: It appears every user is affected by this.

Notes:
- The FFZ emote picker is unaffected by this.
- The browser choice does not seem to matter either. Tested in Firefox and Chrome.

**Comment by Mitsunee** [comment]
Not sure what changed but everything seems fixed now for me.

**Comment by Gambloide** [comment]
Indeed. Thank you. Time to remove the workarounds again.
