### ISSUE TITLE
Click on video area to pause

### ISSUE THREAD

**Issue by mod098** [FrankerFaceZ/FrankerFaceZ#1279]
would love to have play/pause by simply clicking on video area (just like youtube/bttv feature)

since pressing "space" is kinda buggy (sometimes its scroll down the page, sometimes its doing nothing)

**Comment by SirStendec** [comment]
Added in 8cd6545556fbfaaf663b7c383552dc0f77b655bf

**Comment by mod098** [comment]
LETS GOOO
