### ISSUE TITLE
Could we please have an option to disable TAB preview/cycling through of available emotes.

### ISSUE THREAD

**Issue by stormfused** [FrankerFaceZ/FrankerFaceZ#128]
**Web Browser**: Chrome

**Do you use BetterTTV or other Twitch extensions**: FFZ:AP

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Idea**:
Could we please have an ON/OFF button for the TAB preview emote. Right now its partially enter an emote name, which brings the emote preview, then we have select emote and then enter. Its an unnecessary process. 

Please check the links provided as a reference, they are both gif. 
GIF1 is with TAB preview
GiF2 is without TAB preview.

**GIF 1** https://cdn.discordapp.com/attachments/182761079263330304/299527328181125120/GIF.gif

**GIF 2** https://cdn.discordapp.com/attachments/296026914991374346/299632278236299265/GIF.gif 

Would  really appreciate if you guys can implement a on/off button for that. 

thnx.

**Comment by SirStendec** [comment]
I'm not going to implement in-line tab completion. Pressing a single additional keystroke is not a burden, and this is not the 1990s. Twitch is not running in a shell window with limited space. I can display choices, so I'm going to display choices.
