### ISSUE TITLE
Hide Elevated Chat button

### ISSUE THREAD

**Issue by brynjolf** [FrankerFaceZ/FrankerFaceZ#1280]
**Is your feature request related to a problem? Please describe.**
I would like to hide the new button next to the emote button for Twitch experimental feature Elevated Chat

**Describe the solution you'd like**
Option to hide the button so I don't missclick it, especially since it now deletes your message if you click it.

**Describe alternatives you've considered**
I could block it with Adblocker but since FFZ does it so nicely with an option I would prefer that solution.

**Additional context**
Here you can read more about it and see the icon used.
https://help.twitch.tv/s/article/elevated-chat?language=en_US

It is featured in for example [imaqtpies](https://www.twitch.tv/imaqtpie) chat while logged in.

**Comment by SirStendec** [comment]
Added in 8cd6545556fbfaaf663b7c383552dc0f77b655bf
