### ISSUE TITLE
Chat box disappeared after failure to tab-complete emote

### ISSUE THREAD

**Issue by robmonte** [FrankerFaceZ/FrankerFaceZ#1282]
**Describe the bug**
I was trying to tab-complete an emote I knew existed, but after hitting tab, it instead tabbed to the next webpage element (chat identity button) instead of opening the emote menu. Upon going back to the chat box and hitting tab again, the entire chat input box disappeared.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows
 - Browser: Chrome v106
 - Addons: 7TV, uBlock Origin (no BTTV)

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:
Unfortunately I refreshed to fix the issue, but when it happens again I'll try to remember to grab the log

**Additional context**
Honestly not sure if this is an FFZ issue, if 7TV is causing a conflict, or if this is a stock Twitch website issue. I am inclined to think it is not 7TV because I turn off all of its chat settings except animated avatars and namepaints, but it's still possible.

**Comment by chukwumaokere** [comment]
Im encountering this problem as well. Its still persistent. 
I uninstalled FFZ and the problem went away for a month, reinstalled it today, and it came back right away. 

It _could_ be a conflict of FFz with 7tv... but its definitely FFZ

**Comment by chukwumaokere** [comment]
Issue is here: https://github.com/SevenTV/Extension/issues/291 
Referenced here: https://github.com/night/betterttv/issues/5684

Fixed here: https://github.com/SevenTV/Extension/pull/300
