### ISSUE TITLE
Allow sending duplicate messages in chat

### ISSUE THREAD

**Issue by MasterLH** [FrankerFaceZ/FrankerFaceZ#1283]
The 7TV Addon allows users to send duplicated messages in the twitch chat, although normally this is not possible in chats, where duplicated messages are not allowed by twitch / the streamer. This is done by just adding a space to the duplicated message, so the addon automatically detects the "duplicate message" warning and sends the slightly "edited" message by adding a space. I'd love to see this feature in FFZ too :)

**Comment by Lordmau5** [comment]
Closed as per #1202
