### ISSUE TITLE
Not possible to pin messages as moderator with FrankerFaceZ add-on on

### ISSUE THREAD

**Issue by Gellyh** [FrankerFaceZ/FrankerFaceZ#1284]
**Describe the bug**
Twitch recently introduced a feature for moderators that allows them to pin a message and have it displayed at the top of the chat box. This is done by hovering over the message you want to pin and then it will display the icon of a pin as well as the icon to reply. The icon to reply is there, but the pin is not. Disabling FrankerFaceZ allows me to pin messages again.

**To Reproduce**
1. Enable FrankerFaceZ add-on.
2. Go to channel where you are moderator.
3. Hover over any one message in chat.
4. Observe that there is no pin icon to pin any one message.
5. Disable FrankerFaceZ add-on.
6. Repeat step 2 and 3.
7. Observe that there is now a pin icon.

**Expected behavior**
I expect to still have the option to pin messages as a moderator while having the FrankerFaceZ add-on enabled.

**Screenshots**
![image](https://user-images.githubusercontent.com/10024899/195626843-92992ef4-a51f-42ce-a33d-09f031266303.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 105.0.3
 - Other Extensions: BetterTTV, AdBlocker Ultimate, uBlock Origin

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:
It is stuck at uploading and nothing seems to happen. I checked other issues and followed what user PotionSelller did and copy-pasted it into a text file if that helps:
[FFZLog.txt](https://github.com/FrankerFaceZ/FrankerFaceZ/files/9777828/FFZLog.txt)

**Additional context**
Never done one of these before, but I would really like to keep using FrankerFaceZ, but sometimes pinning messages is really necessary in the channel I mod for. Thank you!

**Comment by jbaylies** [comment]
Seems like this may have become an issue again? macOS 15.1.1 // Chrome 131.0.6778.140  // Firefox 133.0.3 // FFZ 4.76.3.0
https://logs.frankerfacez.com/d68680b4-2f9e-4389-9527-053b13fb575c
