### ISSUE TITLE
Add a "Highlight" button to user context menu in chat

### ISSUE THREAD

**Issue by BubiBalboa** [FrankerFaceZ/FrankerFaceZ#1290]
**Is your feature request related to a problem? Please describe.**
Adding and removing a username to be highlighted in chat is a bit inconvenient when using the normal settings menu. 

**Describe the solution you'd like**
Add feature to highlight a user via the username context menu in chat. 

Click the user in chat > a popup opens > add "Highlight" button next to "Follow" "Whisper" and "Gift a Sub"

I think this would be very useful.

**Comment by SirStendec** [comment]
The Mod Tools add-on adds a "Highlight User" chat action. I'd suggest trying that. I don't plan on adding a highlight action into the main extension.
