### ISSUE TITLE
"Pin Message" button not working while FFZ is active

### ISSUE THREAD

**Issue by slydolphin** [FrankerFaceZ/FrankerFaceZ#1293]
When FFZ is active the Twitch's newest feature "Pin This Message" button is not appearing as a moderator.

Disabling the extension fixes the issue so the fault is within it.

Browser: Chrome
Windows 10
Other extensions: BTTV, 7TV

**Comment by mdw19873** [comment]
Can confirm this issue resides in FFZ. Tested Chrome and Brave on Windows 10 with the BTTV extension disabled to be sure. Button returns when FFZ is disabled.
