### ISSUE TITLE
[Idea] Friend Button on *New* Profile/Channel page

### ISSUE THREAD

**Issue by Cresentrend** [FrankerFaceZ/FrankerFaceZ#13]
I noticed just now, the add friend/remove request button is not on the new page for your channel/profile.

As some people might find it more convenient to have it if they use the feature maybe pass it on to the right people to have them re-add that or add an option for it to appear there.
Could be like the edit button on the page where it only shows when the cover is being displayed.

Idk, just feels weird to not have something so "significant" for a "feature" there anymore.

**Comment by SirStendec** [comment]
This is already possible, though it's not super obvious at first glance. Hover over the person's name/avatar and it opens a profile card for them where you can send a friend request.

![image](https://cloud.githubusercontent.com/assets/14036657/19058343/783e0466-89a4-11e6-89c1-c8dfd7f0adea.png)
