### ISSUE TITLE
Chat dissapearing 

### ISSUE THREAD

**Issue by CrazyWolf13** [FrankerFaceZ/FrankerFaceZ#1309]
If i join a Twitch channel my chat stays blank 9 out of 10 times so i have to reload my page many many times to finally acess the chat. 

Go to twitch.tv and a channel 

The chat loading always lmao

![image](https://user-images.githubusercontent.com/96661824/208256297-05625ada-4c27-4e68-8036-7dfcc0bd4253.png)

**Environment (please complete the following information):**
 - OS: Windows
 - Browser Opera GX
 - Version ![image](https://user-images.githubusercontent.com/96661824/208256325-79c2664a-69e7-40d4-a96a-53e40530d702.png)
 - Other Extensions: BTTV, FFZ-Addons, AdGuardExtra, TwitchAdblock(deprecated), 7TV, FFZ-Enhancing-Addon, AdGuard DNS. None of them have an impact , i tested nearly every configuration. 

Logs:
https://pastebin.com/R8ejA9WA 
PS. the upload did not work (button is stuck at uploading even after 10minutes)

Not really, i think the issue is clear.

**Comment by CrazyWolf13** [comment]
I could resolve it. More or less, through Chrome dev tools i found out they were blocked by opera gx's built in abdlocker lol. But the dev tools show way too many 404 errors on 
![image](https://user-images.githubusercontent.com/96661824/208263280-d9feb00c-fac7-4ad9-8eda-76f5cc8e7a95.png)
![image](https://user-images.githubusercontent.com/96661824/208263287-66e61b64-74dd-4563-aa92-58a24b8eaf1e.png)
![image](https://user-images.githubusercontent.com/96661824/208263299-6730346c-92e0-47e4-b952-0eaef8dcdf7a.png)
![image](https://user-images.githubusercontent.com/96661824/208263305-d2114ccf-f857-4bd7-9fe7-662a5f7cad8b.png)
And many more.
Any way to fix them? or is that not neccessary?
@SirStendec

**Comment by SirStendec** [comment]
None of the errors you've shown have anything to do with chat not appearing, I'm sorry to say. I can't reproduce the issue at all on my end.

A FFZ network request returning a 404 is common and expected, particularly when trying to request emotes for a channel that don't have any. Not sure what all the 7tv stuff is about. I would suggest testing with only FFZ enabled to make sure the issue isn't related to one of the other extensions.

The [site.chat] error, related to UnreadMentionsCounter, is not capable of crashing chat. (When FFZ emits an event, which the unread mentions counter add-on is subscribed to, it runs event listeners within a try/catch block so they don't cause issues.)

**Comment by CrazyWolf13** [comment]
> None of the errors you've shown have anything to do with chat not appearing, I'm sorry to say. I can't reproduce the issue at all on my end.
> 
> A FFZ network request returning a 404 is common and expected, particularly when trying to request emotes for a channel that don't have any. Not sure what all the 7tv stuff is about. I would suggest testing with only FFZ enabled to make sure the issue isn't related to one of the other extensions.
> 
> The [site.chat] error, related to UnreadMentionsCounter, is not capable of crashing chat. (When FFZ emits an event, which the unread mentions counter add-on is subscribed to, it runs event listeners within a try/catch block so they don't cause issues.)

Thanks for the detailed explanation. As is said i could solve the issue, but i still got those errors and wondered if they are problematic. But as you say, i suggest they are not that serious. 
I'd say the problem is resolved. Thank you for this great service and all the time you are investing in it.
