### ISSUE TITLE
Set the default playback quality

### ISSUE THREAD

**Issue by Keith94** [FrankerFaceZ/FrankerFaceZ#131]
I like to watch streams and past broadcasts in "Source" quality, but sometimes the player switches back to "Auto" for unknown reasons. Is it possible to set the quality to "Source" by default?

**Comment by SirStendec** [comment]
Twitch's player is just buggy, unfortunately. The most I could do for the player with FFZ is set the value in localStorage that it reads to see what your last setting was, and that stands no more chance of being respected than the existing value from regularly using the player.

They constantly update their player, so hopefully any issues with it defaulting to Auto when you didn't have it selected will be fixed soon.
