### ISSUE TITLE
Chat Actions do not respect modifiers on Firefox

### ISSUE THREAD

**Issue by DoraTheExploder** [FrankerFaceZ/FrankerFaceZ#1316]
After the recent update introducing Message Hover chat actions (which are great otherwise btw!), actions no longer retain the settings for button modifiers nor do they respect the option(s) chosen. 

**To Reproduce**
1. Go to 'Chat->Actions->Message Hover' (have not tested others)
2. Click on '+ New...'
3. Choose any option to create a new action (e.g. "Chat Command")
4. Follow the prompt to create any action you like, include one or more 'Visibility->Modifiers' options.
5. Navigate to chat window and hover your pointer over any message to see issue.

**Expected behavior**
Chat actions created with a 'Visibilty->Modifiers' option set should only present themselves when the corresponding key is pressed.

**Screenshots**
![FFZ Control Panel with Chat Action Dialogue Open](https://user-images.githubusercontent.com/7133316/210007120-84eaffc6-af16-49aa-a7b2-3cf6992f7e05.png)
![Example of Issue](https://user-images.githubusercontent.com/7133316/210007127-1797b52d-b8b2-497d-92be-4c31470fc805.png)

No modifier keys are being depressed during the second screenshot.

**Environment (please complete the following information):**
 - OS: EndeavourOS Cassini (Arch Linux 6.1.1-arch1-1) 
 - Browser Firefox for Arch Linux 108.0.1 64-bit
 - Other Extensions: uBlock Origin, TTV LOL ([PRO](https://github.com/younesaassila/ttv-lol-pro/))
 - FFZ Extensions: 7TV Emotes, BTTV Emotes, Chatterino Badges, FFZ:AP

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**: https://gist.github.com/DoraTheExploder/1b5a3e29a054244bb5d84dcff308d51a

**Additional context**
Modifier keys were working prior to the implementation of the 'Message Hover' action type. I migrated my current chat commands as-is from the 'In-Line' style.

**Comment by flonou** [comment]
Got the same behavior on Brave 1.46.153 on Windows 10 and BTTV installed too
