### ISSUE TITLE
Stream doesn't load when compressor is auto enabled

### ISSUE THREAD

**Issue by MiguelRamon** [FrankerFaceZ/FrankerFaceZ#1317]
I have issues loading streams (video) when the option: "Enable the compressor by default" is enabled.
I don't have an issue when loading the first stream I visit. 
But as soon as I go to a another stream, it doesn't load. It shows the loading icon forever.
Even when I go back to the first stream I was watching, it doesn't load anymore.
Chat is normal.

I don't have this problem in Edge with the same settings and extensions. 

1. Go to twitch.tv
2. Click on any stream
3. Normal behavior
4. Go to another stream
5. Player doesn't load 

**Expected behavior**
To load the stream correctly and fast.

**Environment (please complete the following information):**
 - OS: Windows 11 Home 22H2 Build 22621.963
 - Browser: chrome 
 - Version 108.0.5359.125
 - Other Extensions: BetterTTV, AdBlock, 7tv, Volume master

**FFZ Logs 
I couldn't upload the log but here is the txt file:
[filebin](https://filebin.net/29iomho4e7ss6rmr)

**Comment by mariusandersen** [comment]
I also started getting this issue and it's recent in one of the newer versions. Maybe past 2ish weeks?

This issue together with #1230 unfortunately makes me have to turn of the "Enable the compressor by default" option.

**Comment by mseals1** [comment]
I'm having the same issue. I didn't know what was causing it, but it does, in fact, seem to be the audio compressor. When I disable both options related to it, refresh the twitch tab (I only have one open), then change the channel to anyone else, it works fine. But when I have the audio compressor options enabled (the two at the top of the compressor tab), then I refresh, then first stream works, then if i click any other that is not loaded into the cache, the player will not load.

I just experimented with it:
- disabled both options
- reloaded the tab
- clicked the first 5 followed channels, and each loaded
- re-enabled the options
- reloaded
- clicked the first 5, all loaded
- clicked the 6th, it failed to load
- clicked on others, failed to load
- clicked on any of the first 5, they failed to load too

Hopefully this helps!

**Comment by SirStendec** [comment]
This is, as far as I can tell, fixed in development now. There should be a release tomorrow addressing it.
