### ISSUE TITLE
Make FFZ work independently on each tab 

### ISSUE THREAD

**Issue by bottleblue** [FrankerFaceZ/FrankerFaceZ#1320]
**Is your feature request related to a problem? Please describe.**
I frequently have multiple streams open and don't want the Highlight option to apply to all the tabs. If I modify something in Highlight it applies to all the tabs instantly. If I disable FFZ on one tab it disables it on all of them.

**Describe the solution you'd like**
Have FFZ work independently on each tab

**Describe alternatives you've considered**
Using different browsers

**Additional context**

**Comment by michaelchany** [comment]
I'm sure there's a more elegant way to put it, but I don't think it's possible for FFZ to know which tab corresponds to which profile.  At least, as it is coded now, since you tried switching FFZ profiles but choosing one sets it for all other tabs.

A way to do what you want (kind of) is separate browser profiles.  If you have Firefox, you can create new profiles through `about:profiles`.  Chrome seems a bit more work, as each profile needs to be associated with a Google account, while for FF you don't need to log-in.

**Comment by bottleblue** [comment]
Betterttv recently released an option to whitelist channels for highlighted keywords.  Maybe you can copy what they did. Although it'd be nice to also be able to blacklist channels as well.

**Comment by SirStendec** [comment]
You realize you can just make a profile with a rule so that it's only active when you're viewing a specific channel, I hope? Or invert the rule so it's active *except* when you're viewing that specific channel.

**Comment by bottleblue** [comment]
> You realize you can just make a profile with a rule so that it's only active when you're viewing a specific channel, I hope? Or invert the rule so it's active _except_ when you're viewing that specific channel.

Where do you find this rule? I tried making a new profile before but it applied to all other tabs. This method isn't ideal anyway as I have many channels that I only want certain keywords to work in. I'd have to create many profiles and then having to sort through them would be tedious. Betterttv has a config button next to the highlighted word which lets you enter the name of the channel(s) you want it to work in.

**Comment by SirStendec** [comment]
When you're editing a profile, you can add rules at the bottom. If you want a profile to be active for several different channels, as an example, you can also use an "Or" rule with several sub-rules. Example:
![image](https://user-images.githubusercontent.com/14036657/218160477-d718306d-60bb-41d0-b194-0f86329bfeb6.png)
