### ISSUE TITLE
Option to block specific emotes/emote codes

### ISSUE THREAD

**Issue by SyfSchydea** [FrankerFaceZ/FrankerFaceZ#1321]
**Is your feature request related to a problem? Please describe.**
Many 7tv emotes in particular often use common words as their emote codes, eg. "what", "ok", "THIS", "AND". This can lead to these emotes being substituted in accidentally and breaking up sentences which weren't supposed to have any emotes in them.

**Describe the solution you'd like**
It would be nice to have an option to have an emote blacklist. Emotes or emote codes on this blacklist would just not get substituted in, instead leaving the emote code text untouched. 

**Describe alternatives you've considered**
The closest workaround for blocking emotes at present is adding them as blocked words. This does stop the emote itself from being shown, but this still isn't ideal in the case of accidental usage as the word gets replaced with "xxx". This also means that the word gets filtered out on other channels where the emote may not even be present.

**Comment by Sacred-Shadow** [comment]
You could also link the solution to whether you have hidden the emotes in the menu. You can hide emotes in the menu yourself.

If I hide an emote there, I don't want to use it myself.
It then makes no sense that my text is automatically converted into this hidden emote when I enter it.

**Comment by BhaaLseN** [comment]
I'll add "the" to the list (which is replaced with an emote that spells out "hte" and is offset from the regular text baseline.)

For my own personal sanity, I'd like to blacklist this (and a few other select ones) from being substituted in chat.

Wanted to create a new feature request for this, but quickly found this one. +1 from me.

**Comment by Lordmau5** [comment]
Stendec made a new add-on which implements this functionality :)
![image](https://github.com/FrankerFaceZ/FrankerFaceZ/assets/1345036/69a4e99d-4401-42c3-aac8-460c19b207f0)
![image](https://github.com/FrankerFaceZ/FrankerFaceZ/assets/1345036/5bf1225a-c662-4244-9ec2-35588d172510)

If you have any issues with that add-on please report them on the [Add-Ons repository](https://github.com/FrankerFaceZ/Add-Ons)
