### ISSUE TITLE
See bans and timeouts as non-moderator

### ISSUE THREAD

**Issue by Jarda-H** [FrankerFaceZ/FrankerFaceZ#1322]
I'm very upset when I see user's messages disappearing and I can't see the reason.
Did he/she get banned or just timeout?
(Even mobile app [DankChat](https://f-droid.org/packages/com.flxrs.dankchat/) have this feature :D)

**Comment by SirStendec** [comment]
Fixed in 5956312ae30a1adff571001f8532f792039e90f0
