### ISSUE TITLE
Disabling Mod Icons Also Disables Pin Message

### ISSUE THREAD

**Issue by ipat8** [FrankerFaceZ/FrankerFaceZ#1328]
**Is your feature request related to a problem? Please describe.**
Disabling mod icons also hides the ability to pin messages.

**Describe the solution you'd like**
Seperate the option for hiding the pin message button from the requirement to have mod icons enabled.

**Describe alternatives you've considered**
Remove FFZ

**Additional context**
N/A

**Comment by SirStendec** [comment]
No it doesn't. The pin message UI is not affected by FFZ at all.
![image](https://user-images.githubusercontent.com/14036657/216850090-4d6e07ba-8608-40fa-b2fa-f12ee283454d.png)

You can also change the settings for the message hover actions to not require mod icons be enabled to see the pin message action.
