### ISSUE TITLE
PrattleNot on VODs missing

### ISSUE THREAD

**Issue by user18081972** [FrankerFaceZ/FrankerFaceZ#1329]
**Describe the bug**
PrattleNot does not work on VODs, neither does the PrattleNot seperate chat box show up.

**To Reproduce**
1. Have PrattleNot enable itself automatically
2. Go to a twitch VOD
3. PrattleNot is not present

**Expected behavior**
When PrattleNot addon is enabled, and works in live chats, have it work in VODs too.

**Environment (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox
 - Version 109
 - Other Extensions: None

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:
[log.txt](https://github.com/FrankerFaceZ/FrankerFaceZ/files/10685249/log.txt)

**Comment by EldritchEevee** [comment]
Windows 11 is not supported.

**Comment by user18081972** [comment]
Also happens on Windows 10 22h1

**Comment by SirStendec** [comment]
PrattleNot does not support VODs. VOD chat has an entirely different implementation than live chat, so supporting it is non-trivial. I might add it in the future, but it's not been a priority.
