### ISSUE TITLE
Emojis do not show properly on Vivaldi

### ISSUE THREAD

**Issue by cornichonche** [FrankerFaceZ/FrankerFaceZ#1330]
Hello,
Emojis do not show properly on Vivaldi.
Emotes work but not emojis.
Thank you.

![emojis](https://user-images.githubusercontent.com/37427646/218269287-21d838c0-77df-4e51-97d5-273d81c88970.png)

**Comment by SirStendec** [comment]
Emoji are not expected to appear as previews within the chat input box, nor are emotes. FFZ does not hook into the WYSIWYG editor at this time because doing so has proven to be unstable and has caused chat input to crash.
