### ISSUE TITLE
Emote information cards not working

### ISSUE THREAD

**Issue by IZeeLikeEyeZee** [FrankerFaceZ/FrankerFaceZ#1332]
**Describe the bug**
I have "Open emote information cards for Twitch emotes by clicking them." enabled, yet it has not been working.

**To Reproduce**
1. Go to any channel
2. Click on any twitch native emote
3. See nothing happens

**Expected behavior**
Usually when you click twitch native emotes they give the little popup card with the channel, artist, etc.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 110.0.5481.96 (Official Build) (64-bit)
 - Other Extensions: None (tested with all other extensions disabled)

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:
https://pastebin.com/1GG4Bc5G (upload button wasn't working for some reason; or at least just taking forever to load)

**Additional context**
Tried disabling all other extensions to fix the issue, the only thing that fixed it was disabling ffz as a whole.

**Comment by xHxCxPeter** [comment]
I have the same problem,stops working all of the sudden.
Had this issue a few weeks ago too,no idea why.

**Comment by EldritchEevee** [comment]
Breaks upon loading FFZ.

**Comment by scsa20** [comment]
Not sure if it matters but same thing happens on Windows 11, started about a week or 2 ago, and only when the FFZ extension is enabled.

Also, this might require me to open a separate bug report but thought I mention that the links to twitchemotes.com when you shfit+click an email leads to a dead page (looks like twitchemotes.com changed how the URLs are)

**Comment by IZeeLikeEyeZee** [comment]
> Also, this might require me to open a separate bug report but thought I mention that the links to twitchemotes.com when you shfit+click an email leads to a dead page (looks like twitchemotes.com changed how the URLs are)

Yeah I've had the same issue with that as well

**Comment by kh0nsu** [comment]
Did a bit of debugging. This search returns null:

https://github.com/FrankerFaceZ/FrankerFaceZ/blob/8e48021c439e3e6191869e3ba3c2c4c4f25fa1d9/src/modules/chat/emotes.js#L516

Twitch's scripts also reference "onShowEmoteCard" but I don't know anything else.

**Comment by xHxCxPeter** [comment]
So are there not more people who has this issue?
And no one knows how to fix that bug?

**Comment by Houdini111** [comment]
I also have this issue and I've confirmed it with a few other users who haven't commented here. But instead of clogging this up with useless "Me too" I just subscribed to the ticket. You should do the same.

**Comment by Lordmau5** [comment]
Seeing as Stendec hasn't posted about this in this issue yet:

This is a known problem and he's working on a fix, but unfortunately said fix is taking a bit longer.
