### ISSUE TITLE
Emote Modifier Documentation and/or Selection

### ISSUE THREAD

**Issue by IZeeLikeEyeZee** [FrankerFaceZ/FrankerFaceZ#1334]
**Is your feature request related to a problem? Please describe.**
In the changelog I saw "Support for modifier emote effects, as well as settings to disable them." however there is no list or way to select said modifiers (at least as far as I could tell).

**Describe the solution you'd like**
A way to select emote modifiers in the emote selector menu.

**Describe alternatives you've considered**
Comments next to the 'Enable the effect x' options with what modifier(s) results in that emote effect could work too.

**Additional context**
If this is referring to BTTV's emote modifiers then ffz's implementation doesn't work, so I'm assuming ffz is implementing their own modifiers.

**Comment by Lordmau5** [comment]
If all things go well this will be released today, but I am not in a position to give an actual ETA - Stendec and Dan are the ones to make the call on this.

It is not referring to BTTV's emote modifiers, though I will be adding support for them in the BTTV Emotes add-on once this is public

**Comment by IZeeLikeEyeZee** [comment]
Ah ok cool! tyvm :)

**Comment by SirStendec** [comment]
Emote Effects are a new perk we've added to support people who support us.

In effect, they're modifiers for other emotes that apply interesting effects. You can see them in a new section of the FFZ emote menu, or read a small blurb about them at https://www.frankerfacez.com/subscribe
