### ISSUE TITLE
Random Emote adding itself

### ISSUE THREAD

**Issue by LilRed765** [FrankerFaceZ/FrankerFaceZ#1337]
**Describe the bug**
When I go to choose an emote and click it, it adds a random emote before the one I chose.

**To Reproduce**
1. Go to 'any emote'
2. Click on 'and insert in chat'

**Expected behavior**
Just the emote I pick t be displayed

**Screenshots**
If applicable, add screenshots to help explain your problem. Attached

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version FrankerFaceZ v4.42.1 
 - Other Extensions: Honey

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**: Attached

**Additional context**
![ss1](https://user-images.githubusercontent.com/127366751/223901528-8288a11c-7ded-4584-a897-f625dd351860.png)
![ss2](https://user-images.githubusercontent.com/127366751/223901533-fa841e4c-a25e-4de7-a915-9aa85cc0ffa2.png)
[FF Log.txt](https://github.com/FrankerFaceZ/FrankerFaceZ/files/10927135/FF.Log.txt)

**Comment by tizzo513** [comment]
I am also having this issue
