### ISSUE TITLE
Broken FFZ

### ISSUE THREAD

**Issue by Adam022695** [FrankerFaceZ/FrankerFaceZ#1342]
**Describe the bug**
Removes all customization and get this error with 2 tabs open on twitch  This profile is not active.
This profile's rules don't match the current context and it therefore isn't currently active, so you won't see changes you make here reflected on Twitch. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g. chrome, firefox]
 - Version [e.g. 70]
 - Other Extensions: [e.g. BetterTTV, Privacy Badger, AdBlock, etc.]

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:

**Additional context**

**Comment by Lordmau5** [comment]
Please fill out the issue template properly. Important information for us would be which other extensions you have installed, such as 7TV or BetterTTV.

**Comment by Adam022695** [comment]
I have both 7tv and betterttv.  Its on firefox 111.0 (64-bit) windows 11

**Comment by Lordmau5** [comment]
Can you try disabling 7TV? They recently put out an update which replaces the entire chat so maybe something else get's messed up with FFZ's detection (and in that case also customization)

BetterTTV as well just in case

**Comment by Lordmau5** [comment]
I'm gonna assume this was resolved
