### ISSUE TITLE
Larger Emotes not working after 7TV 3.0

### ISSUE THREAD

**Issue by bennybanano** [FrankerFaceZ/FrankerFaceZ#1346]
Larger Emotes setting (Emotes only) is broken following the new 7TV update.

1. Go to 'Chat'
2. Click on 'Appearance'
3. Scroll down to 'Larger Emotes'
4. Set to "Emotes"
5. See error (in chat)

It should make the emotes bigger.

[Screenshot of setting not working](https://i.imgur.com/R8I2Aqx.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser: Opera GX
 - Version 96.0.4693.104
 - Other Extensions: 7TV, BTTV, Twitch Previews, Twitch Enhancer, uBlock Origin, Privacy Badger

Logs:
initialization
-------------------------------------------------------------------------------
[1:00:12] info | core: FrankerFaceZ v4.44.0 (s:twitch f:main b:f833b4a9ade874171206 c:21bc0a704f5f9f482b722611e5ab7c0c5c5d5f7b)
[1:00:12] info | core: Initial URL: https://www.twitch.tv/mizkif
[1:00:12] info | site: Using: Twilight
[1:00:12] info | site.web_munch: Found and wrapped webpack's loader after 0ms.
[1:00:12] info | settings: Using Provider: LocalStorageProvider
[1:00:12] info | site.web_munch: require() grabbed in 2.80000ms.
[1:00:12] info | core: Loaded descriptions of 0 modules.
[1:00:12] info | settings: Initialization complete after 13.40000ms -- Values: 88 -- Profiles: 3
[1:00:12] info | site.fine: Installing MutationObserver.
[1:00:12] info | site: Loaded descriptions of 16 modules.
[1:00:12] info | site.elemental: Installing MutationObserver.
[1:00:12] info | experiments: Loaded information on 3 experiments.
[1:00:12] info | socket: Using Server: wss://tuturu.frankerfacez.com/
[1:00:12] info | core: Initialization complete in 562.50000ms.

settings
-------------------------------------------------------------------------------
i18n.debug.capture: false
i18n.format.date: "default"
i18n.format.time: "short"
i18n.format.datetime: "medium"
i18n.debug.transform: null
i18n.locale: "en"
data.use-staging: false
addons.dev.server: false
socket.use-cluster: "Production"
chat.bits.show: false
layout.display-bits-button: false
metadata.modview.hide-info: false
layout.side-nav.hide-viewers: false
metadata.uptime: 2
metadata.uptime.no-native: true
metadata.viewers: false
metadata.viewers.no-native: false
layout.swap-sidebars: false
layout.portrait: false
layout.portrait-threshold: 1.25
layout.use-portrait: false
chat.width: null
chat.use-width: false
layout.use-chat-fix: false
layout.theatre-navigation: false
layout.minimal-navigation: false
layout.side-nav.show-avatars: true
layout.side-nav.show: 1
layout.side-nav.hide-offline: true
layout.hide-discover-luna: false
layout.prime-offers: false
layout.discover: true
channel.hide-unfollow: false
channel.round-avatars: true
channel.hide-live-indicator: false
layout.side-nav.rerun-style: 1
layout.side-nav.show-rec-channels: 1
layout.side-nav.show-friends: 1
whispers.show: true
channel.show-celebrations: true
layout.theme.global-font: ""
layout.portrait-invert: true
layout.portrait-min-chat: false
layout.inject-portrait: false
layout.use-portrait-swapped: false
player.theatre.metadata: false
layout.use-portrait-meta: false
layout.use-portrait-meta-top: false
layout.portrait-extra-width: 24
player.theatre.no-whispers: false
layout.portrait-extra-height: 14
theme.disable-auto-dark: false
theme.can-dark: true
theme.is-dark: true
theme.color.background: "#0C0912"
theme.color.text: ""
theme.color.accent: "#6e3fa7"
theme.color.tooltip.background: ""
theme.color.tooltip.text: ""
theme.color.chat-background: ""
theme.color.chat-text: ""
theme.color.chat-accent: "#6e3fa7"
theme.font.size: 13
directory.show-channel-avatars: undefined
directory.hide-live: false
directory.hidden.reveal: false
directory.hidden.style: 2
channel.panel-tips: false
channel.auto-click-chat: false
player.gain.enable: false
player.gain.no-volume: false
player.volume-always-shown: true
player.ext-interaction: true
player.hide-mouse: true
player.fade-pause-buffer: true
player.ext-hide: 0
player.captions.font-size: ""
player.captions.font-family: ""
player.compressor.enable: true
player.compressor.shortcut: null
player.no-autoplay: false
player.home.autoplay: true
player.button.pip: true
player.button.reset: true
player.gain.min: 0
player.gain.max: 2
player.compressor.default: false
player.allow-catchup: true
player.hide-event-bar: false
chat.lines.alternate: true
player.theatre.auto-enter: false
smokemotes.pinned_mentions: true
addon.inlinetab.no_mentions: true
addon.inlinetab.no_commands: true
addon.inlinetab.tips: true
addon.chatterino_badges.badges: true
addon.fs-chat.bg.blur: 2
addon.fs-chat.height: "400"
addon.fs-chat.width: null
addon.fs-chat.bg.color: "rgba(0, 0, 0, 0.3)"
addon.fs-chat.automatic: false
addon.fs-chat.shortcut: "alt+c"
sub-button.prime-notice: true
player.force-visible: undefined
ffz.show-new-settings: true
directory.block-titles: []
__filter:directory.block-titles: null
channel.extra-links: true
ffz.search.matches-only: true

experiments
-------------------------------------------------------------------------------
Unique ID: 9wJxZAsZfGFcoQAampQlz5eTrDFjQwui

FFZ | API-Based Link Lookups: false (r:0.7)
FFZ | Modular Chat Line Rendering: true (r:0.8)
Twitch | TWILIGHT_AD_DENSITY_WIDGET: no (r:0, t:channel_id, c:mizkif)
Twitch | channel_points_reward_limits_v2: control (r:0, t:channel_id, c:mizkif)
Twitch | copo_multi_option_predictions: control (r:0, t:channel_id, c:mizkif)
Twitch | ht_celeb_experiment: Control (r:0, t:channel_id, c:mizkif)
Twitch | hype_train_all_time_high: hype_train_all_time_high_off (r:0, t:channel_id, c:mizkif)
Twitch | more_default_quick_actions: control (r:0, t:channel_id, c:mizkif)
Twitch | one_click: variant_1 (r:0, t:device_id)
Twitch | persistent_goals_2: control (r:0, t:channel_id, c:mizkif)
Twitch | project_ape: control (r:0, t:channel_id, c:mizkif)
Twitch | community_insights: control (r:0.01, t:channel_id, c:mizkif)
Twitch | consent_tool_headline: F (r:0.14, t:device_id)
Twitch | catsug_v2: variant3 (r:0.2, t:user_id)
Twitch | Devsite_create_apps_form_recaptcha: control (r:0.5, t:user_id)
Twitch | bits_insufficient_balance_checkout: treatment (r:0.5, t:user_id)
Twitch | bits_top_nav_explanation : experiment (r:0.5, t:user_id)
Twitch | cf_wp_new_onboarding: control (r:0.5, t:channel_id, c:mizkif)
Twitch | creator_follow_cue: chat (r:0.5, t:user_id)
Twitch | giftcard_redemption_in_checkout: control (r:0.5, t:device_id)
Twitch | mobile_native_web_transcode_mode: cbr_v2 (r:0.5, t:device_id)
Twitch | sda_post_fill_drop: treatment (r:0.5, t:device_id)
Twitch | subscriber_recap: control (r:0.5, t:channel_id, c:mizkif)
Twitch | v6s_versions: treatment (r:0.5, t:device_id)
Twitch | percolite-shelf-reranking-logged-in: control (r:0.7, t:user_id)
Twitch | percolite-shelf-reranking-logged-out: control (r:0.7, t:device_id)
Twitch | com30_lil_bro_browsing: control (r:0.9, t:device_id)
Twitch | com30_shapeshifting_ocp: control (r:0.9, t:device_id)
Twitch | warp_web_staff: control (r:0.9, t:device_id)
Twitch | cheering_web_ux_improvements: treatment (r:0.95, t:user_id)
Twitch | vxp_hide_miniplayer: control (r:0.95, t:device_id)
Twitch | liverecs_holdout_device: control (r:0.98, t:device_id)
Twitch | liverecs_holdout_v2: control (r:0.98, t:user_id)
Twitch | warp_web_prod: control (r:0.98, t:device_id)
Twitch | disco_carousel_shelf: control (r:0.99, t:user_id)
Twitch | disco_sprig_logged_out: control (r:0.99, t:device_id)
Twitch | homepage_signup_login_gate: control (r:0.99, t:device_id)
Twitch | mse_in_workers: treatment (r:0.99, t:device_id)

addons
-------------------------------------------------------------------------------
Known
7tv-emotes | enabled | external | 7TV v1.3.0
aplatypuss-emotes | disabled | Aplatypuss Emotes v1.0.0
ffzap-core | enabled | FFZ:AP Core v3.3.10
brcm | disabled | brcm v1.0.0
chatterino-badges | enabled | Chatterino v1.0.0
clip-confirm | disabled | ClipConfirm v1.0.1
deck | disabled | Deck v2.2.1
emoteless | disabled | emote_less_chat v1.0.6
ffzap-bttv | enabled | FFZ:AP BTTV v3.3.13
ffzap-liriklive | enabled | FFZ:AP LirikLIVE v3.2.2
first-message-highlighter | disabled | first_msg_highlight v1.0.2
fs-chat | enabled | fs-chat v1.5.0
inline-tab-completion | enabled | Inline Tab v1.2.4
ModTools | disabled | Mod Tools v1.0.1
new-account-highlighter | disabled | New Account Highlighter v1.1.1
poll-shim | disabled | poll_shim v0.2.2
prattlenot | disabled | PrattleNot v0.6.0
pronouns | disabled | pronouns v1.1.1
repetition-detector | disabled | repetition_detector v1.1.0
smokemotes | enabled | smokeys_utils v1.1.7
unread-mentions-counter | disabled | UnreadMentionsCounter v1.1.1

Modules
loaded   | enabled  | 
loaded   | enabled  | core
loaded   | enabled  | settings
loaded   | enabled  | experiments
loaded   | enabled  | i18n
loaded   | enabled  | staging
loaded   | enabled  | load_tracker
loaded   | enabled  | socket
loaded   | enabled  | site.web_munch
loaded   | enabled  | site.fine
loaded   | enabled  | site.elemental
loaded   | enabled  | site.router
loaded   | enabled  | site.apollo
loaded   | enabled  | site.twitch_data
loaded   | enabled  | site.subpump
loaded   | enabled  | site
loaded   | enabled  | addons
loaded   | enabled  | vue
loaded   | enabled  | addon.7tv-emotes
loaded   | enabled  | tooltips
loaded   | disabled | chat/actions
loaded   | enabled  | chat.badges
loaded   | enabled  | chat.emotes
loaded   | enabled  | chat.emoji
loaded   | enabled  | chat.actions
loaded   | enabled  | chat.overrides
loaded   | enabled  | chat
loaded   | enabled  | emote_card
loaded   | enabled  | main_menu
loaded   | enabled  | site.bits_button
loaded   | enabled  | metadata
loaded   | enabled  | site.bttv_compat
loaded   | enabled  | site.css_tweaks
loaded   | enabled  | site.channel
unloaded | disabled | translation_ui
loaded   | enabled  | site.chat.scroller
loaded   | enabled  | site.chat.chat_line.rich_content
loaded   | enabled  | site.chat.chat_line
loaded   | enabled  | site.chat.settings_menu
loaded   | enabled  | site.chat.emote_menu
loaded   | enabled  | site.chat.input
loaded   | enabled  | site.chat.viewer_cards
loaded   | enabled  | site.chat
loaded   | enabled  | site.compat_emote_menu
loaded   | enabled  | site.dashboard
loaded   | enabled  | site.directory.game
loaded   | enabled  | site.directory
loaded   | enabled  | site.featured_follow
loaded   | enabled  | site.layout
loaded   | enabled  | site.menu_button
loaded   | enabled  | site.mod-view
loaded   | enabled  | site.player
loaded   | enabled  | site.sub_button
loaded   | enabled  | site.theme
loaded   | enabled  | site.video_chat
loaded   | enabled  | addon.ffzap-core
loaded   | enabled  | addon.ffzap-bttv
loaded   | enabled  | addon.smokemotes
loaded   | enabled  | addon.inline-tab-completion
loaded   | enabled  | addon.chatterino-badges
loaded   | enabled  | addon.ffzap-liriklive
loaded   | enabled  | addon.fs-chat

chat
-------------------------------------------------------------------------------
chat settings
-------------------------------------------------------------------------------
chat.effects.enable: true
chat.effects.FlipX: true
chat.effects.FlipY: true
chat.effects.ShrinkX: true
chat.effects.GrowX: true
chat.emotes.animated: 1
chat.effects.Slide: true
chat.effects.Appear: true
chat.effects.Leave: true
chat.effects.Rotate: true
chat.effects.Rainbow: true
chat.effects.HyperRed: true
chat.effects.Shake: true
chat.effects.Photocopy: true
chat.effects.Jam: true
chat.effects.Bounce: true
chat.badges.fix-colors: true
theme.can-dark: true
theme.is-dark: true
chat.badges.style: 1
chat.badges.clickable: 2
chat.badges.version: 2
chat.filtering.color-mentions: false
chat.actions.inline: [{"action":"ban","appearance":{"type":"icon","icon":"ffz-i-block"},"options":{},"display":{"mod":true,"mod_icons":true,"deleted":false},"ctx":"inline"},{"action":"unban","appearance":{"type":"icon","icon":"ffz-i-ok"},"options":{},"display":{"mod":true,"mod_icons":true,"deleted":true},"ctx":"inline"},{"action":"timeout","appearance":{"type":"icon","icon":"ffz-i-clock"},"display":{"mod":true,"mod_icons":true},"ctx":"inline"},{"action":"msg_delete","appearance":{"type":"icon","icon":"ffz-i-trash"},"options":{},"display":{"mod":true,"mod_icons":true},"ctx":"inline"}]
chat.actions.hover: [{"action":"pin","appearance":{"type":"icon","icon":"ffz-i-pin"},"options":{},"display":{"mod_icons":true},"ctx":"hover"},{"action":"reply","appearance":{"type":"dynamic"},"options":{},"display":{},"ctx":"hover"}]
chat.scroller.freeze-requires-hover: true
chat.scroller.hover-delay: 750
chat.scroller.freeze: 5
chat.scroller.smooth-scroll: 1
chat.input.hide-identity: false
chat.emote-menu.enabled: true
chat.emote-menu.icon: true
chat.emoji.style: "twitter"
chat.inline-preview.enabled: true
chat.actions.room-above: false
chat.actions.room: []
chat.tab-complete.emotes-without-colon: true
chat.emotes.2x: 1
chat.emotes.limit-size: false
chat.banners.last-events: true
chat.input.show-mod-view: true
chat.input.show-highlight: true
chat.input.show-shield: true
chat.lines.padding: true
chat.bits.show: false
chat.bits.show-pinned: false
chat.filtering.deleted-style: 1
chat.filtering.clickable-mentions: false
chat.filtering.bold-mentions: true
chat.hide-community-highlights: false
chat.lines.alternate: true
chat.filtering.highlight-mentions: true
chat.filtering.highlight-tokens: true
chat.filtering.mention-color: "#D0021B"
chat.input.show-elevate-your-message: false
chat.disable-handling: false
chat.adjustment-mode: 1
chat.adjustment-contrast: 4.5
theme.color.chat-background: ""
theme.color.background: "#0C0912"
theme.color.chat-text: ""
theme.color.text: ""
chat.lines.borders: 0
chat.bits.animated: true
theme.tooltips-dark: false
chat.banners.charity: true
chat.subs.gift-banner: true
chat.banners.hype-train: false
chat.banners.prediction: false
chat.banners.polls: true
chat.banners.drops: true
chat.badges.custom-mod: true
ffzap.core.highlight_sound: "https://cdn.ffzap.com/sounds/coin.mp3"
ffzap.core.highlight_sound_types: ["mention"]
ffzap.core.enable_highlight_sound: true
ffzap.core.message_deletion: 0
ffzap.core.highlight_sound_volume: 10
ffzap.betterttv.global_emoticons: true
ffzap.betterttv.pro_badges: true
ffzap.betterttv.channel_emoticons: true
ffzap.betterttv.arbitrary_emoticons: true
chat.update-when-loaded: true
chat.delay: -1
chat.scrollback-length: 150
chat.filtering.remove-deleted: 1
smokemotes.keep_hd_video: false
smokemotes.mod_keybinds: false
ffzap.liriklive.global_emoticons: true
ffzap.liriklive.sub_emoticons: true
chat.filtering.blocked-types: {}
layout.portrait: false
layout.portrait-threshold: 1.25
layout.use-portrait: false
layout.portrait-min-chat: false
chat.points.show-rewards: true
chat.points.show-button: true
chat.emote-menu.combine-tabs: false
chat.emote-menu.stay-loaded: false
chat.emote-menu.show-quick-nav: false
chat.emote-menu.show-heading: 1
chat.emote-menu.tall: false
chat.emote-menu.reduced-padding: false
chat.emote-menu.show-search: true
chat.emote-menu.clear-search: false
chat.emote-menu.sort-emotes: 4
chat.emote-menu.sort-tiers-last: true
chat.fix-bad-emotes: true
chat.emotes.enabled: 2
chat.emote-menu.effect-tab: true
chat.emote-menu.show-emoji: true
chat.filtering.display-deleted: false
chat.replies.style: 1
chat.filtering.debug: false
chat.filtering.highlight-basic-users-blocked: []
__filter:block-users: null
chat.filtering.highlight-basic-blocked: []
__filter:block-terms: null
chat.filtering.highlight-basic-badges: [{"remove":false,"v":"2","c":"rgba(0, 0, 0, 0)","p":21},{"remove":false,"v":"broadcaster","c":"rgba(255, 160, 8, 0.71)","p":31},{"remove":false,"v":"staff","c":"#7ED321","p":5},{"remove":false,"v":"moderator","c":"rgba(65, 117, 5, 0)","p":1},{"remove":false,"v":"vip","c":"rgba(0, 0, 0, 0.11)","p":5},{"remove":false,"v":"addon.chatterino_badges.badge-0","c":"#50E3C2","p":22},{"remove":false,"v":"partner","c":"rgba(189, 16, 224, 0.02)","p":0}]
__filter:highlight-badges: {}
chat.filtering.highlight-basic-badges-blocked: []
__filter:block-badges: null
chat.filtering.highlight-basic-users: [{"v":"mizkif","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"esfandtv","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"jerma985","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"ninja","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"trainwreckstv","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"lirik","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"forsen","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"emiru","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"zackrawrr","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"pokimane","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"connoreatspants","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"austinshow","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"wantep","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"cyr","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"vigors","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"syn4ack","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"dedokif","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"zoil","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"moistcr1tikal","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"ludwig","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"theneedledrop","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"simply","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"nmplol","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"maya","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"gmhikaru","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"erobb221","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"hasanabi","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"nymn","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"pokelawls","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"m0xyy","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"xqcow","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"sodapoppin","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"greekgodx","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"shroud","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"myth","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"clintstevens","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"loltyler1","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"moonmoon","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"qtcinderella","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"richwcampbell","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"sykkuno","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"knut","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"tfue","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"tubbo","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"tommyinnit","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"dreamwastaken","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"nickmercs","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"adinross","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"brucedropemoff","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"amouranth","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"summit1g","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"asmongold","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"disguisedtoast","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"quin69","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"smallant","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"tectone","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"northernlion","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"stableronaldo","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"alinity","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"willneff","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"destiny","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"aiden","t":"text","c":"rgba(0, 0, 0, 0)","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"imkaicenat","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"islandgrown","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"wilko","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"remove":false,"v":"macaiyla","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30},{"remove":false,"v":"graycen","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30},{"v":"brookeab","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"CORINNAKOPF","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"andymilonakis","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"koaster","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"modestcube","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"atrioc","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"malena","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"sennyk4","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"justaminx","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"miamalkova","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"SIMPMOM","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"vadikus007","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"jakenbankelive","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"smitegame","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"fream","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"kaicenat","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"bonnierabbit","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"russel","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"extraemily","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"yungjeff","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"snuffy","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"shylily","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false},{"v":"veibae","t":"text","c":"#9013FE","s":false,"h":false,"w":true,"p":30,"remove":false}]
__filter:highlight-users: [[30,"#9013FE",{}],[30,false,{}]]
chat.filtering.highlight-basic-terms: []
__filter:highlight-terms: null
chat.emoji.replace-joiner: 1
chat.filtering.mention-priority: 999
ffzap.core.remove_spaces: false
ffzap.betterttv.emote_modifiers: true
chat.rich.enabled: true
chat.rich.minimum-level: 0
chat.rich.want-mid: false
chat.name-format: 0
chat.timestamp-format: "h:mm"
chat.badges.hidden: {}
chat.badges.custom-vip: true
chat.filtering.hidden-tokens: {}
chat.subs.show: 3
chat.width: null
chat.effective-width: 340
chat.actions.size: 16
chat.actions.hover-size: 30
chat.timestamp-size: null
chat.font-size: 17
chat.lines.emote-alignment: 0
chat.font-family: "lucida sans unicode"
tooltip.images: true
tooltip.link-images: true
tooltip.link-nsfw-images: false

Probably to do with 7TV 3.0 update.

Edit:
Added browser version.

**Comment by Lordmau5** [comment]
You are correct, this is because of 7TV's new 3.0 extension update.
They are rewriting the entire chat so FFZ can't modify it anymore since everything's different.

For now, please uninstall their extension and use the add-on within FFZ.
It might not offer their new emote menu or tab-completion, but it should offer everything else.
