### ISSUE TITLE
Cinema mode

### ISSUE THREAD

**Issue by jezokshe** [FrankerFaceZ/FrankerFaceZ#1351]
**Describe the bug**
In cinema mode, when you hover over the player, the channel panel appears
**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/77186394/230481565-ea5a33fb-d900-445b-9bda-4f4372bfe2c3.png)

**Environment (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g. chrome, firefox]
 - Version [e.g. 70]
 - Other Extensions: [e.g. BetterTTV, Privacy Badger, AdBlock, etc.]
All Browsers
**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:

**Additional context**

**Comment by SirStendec** [comment]
That is expected behavior. To disable it, go to Player > General and in the Theatre Mode section disable "Show metadata when mousing over the player."
