### ISSUE TITLE
Ability to manually reconnect to chat

### ISSUE THREAD

**Issue by pointydev** [FrankerFaceZ/FrankerFaceZ#1352]
**Is your feature request related to a problem? Please describe.**
Currently I have an intermittent connection that causes both streams and their chats to experience issues. While the stream can recover by itself, most of the time the connection loss isn't long enough to cause the chat to enter a "disconnected" state, where it would reconnect automatically. That often leaves me in a state where I am not receiving new messages while under the impression nothing is wrong (especially in low-traffic rooms).

**Describe the solution you'd like**
A chat command to forcefully reconnect to chat, regardless of the current connection state.

**Describe alternatives you've considered**
A room action to forcefully reconnect to chat, or an option to also perform a chat reconnect when the "Reset Player" button is active and interacted with.

Thanks,
pointy

**Comment by SirStendec** [comment]
Added in 5956312ae30a1adff571001f8532f792039e90f0

I forgot to write it in the changelog, but there is now a /reconnect command.
