### ISSUE TITLE
Reset player button still shows in embedded clips with setting unchecked

### ISSUE THREAD

**Issue by TrantaLocked** [FrankerFaceZ/FrankerFaceZ#1356]
The setting for showing a reset player button does not affect embedded clips on reddit.

**Comment by SirStendec** [comment]
So, there's a whole problem with accessing settings data on other domains. FrankerFaceZ's settings are stored specifically on the domain `www.twitch.tv`, so when you access them from, for example, the clips subdomain `clips.twitch.tv` FrankerFaceZ needs to load a page from `www.twitch.tv` into an iframe so it can request its settings from itself.

This is obviously not a great situation, and it results in increased load times for settings. It *should* work in embeds, though, and it definitely works in my testing.

Are you using any sort of non-default privacy settings in your browser, or any extensions that try to block tracking / improve privacy? Something like that could easily stop what FFZ does to pass its settings around.

In the future, please fill out the issue template and don't just delete it.
