### ISSUE TITLE
Twitch link embeds do not seem to work if there is text after the URL

### ISSUE THREAD

**Issue by secondubly** [FrankerFaceZ/FrankerFaceZ#1362]
**Describe the bug**
When attaching a twitch url to a message, the embed will not return any data if there is text after the url, instead the embed will say: No data was returned

**To Reproduce**
1. Go to a Twitch chat 
2. Type in a twitch url and then any text afterwards (e.g. https://www.twitch.tv/deejayknight this is a test message)
3. Submit message
4. The resulting embed will state "No data was returned."

**Expected behavior**
No matter where you put the link, it should probably embed, right?

**Screenshots**
![firefox_zsiiQjFIfS](https://user-images.githubusercontent.com/6021602/235757010-4f69965a-57af-4f3a-8835-83f0e50da64c.png)
(failed embed)

![firefox_sqOb25mPjV](https://user-images.githubusercontent.com/6021602/235757166-d378e50c-e07d-4a48-bc53-ae1b6f09ce27.png)
(working embed)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 112.0.2
 - Other Extensions: BetterTTV, Ublock Origin, TTV LOL PRO

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**: https://ghostbin.me/64515c5f8ed19 (the FFZ upload was taking quite some time so I just copy+pasted it into another online editor)

**Additional context**
N/A

**Comment by SirStendec** [comment]
Fixed in 109898a10d49adaedcfcc1480798d221357721bc
