### ISSUE TITLE
Lost Access to Authenticator App for 2FA - Unable to Access My Account

### ISSUE THREAD

**Issue by mixofseasonings** [FrankerFaceZ/FrankerFaceZ#1364]
Long story short, I deleted my Google Authenticator App thinking that I had saved everything first for 2FA Access for the FFZ account. I did not save. No, I will not go into why I deleted that app. I cannot get into my account, even after logging in with my Twitch information. I am being asked to provide an authenticator code or a recovery code. I can't provide either. I need to make changes to payment for my subscription, and I am not clear on who to contact.  Can someone help? Thank you. Also my Twitch account name is this name, if that information is needed.

**Comment by SirStendec** [comment]
Please send a message to stendec@frankerfacez.com or DM me on Discord at SirStendec # 8530 to discuss this. GitHub issues are not private enough for discussing accounts.
