### ISSUE TITLE
Earn Channel Points when only using pop-out chat

### ISSUE THREAD

**Issue by Jademalo** [FrankerFaceZ/FrankerFaceZ#1371]
**Is your feature request related to a problem? Please describe.**
I use Streamlink, and don't have the twitch page of the channel I am watching open. Instead, I use pop-out chat in a chromium instance with FFZ installed.
When pop-out chat alone is open, you don't earn channel points for watching streams. 
I believe the same system is used for watch time for drops, though I'm not sure.

**Describe the solution you'd like**
In a similar vein to the `Automatically claim bonus rewards` option, it would be nice if points could be earned in pop-out chat alone when FFZ is installed.

**Describe alternatives you've considered**
Streamlink itself used to support this, but the functionality was removed a few years ago due to issues with authenticating through twitch. Since FFZ exists in an already authenticated instance of the site, it should be possible to implement as far as I am aware.

**Comment by SirStendec** [comment]
FFZ doesn't interact at all with the logic that Twitch uses to decide if you should be earning channel points, and I'm not interested in attempting to do that.

**Comment by Jademalo** [comment]
Alright, no worries
