### ISSUE TITLE
Auto-open the new native fullscreen chat

### ISSUE THREAD

**Issue by Hannah-GBS** [FrankerFaceZ/FrankerFaceZ#1377]
Since Twitch have apparently added a native way to view chat when in fullscreen (see video below), an option to automatically open this when entering fullscreen would be awesome.

Note that this feature seems to be still rolling out as the button did not appear to me when logged out, only when logged in.

https://github.com/FrankerFaceZ/FrankerFaceZ/assets/7504779/225af6a7-cf9b-4794-9d00-237627b0d4a2

**Comment by Tester798** [comment]
@EldritchEevee you can turn it on in experiments, it's called `chat_happening_now_2023`.

**Comment by jtyankees23** [comment]
just got the new feature today and noticed whenever I go into fullscreen it breaks Show metadata when mousing over the player.
since it thinks I'm hovered over the player.
