### ISSUE TITLE
Hide "hype chat" elements

### ISSUE THREAD

**Issue by Avenred** [FrankerFaceZ/FrankerFaceZ#1387]
**Is your feature request related to a problem? Please describe.**
Hype chats were recently added as a new feature, and I'd like to be able to hide the lightning bolt icon in the chat window & possibly more elements.

**Describe the solution you'd like**
I'd like an option to
- [Hide the lightning bolt icon next to the send button](https://i.imgur.com/AMHQbqN.png)
- [Hide the list of hype chats at the top of chat](https://i.imgur.com/WzXJmqe.png)
- Possibly hide, or at least make the in-chat effect when a hyper chat is sent less obtrusive

**Describe alternatives you've considered**
Using uBlock Origin to hide the button & element above the chat seems to work for now.

**Additional context**
N/A

**Comment by toofar** [comment]
I think this is done in the latest release, at least the first two.
