### ISSUE TITLE
Possible Massive Compatibility Issue With FrankerFaceZ and Twitch Integrated Tangia Interactive

### ISSUE THREAD

**Issue by cloudy1punk** [FrankerFaceZ/FrankerFaceZ#1388]
**Describe the bug**

Discovered a Possible Compatibility Issue With Twitch Integrated Tangia Interactive and FrankerFaceZ which resulted with My Computer freezing up after a few seconds several times. 

**To Reproduce**

1. Opened a Stream that has Tangia Interactive enabled through Twitch Integration My Computer Froze Up after a few seconds. Restarted my computer returned to the same streamer, my computer froze again, restarted again went to different streamer who was NOT using Tangia Interactive and it was fine. Went back to streamer who has Tangia Interactive and computer freezes yet again so I disabled FFZ returned yet to that stream and everything was fine.

**Environment (please complete the following information):**
 - OS: [e.g. Windows] Windows 8
 - Browser [e.g. chrome, firefox] Opera GX/Firefox
 - Version [e.g. 70]
 - Other Extensions: [e.g. BetterTTV, Privacy Badger, AdBlock, etc.]

**Comment by Tester798** [comment]
Can you provide a link to a streamer who is using Tangia Interactive?

**Comment by cloudy1punk** [comment]
https://www.twitch.tv/filian

**Comment by cloudy1punk** [comment]
> Can you provide a link to a streamer who is using Tangia Interactive?
https://www.twitch.tv/filian

**Comment by Tester798** [comment]
Does it work ok for you if you disable FFZ ?
I see a massive spike in memory consumption for extension subframe on page load:
![image](https://github.com/FrankerFaceZ/FrankerFaceZ/assets/8844478/f2ab2ad9-e034-4e92-92ca-ccc361fef6e4)
After initial spike it goes down. Maybe if you have faster PC it eats into you memory faster? I'm not sure.
But I see the same spike with FFZ enabled or disabled.
Also if I add https://assets.tangia.co/ url to my adblock there is no spike anymore.
Also in Firefox the spike isn't that dramatic.
Anyway, it's strange that your PC would completely froze on memory spikes, maybe it's some issue with drivers etc.
You can try to experiment with these variables (starting with adblock extension url) and check if you can make it work. Also try to disable all other extensions and check if it would work in this case.

**Comment by cloudy1punk** [comment]
I've been watching this stream today with FFZ enabled and I noticed the memory spike in my task manger it actually opens a new background Opera GX process and immediately goes to a gigabyte memory usage and keeps climbing I ended the process which stopped it from freezing. Will try try adblock.

**Comment by cloudy1punk** [comment]
Adblocking seems to be working
