### ISSUE TITLE
Chats Background Picture is Black

### ISSUE THREAD

**Issue by BBJK26** [FrankerFaceZ/FrankerFaceZ#139]
**Web Browser**: Using Chrome extention and when I click on people in chats name their background image is always black.  Is this a bug or something that can be enabled?

**Do you use BetterTTV or other Twitch extensions**:

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**:

**Steps to Reproduce (if Applicable)**:

**Comment by SirStendec** [comment]
This is a minor bug with Twitch's template, so rather than fixing it myself, I've forwarded the bug report ahead. Hopefully it will be fixed in a day or two.

Thanks for the report!
