### ISSUE TITLE
Add an option to block/hide streams with specified tags

### ISSUE THREAD

**Issue by Foretack** [FrankerFaceZ/FrankerFaceZ#1392]
**Is your feature request related to a problem? Please describe.**
I don't want to see VTubers on my home page, and I'm sure many others don't want to as well

**Describe the solution you'd like**
FFZ already provides a way to block or hide certain categories, and also streams that match a title regex. So I think it's only logical to have an option to filter out stream tags, such as `Vtuber` `ASMR` etc...

**Describe alternatives you've considered**
Not using the frontend, because recommendations suck

**Comment by SirStendec** [comment]
Implemented in 92fcc853a60c9e95c48fd8108dd7e7349272e0bb
