### ISSUE TITLE
Fullscreen doesn't really go to full screen

### ISSUE THREAD

**Issue by MrAmericanMike** [FrankerFaceZ/FrankerFaceZ#1394]
**Describe the bug**
The stream isn't really in full screen, but has a margin all around when going into Fullscreen mode.

**To Reproduce**
Enter any stream, click "Fullscreen"
The stream isn't really in full screen, but has a margin all around

**Expected behavior**
The stream should be full screen

**Screenshot**
![U](https://github.com/FrankerFaceZ/FrankerFaceZ/assets/8037559/ea2d3be1-3476-48f7-8168-5282c35b3a1e)
(Notice the black margin)

**Environment (please complete the following information):**
 - OS: Windows
 - Browser: Brave
 - Version: 1.56.9
 - Other Extensions: n/a

**Comment by MrAmericanMike** [comment]
As extra information. The responsible for this issue is this setting (Causing the issue when enabled)

```
Show the minimized navigation bar when in theatre mode.
```

As we can see, this should only affect theatre mode, but it's affecting Fullscreen.

**Comment by solomongrundy6** [comment]
I just came to report the same thing, and the same workaround.  Using Firefox.

**Comment by SirStendec** [comment]
Fixed in 92fcc853a60c9e95c48fd8108dd7e7349272e0bb
