### ISSUE TITLE
Option to auto-disable "Featured Clips Only" when browsing clips

### ISSUE THREAD

**Issue by Taizunz** [FrankerFaceZ/FrankerFaceZ#1396]
**Is your feature request related to a problem? Please describe.**
Twitch just released a new feature that allows channel owners to set their clips page to always default to "Featured Clips Only".
The user browsing a channels clips page has to manually toggle this switch to display the full list of clips.

**Describe the solution you'd like**
An option in FFZ that automatically toggles this new option off whenever the user is browsing a channels clips page.

**Describe alternatives you've considered**
None at the moment.

**Additional context**
![image](https://github.com/FrankerFaceZ/FrankerFaceZ/assets/15648000/9d998cb1-ebc7-4673-a9d8-81ca138f352d)

**Comment by Morten79** [comment]
I would really like to see such feature in the next release, please.

**Comment by Morten79** [comment]
Thanks alot for making the enhancement a reality :smiley: :thumbsup:

**Comment by Taizunz** [comment]
https://github.com/FrankerFaceZ/FrankerFaceZ/commit/cef58241d429625f14c8afdf249d1b8bab8dd553
