### ISSUE TITLE
Add a Blacklist for Raid functions

### ISSUE THREAD

**Issue by TsukiZero** [FrankerFaceZ/FrankerFaceZ#1398]
**Is your feature request related to a problem? Please describe.**
In a sense, yes. I don't want to join raids to specific channels and want to automatically opt out of raid to those specific channels.

**Describe the solution you'd like**
Simple: a blacklist option where we add channels we never ever want to be sent to. If the raid target matches a blacklisted channel, the user automatically leaves the raid.

**Describe alternatives you've considered**
Actually asked ChatGPT to try and make a code to do so, but didn't work. And found no script for this anywhere.

**Additional context**
Add a button in the Raid notification to "Leave and Blacklist"

**Comment by SirStendec** [comment]
Implemented in 92fcc853a60c9e95c48fd8108dd7e7349272e0bb

**Comment by TsukiZero** [comment]
Thank you so much!
