### ISSUE TITLE
Golden Kappa Train whitelist

### ISSUE THREAD

**Issue by pointydev** [FrankerFaceZ/FrankerFaceZ#1399]
**Is your feature request related to a problem? Please describe.**
Usually I prefer to have Hype Trains hidden as they're effectively just a Twitch cash grab. However Golden Kappa Trains have been becoming more common recently, and I would personally like to participate in them for the memes.

**Describe the solution you'd like**
An option to whitelist Golden Kappa Trains when regular Hype Trains are hidden via the option in Appearance.

**Describe alternatives you've considered**
Using CSS to hide regular Hype Trains while whitelisting Golden Kappa Trains due to their unique styling. This would however result in UI artifacts when multiple pinned events are present.

**Additional context**
![example](https://github.com/FrankerFaceZ/FrankerFaceZ/assets/22241432/79d9543b-2726-4a4c-92cd-6067892d0bef)

The unique styling used on one of the Hype Train parent elements:
```css
--hype-train-progress: var(--color-orange-12); --hype-train-background: linear-gradient(
  99.04deg,
  rgba(255, 255, 255, 0) 4.07%,
  rgba(255, 255, 255, 0.8) 15.55%,
  rgba(255, 255, 255, 0) 29.58%,
  rgba(255, 255, 255, 0) 39.14%,
  rgba(255, 255, 255, 0.77) 48.71%,
  rgba(255, 255, 255, 0.05) 56.36%,
  rgba(255, 255, 255, 0.447714) 75.49%,
  rgba(255, 255, 255, 0.92) 78.68%,
  rgba(255, 255, 255, 0.78) 82.5%,
  rgba(255, 255, 255, 0) 92.71%,
  rgba(255, 255, 255, 0.432432) 102.91%,
  rgba(255, 255, 255, 0.78) 107.37%
),
var(--color-orange-14); --hype-train-progress-filled: linear-gradient(
  99.04deg,
  rgba(255, 255, 255, 0) 4.07%,
  rgba(255, 255, 255, 0.8) 15.55%,
  rgba(255, 255, 255, 0) 29.58%,
  rgba(255, 255, 255, 0) 39.14%,
  rgba(255, 255, 255, 0.77) 48.71%,
  rgba(255, 255, 255, 0.05) 56.36%,
  rgba(255, 255, 255, 0.447714) 75.49%,
  rgba(255, 255, 255, 0.92) 78.68%,
  rgba(255, 255, 255, 0.78) 82.5%,
  rgba(255, 255, 255, 0) 92.71%,
  rgba(255, 255, 255, 0.432432) 102.91%,
  rgba(255, 255, 255, 0.78) 107.37%
),
var(--color-orange-14);
```

Thanks,
pointy

**Comment by SirStendec** [comment]
Hype trains are hidden at the data layer, and not with simple CSS. There's a list of active community highlights, and FFZ intercepts changes to the list to instantly remove types the user doesn't want to see.

I'm not sure if there is any information on the community highlight to actually identify if a given hype train event is a golden kappa train or not. If you encounter one in the wild, please run this in your browser's console (F12 to open) and upload the resulting JSON here:

```javascript
JSON.stringify((ffz.resolve('site.chat').community_stack?.highlights ?? []).filter(x => x.event?.type === 'hype_train').map(x => x.event), null, '\t')
```

**Comment by SputNikPlop** [comment]
@SirStendec This was the golden kappa hype train on BasiilLeafs about 6:20PST
```
[
	{
		"type": "hype_train",
		"typeDetails": "0",
		"eventID": "fcb012d0dff20cf56b294007b95e47f7"
	}
]
```

**Comment by SirStendec** [comment]
This is, in theory, implemented in 92fcc853a60c9e95c48fd8108dd7e7349272e0bb but I don't know if it will work as expected. Going to leave this issue open for a bit, hoping that someone reports back in the positive (or not).

**Comment by pointydev** [comment]
Just discussed this on Discord but thought I'd post here too, typeDetails 0 seems to be "A hype train is close!", and [not a Golden Kappa Train](https://github.com/FrankerFaceZ/FrankerFaceZ/commit/92fcc853a60c9e95c48fd8108dd7e7349272e0bb#diff-a7b9f3d73aa94e25e5af21d4799da0f8994114e53545a76d478ba0d3b9d82547R1683-R1685). I confirmed this by hiding regular trains but enabling the new option, and the event showed up.

![hype train close](https://github.com/FrankerFaceZ/FrankerFaceZ/assets/22241432/f28a2867-0a0c-4ab9-8984-071e3510b9bc)

**Comment by pointydev** [comment]
Closing since the overarching setting was removed in 10d35468a9d1041f0946198d2a5aca1b8cb49358.

**Comment by SputNikPlop** [comment]
Just updating this but this is now available in eventsub per https://dev.twitch.tv/docs/change-log/
