### ISSUE TITLE
MetaData goes onto 2 lines

### ISSUE THREAD

**Issue by LawlyPopz** [FrankerFaceZ/FrankerFaceZ#14]
**Web Browser**: Chrome

**Do you use BetterTTV or other Twitch extensions**: BTTV 4 FFZ

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: N/A

**Bug / Idea**:

![bug](http://pushzz.xyz/img/baace.png)

**Steps to Reproduce (if Applicable)**:

If you remove the code below it will fix it back like the image below

![bug](http://pushzz.xyz/img/4b2df.png)

`.ffz-theater-stats .app-main.theatre .cn-metabar__more {
    /* max-width: calc(100% - 600px); */
}`

**Comment by SirStendec** [comment]
This is the correct behavior. The width is fixed to prevent it from making the player's menu unusable.

**Comment by LawlyPopz** [comment]
oh ok i got ya mate!
