### ISSUE TITLE
Black bar blocking video in portrait mode

### ISSUE THREAD

**Issue by TWHou** [FrankerFaceZ/FrankerFaceZ#140]
**Web Browser**: 
Safari

**Do you use BetterTTV or other Twitch extensions**: 
No

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:
http://putco.de/NTgzMg.log

**Bug / Idea**:
The left side of the video (where my chat is normally at) gets block by a black bar when the layout switch to portrait mode.

![screen shot 2017-04-20 at 18 24 21](https://cloud.githubusercontent.com/assets/12669000/25254996/9f5ffb28-25f6-11e7-9eca-011f1c8b55bf.png)

**Steps to Reproduce (if Applicable)**:

**Comment by SirStendec** [comment]
I think this might be an issue with how Safari handles CSS, as I can't reproduce it in Chrome with your exact settings. I've asked a friend with a Mac to see if they can reproduce the issue, so we'll see.
