### ISSUE TITLE
Stream delay disappeared in new moderator view of Twitch

### ISSUE THREAD

**Issue by webmylife** [FrankerFaceZ/FrankerFaceZ#1400]
**Describe the bug**
The moderator view has changed recently and the stream delay isn't showed anymore

**To Reproduce**
Note that I have FFZ in French, so I will do my best to translate
1. Go to Moderator view of Twitch
2. In FFZ settings, activate Channel > Metadata > Playing statistics (4th one from the top)

Edit : Here's a screenshot of the option that has been activated https://i.imgur.com/x01QE4M.png 

**Expected behavior**
Stream delay showed

**Screenshots**
Before : https://i.imgur.com/gvEi54V.png
After : https://i.imgur.com/Lh99ulB.png

**Environment (please complete the following information):**
 - OS: Windows 11
 - Browser : Chrome
 - Version 116.0.5845.111 
 - Other Extensions: BetterTTV

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:
https://sharetext.me/4nspmgfhaw

**Comment by SirStendec** [comment]
Fixed in 588d3e3da9a12a59d231364a7695d4c36b41f5f4
