### ISSUE TITLE
Tooltip 'NaN spec' when there are more than 1k viewers

### ISSUE THREAD

**Issue by Nicolas-Leucci** [FrankerFaceZ/FrankerFaceZ#1401]
Hi all !

When a live Twitch channel have more than 1k viewers, the tooltip is not showing properly.
PS: I'm in french language.

**Screenshots**
(>1k)
![image](https://github.com/FrankerFaceZ/FrankerFaceZ/assets/6442801/7bebb97f-586a-44fb-acba-ed5ba8bc2e96)
![image](https://github.com/FrankerFaceZ/FrankerFaceZ/assets/6442801/e7509a2f-1122-4c42-83d3-7e896e4056fe)

(<1k)
![image](https://github.com/FrankerFaceZ/FrankerFaceZ/assets/6442801/3a672331-142e-45d3-82d9-ca4d8aeb2ab2)
![image](https://github.com/FrankerFaceZ/FrankerFaceZ/assets/6442801/0a64fc87-f852-4ac6-bb7b-02dff66d87c9)

**Environment:**
 - OS: Windows 10
 - Latest Firefox (117 atm)

Thanks !

**Comment by kioshimushi** [comment]
I don't really know if it's a FFZ issue or a twitch issue but it happened in different language, like French, Deutsh and Polish for example and it's like this for quit some months now.

As of today it looks like it is finnaly fixed and I did not noticed any update on FFZ so it might just have been Twitch. Check on your part if it is working for you.
