### ISSUE TITLE
"Display Leaderboard" setting not working under Chat > Appearance

### ISSUE THREAD

**Issue by masatti** [FrankerFaceZ/FrankerFaceZ#1403]
**Describe the bug**
This setting stopped working a few hours ago and I'm now seeing the leaderboard despite not having this setting enabled.

**To Reproduce**
1. Go to a Twitch stream
2. Open chat

**Expected behavior**
Leaderboard should not be visible at any point if the setting isn't enabled.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser Microsoft Edge
 - Version 4.50.0
 - Other Extensions: uBlock Origin

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**: 
https://pastebin.com/msqLsh9G

**Comment by Dan-Y89** [comment]
The same bug occurs when you block the poison sub display with uBlock Origin, which then displays the bits display. And in full screen mode the hype chat. 


Browser Chrome.
Log shows that the function is disabled, although it is enabled in FFZ (poison display in chat.)
chat.bits.show-pinned: false
chat.subs.gift-banner: false
chat.banners.hype-train: false
![gift1](https://github.com/FrankerFaceZ/FrankerFaceZ/assets/28935869/eb0a9345-d9ba-427d-a127-c4c01712f9c9)

Not working: 
![gift](https://github.com/FrankerFaceZ/FrankerFaceZ/assets/28935869/26851e9c-4632-4fb3-8c6a-d98a7d78d2d7)


But also with Hype and Bits, but this is currently not displayed in normal chat, so I only have the screen for the Gift display.
I hope you can fix it quickly, the ads are really annoying :D.

Thank You

**Comment by swoops44** [comment]
Im getting the same problem, i cant get rid of the top gifters with the "display leaderboard" option turned off.  I think its twitch's fault for updating it about 20 hours ago.

**Comment by SirStendec** [comment]
Fixed in 588d3e3da9a12a59d231364a7695d4c36b41f5f4
