### ISSUE TITLE
Compressor option/button is missing in Firefox.

### ISSUE THREAD

**Issue by esonique** [FrankerFaceZ/FrankerFaceZ#1406]
**Describe the bug**
FFZ extension in Firefox is missing the option for audio compression.  Brave and Chrome both have the option when installing the extension.

**To Reproduce**
1. Watch Twitch stream
2. Click on FFZ extension button
3. Scroll down to Player
4. Missing Audio Compressor option in list

**Expected behavior**
Button should appear on stream page next to volume slider; Compressor option should be visible under extension settings.

**Screenshots**
Screenshots of Firefox vs Brave attached.

**Environment (please complete the following information):**
 - OS: [Windows 11 Version 22H2 (0S Build 22621.1848)]
 - Browser [Firefox]
 - Version [118.0b6 (64-bit)]
 - Other Extensions: [BetterTTV, AdGuard, Firefox Multi-containers]

**FFZ Logs [attached as text file]

**Additional context**
Added log as a text file to issue.  Upload button in extension hangs after pressing it.
[Log_20230908.txt](https://github.com/FrankerFaceZ/FrankerFaceZ/files/12565152/Log_20230908.txt)
![FFZ Compressor Firefox](https://github.com/FrankerFaceZ/FrankerFaceZ/assets/85214149/6b5f0e56-80ed-4e71-97b8-ac705dd5d595)
![FFZ Compressor Brave Browser](https://github.com/FrankerFaceZ/FrankerFaceZ/assets/85214149/4907553f-5492-44fa-813b-27a1e02dc1de)

**Comment by SirStendec** [comment]
This means that something in your browser's configuration has disabled the HTML5 audio APIs. The settings do not appear if a feature check fails.

Since you're using firefox, open `about:config` and search for `audio` to see if you have any settings that aren't set to the default values. The most likely problem here is `dom.webaudio.enabled`. That needs to be set to true.

**Comment by esonique** [comment]
Thank you.  dom.webaudio.enabled was set to false in Firefox.  Which is
kind of weird as I just reinstalled a fresh copy of Firefox yesterday.  But
thank you again for helping me with my issue.
