### ISSUE TITLE
Don't show bits / subs leaderboard on fullscreen chat

### ISSUE THREAD

**Issue by Zoooook** [FrankerFaceZ/FrankerFaceZ#1415]
**Is your feature request related to a problem? Please describe.**
"Gift 1 sub to take first!" is now showing up at the top of full screen chat, I don't recall this happening before.
The button is also white instead of purple, which makes me think there's a possible way to write an adblock filter for it, but I haven't figured it out yet.

**Describe the solution you'd like**
An option to remove all of this type of header in full screen chat, including hype chats, hype trains, etc.

**Describe alternatives you've considered**
Adblock filter

**Comment by SirStendec** [comment]
There are already FrankerFaceZ settings to hide those elements. If you only want them to be hidden while you're using fullscreen, you can make a new profile, add a rule to it so it's only active when you're in fullscreen, and then enable the settings to hide those features in that profile.

Here's an example profile that does just that that you can import:

[ffz-profile - Hide Unwanted Stuff in Fullscreen.json](https://github.com/FrankerFaceZ/FrankerFaceZ/files/12908299/ffz-profile.-.Hide.Unwanted.Stuff.in.Fullscreen.json)
