### ISSUE TITLE
Block all messages that consist of just emotes

### ISSUE THREAD

**Issue by MrAmericanMike** [FrankerFaceZ/FrankerFaceZ#1416]
**Is your feature request related to a problem? Please describe.**
Yes the main problem is that many channels use BTTV Emojis or others like 7TV and so on. So me only using FFZ I don't see them but I see text spam like:

patrickPls, bartJAM, duckPls, dogJAM, pepeEyeRoll, peepoBike and the list can go on and on for ever.

**Describe the solution you'd like**
A feature to block all non Twitch Emojis (Yes including FFZ ones) and make messages that consist of just those, not even show in chat, or alternatively, instead of replacing them with `×××` replace them with just `×` maybe or whatever makes it cleaner.

**Describe alternatives you've considered**
I have been blocking emojis manually by adding them to the blocked Terms in FFZ, but even doing so I end up with messages that consist in just.
```
××× ××× ××× ××× ××× ××× ××× ××× ××× ××× ××× ×××
```

**Additional context**

For example, if a message looks like this:

![image](https://github.com/FrankerFaceZ/FrankerFaceZ/assets/8037559/1253f2ca-6f4d-411f-ad29-9ad7e18a979c)

Give me options over that, like hiding the whole message or grouping all emojis into just 1.

**Comment by SirStendec** [comment]
There is already an add-on specifically for blocking messages with nothing but emotes.

Alternatively, PrattleNot can be configured to act that way and you can hide the secondary panel that PrattleNot creates by setting its size to zero.

**Comment by MrAmericanMike** [comment]
> There is already an add-on specifically for blocking messages with nothing but emotes.
> 
> Alternatively, PrattleNot can be configured to act that way and you can hide the secondary panel that PrattleNot creates by setting its size to zero.

Thanks a lot, will take a look into that.
