### ISSUE TITLE
A setting to keep the channel categories sort option to what I choose instead of going back to default

### ISSUE THREAD

**Issue by thinkpad4** [FrankerFaceZ/FrankerFaceZ#1417]
Is it possible to add a setting to change the sort options in the channel categories?

I would like to be able to set it to Viewers (High to Low) instead of Recommended For You which is keeps defaulting all the time

**Comment by SirStendec** [comment]
Implemented in 21ae0059a5d4bf376222591ca8e0a4995d030f0f
