### ISSUE TITLE
Unwanted bots, blocking and highlighting

### ISSUE THREAD

**Issue by fbck** [FrankerFaceZ/FrankerFaceZ#1419]
There's always a bunch of these suspicious bots around in chats (see https://twitchinsights.net/bots - this kind, not the useful "known good bots"/streamer bots kind). 
Seeing how people still get thrown off and confused by seeing those in user list ('who are these people? are they chatting? are they viewing? or even people at all? etc), it'd be really helpful if there was something to identify them in the Users in chat panel, and maybe even tools for banning/blocking them. 
Maybe a Bots/Idle Bots section in users list, maybe even some one-button thing for banning/blocking (like, a ban/block hover button next to user names, or 'ban all that are in chat', or 'auto ban from a list').
It'd be way easier to point people to something like that as an explanation and a solution. (so that it wouldn't have to be the whole 'well, it's bots, and there's a list, and manual banning, etc. etc.' thing, but more like 'install this')

**Comment by SirStendec** [comment]
I have no plans to do anything with the viewer list.

I personally think the viewer list should be removed as a feature, and I refuse to spend any effort on it.
