### ISSUE TITLE
Scroll wheel volume control doesn't always work on all channels

### ISSUE THREAD

**Issue by robmonte** [FrankerFaceZ/FrankerFaceZ#1424]
**Describe the bug**
On some channels, scrolling the mouse wheel does not change the stream volume when hovering the stream, and _only_ works when hovering the volume bar. For example, on Esfandtv it will always have this behavior for me, but most other streams work as expected.

**To Reproduce**
1. Go to https://www.twitch.tv/esfandtv
2. Enable scroll to change volume
3. Try scrolling the wheel while mousing over the player
4. The page moves up and down instead of adjusting the volume

**Expected behavior**
The volume should change when mousing anywhere over the stream video

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 119
 - Other Extensions: uBlock Origin

**Additional context**
I am wondering if it may have to do with something like Twitch extensions on his channel page? Not sure why else it always affects his channel and not most others I go to.

&nbsp;

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:
<details>
<summary>FFZ log data</summary>
initialization
-------------------------------------------------------------------------------
[23:54:04] info | core: FrankerFaceZ v4.55.3 (s:twitch f:main b:null c:60e4edf7c231c745bafd1e9a601a5af0255603b8)
[23:54:04] info | core: Initial URL: https://www.twitch.tv/esfandtv
[23:54:04] info | site: Using: Twilight
[23:54:04] info | site.web_munch: Found and wrapped webpack's loader after 0ms.
[23:54:04] info | settings: Using Provider: LocalStorageProvider
[23:54:04] info | site.web_munch: require() grabbed in 1.70000ms.
[23:54:04] info | core: Loaded descriptions of 0 modules.
[23:54:04] info | settings: Initialization complete after 21.60000ms -- Values: 68 -- Profiles: 2
[23:54:04] info | site.fine: Installing MutationObserver.
[23:54:04] info | site: Loaded descriptions of 17 modules.
[23:54:04] info | site.elemental: Installing MutationObserver.
[23:54:04] info | main_menu: Built Tree in 10.00000ms with 180 structure nodes and 311 settings nodes.
[23:54:04] info | experiments: Loaded information on 3 experiments.
[23:54:04] warn | site.player: Unable to install document visibility hook. TypeError: Cannot redefine property: hidden
[23:54:04] info | site.chat: Chat Types have changed from static mappings for categories: CHAT_TYPES
[23:54:04] info | core: Initialization complete in 458.80000ms.

settings
-------------------------------------------------------------------------------
i18n.debug.capture: false
i18n.format.date: "default"
i18n.format.time: "short"
i18n.format.datetime: "medium"
i18n.debug.transform: null
i18n.locale: "en"
data.use-staging: false
addons.dev.server: false
chat.bits.show: true
layout.display-bits-button: true
metadata.modview.hide-info: false
layout.side-nav.hide-viewers: false
metadata.uptime: 2
metadata.uptime.no-native: true
metadata.viewers: false
metadata.viewers.no-native: false
layout.swap-sidebars: false
layout.portrait: true
layout.portrait-threshold: 1.25
layout.use-portrait: false
chat.width: null
chat.use-width: false
layout.use-chat-fix: false
layout.is-theater-mode: false
layout.theatre-navigation: false
layout.minimal-navigation: false
layout.side-nav.show-avatars: true
layout.side-nav.show: 1
layout.side-nav.hide-offline: false
layout.hide-discover-luna: false
layout.prime-offers: true
channel.hide-unfollow: false
chat.hype.show-pinned: true
channel.round-avatars: false
channel.hide-live-indicator: false
layout.side-nav.rerun-style: 0
layout.side-nav.show-rec-channels: 0
layout.side-nav.show-friends: 1
whispers.show: true
channel.show-celebrations: true
layout.subtember: false
layout.theme.global-font: ""
layout.turbo-cta: true
layout.portrait-invert: false
layout.portrait-min-chat: false
layout.inject-portrait: false
layout.use-portrait-swapped: false
player.theatre.metadata: false
layout.use-portrait-meta: false
layout.use-portrait-meta-top: false
layout.portrait-extra-width: 5
player.theatre.no-whispers: false
layout.portrait-extra-height: 14
theme.disable-auto-dark: false
theme.can-dark: true
theme.is-dark: true
theme.color.background: ""
theme.color.text: ""
theme.legacy-dark-input: false
theme.color.accent: ""
theme.color.tooltip.background: ""
theme.color.tooltip.text: ""
theme.color.chat-background: ""
theme.color.chat-text: ""
theme.color.chat-accent: ""
theme.font.size: 13
directory.show-channel-avatars: undefined
directory.hide-live: false
directory.hidden.reveal: false
directory.hidden.style: 2
channel.panel-tips: true
channel.auto-click-chat: true
player.gain.enable: true
player.gain.no-volume: false
player.volume-always-shown: true
player.ext-interaction: true
player.hide-mouse: false
player.fade-pause-buffer: true
player.ext-hide: 0
player.captions.font-size: ""
player.captions.font-family: ""
player.compressor.enable: true
player.compressor.shortcut: null
player.no-autoplay: false
player.home.autoplay: false
player.disable-content-warnings: false
player.button.pip: true
player.button.reset: true
player.gain.min: 0
player.gain.max: 2
player.compressor.default: true
player.allow-catchup: true
player.hide-event-bar: false
ffz.show-new-settings: true
directory.block-titles: []
__filter:directory.block-titles: null
channel.extra-links: true
player.compressor.force-legacy: false
player.gain.default: 1
player.compressor.threshold: -50
player.compressor.knee: 40
player.compressor.ratio: 12
player.compressor.attack: 0
player.compressor.release: 0.25
player.theatre.auto-enter: false
addon.seventv_emotes.badges: true
addon.seventv_emotes.global_emotes: true
addon.seventv_emotes.channel_emotes: true
addon.seventv_emotes.nametag_paints: true
addon.seventv_emotes.animated_avatars: true
addon.seventv_emotes.emote_updates: true
addon.chatterino_badges.badges: true
addon.seventv_emotes.unlisted_emotes: true
sub-button.prime-notice: true
metadata.clip-download: true
metadata.featured-follow: true
metadata.player-stats: true
metadata.stream-delay-warning: 10
player.volume-scroll: true
player.gain.scroll: 2
player.volume-scroll-steps: 0.01
ffz.search.matches-only: true

experiments
-------------------------------------------------------------------------------
Unique ID: pIiL6HqnGmgMKVIRDps1PpbEuwIYt4WN

FFZ | MQTT-Based PubSub: false (r:0.85)
Twitch | TWILIGHT_AD_DENSITY_WIDGET: no (r:0, t:channel_id, c:esfandtv)
Twitch | auto_mod_smart_detection: control (r:0, t:channel_id, c:esfandtv)
Twitch | channel_points_reward_limits_v2: control (r:0, t:channel_id, c:esfandtv)
Twitch | chat_ad_alerts: control (r:0, t:channel_id, c:esfandtv)
Twitch | chmod-bcsvs: control (r:0, t:channel_id, c:esfandtv)
Twitch | copo_multi_option_predictions: control (r:0, t:channel_id, c:esfandtv)
Twitch | ht_celeb_experiment: Control (r:0, t:channel_id, c:esfandtv)
Twitch | hype_train_all_time_high: hype_train_all_time_high_off (r:0, t:channel_id, c:esfandtv)
Twitch | ltd_experiment_v2: PRERELEASE (r:0, t:channel_id, c:esfandtv)
Twitch | more_default_quick_actions: control (r:0, t:channel_id, c:esfandtv)
Twitch | new_affiliates_goals: control (r:0, t:channel_id, c:esfandtv)
Twitch | persistent_goals_2: control (r:0, t:channel_id, c:esfandtv)
Twitch | project_ape: control (r:0, t:channel_id, c:esfandtv)
Twitch | toga-turtle-street: control (r:0, t:channel_id, c:esfandtv)
Twitch | community_insights: control (r:0.01, t:channel_id, c:esfandtv)
Twitch | consent_tool_headline: E (r:0.14, t:device_id)
Twitch | brand_lift_survey_experiment_2: variant_1 (r:0.33, t:user_id)
Twitch | Devsite_create_apps_form_recaptcha: variant1 (r:0.5, t:user_id)
Twitch | bits_card_evolution: control (r:0.5, t:user_id)
Twitch | bits_top_nav_explanation : experiment (r:0.5, t:user_id)
Twitch | creator_follow_cue: activity-feed (r:0.5, t:user_id)
Twitch | giftcard_redemption_in_checkout: experiment (r:0.5, t:device_id)
Twitch | new_pubsub_client: control (r:0.5, t:device_id)
Twitch | player_core_edge_prewarm: treatment (r:0.5, t:device_id)
Twitch | sda_post_fill_drop: treatment (r:0.5, t:device_id)
Twitch | subscriber_recap: control (r:0.5, t:channel_id, c:esfandtv)
Twitch | toad_experiment: control (r:0.6, t:channel_id, c:esfandtv)
Twitch | disco_bpli: control (r:0.75, t:user_id)
Twitch | cheering_web_ux_improvements: treatment (r:0.95, t:user_id)
Twitch | hype_chat_buy_your_own: treatment (r:0.95, t:user_id)
Twitch | liverecs_holdout_device: control (r:0.98, t:device_id)
Twitch | liverecs_holdout_v2: control (r:0.98, t:user_id)
Twitch | percolite-shelf-reranking-logged-in: variant1b (r:0.98, t:user_id)
Twitch | chat_happening_now_2023: variant (r:0.99, t:user_id)
Twitch | disco_carousel_shelf: control (r:0.99, t:user_id)
Twitch | disco_sprig_logged_out: control (r:0.99, t:device_id)
Twitch | guest_star_left_nav_online_channel_augmentation: allowed (r:0.99, t:device_id)
Twitch | mse_in_workers: treatment (r:0.99, t:device_id)

addons
-------------------------------------------------------------------------------
Known
unread-mentions-counter | disabled | UnreadMentionsCounter v1.1.1
smokemotes | disabled | smokeys_utils v1.1.7
smm2-links | disabled | SMM2 Links v1.0.0
screenshoter | disabled | screenshoter v1.1.1
repetition-detector | disabled | repetition_detector v1.1.0
pronouns | disabled | pronouns v1.1.1
prattlenot | disabled | PrattleNot v0.8.1
poll-shim | disabled | poll_shim v0.2.2
new-account-highlighter | disabled | New Account Highlighter v1.1.1
inline-tab-completion | disabled | Inline Tab v1.2.4
fs-chat | disabled | fs-chat v1.5.2
first-message-highlighter | disabled | first_msg_highlight v1.0.2
ffzap-liriklive | disabled | FFZ:AP LirikLIVE v3.2.2
ffzap-core | enabled | FFZ:AP Core v3.3.11
ffzap-bttv | enabled | FFZ:AP BTTV v3.3.18
emoteless | disabled | emote_less_chat v1.0.6
deck | disabled | Deck v2.4.0
clip-confirm | disabled | ClipConfirm v1.0.5
chatterino-badges | enabled | Chatterino v1.0.0
brcm | disabled | brcm v1.0.0
aplatypuss-emotes | disabled | Aplatypuss Emotes v1.0.0
ModTools | disabled | Mod Tools v1.0.1
7tv-emotes | enabled | 7TV v1.3.2

Modules
loaded   | enabled  | 
loaded   | enabled  | core
loaded   | enabled  | settings
loaded   | enabled  | experiments
loaded   | enabled  | i18n
loaded   | enabled  | staging
loaded   | enabled  | load_tracker
loaded   | enabled  | socket
loaded   | enabled  | pubsub
loaded   | enabled  | site.web_munch
loaded   | enabled  | site.fine
loaded   | enabled  | site.elemental
loaded   | enabled  | site.router
loaded   | enabled  | site.apollo
loaded   | enabled  | site.twitch_data
loaded   | enabled  | site.subpump
loaded   | enabled  | site
loaded   | enabled  | addons
loaded   | enabled  | vue
loaded   | enabled  | tooltips
loaded   | enabled  | chat.badges
loaded   | enabled  | chat.emotes
loaded   | enabled  | chat.emoji
loaded   | enabled  | chat.actions
loaded   | enabled  | chat.overrides
loaded   | enabled  | chat
loaded   | enabled  | emote_card
loaded   | enabled  | link_card
loaded   | enabled  | main_menu
loaded   | enabled  | site.bits_button
loaded   | enabled  | metadata
loaded   | enabled  | site.bttv_compat
loaded   | enabled  | site.css_tweaks
loaded   | enabled  | site.channel
unloaded | disabled | translation_ui
loaded   | enabled  | site.chat.scroller
loaded   | enabled  | site.chat.chat_line.rich_content
loaded   | enabled  | site.chat.chat_line
loaded   | enabled  | site.chat.settings_menu
loaded   | enabled  | site.chat.emote_menu
loaded   | enabled  | site.chat.input
loaded   | enabled  | site.chat.viewer_cards
loaded   | enabled  | site.chat
loaded   | enabled  | site.compat_emote_menu
loaded   | enabled  | site.dashboard
loaded   | enabled  | site.directory.game
loaded   | enabled  | site.directory
loaded   | enabled  | site.featured_follow
loaded   | enabled  | site.layout
loaded   | enabled  | site.loadable
loaded   | enabled  | site.menu_button
loaded   | enabled  | site.mod-view
loaded   | enabled  | site.player
loaded   | enabled  | site.sub_button
loaded   | enabled  | site.theme
loaded   | enabled  | site.video_chat
loaded   | enabled  | addon.7tv-emotes
loaded   | enabled  | addon.7tv-emotes.api.emotes
loaded   | enabled  | addon.7tv-emotes.api.cosmetics
loaded   | enabled  | addon.7tv-emotes.api
loaded   | enabled  | addon.7tv-emotes.avatars
loaded   | enabled  | addon.7tv-emotes.badges
loaded   | enabled  | addon.7tv-emotes.emotes
loaded   | enabled  | addon.7tv-emotes.eventapi
loaded   | enabled  | addon.7tv-emotes.nametag-paints
loaded   | enabled  | addon.chatterino-badges
loaded   | enabled  | addon.ffzap-core
loaded   | enabled  | addon.ffzap-bttv

chat
-------------------------------------------------------------------------------
chat settings
-------------------------------------------------------------------------------
chat.effects.enable: true
chat.effects.FlipX: true
chat.effects.FlipY: true
chat.effects.ShrinkX: true
chat.effects.GrowX: true
chat.emotes.animated: 1
chat.effects.Slide: true
chat.effects.Appear: true
chat.effects.Leave: true
chat.effects.Rotate: true
chat.effects.Rainbow: true
chat.effects.HyperRed: true
chat.effects.Shake: true
chat.effects.Photocopy: true
chat.effects.Jam: true
chat.effects.Bounce: true
chat.badges.fix-colors: true
theme.can-dark: true
theme.is-dark: true
chat.badges.style: 1
chat.badges.clickable: 2
chat.badges.version: 2
chat.filtering.all-mentions: false
chat.filtering.color-mentions: true
chat.filtering.need-colors: true
chat.actions.inline: [{"action":"ban","appearance":{"type":"icon","icon":"ffz-i-block"},"options":{},"display":{"mod":true,"mod_icons":true,"deleted":false},"ctx":"inline"},{"action":"unban","appearance":{"type":"icon","icon":"ffz-i-ok"},"options":{},"display":{"mod":true,"mod_icons":true,"deleted":true},"ctx":"inline"},{"action":"timeout","appearance":{"type":"icon","icon":"ffz-i-clock"},"display":{"mod":true,"mod_icons":true},"ctx":"inline"},{"action":"msg_delete","appearance":{"type":"icon","icon":"ffz-i-trash"},"options":{},"display":{"mod":true,"mod_icons":true},"ctx":"inline"}]
chat.actions.hover: [{"action":"pin","appearance":{"type":"icon","icon":"ffz-i-pin"},"options":{},"display":{"mod_icons":true},"ctx":"hover"},{"action":"reply","appearance":{"type":"dynamic"},"options":{},"display":{},"ctx":"hover"}]
chat.scroller.freeze-requires-hover: true
chat.scroller.hover-delay: 750
chat.scroller.freeze: 0
chat.scroller.smooth-scroll: 0
chat.input.hide-identity: false
chat.emote-menu.enabled: true
chat.emote-menu.icon: true
chat.emoji.style: "twitter"
chat.inline-preview.enabled: true
chat.hype.display-input: true
chat.actions.room-above: false
chat.actions.room: []
chat.tab-complete.emotes-without-colon: true
chat.emotes.2x: 0
chat.emotes.limit-size: false
chat.banners.last-events: true
chat.input.show-mod-view: true
chat.input.show-highlight: true
chat.input.show-shield: true
chat.lines.padding: true
chat.bits.show: true
chat.filtering.deleted-style: 1
chat.filtering.clickable-mentions: false
chat.filtering.bold-mentions: true
chat.hide-community-highlights: false
chat.lines.alternate: true
chat.filtering.highlight-mentions: true
chat.filtering.highlight-tokens: false
chat.filtering.mention-color: ""
chat.input.show-elevate-your-message: true
chat.disable-handling: false
chat.adjustment-mode: 0
chat.adjustment-contrast: 4.5
theme.color.chat-background: ""
theme.color.background: ""
theme.color.chat-text: ""
theme.color.text: ""
chat.lines.borders: 1
chat.bits.animated: true
theme.tooltips-dark: false
chat.width: null
chat.effective-width: 340
chat.actions.size: 16
chat.actions.hover-size: 30
chat.timestamp-size: null
chat.font-size: 13
chat.lines.emote-alignment: 1
chat.font-family: ""
chat.banners.charity: true
chat.subs.gift-banner: true
chat.banners.hype-train: true
chat.banners.prediction: true
chat.banners.polls: true
chat.banners.drops: true
chat.scrollback-length: 150
chat.delay: -1
chat.filtering.remove-deleted: 0
chat.filtering.blocked-types: {}
chat.filtering.debug: false
chat.filtering.highlight-basic-users-blocked: []
__filter:block-users: null
chat.filtering.highlight-basic-blocked: []
__filter:block-terms: null
chat.filtering.highlight-basic-badges: []
__filter:highlight-badges: null
chat.filtering.highlight-basic-badges-blocked: []
__filter:block-badges: null
chat.filtering.highlight-basic-users: []
__filter:highlight-users: null
chat.filtering.highlight-basic-terms: [{"v":"hobo","t":"text","c":"","s":false,"h":false,"w":true,"p":0,"remove":false}]
__filter:highlight-terms: {"hl":null,"non":[[0,null,[null,{}]]]}
chat.emotes.enabled: 2
chat.fix-bad-emotes: true
chat.emoji.replace-joiner: 1
chat.filtering.mention-priority: 0
chat.filtering.display-deleted: "DETAILED"
chat.replies.style: 1
chat.rich.enabled: true
chat.rich.minimum-level: 0
chat.rich.want-mid: false
chat.name-format: 0
chat.timestamp-format: "h:mm:ss"
chat.badges.hidden: {}
chat.badges.custom-mod: true
chat.badges.custom-vip: true
chat.filtering.hidden-tokens: {}
ffzap.core.highlight_sound: "https://cdn.ffzap.com/sounds/default_wet.mp3"
ffzap.core.highlight_sound_types: ["badge","mention","term","user"]
ffzap.core.enable_highlight_sound: false
ffzap.core.message_deletion: 0
ffzap.core.highlight_sound_volume: 50
ffzap.betterttv.global_emoticons: true
ffzap.betterttv.pro_badges: true
ffzap.betterttv.channel_emoticons: true
ffzap.core.remove_spaces: false
ffzap.betterttv.arbitrary_emoticons: true
chat.update-when-loaded: true
layout.portrait: true
layout.portrait-threshold: 1.25
layout.use-portrait: false
layout.portrait-min-chat: false
chat.points.show-rewards: true
chat.points.show-button: true
chat.bits.show-pinned: true
chat.emote-menu.combine-tabs: true
chat.emote-menu.stay-loaded: true
chat.emote-menu.show-quick-nav: true
chat.emote-menu.show-heading: 1
chat.emote-menu.tall: false
chat.emote-menu.reduced-padding: false
chat.emote-menu.show-search: true
chat.emote-menu.clear-search: true
chat.emote-menu.sort-emotes: 4
chat.emote-menu.sort-tiers-last: true
chat.emote-menu.effect-tab: true
chat.emote-menu.show-emoji: true
chat.rich.all-links: false
</details>

**Comment by SirStendec** [comment]
This is not a FFZ bug. This is a limitation of the browser security model.

The channel you're viewing has a player overlay extension. Because there is an overlay extension, mouse events are unavailable.

The only way to allow mouse events to fire is to disable "Allow mouse interaction with overlay extensions." in player settings, or just outright hide overlay extensions.

**Comment by robmonte** [comment]
Oh thank you, I had never noticed that setting before but also wasn't sure if the extensions were the actual cause because that was just an initial theory. It works now! 👍
