### ISSUE TITLE
Option to show modified settings

### ISSUE THREAD

**Issue by BoringBoredom** [FrankerFaceZ/FrankerFaceZ#1426]
I'd like to have a toggle that shows which settings have been modified by the user, similar to VSCode's `@modified` filter.

![image](https://github.com/FrankerFaceZ/FrankerFaceZ/assets/16615327/71bc0958-85e5-4ff8-a3ff-83d846450599)

**Comment by SirStendec** [comment]
Implemented in ba72969c51d42e651befdf04b9acf64c1cbd1a4e
