### ISSUE TITLE
Chat width setting causing channel issues when a Watch Party is active

### ISSUE THREAD

**Issue by Taizunz** [FrankerFaceZ/FrankerFaceZ#1427]
**Describe the bug**
FFZ's chat width setting (Chat > Appearance) completely messes up the page layout and functionality on channels that are hosting a Watch Party using the native Amazon Prime/Prime Video feature.

**To Reproduce**
1. Go to a channel that has an active Watch Party
2. Go to FFZ Control Center > Chat > Appearance
3. Adjust the "Width" setting to any value
4. Reload the page

**Screenshots**
This is how a Watch Party channel looks with my FFZ profile (my width is at 482, but the value doesn't appear to have an influence - just the mere fact that it's altered is enough):
![image](https://github.com/FrankerFaceZ/FrankerFaceZ/assets/15648000/748bc387-b212-4eb4-b7e1-6128789d5e32)

This is how it looks if I reset the chat width setting to default.
![image](https://github.com/FrankerFaceZ/FrankerFaceZ/assets/15648000/dcb50b9f-d865-4a92-8b31-074a80a3ce27)

**Environment (please complete the following information):**
 - OS: Windows 10 19045.3636
 - Browser: Tested on Chrome 118.0.5993.118 and Firefox 119
 - Other Extensions: Tested with just FFZ and not additional FFZ addons enabled.

**Comment by SirStendec** [comment]
This should be fixed I think, as of the latest update, but let me know. The CSS is messy.

**Comment by Taizunz** [comment]
I never got around to actually testing if the changes you made last year fixed it (I assume it did).
Now that Watch Party has been shut down by Twitch I'm closing this.
