### ISSUE TITLE
Missing feature from vanilla twitch

### ISSUE THREAD

**Issue by undriann** [FrankerFaceZ/FrankerFaceZ#1428]
**Is your feature request related to a problem? Please describe.**
The feature of `alt enter` to reply is missing when i use the ffz extension
![image](https://github.com/FrankerFaceZ/FrankerFaceZ/assets/96785681/add9f88c-5a0a-43b9-913c-d6fa17c7ddaa)
![image](https://github.com/FrankerFaceZ/FrankerFaceZ/assets/96785681/02768ff1-bdaa-42fc-b4f7-c1a4382d425a)

**Describe the solution you'd like**
I want this feature because i can't seem to find any setting that gets it back to normal, and if there already is not having it turn off by default is not smart in my opinion.

**Describe alternatives you've considered**
Only alternative is just not use the extension at all.

**Additional context**

**Comment by SirStendec** [comment]
Unable to reproduce this issue. As long as you aren't using the In-Line Tab Completion add-on, this works fine with FFZ.
