### ISSUE TITLE
Game directory pages don't always load

### ISSUE THREAD

**Issue by AngelTiger** [FrankerFaceZ/FrankerFaceZ#143]
**Web Browser**: 
Google Chrome

**Do you use BetterTTV or other Twitch extensions**:
I use FFZ and [this](https://chrome.google.com/webstore/detail/the-ffz-add-on-pack/aiimboljphncldaakcnapfolgnjonlea) add-on pack.

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: 
http://putco.de/NTg1Mg.log

**Bug / Idea**:
Sometimes, pages don't load like that 
![1](https://cloud.githubusercontent.com/assets/20018960/25306456/b7ae2a86-278d-11e7-986e-615137538eef.png)
That's mostly in the game directory pages.
I would like to know if the add-on pack causes this bug and if it's fixable.

Thanks for helping

**Comment by SirStendec** [comment]
Hmm. I'm not able to produce any issues like this myself and I don't see anything in the log you've provided. I also haven't heard of any other users having similar issues.

If and when this happens again, can you please open your browser's developer tools (Ctrl-Shift-I), go to the Console tab, and check for any errors? There might be something there that can help me figure it out.

**Comment by AngelTiger** [comment]
![1](https://cloud.githubusercontent.com/assets/20018960/25313340/ccb282de-282c-11e7-9ca2-2027fcd21f25.PNG)
![4](https://cloud.githubusercontent.com/assets/20018960/25313391/c3921d80-282d-11e7-9dee-c23b0b92050e.PNG)
![2](https://cloud.githubusercontent.com/assets/20018960/25313341/ccd2d584-282c-11e7-9608-f0c1a8548edc.PNG)



Also, when I'm here, if I click on a game, nothing happens, I have to enter the url to have the enless loading screen.
![3](https://cloud.githubusercontent.com/assets/20018960/25313349/eaacf4fe-282c-11e7-8c93-7736d85273f5.PNG)
