### ISSUE TITLE
Settings dont save

### ISSUE THREAD

**Issue by megadude9704** [FrankerFaceZ/FrankerFaceZ#144]
**Web Browser**:

**Do you use BetterTTV or other Twitch extensions**:

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:
http://putco.de/NTg1Ng.log

**Bug / Idea**:
settings reset on every refresh and dont import via file

**Steps to Reproduce (if Applicable)**:

**Comment by jartin** [comment]
I'm having the same issue

http://putco.de/NTg1Nw.log

**Comment by SirStendec** [comment]
First, please confirm that you don't have anything that would be clearing your browser's local storage.

Now, could you both please list every single extension you have installed? This is likely the result of a misbehaving extension.

**Comment by riking** [comment]
Are you using Chrome Canary? v60.0.3078.0

**Comment by megadude9704** [comment]
lock plus                           
1.13.2          not affected
Chrunchyroll widescreen      
0.3.2            disabling fixed
easy Autorefresh                 
4.5              not effected
frankerfaceZ                            
1.5.7           N/A
Go back with backspace          
2.0             not effected
Halo waypoint tools                
 0 .2.2         not effected
magic actions for youtube       
6.9.4.3       not effected
Twitch Now                              
1.1.189       disabling fixed
Ultrawide video                       
1.7              not affected
Window resizer beta                
2.1.0 beta   disabling fixed
windscribe VPN                        
1.1.31         disabling fixed

the only ones i run with twitch is window resizer to change window size to not waste screen spac
and twitch Now +adblock of course(set to off for this site)
tried removal of plugin as well..to no avail 
disabling select few can fix and yes im using google canary Version 60.0.3078.0 (Official Build) canary

**Comment by jartin** [comment]
Adobe Acrobat 15.1.0.6
Application Launcher for Drive (by Google) 3.2
Chrome Remote Desktop 57.0.2987.84
Flix Plus Lifehacker 3.18
Forecastfox 2.0.10
FFZ 1.57
Gif Delayer 0.1.1
Google Dictionary 4.0.5
Google Docs 0.9
Google Sheets 1.1
Google Slides 0.9
Google Voice 2.4.4
Honey 9.8.2
Reddit Enhancement Suite 5.4.3
Search by Image (by Google) 1.5.2
Super Browse for Netflix 1.5
Super Netflix 2.1.0.1028
Tampermonkey 4.2.7
FFZ Addon Pack 2.0.11
uBlock Origin 1.12.1
Video Downloader 1.97.54

Chrome Canary 64bit 60.0.3078.0

**Comment by riking** [comment]
Please test the new FFZ version v3.5.473

**Comment by riking** [comment]
This seems to be a chrome bug, actually.

**Comment by SirStendec** [comment]
I've just pushed v3.5.474 of FrankerFaceZ. I don't use localStorage.hasOwnProperty anymore, which seems to have been the issue.

Let me know if everything is working now, thanks!

**Comment by jartin** [comment]
How do I use Nodejs to upgrade to 3.5.474?

**Comment by megadude9704** [comment]
when you say update...where can we update..
chrome webstore?

**Comment by SirStendec** [comment]
You just have to refresh the page. You might have to do a hard refresh if your browser has the old version cached.

FFZ's script is always pulled from FFZ's servers to make sure clients have the latest version and to avoid having to wait for potentially lengthy approval delays from the various browser teams.

**Comment by megadude9704** [comment]
oh neat its automatic

**Comment by jartin** [comment]
Seems to be working now. Than you Riking and Sir Stendec!
