### ISSUE TITLE
7TV-like first time chatter highlight

### ISSUE THREAD

**Issue by popopoplus** [FrankerFaceZ/FrankerFaceZ#1441]
**Is your feature request related to a problem? Please describe.**
I noticed that 7tv has an option that FFZ doesn't have to highlight a user's first message in a chat. As far as I know, it's not really possible to retrieve this kind of information from twitch. So my question is, how does 7tv go about it? Is the "first time chatter" mention reliable and if so, won't FFZ be able to implement this option in the future?

**Comment by Lordmau5** [comment]
Twitch has a native feature to highlight first time chatters, but you have to be a moderator or broadcaster to see those.
The information is being sent to the client but isn't processed if you aren't a mod or higher.

From a quick talk about it in Discord Stendec said it doesn't matter at all if you are a normal viewer (and I fully agree with him there).
It's similar to the account creation date in the user card if you click on someone's name in chat - that one also shows in a channel you're a moderator or broadcaster in natively, but not as a normal viewer.

**Comment by popopoplus** [comment]
Thanks for your reply.

So if I understand correctly, the information is available but FFZ has chosen not to display it. I understand your point of view but I still think it would be a good idea to give users the choice. Regarding the example of the account creation date, it seems to me that FFZ is the only extension that dit not display this kind of information. It's a shame to be forced to install a second extension that will conflict with FFZ just for such a small feature in my opinion.

**Comment by Lordmau5** [comment]
FFZ has quite the extensible add-on system, so if you or someone else would like to see this as a feature they're free to make an add-on that would add these features

**Comment by popopoplus** [comment]
Yes, unfortunately I don't have the skills to do something like that, but if anyone does I'll be very grateful.
