### ISSUE TITLE
Do not join raid FROM specific channels

### ISSUE THREAD

**Issue by Xaralabos23** [FrankerFaceZ/FrankerFaceZ#1442]
Thats a me problem, related to the yearly twitch recap
i am using 'alternate player for twitch', because watching from the site lags my pc (i am on a toaster)
-this extension doesnt count hours watched, so i could watch some1 for 800 hours through the extension and the recap would say 0
-also the extension doesnt claim channel points

so for both those reasons i would have to open channels in the background from the twitch site, in a 100x100 window and muted so i wont lag while i am watching whatever i am watching through the extension
so while i am watching, the channels in the background will raid some1, i wont notice and i dont want that some1 on my recap (or even their game category like asmr or forknife)

**Describe the solution you'd like**
just a setting like "You will not automatically join raids to channels listed here." which already exists but instead of 'to' it would be 'from'

**Additional context**
i know i can check the 'Do not automatically join raids.' but i keep forgeting to join while watching from the extension, so -400 channel points every time sadge.

and even though its just me, i think it would be a good addition anyway.

**Comment by SirStendec** [comment]
You can already accomplish this by creating a profile that uses rules so it's only active on certain channels, and just enabling the "Do not automatically join raids." option within that profile.
