### ISSUE TITLE
Delete, edit emoticons

### ISSUE THREAD

**Issue by jezokshe** [FrankerFaceZ/FrankerFaceZ#1445]
Why can’t I hide channel emoticons (which are not available) and ugly Twitch emoticons? Please let us disable smileys in entire categories, and generally show the rest of the smileys in one tab! These are damn emoticons, and now they are a mess, as if it were a separate program.

**Comment by SirStendec** [comment]
The FFZ emote menu *does* let you hide emotes, should only display emotes that are available in the current context, and hasn't changed significantly in quite a while.

Are you using the 7tv browser extension, by chance? It completely replaces chat and has its own emote menu, which makes FFZ's own chat related features nonfunctional.

**Comment by jezokshe** [comment]
@SirStendec 
No, for Twitch only FFZ. I mean it
![image](https://github.com/FrankerFaceZ/FrankerFaceZ/assets/77186394/850488d0-7c1f-434b-864e-478a7172411f) 
![image](https://github.com/FrankerFaceZ/FrankerFaceZ/assets/77186394/95c72856-bce7-44b1-aa62-2a93f058d6ca)
Why not turn these off? They take up space and you have to scroll. Just “disable unavailable emoticons” (categories)

**Comment by SirStendec** [comment]
You can hide all that stuff. The eye icon, next to the search field, toggles a visibility mode where you can show or hide emote sets or individual emotes. Click once to enter visibility mode, click stuff to toggle it, then click the eye again to go back to normal mode.

You can also use settings to put all the emotes on a single tab if you'd like. You can use a setting to hide the headers at the top of sections if you want.

**Comment by jezokshe** [comment]
@SirStendec  Damn, I didn't notice there was an eye icon there. Can you tell me how to put it on one tab? There are just a lot of settings, it’s hard to figure it out. Thank you

**Comment by SirStendec** [comment]
All the relevant settings are in the Chat > Emote Menu section of the FFZ Control Center. The one you're asking about is specifically:

* General >> Display all emotes on one tab.

**Comment by jezokshe** [comment]
@SirStendec  Thanks bro, sorry for the harshness
