### ISSUE TITLE
Add 7TV preview when adding a new emote

### ISSUE THREAD

**Issue by rukk1** [FrankerFaceZ/FrankerFaceZ#1451]
**Is your feature request related to a problem? Please describe.**
Adding a new 7TV emote doesn't display what the emote actually is.  

**Describe the solution you'd like**
With 'Show update messages' ticked within the 7TV plugin it displays an example of the emote.

**Describe alternatives you've considered**
Currently in my OBS I need to use BTTV solely for the ability to see what emotes my chatters are adding (via channel points), which leaves to issues with BTTV and FFZ doubling up.

**Additional context**
Makes it easier to moderate, some of the emotes are wild.

**Comment by Lordmau5** [comment]
Was added in 1.4.19 (and fixed in 1.4.20) of the 7TV Emotes add-on :)

Didn't even know the 7TV extension did this - gonna adapt that feature into the BetterTTV Emotes add-on as well ;)
