### ISSUE TITLE
sidebar grouping favorite channels

### ISSUE THREAD

**Issue by CopperFig** [FrankerFaceZ/FrankerFaceZ#1460]
**Is your feature request related to a problem? Please describe.**
i like to have all my favorite channels at the top of the sidebar

I used a different extension for this feature, but they decided to not longer be open-source and started locking features behind a paywall. This extension requests more website permissions and no way to manually disabled them.

**Describe the solution you'd like**
add a setting to define favorite channels.
this favorite channels should than be grouped if live and shown on the very top of the sidebar in its own section, all other channels below that section.

it requires to have the full list of online channels, the previews extension do this by automatically pressing the show more button in the sidebar. 
if the sidebar is collapsed the extension expand the list, click the show more button and collapse the list.

**Describe alternatives you've considered**
i know Twitch offers a similar function with the "For you" option, but some small streamers that do not stream constantly/long are missing on top, and the sidebar is no longer sorted by the viewer count than.

**Additional context**
previews extension https://previews-app.com/ (not longer open-source)

**Comment by SirStendec** [comment]
So, there's an add-on for FrankerFaceZ called Deck. This add-on creates an alternative system to the existing Twitch Directory, with customizable columns to find content.

Deck also allows you to customize the sidebar by creating a tab and then setting it to be used as your sidebar. You could set up a custom sidebar section that only shows a specific collection of channels pretty easily.

I don't plan on implementing any major sidebar / directory customization features outside of Deck.

**Comment by CopperFig** [comment]
Sorry @SirStendec for my late response, I have a couple of issues with this approach 

- there is no option to customize the preview thumbnail size. I like to adjust the size, so I can read text on the preview thumbnail

- if a channel goes offline or the sidebar gets refreshed, the sidebar is flickering. It would be great if there is a little animation like on the normal twitch sidebar 

- a setting to exclude a list from another list 
like all channel from my favorite list should be removed from the followed live list, so there is no duplicated channel in the sidebar

- an option for a separated column with all other offline channels

- option to toggle stream together integration / newer twitch sidebar updates / ...
