### ISSUE TITLE
Quick swap the side chat is on

### ISSUE THREAD

**Issue by Alfie94** [FrankerFaceZ/FrankerFaceZ#1467]
**Is your feature request related to a problem? Please describe.**
I like to swap the side my chat is on depending on what monitor I watch twitch on. Going into "settings -> chat -> layout -> Swap sidebars" is a bit of an inconvenience.

**Describe the solution you'd like**
Add a toggle to add a button to the settings in the chat window that allows to quickly change which side the chat is on

**Comment by SirStendec** [comment]
You can do this using settings profiles.

1. Create a new settings profile for swapping the layout around.
2. Within that profile, enable the Swap Sidebars option.
3. Toggle that profile on/off as desired.

To toggle a profile on/off, there are two quick ways to do it. First, if you right-click on the FFZ menu button at the top of Twitch, it'll open a profile selector and you can toggle it with a click there. Second, you can assign a keyboard shortcut to toggle a profile. You need to go to Profiles and edit the profile to add a hotkey.
