### ISSUE TITLE
Forward raids to live channel

### ISSUE THREAD

**Issue by fdge** [FrankerFaceZ/FrankerFaceZ#1468]
When a Streamer is raiding over to another streamer, forward the page to the actual channel to remove the `?referrer=raid` tag.

i.e. StreamerA raids StreamerB
The url becomes "twitch.tv/StreamerB?referrer=raid"
Have FrankerFaceZ forward to "twitch.tv/StreamerB" to remove the `?referrer=raid` tag and to count as an actual viewer.

**Comment by SirStendec** [comment]
Not counting as a viewer when you have `?referrer=raid` is misinformation. This would be pointless.

**Comment by argowizbang** [comment]
And for clarification on what Stendec said, in case it's needed:

["While it is true that raid viewers "don't count" towards getting partnership, removing referrer=raid won't help. We know who is watching a stream and who that stream raids regardless. All you're doing by asking people to refresh is giving a viewer an opportunity to stop watching."](https://twitter.com/Fugiman/status/1401052105989771267)
