### ISSUE TITLE
Add option to hide Charity/Fundraiser bar above chat

### ISSUE THREAD

**Issue by Taizunz** [FrankerFaceZ/FrankerFaceZ#1469]
**Is your feature request related to a problem? Please describe.**
When I'm using Twitch on a monitor in portrait mode I don't have a lot of chat visible, so I'd like to get rid of as many elements as possible that aren't important to me in that particular setup so that I can at least have a few more lines of chat visible.

**Describe the solution you'd like**
An option to hide the charity/fundraiser bar that appears above chat when a channel has an active charity/fundraiser going.
This option would allow me to set up a conditional rule that makes sure that the bar only hides for me when I'm using Twitch on my portrait monitor.
![image](https://github.com/FrankerFaceZ/FrankerFaceZ/assets/15648000/dbdc0981-6462-4bc3-b83e-e88718a72e3c)

**Describe alternatives you've considered**
Hiding it using something like uBlock Origin filters, but that would be too permanent for my liking as that would affect Twitch no matter what monitor I'm using it on.

**Comment by SirStendec** [comment]
This has been a feature since version 4.44.0 released on March 27th, 2023.

Chat > Appearance >> Community.
Allow the charity fundraiser progress to be displayed in chat.
