### ISSUE TITLE
Keyboard shortcut for "Swap Sidebars" function

### ISSUE THREAD

**Issue by marcusziade** [FrankerFaceZ/FrankerFaceZ#1478]
**Is your feature request related to a problem? Please describe.**
Clicking through the FFZ UX is annoying

**Describe the solution you'd like**
I want to swap the sidebar with a keyboard shortcut

**Describe alternatives you've considered**
Built my own extension but didn't work. Chat sidebar was blank when on the left.

**Comment by SirStendec** [comment]
Already possible.

1. Make a new settings profile.
2. Assign a hotkey to that profile.
3. Toggle the Swap Sidebars setting within that profile.

**Comment by marcusziade** [comment]
Hell yeah, thanks
