### ISSUE TITLE
Not seeing all my streamers and missing emotes

### ISSUE THREAD

**Issue by zigazi** [FrankerFaceZ/FrankerFaceZ#148]
**Web Browser**: chrome

**Do you use BetterTTV or other Twitch extensions**: yes bttv, frankerz, ffz add on pack

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: http://putco.de/NTg5Mw.log

**Bug / Idea**: I am subscribed to 2 streamers via gamewisp, only seeing 1 streamer in the "my emoticons -> all emoticons" and that 1 streamer only has 1 emote available to click even though she actually has like 8 emotes
![aaaa](https://cloud.githubusercontent.com/assets/28076665/25464344/d578b4de-2ac9-11e7-8f7b-d868b0af6e69.png)

**Steps to Reproduce (if Applicable)**: everytime i open twitch, tried uninstalling the extensions and reinstalling but no success

**Comment by SirStendec** [comment]
FrankerFaceZ does not directly support GameWisp. That is added by FFZ: Add-on Pack through our client-side API. Please open an issue with FFZ:AP for support with that extension and the features it adds. They have a repo at https://github.com/Lordmau5/The-FFZ-Addon-Pack
