### ISSUE TITLE
Option to Disable Mini-Player When Clicking off a Live Stream

### ISSUE THREAD

**Issue by okicks** [FrankerFaceZ/FrankerFaceZ#1481]
**Is your feature request related to a problem? Please describe.**
When I click off a live stream (go back to the categories page for example) on Twitch there's a mini-player that plays in the bottom corner of the page continuing the live stream that I just tried to leave.

**Describe the solution you'd like**
I would like this mini-player to not exist (auto-close) or at a very minimum be paused or muted

**Describe alternatives you've considered**
I could block it with my ad blocker (may do this as a temporary fix), but, as with many things I block with my ad blocker, as soon as something changes about the element, it'll come right back

Edit:
Just tested this. It blocks the player but not the audio, which is even more cursed

**Additional context**
![image](https://github.com/FrankerFaceZ/FrankerFaceZ/assets/52147487/7197028e-fb4a-432d-8062-10c825899c7b)

Thank you in advance for this feature consideration!

**Comment by SirStendec** [comment]
This is a native Twitch feature. Open the player settings menu, go to Advanced, and disable Mini Player.
