### ISSUE TITLE
Microsoft Edge recognized the extension as Malware

### ISSUE THREAD

**Issue by shinigami92h** [FrankerFaceZ/FrankerFaceZ#1499]
![Screenshot 2024-05-31 161143](https://github.com/FrankerFaceZ/FrankerFaceZ/assets/120877050/0c4d25bd-15c1-4285-8b9c-5e8a990d8d31)

**Comment by T3h-vICE** [comment]
Get the one from Chrome store, or choose it from the offcial FrankerFaceZ homepage, which redirect you there. Edge lets you install Chrome extensions, since both browers are based on Chromium. I can see that yours is from the Edge store.

**Comment by Lordmau5** [comment]
The one from the Microsoft store is not official.

Please follow the steps outline by @T3h-vICE (or the steps on the FFZ homepage - https://frankerfacez.com)
