### ISSUE TITLE
Highlight your own messages in chat

### ISSUE THREAD

**Issue by Twichigo** [FrankerFaceZ/FrankerFaceZ#1503]
**Is your feature request related to a problem? Please describe.**
Currently, using your own name as a term for Chat->Filtering->Highlight->Users does nothing, on any channel.
![2024 c3be6f3f860b](https://github.com/FrankerFaceZ/FrankerFaceZ/assets/123217314/9e71407b-7908-4c17-b67f-80d23ed9da8d)

**Describe the solution you'd like**
It should also be able to highlight messages for your own name. Alternatively, it could be a feature separate from Highlight->Users, which will help avoid making a highlight sound after sending a message if you have Highlight User enabled as a trigger in FFZ:AP Core add-on.

**Describe alternatives you've considered**
BTTV extension has such feature, but it's also highlighting replies to your messages as if they were your own (which also overwrites  highlights from FFZ when you are mentioned) and one of the latest updates made it non-functional.

**Additional context**
Having your messages highlighted helps find them easily in fast moving chats or when you need to trace down a conversation from a while ago in slow chats.

**Comment by SirStendec** [comment]
You need to enable "Filter your own messages." in Chat > Filtering > General under Behavior. Otherwise, no filtering will be run on your own messages, which includes checking for highlight rules.

**Comment by Twichigo** [comment]
> You need to enable "Filter your own messages." in Chat > Filtering > General under Behavior. Otherwise, no filtering will be run on your own messages, which includes checking for highlight rules.

Ah shoot, all this time it was right under my nose. Thanks!
