### ISSUE TITLE
Chat disappearing every message or two in twitch chat

### ISSUE THREAD

**Issue by heyyitsshay** [FrankerFaceZ/FrankerFaceZ#1504]
In twitch chat - you can only see one or two messages and as new ones come in the rest disappear. You also cannot access settings to adjust or see if anything helps. 

Screenshot:
<img width="374" alt="Screen Shot 2024-06-07 at 3 40 59 PM" src="https://github.com/FrankerFaceZ/FrankerFaceZ/assets/172076846/81f0f7b4-4f76-49e4-9ab1-7e47c577bf7c">

two messages later: 
<img width="338" alt="Screen Shot 2024-06-07 at 3 41 40 PM" src="https://github.com/FrankerFaceZ/FrankerFaceZ/assets/172076846/fc6715c6-d46a-4aee-a335-66dc1e7199f6">

Environment:
 - OS: Apple Macbook
 - Browser Firefox
 - Version 126.0.1
 - Other Extensions: BetterTV, 7TV 

In order for the issue to fix - I need to remove the extension which I do not want to do of course but will have to so I can mod properly.

**Comment by Lordmau5** [comment]
This very much sounds like the issue with the old 7TV extension that overwrites some FFZ related setting.

Please check in the FFZ settings if "Scrollback Length" is set to 1 or 2 (you can use the search bar at the top)
![image](https://github.com/FrankerFaceZ/FrankerFaceZ/assets/1345036/50653116-8b75-462d-aa75-aa7716598fa6)

Additionally it's recommended to uninstall the 7TV extension - as I said, the old extension (v2) is messing with FFZ settings, while the new extension (v3) is completely replacing the Twitch chat causing FFZ functionality to not be present in chat.
