### ISSUE TITLE
Error message when trying to take a timestamp

### ISSUE THREAD

**Issue by clark788** [FrankerFaceZ/FrankerFaceZ#1505]
Getting two different error messages when clicking on the stream uptime clock to create a timestamp. This only happens on some streams.

Screenshots:

<img width="318" alt="firefox_4w9sBOCkva" src="https://github.com/FrankerFaceZ/FrankerFaceZ/assets/172225583/5a13daa4-97c9-4087-af9d-32cb490d3490">

<img width="324" alt="firefox_UCEWaDyZSZ" src="https://github.com/FrankerFaceZ/FrankerFaceZ/assets/172225583/355faddd-1cf0-4878-aee5-7e8099f6a882">

**Environment (please complete the following information):**
 - OS: Windows
 - Browser firefox, chrome
 - Version 126.0.1.0, 125.0.6422.142
 - Other Extensions: BetterTTV, 7TV

**Additional context**
randomly started a couple days ago. have removed FFZ extension and re-downloaded.

**Comment by Taizunz** [comment]
I noticed that it started happening for me just now as well.
![image](https://github.com/FrankerFaceZ/FrankerFaceZ/assets/15648000/40c4e009-4b90-4555-b1af-b1fe00f74ea4)
