### ISSUE TITLE
FFZ Emote Menu breaks new "Power-ups" feature

### ISSUE THREAD

**Issue by dude22072** [FrankerFaceZ/FrankerFaceZ#1507]
**Describe the bug**
Two of the new power ups, "Gigantify an emote" and "On-Screen Celebration" will bring up the emote menu when clicked. With FFZ's emote menu enabled, this causes an empty box.

**To Reproduce**
1. Bring up the "Power-ups and Rewards" menu (previously just the channel points redeems menu)
2. Click on either  "Gigantify an emote" or"On-Screen Celebration"
3. See error

**Expected behavior**
Ability to select an emote.

**Screenshots**
FFZ emote menu on: 
<img width="249" alt="FFZ Emote Menu Issue" src="https://github.com/FrankerFaceZ/FrankerFaceZ/assets/4349800/f795e1c1-f196-4e25-8328-86d451a89136">
FFZ emote menu off: 
<img width="252" alt="FFZ Emote Menu Issue-disabled" src="https://github.com/FrankerFaceZ/FrankerFaceZ/assets/4349800/551035a3-b364-452f-b5c1-101b87b23346">

**Environment (please complete the following information):**
 - OS: Windows 10 22H2
 - Browser Firefox
 - Version 127
 - Other Extensions: BetterTTV

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:
(Firefox can’t establish a connection to the server at wss://ayaya.frankerfacez.com:8084/mqtt.)

**Additional context**
N/a

**Comment by ToxxicRewind** [comment]
I have a similar issue. Emotes appear in the selection window, however the effects do not appear in the chat window unless I use an incognito tab to view chat. 

Even with both FFZ and BTTV turned off, I cannot see the effects. Other chatters have mentioned being able to see the effects while only using BTTV

**Comment by SirStendec** [comment]
All issues should be fixed as of e2e315d7028b7822ac7bd27c480bacc5bb4f37d6
