### ISSUE TITLE
Blue buttons since BTTV removed them now

### ISSUE THREAD

**Issue by thinkpad4** [FrankerFaceZ/FrankerFaceZ#151]
Can you add blue buttons since BTTV removed them?

**Web Browser**:

**Do you use BetterTTV or other Twitch extensions**:

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**:

**Steps to Reproduce (if Applicable)**:

**Comment by SirStendec** [comment]
Custom themes are planned for the FFZ v4 rewrite. Once that comes, you'd be able to make your buttons blue by setting the branding color to blue.

I'm not going to implement a feature specifically for the buttons at this point. It would be a complete mess on v3.
