### ISSUE TITLE
Gigantic emotes mouse over not accounted for.

### ISSUE THREAD

**Issue by NeoGanon** [FrankerFaceZ/FrankerFaceZ#1510]
**Describe the bug**
Gigantified emotes remain static and doesn't parse the animated emote when you mouse over it if you have animate on mouse over selected as an option.

**How to reproduce**
Appearance > Emotes > Animated Emotes > Enable on Hover.

**Expected behavior**
it only uses https://static-cdn.jtvnw.net/emoticons/v2/emotesv2_933fe660f8bb4af18f218fa969049a36/static/dark/3.0
and doesn't use https://static-cdn.jtvnw.net/emoticons/v2/emotesv2_933fe660f8bb4af18f218fa969049a36/default/dark/3.0

I would like to see it have its own drop down option for how it behaves it doesn't get spammed as much and doesn't make the chat look terribly busy when a gigantic emote is used.

**Environment (please complete the following information):**
 Windows 10
 Chrome
Version 126.0.6478.62

[15:31:49] info | core: FrankerFaceZ v4.72.2 (s:twitch f:main b:null c:f79f1ba21d20e47dbb438e2742d9eb6984e89f8e)
[15:31:49] info | core: Initial URL: 
[15:31:49] info | site: Using: Twilight
[15:31:49] info | site.web_munch: Found and wrapped webpack's loader after 0ms.
[15:31:49] info | settings: Using Provider: LocalStorageProvider
[15:31:49] info | site.web_munch: require() grabbed in 2.10000ms.
[15:31:49] info | core: Loaded descriptions of 0 modules.
[15:31:49] info | settings: Initialization complete after 33.60000ms -- Values: 200 -- Profiles: 2
[15:31:49] info | site.fine: Installing MutationObserver.
[15:31:49] info | site: Loaded descriptions of 17 modules.
[15:31:49] info | site.elemental: Installing MutationObserver.
[15:31:49] info | main_menu: Built Tree in 28.40000ms with 187 structure nodes and 324 settings nodes.
[15:31:49] info | experiments: Loaded information on 4 experiments.
[15:31:50] info | core: Initialization complete in 952.00000ms.

settings
-------------------------------------------------------------------------------
i18n.debug.capture: false
i18n.format.date: "default"
i18n.format.time: "short"
i18n.format.datetime: "medium"
i18n.debug.transform: null
i18n.locale: "en"
data.use-staging: true
addons.dev.server: false
pubsub.use-cluster: null
metadata.modview.hide-info: false
layout.side-nav.hide-viewers: false
metadata.uptime: 2
metadata.uptime.no-native: true
metadata.viewers: true
metadata.viewers.no-native: true
layout.swap-sidebars: false
layout.portrait: true
layout.portrait-threshold: 1.25
layout.use-portrait: false
chat.width: 460
chat.use-width: true
layout.use-chat-fix: true
layout.is-theater-mode: true
layout.theatre-navigation: true
layout.minimal-navigation: true
layout.side-nav.show-avatars: true
layout.side-nav.show: 1
layout.side-nav.hide-offline: false
layout.hide-discover-luna: true
layout.prime-offers: true
channel.hide-unfollow: true
chat.hype.show-pinned: true
channel.round-avatars: true
channel.hide-live-indicator: true
layout.side-nav.rerun-style: 2
layout.side-nav.show-rec-channels: 1
layout.side-nav.show-friends: 2
whispers.show: true
channel.show-celebrations: true
layout.subtember: false
layout.theme.global-font: "google:Roboto Slab"
layout.turbo-cta: false
layout.portrait-invert: false
layout.portrait-min-chat: false
layout.inject-portrait: false
layout.use-portrait-swapped: false
player.theatre.metadata: false
layout.use-portrait-meta: false
layout.use-portrait-meta-top: false
layout.portrait-extra-width: 0
player.theatre.no-whispers: true
layout.portrait-extra-height: 1
theme.disable-high-contrast: false
theme.high-contrast-tweaks: true
theme.disable-auto-dark: false
theme.can-dark: true
theme.is-dark: true
theme.color.background: "#000000"
theme.color.text: "#FFFFFF"
theme.legacy-dark-input: false
theme.color.accent: "#1A2E05"
theme.color.tooltip.background: ""
theme.color.tooltip.text: "#000000"
theme.color.chat-background: "#000000"
theme.color.chat-text: "#FFFFFF"
theme.color.chat-accent: "#1A2E05"
theme.font.size: 17
directory.show-channel-avatars: undefined
directory.hide-live: false
directory.hidden.reveal: false
directory.hidden.style: 2
channel.panel-tips: true
channel.auto-click-chat: true
player.gain.enable: false
player.gain.no-volume: false
player.volume-always-shown: true
player.ext-interaction: true
player.hide-mouse: true
player.fade-pause-buffer: false
player.ext-hide: 0
player.captions.font-size: "25px"
player.captions.font-family: "google:Roboto Slab"
player.compressor.enable: true
player.compressor.shortcut: null
player.no-autoplay: false
player.home.autoplay: true
player.disable-content-warnings: true
player.button.pip: true
player.button.reset: true
player.gain.min: 0
player.gain.max: 2
player.compressor.default: false
player.allow-catchup: true
player.hide-event-bar: false
ffz.show-new-settings: true
directory.block-titles: []
__filter:directory.block-titles: null
channel.extra-links: true
chat.bits.show: true
layout.display-bits-button: false
player.theatre.auto-enter: true
addon.repetition_detector.cache_ttl: 600
addon.chatterino_badges.badges: true
addon.clip-confirm.skip-hotkey: ["alt"]
addon.clip-confirm.skip-on-shortcut: true
smokemotes.pinned_mentions: true
addon.fs-chat.bg.blur: 2
addon.fs-chat.height: "720"
addon.fs-chat.width: "300"
addon.fs-chat.bg.color: "rgba(0,0,0,0.50)"
addon.fs-chat.automatic: false
addon.fs-chat.shortcut: "alt+c"
addon.seventv_emotes.animated_avatars: true
addon.seventv_emotes.badges: true
addon.seventv_emotes.global_emotes: true
addon.seventv_emotes.channel_emotes: true
addon.unread-mentions-counter.counter-location: "both"
newusers.minage: "30d"
addon.seventv_emotes.nametag_paints: true
addon.repetition_detector.enable_only_as_mod: false
addon.repetition_detector.ignore_mods: false
addon.repetition_detector.similarity_threshold: 80
addon.repetition_detector.repetitions_threshold: 2
addon.nobademotes.use-common: true
addon.nobademotes.no-filter-global: false
addon.nobademotes.ban-short: true
addon.nobademotes.use-all-lower: false
addon.nobademotes.custom-names: [{"remove":false,"v":"the","t":"glob","c":"","s":false,"h":false,"w":true,"p":0}]
__filter:addon.nobademotes.custom-names: [null,{}]
addon.screenshoter.shortcut: "ctrl+alt+shift+q"
addon.seventv_emotes.unlisted_emotes: true
sub-button.prime-notice: true
addon.pronouns.border: true
addon.pronouns.color: "#579713"
addon.pronouns.color.aeaer: "#579713"
addon.pronouns.color.any: "#579713"
addon.pronouns.color.eem: "#579713"
addon.pronouns.color.faefaer: "#579713"
addon.pronouns.color.hehim: "#579713"
addon.pronouns.color.itits: "#579713"
addon.pronouns.color.other: "#579713"
addon.pronouns.color.perper: "#579713"
addon.pronouns.color.sheher: "#FF4888"
addon.pronouns.color.theythem: "#579713"
addon.pronouns.color.vever: "#579713"
addon.pronouns.color.xexem: "#579713"
addon.pronouns.color.ziehir: "#579713"
addon.nobademotes.capitalization-mode: 0
newusers.priority: 0
newusers.highlightcolor: "#F5A623"
player.force-visible: undefined
metadata.clip-download: true
metadata.featured-follow: true
addon.pronouns.streamer: true
metadata.player-stats: true
smokemotes.pinned_reasons: ["mention","user"]
metadata.stream-delay-warning: 0
debug.link-resolver.source: {"title":"Cloudflare Test Worker","value":"https://link-service.workers.frankerfacez.com"}
addon.seventv_emotes.personal_emotes: true
addon.nobademotes.no-filter-personal: true
addon.repetition_detector.text_color: "#FF0000"
player.volume-scroll: true
player.gain.scroll: false
player.volume-scroll-steps: 0.01
player.single-click-pause: false
player.mute-click: false
addon.nobademotes.process-outgoing: false
smokemotes.pinned_font_color: "#dadada"
smokemotes.pinned_messages_max: 6
smokemotes.pinned_border: "#828282"
smokemotes.pinned_timer: 60
addon.unread-mentions-counter.ping-types: ["mention","term"]
addon.unread-mentions-counter.browser-notifications.icon-photo: "channel"
player.compressor.force-legacy: false
player.compressor.threshold: -50
player.compressor.knee: 40
player.compressor.ratio: 12
player.compressor.attack: 0
player.compressor.release: 0.25
auth.mode: "chat"
player.vod.autoplay: true
ffz.search.matches-only: false

experiments
-------------------------------------------------------------------------------
Unique ID: x8rBaIBoPc98wkooOUbGUaagA5wAeRaG

FFZ | EMQX MQTT-Based PubSub: false (r:0.75)
Twitch | ltd_experiment_v2: GroupF-180s (r:0.18, t:channel_id, c:zoreee)
Twitch | support_panel_simplification: treatment_1b (r:0.2, t:user_id)
Twitch | support_panel_simplification_v2: treatment_1 (r:0.3333333333333333, t:user_id)
Twitch | turbo_and_sub_upsell_during_ads: treatment2 (r:0.3333333333333333, t:user_id)
Twitch | Devsite_create_apps_form_recaptcha: control (r:0.5, t:user_id)
Twitch | Twilight amazon-ivs-web-broadcast enable simulcast: enabled (r:0.5, t:device_id)
Twitch | auto_pinned_cheers: control (r:0.5, t:channel_id, c:zoreee)
Twitch | bits_custom_amount: control (r:0.5, t:user_id)
Twitch | creator_follow_cue: chat (r:0.5, t:user_id)
Twitch | giftcard_redemption_in_checkout: control (r:0.5, t:device_id)
Twitch | ivs_player_web_gpu_transform: holdback (r:0.5, t:device_id)
Twitch | partial_goals_channel: control (r:0.5, t:channel_id, c:zoreee)
Twitch | partner_plus_upsell_nudge: control (r:0.5, t:user_id)
Twitch | sda_post_fill_drop: control (r:0.5, t:device_id)
Twitch | seg_mented_signup: variant_4 (r:0.5, t:device_id)
Twitch | subscriber_recap: variant 1 (r:0.5, t:channel_id, c:zoreee)
Twitch | toad_experiment: control (r:0.6, t:channel_id, c:zoreee)
Twitch | disco_bpli: control (r:0.75, t:user_id)
Twitch | gift_and_sub_button: variant_1 (r:0.95, t:user_id)
Twitch | global_commerce_upsell_holdout: treatment (r:0.95, t:user_id)
Twitch | liverecs_holdout_device: control (r:0.98, t:device_id)
Twitch | liverecs_holdout_v2: control (r:0.98, t:user_id)
Twitch | community_insights: treatment (r:0.99, t:channel_id, c:zoreee)
Twitch | disco_carousel_shelf: control (r:0.99, t:user_id)
Twitch | guest_star_left_nav_online_channel_augmentation: allowed (r:0.99, t:device_id)
Twitch | mse_in_workers: treatment (r:0.99, t:device_id)

addons
-------------------------------------------------------------------------------
Known
unread-mentions-counter | enabled | UnreadMentionsCounter v1.1.2
twir | disabled | Twir v1.1.1
smokemotes | enabled | smokeys_utils v1.2.1
smm2-links | disabled | SMM2 Links v1.2.0
screenshoter | enabled | screenshoter v1.1.1
repetition-detector | enabled | repetition_detector v1.1.0
ragnarok-database | disabled | rodb v1.0.1
pronouns | enabled | pronouns v1.2.0
prattlenot | disabled | PrattleNot v0.9.0
poll-shim | disabled | poll_shim v0.2.2
no-bad-emotes | enabled | NoBadEmotes v1.1.0
new-account-highlighter | enabled | New Account Highlighter v1.1.1
inline-tab-completion | disabled | Inline Tab v1.2.5
fs-chat | enabled | fs-chat v1.5.2
first-message-highlighter | disabled | first_msg_highlight v1.1.3
ffzap-liriklive | disabled | FFZ:AP LirikLIVE v3.2.2
ffzap-core | enabled | FFZ:AP Core v3.3.11
ffzap-bttv | enabled | FFZ:AP BTTV v3.3.21
emoteless | disabled | emote_less_chat v1.0.6
emote-side-panel | disabled | EmoteSidePanel v1.1.0
declutter | disabled | declutter v1.0.0
deck | disabled | Deck v2.7.0
clip-confirm | enabled | ClipConfirm v1.0.5
chatterino-badges | enabled | Chatterino v1.0.0
brcm | disabled | brcm v1.0.0
aplatypuss-emotes | disabled | Aplatypuss Emotes v1.0.0
ModTools | disabled | Mod Tools v1.0.1
7tv-emotes | enabled | 7TV v1.4.22

Modules
loaded   | enabled  | 
loaded   | enabled  | core
loaded   | enabled  | settings
loaded   | enabled  | experiments
loaded   | enabled  | i18n
loaded   | enabled  | staging
loaded   | enabled  | load_tracker
loaded   | enabled  | socket
loaded   | enabled  | pubsub
loaded   | enabled  | site.web_munch
loaded   | enabled  | site.fine
loaded   | enabled  | site.elemental
loaded   | enabled  | site.router
loaded   | enabled  | site.apollo
loaded   | enabled  | site.twitch_data
loaded   | enabled  | site.subpump
loaded   | enabled  | site
loaded   | enabled  | addons
loaded   | enabled  | vue
loaded   | enabled  | tooltips
loaded   | enabled  | chat.badges
loaded   | enabled  | chat.emotes
loaded   | enabled  | chat.emoji
loaded   | enabled  | chat.actions
loaded   | enabled  | chat.overrides
loaded   | enabled  | chat
loaded   | enabled  | emote_card
loaded   | enabled  | link_card
loaded   | enabled  | main_menu
loaded   | enabled  | site.bits_button
loaded   | enabled  | metadata
loaded   | enabled  | site.bttv_compat
loaded   | enabled  | site.css_tweaks
loaded   | enabled  | site.channel
unloaded | disabled | translation_ui
loaded   | enabled  | site.chat.scroller
loaded   | enabled  | site.chat.chat_line.rich_content
loaded   | enabled  | site.chat.chat_line
loaded   | enabled  | site.chat.settings_menu
loaded   | enabled  | site.chat.emote_menu
loaded   | enabled  | site.chat.input
loaded   | enabled  | site.chat.viewer_cards
loaded   | enabled  | site.chat
loaded   | enabled  | site.compat_emote_menu
loaded   | enabled  | site.dashboard
loaded   | enabled  | site.directory.game
loaded   | enabled  | site.directory
loaded   | enabled  | site.featured_follow
loaded   | enabled  | site.layout
loaded   | enabled  | site.loadable
loaded   | enabled  | site.menu_button
loaded   | enabled  | site.mod-view
loaded   | enabled  | site.player
loaded   | enabled  | site.sub_button
loaded   | enabled  | site.theme
loaded   | enabled  | site.video_chat
loaded   | enabled  | addon.new-account-highlighter
loaded   | enabled  | addon.ffzap-bttv
loaded   | enabled  | addon.ffzap-core
loaded   | enabled  | addon.repetition-detector
loaded   | enabled  | addon.chatterino-badges
loaded   | enabled  | addon.clip-confirm
loaded   | enabled  | addon.smokemotes
loaded   | enabled  | addon.fs-chat
loaded   | enabled  | addon.7tv-emotes
loaded   | enabled  | addon.7tv-emotes.api.user
loaded   | enabled  | addon.7tv-emotes.api.emotes
loaded   | enabled  | addon.7tv-emotes.api.cosmetics
loaded   | enabled  | addon.7tv-emotes.api
loaded   | enabled  | addon.7tv-emotes.avatars
loaded   | enabled  | addon.7tv-emotes.badges
loaded   | enabled  | addon.7tv-emotes.emotes
loaded   | enabled  | addon.7tv-emotes.nametag-paints
loaded   | enabled  | addon.7tv-emotes.personal-emotes
loaded   | enabled  | addon.7tv-emotes.socket
loaded   | enabled  | addon.pronouns
loaded   | enabled  | addon.unread-mentions-counter
loaded   | enabled  | addon.no-bad-emotes
loaded   | enabled  | addon.screenshoter

chat
-------------------------------------------------------------------------------
chat settings
-------------------------------------------------------------------------------
chat.effects.enable: true
chat.effects.FlipX: true
chat.effects.FlipY: true
chat.effects.ShrinkX: true
chat.effects.GrowX: true
chat.emotes.animated: 2
chat.effects.Slide: true
chat.effects.Appear: true
chat.effects.Leave: true
chat.effects.Rotate: true
chat.effects.Rainbow: true
chat.effects.HyperRed: true
chat.effects.Shake: true
chat.effects.Photocopy: true
chat.effects.Jam: true
chat.effects.Bounce: true
chat.badges.fix-colors: true
theme.can-dark: true
theme.is-dark: true
chat.badges.style: 1
chat.badges.clickable: 2
chat.badges.version: 2
chat.filtering.all-mentions: true
chat.filtering.color-mentions: true
chat.filtering.need-colors: true
chat.actions.inline:
chat.scroller.freeze-requires-hover: true
chat.scroller.hover-delay: 750
chat.scroller.freeze: 0
chat.scroller.smooth-scroll: 3
chat.input.hide-identity: true
chat.emote-menu.enabled: true
chat.emote-menu.icon: true
chat.emoji.style: "google"
chat.inline-preview.enabled: true
chat.tab-complete.emotes-without-colon: false
chat.emotes.2x: 2
chat.emotes.limit-size: false
chat.banners.last-events: true
chat.input.show-mod-view: true
chat.input.show-highlight: true
chat.input.show-shield: true
chat.lines.padding: true
chat.bits.show: true
chat.filtering.deleted-style: 2
chat.filtering.clickable-mentions: true
chat.filtering.bold-mentions: true
chat.hide-community-highlights: false
chat.lines.alternate: true
chat.filtering.highlight-mentions: true
chat.filtering.highlight-tokens: true
chat.filtering.mention-color: "#00FF26"
chat.input.show-elevate-your-message: true
chat.disable-handling: false
chat.adjustment-mode: 1
chat.adjustment-contrast: 4.5
theme.color.chat-background: "#000000"
theme.color.chat-text: "#FFFFFF"
chat.lines.borders: 2
chat.bits.animated: false
theme.tooltips-dark: false
chat.width: 460
chat.effective-width: 460
chat.actions.size: 16
chat.actions.hover-size: 20
chat.timestamp-size: 24
chat.font-size: 32
chat.lines.emote-alignment: 2
chat.font-family: "google:Roboto Slab"
chat.banners.charity: true
chat.hype.display-input: false
chat.actions.room-above: false
chat.actions.room: []
chat.subs.gift-banner: true
chat.banners.hype-train: true
chat.banners.prediction: true
chat.banners.polls: true
chat.banners.pinned-message: true
chat.banners.drops: true
chat.delay: 0
chat.scrollback-length: 150
chat.filtering.remove-deleted: 0
chat.filtering.display-deleted: "DETAILED"
chat.replies.style: 1
chat.filtering.show-reasons: 1
chat.filtering.debug: false
chat.filtering.highlight-basic-users-blocked: []
__filter:block-users: null
chat.filtering.highlight-basic-blocked: 
__filter:block-terms: {"remove":[null,{}],"non":[null,{}]}
chat.filtering.highlight-basic-badges: [{"remove":false,"v":"broadcaster","c":"#000585","p":0}]
__filter:highlight-badges: {}
chat.filtering.highlight-basic-badges-blocked: []
__filter:block-badges: null
chat.filtering.highlight-basic-users: 
__filter:highlight-users: [[0,"#3A006E",{}],[0,"#511BED",{}],[0,"#2A000C",{}],[0,null,{}]]
chat.filtering.highlight-basic-terms: 
__filter:highlight-terms: {"hl":[[0,"#828700",[{},null]],[0,null,[{},{}]]],"non":[[0,null,[null,{}]]]}
chat.emotes.enabled: 2
chat.fix-bad-emotes: true
chat.emoji.replace-joiner: 1
chat.filtering.mention-priority: 0
chat.rich.enabled: true
chat.rich.minimum-level: 0
chat.rich.want-mid: true
chat.name-format: 0
chat.timestamp-format: "h:mm"
chat.badges.hidden: {}
chat.badges.custom-mod: true
chat.badges.custom-vip: true
chat.filtering.hidden-tokens: {}
ffzap.betterttv.global_emoticons: true
ffzap.betterttv.pro_badges: true
ffzap.betterttv.channel_emoticons: true
ffzap.core.highlight_sound: "https://cdn.ffzap.com/sounds/zelda_secret.mp3"
ffzap.core.highlight_sound_types: ["mention","user","term"]
ffzap.core.enable_highlight_sound: true
ffzap.core.message_deletion: 0
ffzap.core.highlight_sound_volume: 60
smokemotes.mod_keybinds: false
ffzap.core.remove_spaces: true
ffzap.betterttv.arbitrary_emoticons: true
chat.update-when-loaded: true
smokemotes.keep_hd_video: true
chat.points.show-button: true
layout.portrait: true
layout.portrait-threshold: 1.25
layout.use-portrait: false
layout.portrait-min-chat: false
chat.points.show-rewards: true
chat.emote-menu.combine-tabs: true
chat.emote-menu.stay-loaded: true
chat.emote-menu.show-quick-nav: true
chat.emote-menu.show-heading: 1
chat.emote-menu.tall: true
chat.emote-menu.reduced-padding: true
chat.emote-menu.show-search: true
chat.emote-menu.clear-search: true
chat.emote-menu.sort-emotes: 4
chat.emote-menu.sort-tiers-last: true
chat.emote-menu.effect-tab: true
chat.emote-menu.show-emoji: true
chat.bits.show-pinned: false
chat.filtering.blocked-types: {}
ffzap.core.highlight_sound_prevent_own_channel: true
chat.extra-timestamps: true
chat.me-style: 3
chat.rich.all-links: true
chat.rich.hide-tokens: true
tooltip.images: true
tooltip.link-images: true
tooltip.link-nsfw-images: true
chat.emotes.allow-gigantify: true
chat.points.auto-rewards: true
chat.emote-menu.shortcut: false
chat.mru.enabled: true
chat.filtering.process-own: true
tooltip.badge-images: true
tooltip.rich-links: true
tooltip.link-interaction: true
ffzap.betterttv.pro_emoticons: true
chat.bits.stack: 0
chat.bits.cheer-notice: true
tooltip.emote-images: true
tooltip.emote-sources: true
chat.emote-menu.tooltips: true
tooltip.emote-images.animated: true
**Additional context**

**Comment by Lordmau5** [comment]
From what I know animated emotes are currently not working at all in the gigantic emote redemption.

Stendec is aware of it though and it'll be fixed in a future version of FFZ

**Comment by SirStendec** [comment]
Fixed in e2e315d7028b7822ac7bd27c480bacc5bb4f37d6
