### ISSUE TITLE
Addon installation from website on fresh firefox download doesn't work

### ISSUE THREAD

**Issue by Scy147** [FrankerFaceZ/FrankerFaceZ#1519]
**Describe the bug**
Pressing the download button on the website results in firefox showing that the addon is corrupted, following the steps in the popup does not resolve the issue.

**To Reproduce**
1. Download firefox
2. Login to FF account & sync
3. Open FFZ website
4. Press install button
5. See error
6. Follow popup steps
7. Try again, fail again

**Additional Information**
For full transparency, the installation first failed after i did login to my FF account and it imported all my settings. I then went through the steps in the popup, without problem resolution. After that i was giga annoyed, logged out of my FF account, deleted all the user-data, restarted firefox to save mode, but chose the clean option rather than starting firefox. Short of actually reinstalling the browser, i have done what i can.

I resorted to importing via tampermonkey, which works fine

**Comment by ComfortableMilk4454** [comment]
announcement regarding this issue: https://discord.com/channels/538253705661775872/538264358971637762/1250888420331360297 (join the [discord server](https://discord.gg/UrAkGhT) to see)
