### ISSUE TITLE
can't install ffz on ff release 128.0

### ISSUE THREAD

**Issue by ComfortableMilk4454** [FrankerFaceZ/FrankerFaceZ#1521]
**Describe the bug**
can't install ffz on firefox

**To Reproduce**

1. go to https://cdn.frankerfacez.com/script/frankerfacez-4.0-an+fx.xpi on firefox
2. see error

**Expected behavior**
ffz to install

**Screenshots**
![image](https://github.com/user-attachments/assets/b99f9463-d92a-4084-81be-6de1fefd659d)

**Environment (please complete the following information):**
 - OS: macOS 14.5
 - Browser firefox release
 - Version 128.0
 - Other Extensions: uBlock Origin, 1password, Youtube Auto Hd + fps, Stylus, Bypass paywalls clean

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:
n/a

**Comment by ComfortableMilk4454** [comment]
nvm didnt read https://discord.com/channels/538253705661775872/538264358971637762/1250888420331360297 sorry

**Comment by Lordmau5** [comment]
Closing in favor of https://github.com/FrankerFaceZ/FrankerFaceZ/issues/1495 :)
