### ISSUE TITLE
Problem with Chrome's Live Caption and FFZ's audio compressor

### ISSUE THREAD

**Issue by rantos9** [FrankerFaceZ/FrankerFaceZ#1524]
**Describe the bug**
When FFZ's audio compressor is enabled the live captions text behave erratically with the text shifting a couple characters back and forth multiple times a second. The problem persist even when the compressor is disable and the only way to avoid this is to uncheck the `Enable the compressor by default` option and to never click the compressor, if you click it you need to refresh to go back to normal captions.

**To Reproduce**
Go to a stream and enable the compressor and live captions.

**Expected behavior**
Live Captions to work the same regardless of compressor use or at least for the problem not to persist when you disable the compressor.

**Screenshots**
![Screen Recording 2024-07-25 163912](https://github.com/user-attachments/assets/b2bd793f-2026-405e-8b4d-7448d7cdcee9)

**Environment (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 127
 - Other Extensions: none, I tested this on a clean profile with no other extensions

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:
For some reason log upload seems to not be working right now. I'll post a link later if I'm able to upload it.

**Comment by SirStendec** [comment]
This is a bug with Chrome, not with FrankerFaceZ. We are using the web audio API in a normal way, so if the browser can't handle that correctly, there's nothing for us to do about it. Just don't use the feature if you need live captions to work.

As for needing to reset the player before it starts working again, that has to do with a limitation of the web audio API. Once we have switched the audio pipeline from the standard `<video>` tag to using web audio, there is no way to reverse the process without completely recreating the `<video>` tag, which is what resetting the player does.
