### ISSUE TITLE
Update to Manifest V3 for Google Chrome

### ISSUE THREAD

**Issue by tux18031** [FrankerFaceZ/FrankerFaceZ#1525]
Google will soon be rolling out its Manifest V3 to Chrome extensions like FrankerFaceZ.
According to Google, this will mean that extensions that still use Manifest V2 will no longer work. This also affects the FrankerFaceZ extension for Chrome.

Link:
https://developer.chrome.com/docs/extensions/develop/migrate/what-is-mv3?hl=en
![Screenshot 2024-07-30 16 33 55](https://github.com/user-attachments/assets/fcc1e47c-0e19-46ee-80c4-36ae15b20fb7)
https://developer.chrome.com/docs/extensions/develop/migrate?hl=en

**Comment by SiriosDev** [comment]
more than a bug, its literally vital, for who use this for enhanced moderation

**Comment by tux18031** [comment]
@SirStendec -  Developer of FrankerFaceZ - writes in Discord: 
![Screenshot 2024-08-16 23 19 03](https://github.com/user-attachments/assets/106bad23-bfa1-444a-ab10-6d91657aa356)
 Link: https://discord.com/channels/538253705661775872/538255779279536128/1267950173590392932

**Comment by seky16** [comment]
Any update on this? The extension stopped working after Chrome update (now version 127.0.6533.122)

**Comment by Citillara** [comment]
Updating the homepage of FFZ and chrome extension store page of it saying that an update is on the way may be a good idea, as Chrome keeps warning users to find a replacement

**Comment by polytr0pe** [comment]
On Chrome Beta version 129.0.6668.42 incompatible extensions are disabled upon startup and you are prompted to remove them entirely; you can however choose to "Keep for now" then manually [re-enable them temporarily.](https://support.google.com/chrome_webstore/answer/2664769#unsupported_extensions&zippy=%2Ctemporarily-enable-the-extension) 
![image](https://github.com/user-attachments/assets/45194b0c-8cd5-4a4e-b378-ae5bbf0ddb6c)


![image](https://github.com/user-attachments/assets/43ba9152-9df6-421b-be84-a3f5bfb89085)

⚠note that **if you remove an incompatible extension after receiving this notice, you will be *unable to re-install it*** via the Chrome Web Store:

![image](https://github.com/user-attachments/assets/1d0fdae8-d746-42d9-ae4e-0f61354a4372)

**Comment by tux18031** [comment]
Update to 4.75.4.0 - this version supports Manifest V3
