### ISSUE TITLE
Feature Request: Disable compressor on own channel/dashboard

### ISSUE THREAD

**Issue by HildarTheDorf** [FrankerFaceZ/FrankerFaceZ#1534]
**Is your feature request related to a problem? Please describe.**
I have the compressor defaulted to on as I often watch streams in the evening and find it improves my experience as a stream consumer. However I do not want it to apply to my own channel when listening to my own stream/vods where I am the producer and want to hear the unaltered audio.

**Describe the solution you'd like**
Add a new option to disable the compressor on my own channel and/or the dashboard.

**Describe alternatives you've considered**
Manually turning the compressor off every time I open my own stream. This obviously works but is easy to forget.

**Additional context**
None

**Comment by SirStendec** [comment]
This is already possible.

1. Create a new settings profile.
2. Apply rules to that settings profile so it's only active on your own channel.
3. Set the compressor to be disabled by default in that profile.

**Comment by HildarTheDorf** [comment]
Ah, thank you very much!
