### ISSUE TITLE
Remove the Twitch Turbo "Go Ad-Free for Free" button in the top navigation

### ISSUE THREAD

**Issue by mynameistito** [FrankerFaceZ/FrankerFaceZ#1536]
**Is your feature request related to a problem? Please describe.**

I'm frustrated by the constant mention of "Go Ad-Free for Free with Twitch Turbo" in the top navigation bar. It clutters the interface and detracts from the user experience, especially for those who are already using Twitch Turbo or simply want a cleaner UI.

**Describe the solution you'd like**
I would like the option to remove or hide the "Go Ad-Free for Free with Twitch Turbo" mention from the top navigation bar in FrankerFaceZ. This could be a toggle option within the FrankerFaceZ settings, allowing users to choose whether they want this message displayed or not.

**Describe alternatives you've considered**
Removing via an Adblocker and removing the div.

**Additional context**
Here is a screenshot of the mention in the navigation bar for reference: [Screenshot](https://i.mynameistito.com/W1BZHlhmVU.png). This feature would be especially useful for those who prioritize a clean and minimalistic interface.

**Comment by SirStendec** [comment]
There is already a setting in Appearance > Layout to do that. "Allow the Twitch Turbo button to appear."

**Comment by mynameistito** [comment]
oh ha, thanks for that :) @SirStendec
