### ISSUE TITLE
 Talk with 7TV and BTTV to make a compatibility plugin

### ISSUE THREAD

**Issue by TheGeekno72** [FrankerFaceZ/FrankerFaceZ#1539]
This suggestion will go to the other plugins boards too :
Have an independently published plugin to enable/disable settings and choose which plugin does what
Examples :
- chat message highlight, but I want BTTV's instead of FFZ's
- bot account icon but I want FFZ's instead of BTTV's
- link preview but I want 7TV's instead of FFZ's
- placing the emote menus in one same spot (the empty space between the channel points and the chat button)
etc...

7TV post :
https://discord.com/channels/817075418054000661/1281545200824750081
BTTV post :
https://github.com/night/betterttv/discussions/7018

**Comment by SirStendec** [comment]
The add-ons are unfortunately too complex for this sort of thing to be feasible. A while back, 7tv claimed they would implement some fancy chat API to make it possible for add-ons to introduce their own features but this never materialized. Frankly, it's too much work.

Just maintaining our own extensions can be a lot of work, and trying to consider every possible permutation of features as you have requested would be ludicrous. These are projects of love to the communities, but there are limits.

I just don't have the time and effort to put into tighter but also more finely controllable integration.
