### ISSUE TITLE
[Feature Request] Emote Substitution in Clip Chat Replay

### ISSUE THREAD

**Issue by blaenk** [FrankerFaceZ/FrankerFaceZ#154]
I'm not sure if this pertains to FFZ, but when I open a twitch clip, FFZ doesn't detect and substitute in certain emotes like LUL. Now, as I understand it, LUL is provided by BetterTTV and not FFZ, but I make that work with FFZ via the FFZ Addon Pack which AFAIK uses the FFZ API, which is why I figure that it may fall under FFZ's reach.

**Comment by SirStendec** [comment]
Duplicate of #142
