### ISSUE TITLE
Display UI associated with bits. Not working correctly

### ISSUE THREAD

**Issue by MrAmericanMike** [FrankerFaceZ/FrankerFaceZ#1541]
In settings make sure to have "Display Bits" "Display UI associated with bits. Note: This will not hide cheering in chat messages." unchecked.

Go to a channel that accepts bits.
At the bottom of the chat we will see that the amount of bits our account has will be showing there.

**Expected behavior**
Those bit counts shouldn't be showing there.

**Screenshots**
![image](https://github.com/user-attachments/assets/fa5231ab-5e71-40e2-988f-880c44e36479)

**Environment (please complete the following information):**
 - OS: Windows
 - Browser: Brave
 - Version: 1.69.162

**Comment by SirStendec** [comment]
Addressed in 0ffc041c0ce3f45734d6f61c7950b91a1da71a1d
