### ISSUE TITLE
Display Channel Points button beneath chat also hides bits count

### ISSUE THREAD

**Issue by MrAmericanMike** [FrankerFaceZ/FrankerFaceZ#1542]
**Describe the bug**
Go to settings and make sure to have "Display Channel Points button beneath chat" enabled.

Go to any channel that accepts bits and has channel points enabled.

Uncheck that setting.

Notice how both the bits and the channel points disappear. 

Related to issue: https://github.com/FrankerFaceZ/FrankerFaceZ/issues/1541

OS: Windows
Browser: Brave
Version: 1.69.162

**Comment by SirStendec** [comment]
I would need to do annoying things to make this work, since it's still primarily a channel points UI element that they just happened to shove bits onto after the fact. As such, I'm not going to bother with this.
