### ISSUE TITLE
Support for "Stream Together" shared chat

### ISSUE THREAD

**Issue by BhaaLseN** [FrankerFaceZ/FrankerFaceZ#1546]
**Is your feature request related to a problem? Please describe.**
Yesn't. This isn't a problem per-se, but as Twitch is rolling out shared chats for Stream Together, some of the new features are (obviously) not fully working when FFZ is enabled. And it would be nice to have those features integrated (at least some of them.)

**Describe the solution you'd like**
Stream Together allows streamers to invite other streamers for a shared experience with built-in voice chat and other collaboration features. Recently, they also put shared chat into beta, which allows the chats of all channels to be combined. Mods from all sides can moderate all sides, all sides see cheers/subs/gifts etc. no matter which channel you watch.

**Describe alternatives you've considered**
Not really alternatives, but sure: Leaving FFZ on and not getting the features, or turning it off to use the vanilla chat experience.

**Additional context**
As far as I can tell, this is mostly an addition to the existing IRCv3 message tags including the source chat info (by prepending `source-` to the tags.)

Next to the `badge-info` tag for the channel being viewed currently, there's also a `source-badge-info` tag for the channel where the message came from. Same for `source-badges`, `source-id` and `source-room-id` (all with the same format as the non-`source-` tag.)
Streamer chat in the dashboard includes origin icons in front, but this doesn't seem to be in regular chat yet.

Twitch staff working on the feature confirmed that those message tags are stable and will remain like that.
They also pointed me at the [EventSub API docs](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#shared-chat-message-example) which already includes the documentation and examples for shared chat.

**Comment by SirStendec** [comment]
Addressed in 0ffc041c0ce3f45734d6f61c7950b91a1da71a1d

Due to the complexities of the web app, this may require more work before it's functioning completely correctly, but a good start has been made.
