### ISSUE TITLE
Fully filter messages with blocked words

### ISSUE THREAD

**Issue by asdsadsaasd12312132** [FrankerFaceZ/FrankerFaceZ#1548]
The filtering feature just censors the word. I want to make it so that messages with blocked words don't show at all.

**Comment by SirStendec** [comment]
You just need to check the box to remove matching messages for any relevant terms.
![image](https://github.com/user-attachments/assets/70d4bbc3-6b6b-48de-ab40-6747ca53bc60)

**Comment by asdsadsaasd12312132** [comment]
It doesn't work for announcements. It just censors the words.
![image](https://github.com/user-attachments/assets/65b2da15-96c8-4114-ae70-8c5844ce05e2)
