### ISSUE TITLE
[Suggestion] Making BTTV Channel Emotes visible in whispers like BTTV

### ISSUE THREAD

**Issue by Jampse** [FrankerFaceZ/FrankerFaceZ#155]
**Web Browser**:
Chrome

**Do you use BetterTTV or other Twitch extensions**:
FFZ Addon through Chrome extension

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: 
No

**Bug / Idea**:
 I used to be able to send BTTV channel emotes to my friends in Whisper, so I'm hoping this new FFZ addon would have it very soon.

**Steps to Reproduce (if Applicable)**: 
No

**Comment by SirStendec** [comment]
Channel emotes are specifically emotes that are tied to a channel. Whispers are global private messages.

Adding channel emotes to whispers makes absolutely no sense. What if the person you're whispering isn't watching the same channel? Then they wouldn't have the emotes loaded in their client and they wouldn't see them at all.

I will not add behavior like that to FrankerFaceZ.
