### ISSUE TITLE
Shared Chat: Add in-line chat source tag

### ISSUE THREAD

**Issue by robmonte** [FrankerFaceZ/FrankerFaceZ#1550]
**Is your feature request related to a problem? Please describe.**
It isn't clear who is talking from different twitch channels the the one you are viewing from, when in a Shared Chat, and it isn't realistic to try mousing over every individual person.

**Describe the solution you'd like**
There should be an in-line tag showing which chat people are talking from when Shared Chats are active. It could be akin to the "1ST TIME CHAT" tag on messages but without the message highlight.

**Describe alternatives you've considered**
Not sure of any alternatives.

**Additional context**
N/A

**Comment by SirStendec** [comment]
Already a thing. FFZ Settings. Chat > Shared Chat. Set Pill Style to Channel Name or Avatar, as desired.

**Comment by robmonte** [comment]
Oh thank you, I didn't realize that was what Pill Style meant!
