### ISSUE TITLE
Chat not previewing on whole chat box

### ISSUE THREAD

**Issue by idarsh22** [FrankerFaceZ/FrankerFaceZ#1560]
**Describe the bug**
Chat not previewing on whole chat box

**To Reproduce**
1. Open any channel with FFZ version 4.75.0 enabled

**Expected behavior**
Chat to appear on whole chat box

**Screenshots**
![image](https://github.com/user-attachments/assets/e4a32f58-f89a-44a6-b6a2-605bd1bb4a5d)

**Environment (please complete the following information):**
 - Windows
 - Google Chrome
 - Version 4.75.0
 - Other Extensions: [BTTV, 7TV, UBlock .....]

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:
https://logs.frankerfacez.com/563492a3-ad44-4e49-bc3e-407641a665cd
**Additional context**
CAN YOU JUST GIVE ME A HEADS UP FOR AN UPDATE AND NO AUTO UPDATE

**Comment by SirStendec** [comment]
Your issue is that the 7TV browser extension creates a FFZ settings profile that reduces the chat history length to 1 message. This is not an issue with FrankerFaceZ. It is operating exactly as intended.
