### ISSUE TITLE
Option to disable/hide shared messages

### ISSUE THREAD

**Issue by skwurw** [FrankerFaceZ/FrankerFaceZ#1563]
As the title suggest an option to be able to hide/disable the shared chat feature would be nice. I personally would prefer to see chat messages from the channel I am watching.

**Comment by SirStendec** [comment]
When Shared Chat is enabled, there is effectively only one chat that all the channels are sharing. I don't think it would be reasonable to add a setting to silently drop all messages that originated in a different channel.
