### ISSUE TITLE
FrankerFaceZ no longer be supported on chrome

### ISSUE THREAD

**Issue by Fan4eGGG** [FrankerFaceZ/FrankerFaceZ#1571]
Using latest Opera and extensions says "_This extension may soon no longer be supported_" like this: 

![Screenshot_2](https://github.com/user-attachments/assets/15975650-90cf-4751-b85a-fa938f9cf810)

so it can be fixed or no?

**Comment by SirStendec** [comment]
The manifest v3 version of FrankerFaceZ is already uploaded and waiting to be reviewed/approved by Chrome's team.

We also have a [nightly build version](https://chromewebstore.google.com/detail/frankerfacez-nightly/jgnjpfcdneiofkjkidlokfipfaignogj) of the extension that has already been approved that users can use.

> Note: You should only use one or the other at a time.

**Comment by Fan4eGGG** [comment]
> We also have a [nightly build version](https://chromewebstore.google.com/detail/frankerfacez-nightly/jgnjpfcdneiofkjkidlokfipfaignogj) 
> 
I use it, but I still don't have emoticons displayed in the OBS, without that, it doesn't make much sense to me.

**Comment by SirStendec** [comment]
> I use it, but I still don't have emoticons displayed in the OBS, without that, it doesn't make much sense to me.

Your web browser has literally **nothing** to do with what happens in OBS's embedded chat frame.

**Comment by Fan4eGGG** [comment]
> Your web browser has literally **nothing** to do with what happens in OBS's embedded chat frame.

ah, so thats not the problem. I get it. I'll look for the cause then
Thanks.
