### ISSUE TITLE
Blocked tags in Directory->Channels aren't enforced within category directories

### ISSUE THREAD

**Issue by pwnflakes** [FrankerFaceZ/FrankerFaceZ#1573]
If I add a blocked tag to Directory->Channels, it correctly filters these out within the home of https://www.twitch.tv/directory however when I click into a category like Just Chatting, channels with those tags are now visible.

Given that there isn't a separate section of settings to determine which tags are ignored within specific categories (and why would there be), it makes sense that these blocked tags would be filtered out within categories themselves too. Ultimately categories are still within 'Directory' - https://www.twitch.tv/directory/category/just-chatting - so the same blocking/filtering logic should apply.

If I'm blocking a tag within the general directory, chances are I also don't want to see that tag when going into specific game directories. The only settings on the Directory->Categories page are to do with blocking specific categories (or their thumbnails) from loading, with nothing about tags to block within the category so I assume it should inherit blocked tags from the Channels

**Comment by SirStendec** [comment]
Unable to reproduce the issue. Tags are being blocked from specific categories just fine for me. The issue template exists for a reason, please use it in the future.
