### ISSUE TITLE
[Feature Request] Restore Clip Button Appearance

### ISSUE THREAD

**Issue by F-Lambda** [FrankerFaceZ/FrankerFaceZ#1580]
Twitch recently changed the clip button by moving it, adding text, giving it a background, and making it disappear when pausing stream. It would also be nice to have an option to move it back to its original apperance and location:

New:
(The button is not highlighted, that's just the way it looks. Yes, they placed it *in between* the options button and resolution display)
![image](https://github.com/user-attachments/assets/234ee6d3-0cb9-4e4a-8abe-345e0d9beb93)

Original:
(The button *is* highlighted, showing tooltip. Without being hovered, it looks the same as the other buttons)
![image](https://github.com/user-attachments/assets/0e22ad21-312a-4180-a420-45748ed6278c)

**Comment by F-Lambda** [comment]
Between this and the other related Request, it might be good to have the option to just freely reorder the buttons, including the ability to hide some (or all) of them.

**Comment by gaveitatry2** [comment]
I created a userscript to hide the Cast and Clip buttons. But of course, I would rather be able to do this using only FrankerFaceZ itself.

![notepad_FZsP0gbUIT](https://github.com/user-attachments/assets/263de758-bdf2-48f5-80f3-f559c8e641a5)
