### ISSUE TITLE
Resizable chat (Height) in portrait mode

### ISSUE THREAD

**Issue by ptk1337** [FrankerFaceZ/FrankerFaceZ#1589]
**Is your feature request related to a problem? Please describe.**
While using portrait mode with chat below/above the video player there is no way to make chat bigger to get rid of black bars in video player - can be seen on attached screenshot.

**Describe the solution you'd like**
Possibility to resize height of the chat while in portrait mode.

**Describe alternatives you've considered**
-

**Additional context**
![image](https://github.com/user-attachments/assets/3200c1cc-cbee-434e-a02b-a75bca12e595)

**Comment by SirStendec** [comment]
The gap exists on purpose to avoid potential UI conflicts. You can get rid of it by enabling the following setting:

Player > General > Theater Mode >> Hide whispers when Theatre Mode is enabled.
