### ISSUE TITLE
New custom Clip button stops working after background player pause*

### ISSUE THREAD

**Issue by guniu** [FrankerFaceZ/FrankerFaceZ#1593]
**Describe the bug**
You know that feature when your player is muted and you switch tabs it stops playing in the background and when you go back it resumes. Well that feature breaks the new custom Clip button for me. Clicking the button does nothing, but the Alt+X shortcut sill works. I have to restart the page (or the embed player) for it to work again. It also breaks when using TwitchAdSolution script and it switches to/from the no-ad feed. I assume it's the same issue.

**To Reproduce**
1. Open a muted stream (it has to be pre-muted, if you open unmuted and then mute it won't work).
2. Switch tab so the stream pauses in the background.
3. Go back to the stream tab (if you see resolution info label next to the Settings icon it means player was paused).
4. Press the custom Clip button.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 131.0.6778.109
 - Other Extensions: Tempermonkey with TwitchAdSolutions (video-swap-new)

*Actually after more testing I just noticed that it breaks even when I pause and play the stream manually. The original Clip button disappears when paused, so maybe it's related to that and why it breaks.

**Comment by SirStendec** [comment]
Fixed in 93181dc8e8827a022839d22b8fd442a8956388fd
