### ISSUE TITLE
Emote tooltip darkmode

### ISSUE THREAD

**Issue by FeuFeuAngel** [FrankerFaceZ/FrankerFaceZ#1594]
**Describe the bug**
The tooltip if you hover over a emote is not in darkmode, atleast with Edge?

**To Reproduce**
Hover with the mose over a emote of chat message

**Expected behavior**
Darkmode like the rest of the plugin

**Screenshots**
![image](https://github.com/user-attachments/assets/05568eaa-d92c-4919-8e3b-3a837a875035)

**Environment (please complete the following information):**
 - OS: Win 11 (Latest)
 - Browser edge
 - Version latest
 - Other Extensions: Ublock orgin,stylish

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:
https://logs.frankerfacez.com/292fc4ae-1b60-4096-9512-7d4c0066a7c3

**Additional context**
i fixed this mystelf over stylish years ago

So it looks like this now:
![image](https://github.com/user-attachments/assets/1af1f1bd-cb4b-4ba7-b5f2-7163733a7abb)

Simply add:
`.ffz__tooltip--inner
{
  background-color:#262626;
  color:white;
}`

**Comment by SirStendec** [comment]
Dark tooltips in dark mode is already possible. Open the FFZ Control Center to Appearance > Theme. Change Tooltip Background as desired. You can also set Tooltip Text directly if desired, though it's automatically set to white or black based on the luminosity of your chosen background color.
