### ISSUE TITLE
Following Button Dissappeared On Left Sidebar

### ISSUE THREAD

**Issue by Rmac524** [FrankerFaceZ/FrankerFaceZ#160]
**Web Browser**: Chrome 44

**Do you use BetterTTV or other Twitch extensions**: no

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:
http://putco.de/NTk4Mw.log

**Bug / Idea**:
http://i.imgur.com/gTyV6CY.png

**Steps to Reproduce (if Applicable)**: go onto the following page or a stream
ffz settings:
https://github.com/FrankerFaceZ/FrankerFaceZ/files/965530/ffz-settings.zip

**Comment by SirStendec** [comment]
Please verify that the issue isn't present when FrankerFaceZ is disabled. This seems like a problem with Twitch breaking their old layout and not something FFZ would have done.

**Comment by Rmac524** [comment]
This bug is present without FFZ. :(
