### ISSUE TITLE
[Bug] web_channel_metadata_layout resets after 1-2 days

### ISSUE THREAD

**Issue by ajsglist** [FrankerFaceZ/FrankerFaceZ#1607]
**Describe the bug**
web_channel_metadata_layout resets after an indeterminate time, generally 1-2 days.  Chrome browser has not been closed at any point.  Extension has not been disabled.

**To Reproduce**
1. set web_channel_metadata_layout to "control"
2. use twitch/chrome like normal, setting will be in effect for a while
3. return to twitch stream a day or two later to observe setting has reset to default value

**Expected behavior**
ffz extension won't reset this setting

**Screenshots**
![image](https://github.com/user-attachments/assets/033c85a7-1c4f-4e7c-b58b-f65a472505f1)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version "Version 4.76.3.0 93181dc"
 - Other Extensions: 7TV emotes, BTTV emotes, FFZ:AP core

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:
https://logs.frankerfacez.com/56483a66-45d6-44e0-9dd0-254bc4d7b019

**Additional context**
setting seems to work until reset to default value occurs at an unknown time.  No other settings are getting reset or show apparent issues

**Comment by SirStendec** [comment]
Functioning as intended.

> Adjusting your experiments can have unexpected impacts on your Twitch experience. FrankerFaceZ is not responsible for any issues you encounter as a result of tampering with experiments, and we **will not provide support**.

**Comment by ajsglist** [comment]
Another user told me this value doesn't reset for them, so are you sure this behavior is intended?

In any event, I'm not reporting "issues I encounter as a result of tampering with experiments" (the setting itself works fine), I'm reporting that the setting itself is being reset without user input and without any restarting/updating of the browser and extension.
