### ISSUE TITLE
[Feature Request] Disable Custom Bit Badges

### ISSUE THREAD

**Issue by Rmac524** [FrankerFaceZ/FrankerFaceZ#162]
**Web Browser**:

**Do you use BetterTTV or other Twitch extensions**:

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**: Change the badges next to one's username back to the default for that tier of bit badge.

**Steps to Reproduce (if Applicable)**:

**Comment by SirStendec** [comment]
I really don't want to take away a channel's badge customization. Not for sub badges, not for bits badges.
