### ISSUE TITLE
Title bar colour changer doesn't result in the expected colour.

### ISSUE THREAD

**Issue by darkevilmac** [FrankerFaceZ/FrankerFaceZ#166]
**Web Browser**: Google Chrome

**Do you use BetterTTV or other Twitch extensions**: No.

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: N/A

**Bug / Idea**: When changing the title bar colour in settings the colour doesn't change to the one chosen, the colour that appears is substantially darker than what's selected. Resulting in colours like orange appearing brown.

**Steps to Reproduce (if Applicable)**: Change title bar colour code in settings.

**Comment by SirStendec** [comment]
This is intended behavior. By default, FrankerFaceZ will darken any color you enter so as to maintain readability and the general light-on-dark theme.

If you wish to override this behavior, simply start your value with an exclamation mark as described in the setting's dialog. Example:

![image](https://cloud.githubusercontent.com/assets/14036657/26437788/2b61f2be-40ed-11e7-9645-c14ddb0d40d2.png)

**Comment by darkevilmac** [comment]
My mistake, sorry.
