### ISSUE TITLE
The FFZ prevent chat from working in the <iframe>

### ISSUE THREAD

**Issue by CoolCmd** [FrankerFaceZ/FrankerFaceZ#167]
Hi, I am developer of the "Twitch 5" extension.

[Chrome](https://addons.mozilla.org/firefox/addon/twitch_5/)
[Firefox](https://chrome.google.com/webstore/detail/twitch-5/knankefoajngclnjgnelanfohgihifpc)

My extension loads Twitch.tv chat into <iframe>. With the FFZ installed, chat does not work in the Firefox 53 (endless loading).

FFZ works fine in the Chrome 58. Also BTTV works fine in the Firefox 53.

**Do you use BetterTTV or other Twitch extensions**: No

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: 'Settings' button does not work.

**Bug / Idea**: Bug

**Steps to Reproduce (if Applicable)**: Install "Twitch 5" extension on Firefox 53, then navigate to `twitch5:player?channel=coolcmd`, then open the chat.

**Comment by SirStendec** [comment]
This error is not something I can debug.

First, you inject FrankerFaceZ into pages with your extension in such a way that the developer server I set up will not be used.

Second, Firefox is a complete mess of a browser with completely useless developer tools and I can't actually set breakpoints in the script that is causing the error that I think is causing the issues.

![image](https://cloud.githubusercontent.com/assets/14036657/26533097/1c01eed6-43e1-11e7-993f-49199f9f3071.png)

The problem as far as I can see is that Twitch's global.js is trying to call postMessage and that causes a security exception when the iframe is being hosted in something like you have set up. Twitch doesn't have error handlers around postMessage.

I don't know why postMessage is being called when FFZ is present and not when it is not, and I have no good way of finding out. It doesn't seem to happen in Chrome, where I actually can make breakpoints. Granted, I didn't install your extension there to test it but then you said it works in Chrome already.

Anyways, if you can provide a way to actually track this down or more details about what is happening that breaks, I'd be glad to fix it. I don't have the time to do it myself right now.

**Comment by SirStendec** [comment]
Actually, I do have *one* idea. I'll push an update with a small change and see if that fixes it.

**Comment by SirStendec** [comment]
That seems to have fixed it for me. Excellent then. I'm glad no one had to try getting Firefox's developer tools to actually function.

**Comment by CoolCmd** [comment]
As of 3.5.485, the chat is working again. @SirStendec, thank you. :)
