### ISSUE TITLE
Settings reset on their own

### ISSUE THREAD

**Issue by jjoose** [FrankerFaceZ/FrankerFaceZ#168]
**Web Browser**: Chrome

**Do you use BetterTTV or other Twitch extensions**: No

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: http://putco.de/NjA3MQ.log

**Bug / Idea**: FFZ + FFZ:AP settings reset on their own

**Steps to Reproduce (if Applicable)**: Have had FFZ for a while and recently deleted BTTV and installed FFZ:AP.  However, if the browser is ever closed and reopened, all of my settings are reset.  In addition, the settings will sometimes reset even without closing the browser completely, though I'm not sure what causes the exact trigger for it. I just know that every day I need to redo my settings whether I closed the browser or not, restarting it just guarantees the settings will be wiped.  In the meantime I have the settings backed up so I can restore them.  Tried both the tampermokey and chrome extension versions, same problem.  Have turned off all other extensions to see if there is a problem there, but it happens anyways.

**Comment by jjoose** [comment]
After falling asleep with a stream open, and changing to another after waking up, same tab, browser never closed, the settings were again reset.  Forgot check before changing streams to see if the settings had reset before or after changing.  Will try to make note of this when I get the chance.

**Comment by jjoose** [comment]
Small update, the issue where settings reset without the browser restarting hasn't been happening, so I'm inclined to believe that I might have just inadvertently restarted the browser at some point when that was happening.  However, settings still do reset whenever the browser is closed and reopened for any reason.

**Comment by Tyestor** [comment]
Got this issue on Firefox as well. Spent about half an hour setting the AddOn up through the most moronically placed settings panel of all time (why doesn't it just open in a new tab?) and then the settings reset, probably after closing the browser. Makes me just want to uninstall the AddOnand go back to BTTV.

**Comment by SirStendec** [comment]
FrankerFaceZ stores its settings using local storage on the domain twitch.tv. If this data is reset for any reason, that will clear your settings.

This data will be reset if you clear your browsing data. This data will be reset if you use programs like CCleaner. This data could also be reset, or prevented from being properly stored in the first place, by other extensions.

Please verify that you do not have your browser reset data, that you do not use any sort of cleaning applications, and that the behavior continues when you disable all other extensions (with the exception of FFZ:AP).

**Comment by jjoose** [comment]
Problem persists even after disabling every other extension, and CCleaner wasn't installed when this started.  I only installed it about a week ago for a different reason, and I immediately unchecked all of my browsing data from the list of things to clean, so I know that isn't an issue.  My browsing data hasn't been manually cleared at all, and I haven't noticed a single instance of anything else having been automatically cleared anywhere else except with FFZ.

**Comment by NiteCyper** [comment]
i have the same issue
