### ISSUE TITLE
[Feature Request] "Banned User" Feature

### ISSUE THREAD

**Issue by Jacky1356400** [FrankerFaceZ/FrankerFaceZ#172]
**Web Browser**: Google Chrome 58.0.3029.110

**Do you use BetterTTV or other Twitch extensions**: Yes, FFZ:AP

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: N/A

**Bug / Idea**:
I know Twitch provides an option to `/ignore` a user. But, when the person is a moderator / I am moderator in a channel, the ignore function Twitch provides doesn't work (I know Twitch does that on purpose, so people can still moderate their messages). In a few channels I mod in / I watch, there are bots that does currency system and it gets the chat really spammy. It would be great if there is a "Banned User" (or something similar) to completely block messages from usernames in a user-defined list (like the "Banned Words" feature, but users-specific, and for chat only). Thank you.

**Steps to Reproduce (if Applicable)**: N/A

**Comment by gdiShun** [comment]
Curious if you found a way to accomplish this or gave up? With GDQ back, I'm finding that Twitch's /ignore apparently only blocks the more recent x number of people ignored or something. I'm having to block the same people 2-3 times a day, which is really annoying.

**Comment by Jacky1356400** [comment]
Since I didn't get a response for about half a month, I asked a friend of mine to make me a [Chrome extension](https://chrome.google.com/webstore/detail/twitch-blocker/jdhjmiipchflhojjkefhfljlcabapied) as to solve this problem out.
I would love to have it integrated into FFZ, but looks like I had to give up on this idea.
