### ISSUE TITLE
Blacklisted words-On Bot/mod

### ISSUE THREAD

**Issue by Telcis** [FrankerFaceZ/FrankerFaceZ#173]
**chrome**:

:FFZ old bttv user

When a word is blacklisted remove from chat, excluding known bots. Helps for when Mods are Running, certain things ie. giveaways without the !enter spam but the !enter is in the bot command so that is removed and cannot see the chat of the Bot we use Deep_bot in our channel and i have the Bot highlighted to see if this fixed the issues. Still did not show the bot chat.

**Comment by SirStendec** [comment]
This is a very good point. By default now, messages from moderators won't be filtered.
