### ISSUE TITLE
Custom Bits Badges Value

### ISSUE THREAD

**Issue by OxHard** [FrankerFaceZ/FrankerFaceZ#176]
**Web Browser**:

**Do you use BetterTTV or other Twitch extensions**:

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**: With the new customs bits badges on some channels, having the option to be able to see the bit badge value (1000 bits, 5000, 10000 etc) on mouseover like on the legacy twitch would be appreciated.

**Steps to Reproduce (if Applicable)**:

**Comment by SirStendec** [comment]
This is already working, as far as I know. Unless I'm misunderstanding what you're asking for?

![image](https://user-images.githubusercontent.com/14036657/27193269-438563cc-51cc-11e7-8b08-8708f5ea9b1b.png)

**Comment by OxHard** [comment]
![image](https://user-images.githubusercontent.com/29439402/27193547-7da10312-51ff-11e7-957e-287f546263e4.png)
Well, I'm Lost. It's working on most channels, but it look like this on One of them. I tried with and without the extension, and it's only like that with it. I'm using the chrome extension, and it's only bugged on the channel I'm subscribed to.
