### ISSUE TITLE
Emotes not showing name of partner when hovered over

### ISSUE THREAD

**Issue by frankerz123** [FrankerFaceZ/FrankerFaceZ#177]
**Web Browser**:
Chrome
**Do you use BetterTTV or other Twitch extensions**:
BTTV
**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**:
While FFZ is installed, unable to see whos emote it is

**Steps to Reproduce (if Applicable)**:
Install FFZ and hover over an emote, it will only say the emotes name, not who made it http://imgur.com/a/IdKTy as shown in the imgur link. This was tested by multiple different people i have messaged, BTTV doesnt seem to affect it as if you have BTTV solely installed you can still see the channel. Uninstalling FFZ fixes the issue.

**Comment by SirStendec** [comment]
Displaying what channel the emote is from is not a native Twitch feature. BTTV has its own implementation. FFZ has its own implementation.

There are two situations when FrankerFaceZ will not show where a particular emote is from.

1. It's a new emote and our server hasn't updated the mapping yet.
2. Your client fails to download the data file from the server with the mappings.
