### ISSUE TITLE
[Suggestion/Feature request] Auto-remove chat entries with copypasta/spam phrases/words

### ISSUE THREAD

**Issue by RedSnt** [FrankerFaceZ/FrankerFaceZ#179]
Title leaves little to the imagination except that the feature I think off wouldn't necessarily put anyone on the twitch ignore list, but rather just sort out chat entries with spam messages (instead of the banned words function which only remove words and not the whole spam message/entry).  

Because once the chat starts moving fast and everyone spamming "!rewards" (example from twitch.tv/RocketLeague) even if you remove the word, the chat will still move so fast you can't read messages which isn't spam. 

In the title I wrote "phrases" and that would probably be too advanced a filtering method, if this feature is even feasible, but it would most accurately get rid of specific copypasta.

Last thought on this: Maybe the banned word feature could be expanded with another toggle setting like "Remove message entries from chat that contains banned words.".

**Comment by SirStendec** [comment]
There is a setting to remove messages that contain banned words, actually. (Optionally, even when the person who says it is a mod.)

![image](https://user-images.githubusercontent.com/14036657/27399648-7950f39a-568b-11e7-9cc3-3180a09f7fe7.png)

As for filtering out spammier messages, I know Twitch is working on things like that themselves. Some sort of experiment about 'noisy' messages? Hopefully that ends up working well. I'm not entirely against developing something for the client, but I feel like it's not something that'd work great in a client.

In the event FFZ does get something like that, it'd be an optional module in v4. Closing this for now.

**Comment by RedSnt** [comment]
I always feel dumb when I overlook stuff like this. Thanks for your hard work, you even managed to implement this before I knew I wanted it just minutes ago 😄 👍
