### ISSUE TITLE
Viewer list no longer has "close" button with minimal header

### ISSUE THREAD

**Issue by cLOLe** [FrankerFaceZ/FrankerFaceZ#184]
**Web Browser**: Chrome

**Do you use BetterTTV or other Twitch extensions**: No, but I use Tapermonkeys plugin for BTTV Emotes

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: http://putco.de/NjI0Ng.log

**Bug / Idea**:
With the minimalistic option of "no header", when you open the viewer list, there's no way to exit. No exit button at the top, can't even just close it from the bottom. Page has to be refreshed completely.

**Steps to Reproduce (if Applicable)**: 
Turn on No header in militaristic display 

open viewer list

cant close it. 

Done

**Comment by Sukinidachi** [comment]
This has been happening to me too for probably like a week or two now, maybe longer. 

Anyways, I know nothing about code so here's what is looks like; the only way out is to refresh the page.

![no x in viewer list](https://user-images.githubusercontent.com/10570089/27681046-dc6662ac-5c8b-11e7-985b-e8cffad2b17f.png)

**Comment by dansa** [comment]
I threw together a small temporary fix for myself (until they have time to fix the issue on their end).
![image](https://user-images.githubusercontent.com/5786317/27683399-175f5622-5cc6-11e7-99ad-8b59fbd3f904.png)

```
body.ffz-minimal-chat-head .ember-chat .chatters .chat-header {
    padding: 0;
    height: 0;
    display: block!important;
}

body.ffz-minimal-chat-head .ember-chat .chatters .chat-header > * {
    display: none;
}

body.ffz-minimal-chat-head .ember-chat .chatters .chat-header .close-button {
    display: inline-block;
    right: 10px;
    left: initial;
}
```

Just throw into a Stylus userstyle or some similar addon if it's troubling you a lot (tested on Chrome/FF).
