### ISSUE TITLE
Display on Theater Mode Hover bug

### ISSUE THREAD

**Issue by jtyankees23** [FrankerFaceZ/FrankerFaceZ#185]
**Web Browser**: chrome

**Do you use BetterTTV or other Twitch extensions**: no

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**: when Display on Theater Mode Hover is turned on full the bar is blocking the player buttons for pause and mute

**Steps to Reproduce (if Applicable)**: turning on Display on Theater Mode Hover full

**Comment by Garcia98** [comment]
I'm also having this bug on Firefox, this is the log in case it's useful: http://putco.de/NjI2MA.log
