### ISSUE TITLE
[Question] Bits Icons in Chat & Badges

### ISSUE THREAD

**Issue by ContrarianLemon** [FrankerFaceZ/FrankerFaceZ#186]
**Web Browser**: Chrome

**Do you use BetterTTV or other Twitch extensions**: No, using FFZ w/ FFZ Add-On Pack

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: 

**Bug / Idea**: Was recently told about FFZ and switched to it from BTTV, absolutely love it. One big issue I have however are the bits icons & badges in chat. Is there a way to revert their appearance? I very much hate the "drawn" bits, and miss the non-black centre of bits badges.

Sorry if this has been answered before, or this isn't the correct place to ask but I googled around a bunch and couldn't find anything.

**Steps to Reproduce (if Applicable)**:

**Comment by dansa** [comment]
For the drawn bit icons, did you perhaps accidentally enable the Bits Redesign in settings?

![image](https://user-images.githubusercontent.com/5786317/27742939-b36e729c-5dba-11e7-9dcb-316698014407.png)

The 2017 bit redesign were an aprils fool thing if I remember right.

**Comment by ContrarianLemon** [comment]
Welp, that was the case. Thanks. I thought that option may have had something to do with the black bits icons so I toggled it but didn't notice any change, I then saw somebody use bits and they were drawn. I hadn't seen any between getting FFZ and changing that option so I assumed FFZ itself was responsible.

Nothing on the bits badges though?

**Comment by dansa** [comment]
No idea about bit badges or what the issue is? I've had them turned off since the system was launched though.

Maybe you could provide a screenshot or wait for a ffz dev to chip in :p

**Comment by SirStendec** [comment]
Bits badges are rendered the way they are due to a limitation in how FFZ renders badges. There's not an easy way for me to set the color of the inner image just yet. It's on my to-do list, but low priority.

**Comment by ContrarianLemon** [comment]
I see. Thanks for the help and quick replies!
