### ISSUE TITLE
Timestamps not showing in chat

### ISSUE THREAD

**Issue by huntexD** [FrankerFaceZ/FrankerFaceZ#192]
**Web Browser**: Chrome

**Do you use BetterTTV or other Twitch extensions**: FFZ addon pack

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:
http://putco.de/NjMwOQ.log

**Bug / Idea**: 

Timestamps are not showing in chat

http://imgur.com/YvOow18

**Steps to Reproduce (if Applicable)**:

**Comment by jdew** [comment]
There's a time stamp check box on the menu on the gear at the bottom of the chat
