### ISSUE TITLE
BTTV Emotes show only loading.gif image

### ISSUE THREAD

**Issue by RedGerman** [FrankerFaceZ/FrankerFaceZ#193]
**Web Browser**:Chrome

**Do you use BetterTTV or other Twitch extensions**: ffz add on pack

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:
Loading settings.
Error parsing value for "twitch_chat_dark": SyntaxError: Unexpected token u in JSON at position 0
Found Twitch application after 0 ms at: https://www.twitch.tv/staiy
Initializing FrankerFaceZ version 3.5.500
Injecting FrankerFaceZ Dark Twitch CSS.
Injecting main FrankerFaceZ CSS.
Readying toggleable styles.
Installing mouse-up event to auto-close pop-ups.
Using Socket Server: wss://andknuckles.frankerfacez.com/ [1:1]
Preparing emoticon system.
Creating emoticon style element.
Generating CSS for existing API emoticon sets.
Loading global emote sets.
Loading emoji data.
Watching Twitch emoticon parser to ensure it loads.
Preparing badge system.
Creating badge style element.
Generating CSS for existing API badges.
Generating CSS for existing Twitch badges.
Loading badges.
Hooking the Ember router.
Loading Twitch Emote Data (Try 0)
Hooking Ember chat line helpers.
Creating channel style element.
Hooking the Ember Channel Index redesign.
Hooking the Ember Channel controller.
Creating room style element.
Hooking the Ember Chat PubSub service.
Hooking the Ember Room controller.
Hooking the Ember Room model.
Adding Room: staiy
Hooking the Ember Channel Subscriptions service.
Creating layout style element.
Hooking the Ember service:layout
Hooking the Ember Chat controller.
Hooking the Ember Chat Room Manager component.
Hooking the Ember from-display-preview component.
Listening to the Settings controller to catch mod icon state changes.
Modifying Mousetrap stopCallback so we can catch ESC.
Hooking the Ember Moderation Card view.
Hooking the Ember Chat Input component.
Hooking the Ember Directory views.
Updating Ember classes and instances.
Updated 0 existing instances across 1 classes.
Attempting to modify the Following collection.
Error: Unable to locate the Ember component:twitch-navigation [undefined]
Error: Unable to locate the Ember component:recommended-channels [undefined]
Adding event handler for window focus.
Initializing following support.
Connecting to Live Streams model.
Initializing race support.
Updating Ember classes and instances.
Updated 17 existing instances across 43 classes.
Modifying Tipsy-Tooltip component to use gravity.
Fixing already existing tooltips.
Adding Room: decusde
Listening for Window Messages.
Checking for Feature Friday data...
Initialization complete in 90ms
Updated emoticons for set #3: Global Emoticons
Updated emoticons for set #4330: : Sten's Cheaty Emotes
Added ": Sten's Cheaty Emotes" emote set to 1 users.
Loaded data on 1774 emoji.
Added "developer" badge to 2 users.
Added "bot" badge to 121 users.
Added "supporter" badge to 7,226 users.
Loaded 7,349 total badges across 3 types.
Updated emoticons for set #90538: Channel: Staiy
Updated emoticons for set #58796: Channel: DecusDE
Socket Connected.
Error Saying Hello: Error: Expected array of string, string as arguments.
Loaded Twitch Emote Data
Registered New Extension #0 (ffzap): FFZ Add-On Pack
Ext #0 (ffzap): Injected successfully.
Ext #0 (ffzap): [GameWisp] Socket: Connecting to socket server...
Ext #0 (ffzap): Loaded Emoticon Set #tier2_monthly: Monthly Emote-Vote (5 emotes)
Ext #0 (ffzap): Loaded Emoticon Set #BTTV-Night-Sub: Night (Legacy) (8 emotes)
Ext #0 (ffzap): Loaded Emoticon Set #BTTV-Global: Global Emoticons (91 emotes)
Ext #0 (ffzap): Loaded Emoticon Set #BTTV-Channel-staiy: Channel Emoticons (30 emotes)
Ext #0 (ffzap): [GameWisp] Socket: Error from socket server.
Ext #0 (ffzap): [GameWisp] Socket: Trying to reconnect to socket server...
Ext #0 (ffzap): Loaded Emoticon Set #GameWisp-Global: Global Emoticons (3 emotes)
Ext #0 (ffzap): [GameWisp] Socket: Connecting to socket server...
Ext #0 (ffzap): [GameWisp] Socket: Error from socket server.
Ext #0 (ffzap): [GameWisp] Socket: Trying to reconnect to socket server...
Sets for staiy [staiy]: [3966]
Socket Reply to 8 - FAIL -- "backend http error: 204"
Ext #0 (ffzap): [GameWisp] Socket: Connecting to socket server...
Ext #0 (ffzap): [GameWisp] Socket: Error from socket server.
Ext #0 (ffzap): [GameWisp] Socket: Trying to reconnect to socket server...
BetterTTV was not detected after 60 seconds.
Emote Menu for Twitch was not detected after 60 seconds.
Ext #0 (ffzap): [GameWisp] Socket: Connecting to socket server...
Ext #0 (ffzap): [GameWisp] Socket: Error from socket server.
Ext #0 (ffzap): [GameWisp] Socket: Trying to reconnect to socket server...

**Bug / Idea**:
looking at the bttv emoticons and all of the emotes show the loading.gif ... same in the chat

**Steps to Reproduce (if Applicable)**:

**Comment by SirStendec** [comment]
First, BetterTTV and GameWisp emotes are being provided by FFZ:AP and not FFZ itself.

This isn't a bug though. FrankerFaceZ, Twitch, and the FFZ:AP are all participating in the Open Internet Day of Action in support of network neutrality. Everything will be back to normal tomorrow.
