### ISSUE TITLE
[Feature request] Search settings

### ISSUE THREAD

**Issue by Zoooook** [FrankerFaceZ/FrankerFaceZ#194]
There are a huge number of settings, enough that I frequently can't find one that I'm looking for, even though I use the favorite settings feature. Would be great to be able to search through them.

**Comment by SirStendec** [comment]
You can search through them, but only on the Advanced tab. Just click and type.

![image](https://user-images.githubusercontent.com/14036657/28147474-c4161e68-674e-11e7-9fcc-fbc4fa559063.png)

**Comment by Zoooook** [comment]
Oh. Cool, thanks.
