### ISSUE TITLE
[Feature Request] Way To Translate Chat Messages

### ISSUE THREAD

**Issue by Grendallmayo** [FrankerFaceZ/FrankerFaceZ#203]
**Web Browser**: Google Chrome

**Do you use BetterTTV or other Twitch extensions**: The FrankerFaceZ Add-On Pack for Tampermonkey (Chrome Extension)

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: Not applicable.

**Bug / Idea**: An option to translate foreign languages used in chat via any method.

**Steps to Reproduce (if Applicable)**: Not applicable.

**Comment by eps0003** [comment]
You can right click anywhere on the page and click 'Translate to English' and it will translate every chat message, even new ones.

**Comment by SirStendec** [comment]
Translation APIs are expensive. As mentioned, Chrome has a Translation feature built-in that should work for this.
