### ISSUE TITLE
[Bug] Some emojis in chat are not replaced with images

### ISSUE THREAD

**Issue by Tester798** [FrankerFaceZ/FrankerFaceZ#205]
**Web Browser**: Chrome

**Do you use BetterTTV or other Twitch extensions**: No

**Bug**: Some emojis in chat are not replaced with images

**Steps to Reproduce**: Install FFZ extension, paste in chat `🤔 🐥 🦆 🍀 🦅 🚀`, notice `🦆` and `🦅` emojis are not replaced with images

**Screenshot**:
![image](https://user-images.githubusercontent.com/8844478/28499838-c1f98f26-6fc7-11e7-859a-edc5a3854607.png)

**Comment by notheowner** [comment]
Web Browser: Chrome Windows 10
I use FFZ + FFZ : Addon Pack

Bug: Sometimes emojis typed by other users , (bttv users in all cases ) are not visible , I can only see the emoji text
![image](https://user-images.githubusercontent.com/25968992/28732230-061d197e-73cf-11e7-844f-06053b2fb7b2.png)

As you can see I am using chatterino on the side as a second way too confirm this, even chatterino does not recognize it.
![image](https://user-images.githubusercontent.com/25968992/28732286-4041958a-73cf-11e7-82ed-f68d1db9fc01.png)

The weird thing is BTTV extension users can see the missing emojis in their chat 
So I talked to the devs in the BTTV discord about it and they gave me this:
![image](https://user-images.githubusercontent.com/25968992/28732365-8176456e-73cf-11e7-88f2-096bfc509867.png)

Steps to reproduce: I am not sure, it happens randomly to users in the chat room I am viewing ( bttv users in all of my cases). Sometimes it seems that it does not happen at all 

![image](https://user-images.githubusercontent.com/25968992/28732652-8f531300-73d0-11e7-902a-632ab44e82eb.png)
![image](https://user-images.githubusercontent.com/25968992/28732664-9e3592d0-73d0-11e7-968f-dc0332e3c091.png)

**Comment by SirStendec** [comment]
@notheowner Alright, this isn't a bug or directly associated with the main issue here.

What you have is users not actually sending emoji. Emoji are the actual characters. They aren't like emotes that are strings that are replaced at render time. They're actual characters that are part of the unicode standard, like any other letter.

Here, people are instead sending short codes and BetterTTV is... strangely deciding to replace them. I'm not sure I can call that a bug, but it is not behavior that I would implement into FrankerFaceZ. If someone wants to send an emoji, they should type an emoji. Not rely on the client of other people to replace their nonsense with emoji.

FrankerFaceZ handles this by replacing short codes for emoji with the actual characters as you type, or if you paste text into the input box. What you're probably experiencing is a user with just BetterTTV or some other chat client trying to copy-paste the character and their client isn't replacing it correctly before emitting the message to Twitch's chat servers.

**Comment by 0x263b** [comment]
I can confirm this is happening to me too:

[![missing emoji](https://i.imgur.com/bTMIIei.png)](https://i.imgur.com/bTMIIei.png)

Just form testing I believe the issue is this [EMOJI_REGEX](https://github.com/FrankerFaceZ/FrankerFaceZ/blob/61ac0b97f6d868ffe828d190702d4c9713dc142b/src/constants.js#L103) constant is incomplete

For example, take the first line of that image `😀😃😄😆😅😂🤣☺️😊` and run it with `String.match(regexp)`:

[![String match](https://i.imgur.com/Bb9zL3K.png)](https://i.imgur.com/Bb9zL3K.png)

The emoji `🤣` isn't matched.
