### ISSUE TITLE
Nothing changed on Twitch after installed FrankerFaceZ

### ISSUE THREAD

**Issue by Yistine** [FrankerFaceZ/FrankerFaceZ#206]
**Web Browser**: Google Chrome Version 55.0.2883.87 m (64-bit)

**Do you use BetterTTV or other Twitch extensions**: No, nothing else.

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: The "Menu" button is desactivated. Gray, unclickable. Btw, the icon of FFZ upside-down dog head is also gray, maybe it's normal, Idk.

**Bug / Idea**: No matter how many times I install and reinstall the FFZ, or reload Twitch, or clear all cookies and desactivate all the other plug-in of Chrome I have, tried 2 differents PC... Nothing changed on Twitch, no customized emoji, background-color of Twitch interface is still: #fff;

**Steps to Reproduce (if Applicable)**: Just install it, that's it.

**Comment by Tester798** [comment]
After you install FFZ you can see it here:
![image](https://user-images.githubusercontent.com/8844478/28571532-f6f816ae-714b-11e7-9800-a7cb09c079bf.png)

Also when you paste some emojis in chat like `🚀` you can see them in chat like ![image](https://user-images.githubusercontent.com/8844478/28571581-2fabf2cc-714c-11e7-9341-4a1222661adb.png)

**Comment by Yistine** [comment]
Thanks for your reply. But that's the problem. I don't have this appear in my chatbox.

**Comment by Tester798** [comment]
Also in Chrome console of twitch channel page you can see messages like 
![image](https://user-images.githubusercontent.com/8844478/28571856-65d06bf2-714d-11e7-9629-6bb005295cd0.png)

Do you have something there?
If not, then you can also try to do this on chrome extensions page:
![image](https://user-images.githubusercontent.com/8844478/28571962-cd98ae16-714d-11e7-83fd-6df3a221df0b.png)
And then refresh twitch channel page and see if you have some errors collected there.

**Comment by Yistine** [comment]
I have these errors:
![1](https://user-images.githubusercontent.com/15706298/28572340-eabfc18e-7146-11e7-9931-f4c15db59957.PNG)
![2](https://user-images.githubusercontent.com/15706298/28572341-eac2611e-7146-11e7-8ba0-0c932196d1bd.PNG)

**Comment by Yistine** [comment]
Also, I don't have Collect Errors case to check even if I'm already in Developer Mode.
![capture](https://user-images.githubusercontent.com/15706298/28572406-3e0c786e-7147-11e7-8995-6a60d974fc75.PNG)

**Comment by Tester798** [comment]
Seems like "Collect errors" is available only in Chrome Canary version.
But that's ok, you have FFZ messages in console which means you have FFZ running on twitch.
Now to get logs of FFZ you can go to some channel page (not `https://www.twitch.tv/settings/profile` like on your screenshot), wait until all loaded, and type in console `ffz.paste_logs()` and after some time you will get link to the log:

![image](https://user-images.githubusercontent.com/8844478/28572727-e527cc9e-7150-11e7-9372-c70c4c6f1dab.png)

Maybe after that someone will help you after reading your logs.

**Comment by Yistine** [comment]
Everything is working properly now. Thanks!
