### ISSUE TITLE
Auto-Pause Hosted Channels [Always] not pausing

### ISSUE THREAD

**Issue by Linkviii** [FrankerFaceZ/FrankerFaceZ#21]
**Web Browser**: Firefox

**Do you use BetterTTV or other Twitch extensions**: No

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**:
Hosted channels are not being paused

**Steps to Reproduce (if Applicable)**:
Stream ends and hosts a live channel

**Comment by SirStendec** [comment]
The old code probably needs to be completely rewritten for this to function after the channel redesign significantly changes how the players work by re-using players. In fact, all FFZ code referencing players needs to be rewritten.

For now, just disable hosting mode to avoid getting blasted. :-/

**Comment by Linkviii** [comment]
All streams are paused on load now. You know? I'm ok with this. I bet it will pause the homepage too! (nope)

**Comment by SirStendec** [comment]
Automatically pausing hosts is impossible with how the player is designed right now. I might add an auto-mute feature if I can get that working, but for now I'm just removing the option and closing this issue.
