### ISSUE TITLE
[Feature Request] Play/Pause by clicking on video area

### ISSUE THREAD

**Issue by blaenk** [FrankerFaceZ/FrankerFaceZ#210]
I'm referring to the similar feature in other players such as YouTube's.

I often watch VODs at a very leisurely pace, pausing liberally and resuming whenever I have a chance, and it's annoying to hunt down the little play/pause button each time.

Care would need to be taken to avoid colliding with the player buttons at the bottom, i.e. preventing them from being clicked or making it more difficult to click on them. Perhaps if it were possible to specify the rectangular area consisting of the player area, except for the player buttons at the bottom, as the event target.

It looks like there's a separate div that contains the player buttons, with the classes `player-hover player-controls-bottom`, in case that helps at all to differentiate.

**Comment by bottleblue** [comment]
No progress on this in almost 5 years?

**Comment by mod098** [comment]
any update on this underrated feature?

**Comment by mod098** [comment]
this feature is now available on latest update #1279
