### ISSUE TITLE
Provide WebExtension for Firefox

### ISSUE THREAD

**Issue by AstralStorm** [FrankerFaceZ/FrankerFaceZ#211]
Please provide a WebExtension version of FrankerfaceZ for Firefox.
It seems that "foxified" version of the Chrome extension via "Chrome Store Foxified" works fine when the legacy one no longer does.

Alternatively it's just that legacy Firefox extension is outdated - version 1.57 as opposed to 1.56.

**Comment by MeatyChunks** [comment]
Heads up that Firefox 57 completely turns this off as it's considered Legacy now. :(

**Comment by haganbmj** [comment]
More details on Firefox 57
https://support.mozilla.org/en-US/kb/firefox-add-technology-modernizing

**Comment by furai** [comment]
I'm using latest beta - FFZ don't work on it anymore. It's considered a legacy extension. The current firefox will hit mainstream in few months. Might be a good time to support new firefox now when people still didn't get the update.

**Comment by MegamanXtreme** [comment]
I'm using Violent Monkey and the FFZ script. It works but it won't save my settings, so I have to reload them every time I restart my browser, and how Twitch is a memory-leaking hog, I have to restart my browser countless of times per day. This is annoying to say the least.

**Comment by SirStendec** [comment]
@MegamanXtreme FrankerFaceZ stores your settings in localStorage on Twitch's domain. Using the user script or using the extension works the same in that regard. Your problem is caused by browser settings or an extension clearing your local storage.

**Comment by MegamanXtreme** [comment]
@SirStendec Correct, I disabled "Clear Offline Website Data." Odd that it doesn't affect Twitch on Firefox 56 with the setting on, but it does on 57. Nonetheless, thank you for the information, now I won't worry.

Looking forward for the add-on. :) 👍
