### ISSUE TITLE
[Feature Request] Transparent chat overlay in theatre mode

### ISSUE THREAD

**Issue by eps0003** [FrankerFaceZ/FrankerFaceZ#212]
**Web Browser**: Chrome

**Do you use BetterTTV or other Twitch extensions**: FFZ with addon pack

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: N/A

**Bug / Idea**: I'm suggesting a button on the hover controls to toggle a transparent chat overlay when in theatre mode.

**Steps to Reproduce (if Applicable)**: N/A

**Comment by HDMethos** [comment]
Indeed, transparent chat option would be great!
