### ISSUE TITLE
My emotes won't show up in someone else's stream. Only on mine. Emotes are also not showing up in "My Emoticons."

### ISSUE THREAD

**Issue by plankboii** [FrankerFaceZ/FrankerFaceZ#215]
**Web Browser**:
Google Chrome
**Do you use BetterTTV or other Twitch extensions**:
No
**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:
Invalid language: log
FrankerFaceZ - Debugging Information
2017-08-07T05:08:18.921Z

Navigator
----------------------------------------
User Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
Screen Size: 1920x1080 24bpp 1x DPI
Flash Version: not found

Version Breakdown
----------------------------------------
Ember: 2.14.0
Ember Data: 2.14.3
GIT Version: 

FrankerFaceZ: 3.5.507

WS Client Status
----------------------------------------
Client ID: not set
Socket Server: wss://andknuckles.frankerfacez.com/
Server Ping: unknown
Time Offset: unknown

Logviewer Status
----------------------------------------
Authentication: succeeded
Token Expires: 8/8/2017, 1:08:13 AM
Socket Server: disconnected
Socket Topics: no topics
Current Room: conkerhax
Logging Enabled: loading

Twitch Configuration
----------------------------------------
Deploy Flavor: production
Current User: plankboii [56827737]
User State: broadcaster, premium, turbo, verified
Region: US
Received Language: en

Twitch Experiments
----------------------------------------
TWILIGHT_UPSELL: control
LOGGED_OUT_FRONT_PAGE_EXPERIMENT: localizeTopChannelsOnly
FRONT_PAGE_SIGNUP_EXPERIMENT: control
VODS_IN_CAROUSEL_EXPERIMENT: control
DETERMINATION: yes
AKAMAI_IMAGE_MANAGER: experiment
GAME_FOLLOW_ONBOARD: control
LATENCY_COMPONENT_INSTRUMENTATION: control
SOCIAL_RECOMMENDATIONS: control
AUTOMOD_SMALLER: yes
MESSAGE_HISTORY: off
ZACH_MODE: control
CHAT_RULES_EXPERIMENT: rules_v2
RESUME_WATCHING_BANNER: yes
OFFLINE_RECOMMENDATIONS: yes
OFFLINE_EXPERIENCE: show
LTV: yes
MEDIAPLAYER_BACKEND_SELECT: no
NEXUS_ROLLOUT: disabled

Memory Statistics
----------------------------------------
jsHeapSizeLimit: 2.0 Gb (2190000000)
totalJSHeapSize: 159.3 Mb (167000000)
usedJSHeapSize: 141.1 Mb (148000000)

Player Statistics
----------------------------------------
backend: player-core
bandwidth: 2592.9077786532316
broadcast_id: 25948369440
cluster: jfk03
current_bitrate: 2592.9077786532316
current_fps: 30
current_fps_exact: 30
dropped_frames: 18
hls_latency_broadcaster: 9611
hls_latency_encoder: 7611
hls_target_duration: 5
manifest_cluster: jfk03
manifest_node: video-edge-913afc.jfk03
manifest_node_type: legacyplus
node: video-edge-913afc.jfk03
paused: false
playing: true
segment_protocol: https
serving_id: b3575e5ff6a642ec9137fb57e0cdb827
stream_time: 291.70675
stream_time_offset: 40.4487769604
totalMemoryNumber: 64
version: 1.8.11-ce18d4e
vid_display_height: 720
vid_display_width: 1280
vid_height: 720
vid_width: 1280
video_buffer_size: 4.293249000000003
vod_cdn_origin: 
vod_cdn_region: 
volume: 0.5

Current Settings
----------------------------------------
{
  "global_emotes_in_menu": true
}

Logs
----------------------------------------
Loading settings.
Found Twitch application after 0 ms at: https://www.twitch.tv/conkerhax
Initializing FrankerFaceZ version 3.5.507
Injecting main FrankerFaceZ CSS.
Readying toggleable styles.
Installing mouse-up event to auto-close pop-ups.
Using Socket Server: wss://andknuckles.frankerfacez.com/ [1:1]
Preparing emoticon system.
Creating emoticon style element.
Generating CSS for existing API emoticon sets.
Loading global emote sets.
Loading emoji data.
Preparing badge system.
Creating badge style element.
Generating CSS for existing API badges.
Generating CSS for existing Twitch badges.
Loading badges.
Hooking the Ember router.
Loading Twitch Emote Data (Try 0)
Hooking Ember chat line helpers.
Creating channel style element.
Hooking the Ember Channel Index redesign.
Hooking the Ember Channel controller.
Creating room style element.
Hooking the Ember Chat PubSub service.
Hooking the Ember Room controller.
Hooking the Ember Room model.
Adding Room: conkerhax
Hooking the Ember Channel Subscriptions service.
Creating layout style element.
Hooking the Ember service:layout
Hooking the Ember Chat controller.
Hooking the Ember Chat Room Manager component.
Hooking the Ember from-display-preview component.
Listening to the Settings controller to catch mod icon state changes.
Modifying Mousetrap stopCallback so we can catch ESC.
Hooking the Ember Moderation Card view.
Hooking the Ember Chat Input component.
Hooking the Ember Directory views.
Updating Ember classes and instances.
Updated 0 existing instances across 1 classes.
Attempting to modify the Following collection.
Error: Unable to locate the Ember component:twitch-navigation [undefined]
Error: Unable to locate the Ember component:recommended-channels [undefined]
Adding event handler for window focus.
Initializing following support.
Connecting to Live Streams model.
Initializing race support.
Updating Ember classes and instances.
Updated 17 existing instances across 43 classes.
Modifying Tipsy-Tooltip component to use gravity.
Fixing already existing tooltips.
Listening for Window Messages.
Checking for Feature Friday data...
Initialization complete in 459ms
Socket Connected.
App Path: user.channel.index.index
Adding Room: plankboii
Updated emoticons for set #3: Global Emoticons
Updated emoticons for set #4330: : Sten's Cheaty Emotes
Added ": Sten's Cheaty Emotes" emote set to 1 users.
Updated emoticons for set #112342: Channel: ConkerHax
Added "developer" badge to 2 users.
Added "bot" badge to 121 users.
Added "supporter" badge to 7,461 users.
Loaded 7,584 total badges across 3 types.
Loaded data on 1774 emoji.
Error Saying Hello: Error: Expected array of string, string as arguments.
Adding Room: _thelakmus_1425848862753
Updated emoticons for set #143238: Channel: plankboii
Updated emoticons for set #131168: Group Chat: CS:GO
Loaded Twitch Emote Data
BetterTTV was not detected after 60 seconds.
Emote Menu for Twitch was not detected after 60 seconds.
Changed Setting "advanced_settings" to: false

**Bug / Idea**:

**Steps to Reproduce (if Applicable)**:
-Type in created emote in other streamer's chat
-Go to "My Emoticons"

**Comment by SirStendec** [comment]
It sounds from your report like you have a misconception about what FrankerFaceZ does.

When you add emotes to your channel, those are only available in your channel. They aren't global emotes that you can use anywhere on Twitch.
