### ISSUE TITLE
Supporter Badge not showing

### ISSUE THREAD

**Issue by sktdh** [FrankerFaceZ/FrankerFaceZ#216]
**Web Browser**: Chrome

**Do you use BetterTTV or other Twitch extensions**: BTTV 

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**:  Purchased $5 donation and supporter badge not showing.  twitch username sktdh

**Steps to Reproduce (if Applicable)**:

**Comment by SirStendec** [comment]
Your badge is in the system just fine. However, FFZ badges don't show up in the client immediately. It can take up to half an hour and a page refresh to make new badges appear with how they're currently implemented. You'll just need a bit of patience, or maybe a hard refresh. (Ctrl-F5)

Thanks for your support!
