### ISSUE TITLE
[Feature request] New Notification sound (Get Schwifty)

### ISSUE THREAD

**Issue by Sliger1337** [FrankerFaceZ/FrankerFaceZ#217]
**Web Browser**: Chrome

**Do you use BetterTTV or other Twitch extensions**: Used to.

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: Not Applicable

**Bug / Idea**: Add notification sound. Get Schwifty!!! Get Schwifty in here!! (Rick and Morty)

**Steps to Reproduce (if Applicable)**: Not Applicable

**Comment by SirStendec** [comment]
Notification sounds is a feature of the FFZ Add-on Pack, not FFZ itself. Lordmau5 has stated that custom notification sounds will be added soon, so you can just wait on that, or maybe open the issue directly with FFZ:AP.

**Comment by Sliger1337** [comment]
My bad ma dude! Thanks! :D
