### ISSUE TITLE
Bits appear as plaintext

### ISSUE THREAD

**Issue by PenguinOfLight** [FrankerFaceZ/FrankerFaceZ#219]
**Web Browser**:
Chrome 60.0.3112.90

**Do you use BetterTTV or other Twitch extensions**:
I use FFZ:AP, but the issue persists if FFZ is run standalone with all other extensions removed.

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:
http://putco.de/NjUzNg.log

**Bug / Idea**:
With FrankerFaceZ, currently bits appear as plain text, instead of being parsed into the animated gifs they usually do.

**Comment by av798902** [comment]
@PenguinOfLight The fix came quick. The dev took care of it in version 3.5.511

**Comment by PenguinOfLight** [comment]
Fixed as of 3.5.511
