### ISSUE TITLE
Use Chrome Sync for settings

### ISSUE THREAD

**Issue by Nodebuck** [FrankerFaceZ/FrankerFaceZ#220]
**Web Browser**: Google Chrome 60

**Do you use BetterTTV or other Twitch extensions**: No

**Bug / Idea**:

Use [Chrome Sync](https://developer.chrome.com/extensions/storage#property-sync) for settings to be automatically synced across devices.

**Comment by Tester798** [comment]
Yes, would be nice to see this option in FFZ.

**Comment by SirStendec** [comment]
Merging into #239
