### ISSUE TITLE
Non working emotes

### ISSUE THREAD

**Issue by Theoneandonlymauler** [FrankerFaceZ/FrankerFaceZ#221]
**Web Browser**:Chrome

**Do you use BetterTTV or other Twitch extensions**: Uninstalled BTTV

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**:
Some emotes not working or showing up IE. Feelsbadman and ones like it. And moving emotes like Sourpls, rare***** etc.. Sorry if this was already brought up i couldnt find anything,

**Steps to Reproduce (if Applicable)**:
N/A

**Comment by SirStendec** [comment]
Those emotes are part of BetterTTV and not supported directly by FrankerFaceZ.

That said, support for those is provided by another extension called the FFZ Add-on Pack. You can find more on that at https://ffzap.download/

**Comment by Theoneandonlymauler** [comment]
WOW!! Thank you for your fast response!!!! Glad I changed and donated to this great add on!!
