### ISSUE TITLE
([FFZ:AP] Highlight / Mention Sound) and (Highlight Users) settings overlap

### ISSUE THREAD

**Issue by Imand000** [FrankerFaceZ/FrankerFaceZ#225]
**Web Browser**: 
Chrome

**Do you use BetterTTV or other Twitch extensions**:

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:
http://putco.de/NjY3MQ.log

**Bug / Idea**:
when i turned the **Highlight / Mention Sound** setting on it kept playing the sound when someone from my **Highlighted Users** list typed in chat. 
I tried putting them in the **Highlight / Mention Sound Blacklist** but that's for channels only and i want it to play only when my **Username** or **Highlighted Keywords** are mentioned 

**Steps to Reproduce (if Applicable)**:

**Comment by SirStendec** [comment]
This is something that should be handled by FFZ:AP and not an FFZ issue.
