### ISSUE TITLE
Auto Theater Mode still broken

### ISSUE THREAD

**Issue by CArchetype** [FrankerFaceZ/FrankerFaceZ#23]
**Web Browser**: Firefox 49.0.1

**Do you use BetterTTV or other Twitch extensions**: BTTV4FFZ

**Bug / Idea**: Auto Theater Mode still not working (FFZ 3.5.314)

**Steps to Reproduce (if Applicable)**: load any stream, exit theater mode. refresh the page, it doesn't go back in to theater mode.

**Comment by coleslaw121** [comment]
Also facing the same issue in chrome
