### ISSUE TITLE
[Feature Request] see mod actions without being mod

### ISSUE THREAD

**Issue by TheSqrtMinus1** [FrankerFaceZ/FrankerFaceZ#246]
**Web Browser**:
chrome canary 
**Do you use BetterTTV or other Twitch extensions**:
no

**Bug / Idea**:
add the ability to see which mod did what action in chat when you're not a mod of that chat

is this possible? i dont know, but it'd be really heckin cool if you could implement it

**Comment by SirStendec** [comment]
This is definitely not going to happen. From the technical side of things, it's not possible as Twitch does not send the necessary events to clients that aren't moderators.

From the non-technical side of things, it's a terrible idea. The sort of people who get banned in Twitch chats are not the sort of people who should see who banned them. People harass moderators enough without having access to that sort of thing.
