### ISSUE TITLE
FFZ not working in VODs

### ISSUE THREAD

**Issue by RichardMisencik** [FrankerFaceZ/FrankerFaceZ#254]
**Web Browser**: Chrome

**Do you use BetterTTV or other Twitch extensions**: The FFZ Add-On Pack

**Bug / Idea**:
FFZ chat is not loading at all when watching a VOD. Instead the default twitch chat is shown with the new feature  to post in chat at current time

**Comment by Karpfador** [comment]
And joining the chat room to get it to load also does not work anymore. Please fix this as soon as possible, as some chats rely on FFZ a lot

**Comment by Karpfador** [comment]
Which includes the "old" Twitch. Not just the beta version

**Comment by sparcut** [comment]
See #241 and #218
