### ISSUE TITLE
Refresh Stream Button Gone?

### ISSUE THREAD

**Issue by Dave1456** [FrankerFaceZ/FrankerFaceZ#256]
**Web Browser**: Chrome

**Do you use BetterTTV or other Twitch extensions**: No

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: 

**Bug / Idea**: The refresh stream button seems to have disappeared.

**Steps to Reproduce (if Applicable)**: ^

**Comment by lbux** [comment]
Gone on my end too.

Doesn't work on Edge either, clean install of FFZ and no other extensions running.

**Comment by maddawg836** [comment]
I use BTTV with FFZ and my button has disappeared also. I think it was there earlier today but not anymore

**Comment by lbux** [comment]
[Button](https://i.imgur.com/BbRiwQj.png) is back for me.

**Comment by Dave1456** [comment]
Back here as well.
