### ISSUE TITLE
SRL Race Info Gone

### ISSUE THREAD

**Issue by Lebon14** [FrankerFaceZ/FrankerFaceZ#257]
**Web Browser**: Firefox 56.0.1

**Do you use BetterTTV or other Twitch extensions**: Yes

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: Can't find this setting.

**Bug / Idea**:
I was watching s treamer (RaikouRider) stream a SRL race of The Legend Of Zelda 1 Randomizer. The race in question: http://www.speedrunslive.com/race/?id=1hki0
However, the SRL menu was not below the stream when the race was active.

**Steps to Reproduce (if Applicable)**:
Just watch a streamer in a SRL race and check if the SRL menu is there or not. Probably not.

Thanks in advance.

**Comment by LillieSatou** [comment]
Remove BTTV. IF you use FFZ through the Tampermonkey extension, remove that as well & get the standalone extension.

NOTE: Even though it's there in that version, it doesn't properly fetch data from SRL!
![Proof that it's there and it's bugged](https://user-images.githubusercontent.com/31103855/31597472-593d380c-b1fd-11e7-9628-2d2325938292.png)

Both it and the FFZAP standalone addon are marked as legacy.

**Comment by Lebon14** [comment]
I use the standalone FFZ; using 1.56.0 (I checked and it's the last version). For a while, it was borked like you shown.

And I want my LuL and SourPls :( Even if I remove that, it's still broken anyway.

**Comment by riking** [comment]
There was several bug with the SRL race info fetcher. That's probably what you saw.
