### ISSUE TITLE
[Feature Request] Colored "transparent" badges

### ISSUE THREAD

**Issue by Jihkie** [FrankerFaceZ/FrankerFaceZ#26]
**Web Browser**:

**Do you use BetterTTV or other Twitch extensions**:

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**:
A badge style like the transparent badges, except the shapes are colored like their respective backgrounds (e.g. green sword shape for mod). Example: ![image](https://cloud.githubusercontent.com/assets/18361844/19135285/58057394-8b18-11e6-9602-d6c1d91c8a4f.png)

**Steps to Reproduce (if Applicable)**:

**Comment by SirStendec** [comment]
This is something I've wanted to add in the past, but never got around to it because of limitations in browsers. I think I might be able to pull it off with what I know of CSS now. I'll take a look at it.

**Comment by SirStendec** [comment]
(Just a note, this will only be accessible for users with Chrome. Firefox doesn't yet support the necessary CSS to make it work.)
