### ISSUE TITLE
My Supporter Badge Won't Show Up.

### ISSUE THREAD

**Issue by welkerville** [FrankerFaceZ/FrankerFaceZ#262]
**Web Browser**: Google Chrome

**Do you use BetterTTV or other Twitch extensions**: No

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**: My Supporter Badge Won't Show Up.

**Steps to Reproduce (if Applicable)**:

Why won't my supporter badge show up? I bought a $5 donation and I can see the FrankerFaceZ icon in chat, but I'm not able to use the emoticons i downloaded either... does this take time to authenticate? Or is it a bug?

**Comment by yashendra2797** [comment]
What extensions do you have? Any adblock? Maybe Privacy Badger?
