### ISSUE TITLE
[Feature Request] Whisper Sound

### ISSUE THREAD

**Issue by githubuser110** [FrankerFaceZ/FrankerFaceZ#264]
**Web Browser**: Chrome (64bit) Version 62.0.3202.62

**Do you use BetterTTV or other Twitch extensions**: FFZ+FFZ Addon Pack

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**:
I would like to have an option to hear a sound when people are whispering me, sometimes when I get a message I don't notice it quick enough and people go offline. 

**Steps to Reproduce (if Applicable)**:

**Comment by SirStendec** [comment]
Moving to #299
