### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by sparcut** [FrankerFaceZ/FrankerFaceZ#266]
@SirStendec, have you abandoned this and was it because of the move to react?

**Comment by Lordmau5** [comment]
Stendec's been very active on Twitter in regards to the FFZ rewrite for the Twitch Beta.
That's why there haven't been any changes on this repository lately :)

**Comment by SirStendec** [comment]
I've been working on FrankerFaceZ with the majority of my time for weeks. I've also been tweeting about it ([@SirStendec](https://twitter.com/sirstendec)) somewhat.

The work I'm doing currently is a full rewrite and I won't be doing any commits to this repository until it's ready for an initial release.
