### ISSUE TITLE
FFZ is enabled but does not load on twitch.tv

### ISSUE THREAD

**Issue by EeveeEmma** [FrankerFaceZ/FrankerFaceZ#268]
**Web Browser**: Chrome Version 61.0.3163.100 (Official Build) (64-bit)

**Do you use BetterTTV or other Twitch extensions**: FFZ add-on pack

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: Inaccessible

**Bug / Idea**: FFZ does not appear to load on any twitch.tv stream (not go.twitch.tv). I've tried disabling and re-enabling the extension and restarting my browser, but it still doesn't work.

**Steps to Reproduce (if Applicable)**: Visit any stream

I wonder if Twitch is starting to push beta stuff?

**Comment by hareluuu** [comment]
Same happening to me as of this morning. Last night it worked fine. Tried disabling/enabling, restarting, uninstalling and it still doesn't load.

Browser: Chromium Version 62.0.3202.75 (Developer Build) (64-bit) on Linux
Logs: Can't access them

**Comment by EeveeEmma** [comment]
Update: it's working again?

**Comment by hareluuu** [comment]
Yep, working for me too. Well, that was weird, but glad it sorted itself out

**Comment by ktran-1** [comment]
yes it happens to me, some times when im clicking a new tab for twitch, it will load and sometimes it doesnt.
