### ISSUE TITLE
Firefox 57 Quantum support?

### ISSUE THREAD

**Issue by rhazor** [FrankerFaceZ/FrankerFaceZ#269]
**Web Browser**: 57.0b12 (64-bit)

**Do you use BetterTTV or other Twitch extensions**: 
Yes and BTTV supports it.

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:
Not needed.

**Bug / Idea**:
Add support for new Firefox addon engine.

**Steps to Reproduce (if Applicable)**:
Install Firefox Quantum beta. https://www.mozilla.org/en-US/firefox/quantum/

**Comment by lbux** [comment]
For now, you can use ViolentMonkey and install the user script version of FFZ. (Tampermonkey seems to now support Firefox 57 but they say there might still be some incompatibilities, choice is yours)

**Comment by rhazor** [comment]
solved
