### ISSUE TITLE
[Feature Request] Pin highlighted words to top of chat for a few moments.

### ISSUE THREAD

**Issue by patq911** [FrankerFaceZ/FrankerFaceZ#270]
**Web Browser**:
Chrome

**Do you use BetterTTV or other Twitch extensions**:
Recently switched to FFZ only.

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**:
Pin higlighted keywords/usernames to top of chat for 

I don't constantly look at the chat and in a fast chat messages go by so fast that sometimes I don't see if someone @ me.

I've looked through the advanced settings and didn't see anyhting like this, but please tell me if i'm wrong.

**Steps to Reproduce (if Applicable)**:

**Comment by SirStendec** [comment]
Moving to #299

**Comment by ir2000** [comment]
@root-reindeer-flotilla there is an addon
![image](https://github.com/user-attachments/assets/d352b226-594c-4d75-ac8b-6332bfded39f)
![image](https://github.com/user-attachments/assets/a6e7820f-d290-41d8-8d27-bd947531d473)
