### ISSUE TITLE
Banned word regex not working

### ISSUE THREAD

**Issue by nkamenar** [FrankerFaceZ/FrankerFaceZ#272]
**Web Browser**:
Chrome (latest version)
**Do you use BetterTTV or other Twitch extensions**:
FFZ and FFZ addon pack
**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**:
Messages starting with ! not removed as they should be from regex banned word

**Steps to Reproduce (if Applicable)**:
1. Configure banned words to be removed
2.Add "^!.\*$" as a banned word (also tried "!.\*" and "^!")

Expected Result: Any message starting with ! character should be removed and not display in chat.

Actual Restult: Regex banned word appears to have no effect and messages display.

**Comment by Nightfirecat** [comment]
Wouldn't that regex only ban two-character messages where the first is an exclamation mark? `!w` for example? You'd need it to be `^!.+$` to match messages of any length.

**Comment by nkamenar** [comment]
Sorry I didn't realize the \* character needed to be escaped in this editor, so it was being hidden. Edited to show the correct regex expressions I have tried.

**Comment by SirStendec** [comment]
Moving to #299
