### ISSUE TITLE
Extension fail to update in Firefox 56

### ISSUE THREAD

**Issue by CoolCmd** [FrankerFaceZ/FrankerFaceZ#275]
Navigate to `about:addons`. Click `check for updates`. Open the browser console (ctrl+shift+j). You should see error message:
> 13:53:45.916 1510484025915	addons.xpi	WARN	Download of https://cdn.frankerfacez.com/script/frankerfacez-4.0-an+fx.xpi failed: Refusing to upgrade addon jid1-snHdAu6px3p0jA@jetpack to different ID frankerfacez@frankerfacez.com

**Comment by Lonsfor** [comment]
https://twitter.com/FrankerFaceZ/status/929071832073953280

remove the addon and install it again.

**Comment by CoolCmd** [comment]
> remove the addon and install it again.
Isn't it easier to leave the old identifier?

**Comment by Aaronf9** [comment]
CoolCmd is there a way i can get in touch with you? or will you ever put twitch 5 back on chrome?
