### ISSUE TITLE
Legacy site is constantly reloading with FFZ extension

### ISSUE THREAD

**Issue by jnki** [FrankerFaceZ/FrankerFaceZ#282]
**Web Browser**: Vivaldi

**Do you use BetterTTV or other Twitch extensions**: FFZ:AP tampermonkey script

**Bug**:  When FFZ extension is enabled in twitch Legacy site, the page is constantly reloading.
If I disable the FFZ extension, it loads fine.
twitch beta site works fine with extention enabled

**Comment by SirStendec** [comment]
Can you open your browser's console and check for any kind of logging messages that might indicate why this is happening? You might need to open the log settings:
![image](https://user-images.githubusercontent.com/14036657/32758286-a3856054-c8b1-11e7-9b92-40c352796a4a.png)

And then enable Preserve Log to stop it from clearing messages every time it reloads.

**Comment by jnki** [comment]
Seems to be loading just fine now!
Very strange since it was doing it for over an hour.

I'll make sure to grab the console log if it starts up again.

Thanks!
