### ISSUE TITLE
Setting modal missing bottom of main pane background

### ISSUE THREAD

**Issue by Nightfirecat** [FrankerFaceZ/FrankerFaceZ#283]
**Web Browser**: Firefox 56.0.2

**Do you use BetterTTV or other Twitch extensions**: Yes (but might not work with new Twitch?); The FrankerFacez Addon Pack, via GreaseMonkey

**Bug / Idea**: Settings modal's right (main) pane's background does not cover the full height of the window.

![Missing background to cover bottom of settings modal](https://i.imgur.com/q3hQvng.png)

**Steps to Reproduce (if Applicable)**: N/A

**Comment by SirStendec** [comment]
Fixed by bb26260e23264955655425b487ef7ad35e37eb74
