### ISSUE TITLE
[Suggestion] Most needed features IMO

### ISSUE THREAD

**Issue by S1CkDuD3** [FrankerFaceZ/FrankerFaceZ#285]
I think the 2 next big features you should be working on now are:
1) To make the BTTV (and other) emotes work with FFZ and
2) make all the info you had, like the Delay your stream has, to be displayed in theater mode again, sometimes my stream buffers and I need to know how many seconds far back the stream i am watching is, so I can refresh.

Thanks if you do so!

**Comment by SirStendec** [comment]
BTTV support is provided by FFZ: Addon Pack and we are working with the developer to get things working again. It should be fixed within the week.

The other feature is also something that we'll be supporting again, if possible. It's low priority, so I wouldn't expect it until more important features are in and working.

**Comment by S1CkDuD3** [comment]
I already have the FFZ: AddOn Pack installed, so I am ready to go. I hope the emotes will work within this week, keep up the good work 👍 
I see, as long as it eventually happens It's OK, i am sure it is useful for other viewers too
