### ISSUE TITLE
Alternating chat background doesn't 'scroll' with chat

### ISSUE THREAD

**Issue by Dgc2002** [FrankerFaceZ/FrankerFaceZ#287]
**Web Browser**: Chrome 62

**Do you use BetterTTV or other Twitch extensions**: No

**Bug / Idea**:  
Currently the alternating background colors don't scroll with chat. They seem to color a set message position. So an example would be that the newest message will always be dark, and the second newest will always be light, etc.  
  
This isn't 100% consistent though, sometimes the order switches. I've seen this happen when chat stops entirely for a second, so it doesn't seem directly tied to new chat messages.     
  
[Here](https://gfycat.com/MeagerInbornBoaconstrictor) is a video of what I'm seeing.

**Comment by SirStendec** [comment]
Fixed in 10c6c1cb87e6caa59cac1b0ada22128e488adb57
