### ISSUE TITLE
Twitch prime emotes display two emotes in chat

### ISSUE THREAD

**Issue by jnki** [FrankerFaceZ/FrankerFaceZ#289]
**Web Browser**: Vivaldi

**Do you use BetterTTV or other Twitch extensions**: FFZ:AP tampermonkey script

**Bug**:
If you have twitch prime and have the alternate emote set enabled, it will post both versions of the emote into chat.
Seems to be client side, nobody else sees the first emote.

![image](https://user-images.githubusercontent.com/17442109/32814470-4b8ce178-c9a7-11e7-8e14-95a55816d217.png)
![image](https://user-images.githubusercontent.com/17442109/32814475-5659693c-c9a7-11e7-86a1-2c9369d8a29c.png)

**Reproduce**:

1. Have alternate emote set enabled
2. go into chat and type a smiley :)

Expected: One emote posted
Actually: Both emote posted.

**Notes** using FFZ 4.0.0-beta1.3 on twitch rewrite

**Comment by SirStendec** [comment]
Fixed in 2c28afc6a6424df2ababfae3026cc4205fe422f6
