### ISSUE TITLE
Whisper window covers Twitch follow/subscribe buttons

### ISSUE THREAD

**Issue by Devexer** [FrankerFaceZ/FrankerFaceZ#29]
**Web Browser**: Opera 40.0.2308.81

**Do you use BetterTTV or other Twitch extensions**: No

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: No need here I guess.

**Bug / Idea**: 
Having the whisper window docked to the top of the screen now covers the follow/subscribe button with the new Twitch layout. See images:

![6f80930c-aed1-4dc1-9fd7-60ab17e2100d](https://cloud.githubusercontent.com/assets/15696189/19187906/8b71a208-8c8e-11e6-9ceb-7bd922b54f31.png)

![801aeb2e-2e60-4c1e-9bbb-76f5b3af3eea](https://cloud.githubusercontent.com/assets/15696189/19187909/8dcfea8c-8c8e-11e6-9040-fd4ae887b3b9.png)

**Steps to Reproduce (if Applicable)**: Open any channel.

**Comment by Devexer** [comment]
@LawlyPopz I know of this setting, but then it covers a **small** part of the stream in top right. I know it's no big deal, but figured it couldn't be to much work on changing the offset of where the button is placed.

**Comment by SirStendec** [comment]
This is an issue, but there's no elegant way to solve the problem. For now, all I can say is avoid sticking them both at one side.
