### ISSUE TITLE
Reinsert chatroom selector menu

### ISSUE THREAD

**Issue by olems** [FrankerFaceZ/FrankerFaceZ#291]
**Web Browser**:
Chrome
**Do you use BetterTTV or other Twitch extensions**:
Twitch 5
**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**:
The new twitch website quietly removed the chatroom selection button in the chatroom header. Could it be possible to have an option in FFZ to reinsert this menu for the probably 5 people who use group chat?

**Steps to Reproduce (if Applicable)**:

**Comment by SirStendec** [comment]
Not really, no. Group chat is going away, replaced with Rooms which aren't live yet. I will eventually be adding multiple chat room support to FFZv4 but it's hilariously far away on the priority / complexity list.
