### ISSUE TITLE
Stream uptime randomly show or not shown

### ISSUE THREAD

**Issue by ChaosPaladin** [FrankerFaceZ/FrankerFaceZ#292]
**Web Browser**:
Opera 49.0.2725.34 (PGO)

**Do you use BetterTTV or other Twitch extensions**:
BetterTTV + FrankerFaceZ

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**:
Any time after opening channel with working stream, randomly shown stream uptime or not shown, more times its not shown (~90% not shown)

**Steps to Reproduce (if Applicable)**:
Open stream channel, reload page (wia F5)? Only this steps find for now.

**Comment by Lonsfor** [comment]
can confirm that this also happens in firefox 56 with no other Twitch extensions

**Comment by Doorstop2** [comment]
same sometimes it shows sometimes it dosn't 

Firefox 57

**Comment by neris** [comment]
The same thing in Google Chrome Version 61.0.3163.100 (Official Build) (64-bit)

**Comment by ChaosPaladin** [comment]
Solved for me.
