### ISSUE TITLE
Freeze Chat Scrolling causing chat to stop scrolling automatically regardless of frozen chat state.

### ISSUE THREAD

**Issue by winneon** [FrankerFaceZ/FrankerFaceZ#295]
**Web Browser**: Firefox 57.0 Stable

**Do you use BetterTTV or other Twitch extensions**: No.

**Bug / Idea**:

When using the Freeze Chat Scrolling feature, and you scroll up in the chat, after pressing "More messages below" the chat will eventually stop scrolling automatically even if you are scrolled all the way down and are not hovering over the chat.

**Steps to Reproduce (if Applicable)**:

1. Enable Freeze Chat Scrolling. I use On Hover.
2. Scroll up in the chat a little bit and then press "More messages below" at the bottom to scroll to the bottom of chat.
3. The chat should become unsynced and will stop scrolling automatically. If this does not happen repeat the previous step a few times. I found it happens after doing it more than once.

**Comment by SirStendec** [comment]
I still cannot reproduce this issue, using either Chrome or Firefox and with any combination of settings. Can you try replicating the problem without FFZ enabled? It might be an issue with Twitch's built-in chat scrolling code.

**Comment by winneon** [comment]
The problem does not happen when the feature is not enabled in FFZ though, so how would I even go about testing it in a default Twitch environment?

**Comment by winneon** [comment]
Strange, now I cannot seem to reproduce it. Perhaps that wasn't the trigger after all. I'm going to close this for now until I find the trigger for it, and then I'll update the issue so you can more easily reproduce it.

**Comment by SirStendec** [comment]
Referencing this for #298. People are still having issues.
