### ISSUE TITLE
Chat scroll freeze feature does not work on firefox 57 

### ISSUE THREAD

**Issue by Doorstop2** [FrankerFaceZ/FrankerFaceZ#297]
**Web Browser**: Firefox 57 

**Do you use BetterTTV or other Twitch extensions**: BTTV

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**: When attempting to use the freeze chat feature chat does not stop/freeze  

**Steps to Reproduce (if Applicable)**: Enable the freeze chat feature it will say its "paused" but it does nothing 
![2017-11-15_17-02-39](https://user-images.githubusercontent.com/26550104/32863337-1d3db158-ca29-11e7-83e0-299f28f9d2d6.gif)

**Comment by SirStendec** [comment]
I have made a new issue to consolidate chat scrolling bugs. #298
