### ISSUE TITLE
Chat Scrolling Mega Issue

### ISSUE THREAD

**Issue by SirStendec** [FrankerFaceZ/FrankerFaceZ#298]
If you are having problems related to chat scrolling, please comment on this issue to keep everything contained in one spot. Please include:

* Your Browser
* Your FFZ Version (from the FFZ Control Center, including the build string on the next line)
* Whether or not you use BetterTTV
* Whether or not you use any other extensions on Twitch

There are two different issues that most people are having. Either:

1. Chat is freezing and then refusing to start scrolling again.
2. Chat *should* be frozen but it is continuing to scroll.

Because of the very limited changes FFZ makes to the chat scrolling system at this time, I'm not convinced that FFZ is at fault, but clearly we need more data on the issue. Thanks.

**Comment by winneon** [comment]
**Browser:** Firefox 57.0 & Chrome 61.0.3163.100, both on Windows 10 x64
**FFZ Version:** FFZ 4.0.0-beta1.3 f855394a01c28a59836c
**BetterTTV:** No.
**Other extensions:** None.

After a certain amount of time in a high-velocity chat room (I'm not sure how long, it's a few minutes at least), the chat no longer automatically scrolls when a new message is received. This is the first bug I have experienced today, and it occurs on both browsers I listed above.

When the "Freeze Chat Scrolling" option is enabled, chat continues to scroll even when holding down the trigger for the option, whether it be a mouse hover or a keypress. This only occurs in Firefox. It does not appear to happen when Chrome is used.

**Comment by Jacky1356400** [comment]
**Your Browser**: Google Chrome 62.0.3202.94 (Windows 10 64 bit)
**Your FFZ Version**: 4.0.0-beta1.3@f855394a01c28a59836c
**Whether or not you use BetterTTV**: No
**Whether or not you use any other extensions on Twitch**: None

Same with the situations being mentioned multiple times, seems like the issue happens rather randomly.

I have also found out there's errors being threw in console when the scrolling bug happens, hope this helps:

![](https://cdn.discordapp.com/attachments/300024307080364032/380466561275920396/unknown.png)

**Comment by Doorstop2** [comment]
So i just want to update i have tested this on a few channels both fast and slow chat if you scroll up it will now pause same for using hover or a hotkey idk if this is ffz that fixed it might of been twitch

**Comment by winneon** [comment]
Can confirm, pausing is now working as intended even in Firefox. The first issue is still present, however.

**Comment by Doorstop2** [comment]
It still does break it works on & off checking console found this 

> This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features!

**Comment by SirStendec** [comment]
I haven't pushed any updates to scrolling, so I expect it is changes happening on Twitch's end to fix the issues. With any luck, they'll get it all working flawlessly and I won't have to change anything.

**Comment by SirStendec** [comment]
Thank you very much for the report, Whit. I understand what's happening now, and I've taken steps to fix it. Hopefully this should be the end of the scrolling problems.

On a side note, while your console log was very useful, Firefox is a bit silly. It had me confused for nearly 10 minutes for reporting `i is undefined` because `i` is the name of a variable I use in a loop, and I initialize it like... the line *right* before it said it was undefined.

But while Firefox uses function names and line numbers from source maps, it decided to use a variable name from the minified code. That seems... less than ideal.

Not a problem with you, of course, just an observation.

Thanks again! I'm going to leave this open a bit longer just to be sure, but then I'll be closing it.

**Comment by d0p3t** [comment]
**Browser: Chrome 62.0.3202.89 (macOS)
FFZ Version: 4.0.0-beta1.3 bdf2ec93761131252233
BetterTTV: No
Other extensions: FFZ Add-On Pack**

I can confirm that this issue has been fixed using the latest update. Thank you for your work!

**Comment by Doorstop2** [comment]
Can confirm atm it seems to be working 

Firefox 57 

version: 4.0.0-beta1.3 c89ba74a13dda449dfec

**Comment by SirStendec** [comment]
Everything seems good. I'll close this issue finally.

**Comment by u-C-m** [comment]
Browser: Firefox 58 b8
Version:  Version 4.0.0-beta1.4 8e759e6ddfa7aa70cfea 
Addon: BTTV Emote Addon

Chat freeze still not working for me. It wouldn't work on Firefox 57 stable either before using 58 beta. Sadly I don't provide any more info as I dont know how to debug.

**Comment by winneon** [comment]
**Browser:** Firefox 57.0.1 Stable
**FFZ Version:**  4.0.0-beta1.4 8e759e6ddfa7aa70cfea

I can confirm what @u-C-m says. I've been having this issue these past few days.

When scrolling up, the chat is not frozen, making it difficult to select specific text. The chat also does not freeze when using the Chat Freeze option. The console does not print any errors or anything when attempting to freeze the chat via the above two methods.

**Comment by SirStendec** [comment]
Twitch's own scrolling code has bugs in it. You're likely encountering that, rather than the initial issues that were a result of FrankerFaceZ's Chat Freeze setting. Unfortunately, FFZ relies on Twitch's own scrolling code to not break in order for chat freeze to work. Nothing for me to do about that, at this point. Hopefully Twitch just fixes their website... at some point. It's been a bug for months now.

**Comment by Kevin-Mok** [comment]
Browser: Firefox 57.0.4
Version:  Version 4.0.0-beta1.59a60ce1ee6c58905c6eb 

Yeah, I guess it's Twitch's code breaking. It shows the (more messages below) message, but the chat keeps scrolling.

**Comment by av98911** [comment]
This issue is present for me on Firefox Quantum 61.0 (64-bit). FrankerFaceZ version 4.0.0-rc3.3. I tested it on Chrome and the chat scrolling worked perfectly fine. It only seems to be a problem on Firefox. I use BTTV on both Firefox and Chrome. I tested with and without BTTV enabled on both browsers and there was no change, it works fine on Chrome but no matter what I do on Firefox it won't work (chat continues to scroll/won't pause) including when trying other keys (shift, ctrl, alt).

**Comment by NiteCyper** [comment]
Chrome 
Your FFZ Version (from the FFZ Control Center, including the build string on the next line)
Whether or not you use BetterTTV
Whether or not you use any other extensions on Twitch
There are two different issues that most people are having. Either:

Chat is freezing and then refusing to start scrolling again.
Chat should be frozen but it is continuing to scroll.
