### ISSUE TITLE
emoji shortcode not working?

### ISSUE THREAD

**Issue by gurizzy** [FrankerFaceZ/FrankerFaceZ#3]
when typing emoji shortcode for instance :taco: it doesn't show up in chat. it's possible it shows on the other end. shows up as text on the users end i.e. :taco: instead of the image.
only works on copy+paste.

**Comment by SirStendec** [comment]
There's a setting called `Enter Emoji by Name` that you probably have turned off (as is the default).

![image](https://cloud.githubusercontent.com/assets/14036657/19018701/1686b1ec-883b-11e6-8f41-290be7a8766e.png)

I'm going to assume it's just turned off. Reply again if it's not working with the setting on. I'm going to set it enabled by default too, for future users. ... could've sworn I'd already done it, actually. 😦
