### ISSUE TITLE
frankerfacez.com/developers consistently throwing 500s

### ISSUE THREAD

**Issue by TrampolineTales** [FrankerFaceZ/FrankerFaceZ#30]
**Web Browser**:
Chrome 53.0.2785.143 m

**Do you use BetterTTV or other Twitch extensions**:
No

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:
N/A

**Bug / Idea**:
Without fail, frankerfacez.com/developers is returning 500 errors.

![](http://puu.sh/rAYJ8/777a7b1f85.png)

**Steps to Reproduce (if Applicable)**:
Click the "Developers" link at the bottom of http://www.frankerfacez.com/

**Comment by SirStendec** [comment]
My fault. I just made some changes to the API and I'm still typing up changes to the Developers page. It'll be fixed in 5.

**Comment by SirStendec** [comment]
Developers is updated and working.
