### ISSUE TITLE
[Feature Request] Anon mode

### ISSUE THREAD

**Issue by Californ1a** [FrankerFaceZ/FrankerFaceZ#301]
Don't show up in the chat userlist until you send a message (or /join, and /part to leave again). One of the main reason I've continued to use bttv until now, but they don't have this feature anymore. It's really nice for checking out new streams that don't have many viewers without being called out as a lurker.

**Comment by zoton2** [comment]
That is/was a feature on FFZ:AP but that extension is currently not rewritten for the new site yet.

https://github.com/Lordmau5/The-FFZ-Addon-Pack

**Comment by Mattk50** [comment]
This would be handy.

**Comment by Lordmau5** [comment]
This feature is not something we want to have in FFZ at the current time as we don't want to mess with the chat connection too much so I'm gonna go ahead and close it :)

**Comment by Ruhrev** [comment]
He actually closed it, yikes.

**Comment by bottleblue** [comment]
Don't be afraid to mess with the chat connection! Give us the stealth mode!
