### ISSUE TITLE
[Feature Request] Dark tool-tips in Dark (Gray) Mode

### ISSUE THREAD

**Issue by nurupo** [FrankerFaceZ/FrankerFaceZ#302]
Chromium 62, no BTTV, just FFZ. Tooltips in Dark/Gray Mode have white background, it would be nice to change them to have a dark background in this mode. I'm talking about the emote tooltips (large version of emotes), badge tooltips, uptime tooltip, stream latency tooltip, etc.

**Comment by SirStendec** [comment]
This will be addressed by the implementation of #308.

**Comment by nurupo** [comment]
Weird, it looks like someone else has dark tooltips in their gif at https://github.com/FrankerFaceZ/FrankerFaceZ/issues/303 while I don't. Might be Chromium-specific or something?

**Comment by Dgc2002** [comment]
@nurupo sorry for the confusion. I recorded that gif while trying to 'fix' the tooltip colors for this issue. So you have the correct current tooltip
