### ISSUE TITLE
Playback rate doesn't get updated in the Playback Statistics tooltip

### ISSUE THREAD

**Issue by nurupo** [FrankerFaceZ/FrankerFaceZ#303]
**Web Browser**:
Chromium 62

**Do you use BetterTTV or other Twitch extensions**:
Just FFZ

**Bug / Idea**:
"Playback rate" number in the tooltip of the stream delay information enabled by `Channel -> Metadata -> Playback Statistics` never updates, it's the same kbps value (it's different for each channel though).

**Steps to Reproduce (if Applicable)**:
Check `Channel -> Metadata -> Playback Statistics`. Visit any channel, hover over the stream delay statistics to get a tool tip with "Playback rate", observe how the value of "Playback rate" never seems to change, even though it changes in `Settings -> Advanced -> Show video stats` menu of the Twitch player.

**Comment by Dgc2002** [comment]
Can't reproduce. Seems to be working for me:  
![](https://i.imgur.com/F6mfAle.gif)  
  
Also on Chrome 62

**Comment by nurupo** [comment]
>Also on Chrome 62

I use Chromium 62, not Chrome 62. Not sure if there is much of a difference though. I'm running Debian Linux.

Here is a 1fps gif of [SaltyBet](https://www.twitch.tv/saltybet). Click on it to view a bigger version.

![SaltyBet](https://user-images.githubusercontent.com/1855294/32925608-bd8c9a10-cb10-11e7-8cc9-b255c1cd1404.gif)

**Comment by SirStendec** [comment]
So, I can see from your GIF that your tool-tip is updating. The number of dropped frames is increasing. This means that the problem is in Twitch's player. There's no kind of caching in the tool-tip renderer. It always grabs fresh data straight from the player when it updates.

**Comment by nurupo** [comment]
Yeah, the tooltip updates everything except Playback Rate, which you can see changing in the player statistics. Is there no way to fix this then, the player just falsely reports the same Playback Rate value to FFZ?

**Comment by nurupo** [comment]
I fixed it!

When opening a channel, the player, for a very brief moment, shows the "Right-click to run Adobe Flash Player" Chromium screen, and then immediately falls back to using HTML5 player.

![screenshot](https://user-images.githubusercontent.com/1855294/32930835-0d4d84ba-cb2f-11e7-8a3c-d50a831f7202.png)

Apparently I had `Flash -> Always allow on this site` set. Changing it to `Always block on this site` fixes the issue of Playback Rate in the tooltip not updating.

![screenshot](https://user-images.githubusercontent.com/1855294/32930978-c0c9fe10-cb2f-11e7-82e6-d8f932d87885.png)

**Comment by nurupo** [comment]
Here it is working

![output2](https://user-images.githubusercontent.com/1855294/32931117-78d4c8f0-cb30-11e7-9114-6c4fa76eb396.gif)
