### ISSUE TITLE
[Feature Request] Please add the classic dark twitch chat color palette back as an option

### ISSUE THREAD

**Issue by Meeplee** [FrankerFaceZ/FrankerFaceZ#305]
**Web Browser**: Mozilla Firefox 57.0

**Do you use BetterTTV or other Twitch extensions**: No

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: Not Applicable

**Bug / Idea**: Back when Twitch changed the color scheme of the dark mode chat of a few months ago, FFZ preserved them and was a major point why i started to use the addon.

Please add this back as an option to the new FFZ addon.

For reference, i'm talking about the background / font colors the chat used in theater/dark mode, the font specifically used a less aggressive tone and the background was a bit more purple.

**Steps to Reproduce (if Applicable)**:

**Comment by SirStendec** [comment]
Color palettes are going to be addressed at a later time, once I've got the core features done and have time to work on secondary features. No ETA, but hopefully within a month or two.
