### ISSUE TITLE
"Minimize Navigation" option doesn't move channel bar in Firefox

### ISSUE THREAD

**Issue by jakebailey** [FrankerFaceZ/FrankerFaceZ#309]
**Web Browser**: Firefox 57.0, comparing with Chrome 62.0.3202.94

**Do you use BetterTTV or other Twitch extensions**: Only FFZ:AP.

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: N/A

**Bug / Idea**:
Minimizing navigation in Firefox 57 doesn't move the channel bar up, which covers part of the stream. In Chrome, this works as expected.

Screenshots to compare:
- [Firefox](https://i.imgur.com/X5l4HNE.png)
- [Chrome](https://i.imgur.com/0ep2LJl.png)

**Steps to Reproduce (if Applicable)**:
Enable "Minimize Navigation" in Appearance > Layout in Firefox.

**Comment by SirStendec** [comment]
I cannot reproduce this behavior. Do you have anything else that might be affecting the page, such as a user CSS extension?

**Comment by jakebailey** [comment]
Nope, nothing like that past a slew of uBlock/uMatrix stuff. But, I restarted overnight, and it isn't doing it anymore. I'll close the issue unless I see it again (and can provide more info).
