### ISSUE TITLE
<message deleted> does not show when user is timed out

### ISSUE THREAD

**Issue by CArchetype** [FrankerFaceZ/FrankerFaceZ#31]
**Web Browser**: Firefox 49.0.1

**Do you use BetterTTV or other Twitch extensions**: BTTV4FFZ

**Bug / Idea**: message deleted does not appear when a user is timed out (even as a moderator). both "remove deleted messages" and "show deleted messages" are turned off. in addition, turning either of those settings on results in nothing happening.

**Steps to Reproduce (if Applicable)**: time someone out.

**Comment by SirStendec** [comment]
I noticed this earlier myself, but I wasn't able to reproduce the bug after refreshing. It seems that the ember observers stop working correctly, most likely because of an unhandled exception somewhere. I'm keeping an eye on it.

**Comment by SirStendec** [comment]
I haven't been able to reproduce this bug recently, since refactoring a bit of chat line code. I'm assuming I fixed it by accident. If you still have this happening, let me know. Until then I'm going to assume this closed.

**Comment by SirStendec** [comment]
Reopening this because it occasionally breaks still. Not sure what's going on. Ember is breaking in a way that doesn't generate useful logs at ALL. Here's what I have to work with:
![image](https://cloud.githubusercontent.com/assets/14036657/19376882/89592ca4-91af-11e6-9620-c0c51aa36fa3.png)
