### ISSUE TITLE
Scroll to change volume broken on Firefox

### ISSUE THREAD

**Issue by sisa1917** [FrankerFaceZ/FrankerFaceZ#310]
**Web Browser**: Firefox Dev 58.0b4

**Do you use BetterTTV or other Twitch extensions**: Addon pack

**Bug / Idea**: Scrolling to change the volume always lowers the volume no matter how hard you try to scroll up

**Steps to Reproduce (if Applicable)**: Enable the feature and scroll!

**Comment by Crocbash07** [comment]
Hello,

_Adjust volume by scrolling with the mouse wheel_ feature works fine here. However, scrolling down will increase volume while scrolling up will lower it. It should be the opposite, right?

**Web Browser**: Firefox 57.0 (64-bit)

**FrankerFaceZ version**: 4.0.0-beta1.3 _3c0a6b612462d9174570_ (I'm not sure I have the latest version, I've uninstalled the add-on and downloaded it again from frankerfacez.com but it's still showing the same hash

**Do you use BetterTTV or other Twitch extensions**: Yes, [Twitch Fox](https://addons.mozilla.org/en-US/firefox/addon/twitch-fox/). I doubt it has anything to do with this minor bug though.

Keep up the good work!

**Comment by SirStendec** [comment]
Well, that's silly. I'll make sure to push out a fix for that with the next batch of changes.

**Comment by Crocbash07** [comment]
Just got f93396a7a97f1a01b284

I can confirm it's fixed, thank you @SirStendec!
