### ISSUE TITLE
Username hightlighting not currently functioning

### ISSUE THREAD

**Issue by av798902** [FrankerFaceZ/FrankerFaceZ#311]
**Web Browser**: Firefox 57.0

**Do you use BetterTTV or other Twitch extensions**: Yes. Just BetterTTV and FrankerFaceZ

**Bug / Idea**: I did not see mention of this elsewhere. The highlight of your username in stream chat (@userName) when someone is mentioning you does not function. The "@"mention is treated as normal text like everything else.

EXTRA: If you use the highlighted keywords from BTTV then using the option "display lines with alternating background colors" in FFZ control center can override the highlight of these keywords. But considering that BTTV and FFZ are going through major changes thanks to Twitch website change this is not as big of a deal. Or maybe it would be resolved through the same highlight fix for usernames in FFZ?

The "display lines with alternating background colors" option is the only way to remove change the purple lines to grey in FFZ dark theme.

**Steps to Reproduce (if Applicable)**: 1) Enable FFZ 2) Have someone "@" mention you in a chatroom.

**Comment by SirStendec** [comment]
We know the feature isn't working yet. We haven't had time to add that particular feature back yet. It's coming, soon. You just have to be a bit patient.

**Comment by av798902** [comment]
My mistake. Sorry about that, didn't know it was a known issue. Thanks for continued work  on the extension and having something available so quickly after beta replaced legacy version.
