### ISSUE TITLE
Stream statuses occasionally vanishes

### ISSUE THREAD

**Issue by Jacky1356400** [FrankerFaceZ/FrankerFaceZ#319]
**Web Browser**: Google Chrome 62.0.3202.94 {64 bit, Windows 10)

**Do you use BetterTTV or other Twitch extensions**: No

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: N/A

**Bug / Idea**: The stream statuses (including title, game, stream team and community) occasionally vanishes. Refreshing the page fixes it though.
Edit: It breaks the total views as well, as you can see in the exhibit, it's 0.
Exhibit: ![](https://i.gyazo.com/c518396b3bb89530f3c1f5cb4e7e6cd3.png)

**Steps to Reproduce (if Applicable)**: I am not sure if it's random or not, possibly caused by stream statuses / channel total views updates

**Comment by SirStendec** [comment]
The really interesting thing here to me is that the stream uptime display is still working while everything else is broken. That indicates that Apollo has the data somewhere. I haven't been able to reproduce this issue yet, but I'm aware of it.

The next time it happens, can you open your browser's Developer Tools and check for errors in the Console? Additionally, you can try running this command in the console:

```javascript
console.log(JSON.stringify(ffz.site.apollo.getQuery('ChannelPage_ChannelInfoBar_User').lastResult.data,null,4))
```

Which should give you some data like this. That'll let me know if there's a data loading issue or if it's just not getting to React somehow.
![image](https://user-images.githubusercontent.com/14036657/32982687-7af8c2d6-cc56-11e7-95dd-8b397b438e71.png)

**Comment by SirStendec** [comment]
I should mention that I'm not sure if this is a FFZ bug or not. Something like this could easily just be a bug with the new Twitch rewrite.

**Comment by Jacky1356400** [comment]
I've just managed to reproduce the bug again:
![](https://i.gyazo.com/6646d4dbd2f6d0183d8989e9a620a16f.png)
But unfortunately, I am not able to find any errors when the the bug happened, even with verbose logging level enabled, and the result of the command looks normal, but it's like this:
![](https://i.gyazo.com/672f0c8dc6b33ef9d61ee2dae092e82d.png)

**Comment by Jacky1356400** [comment]
Updates: Seems like I am getting this console errors spam after the statuses are changed, this has never happened before.
![](https://i.gyazo.com/0f02f7b7cbb2ab1745f2d4f6ec3cf3f0.png)

**Comment by jrbury** [comment]
I've also seen this as well, I think I might've narrowed down what could be causing it. 

The stream I was watching had switched games (and therefore game sections) and that appeared to be when the bug occurred. When running `console.log(JSON.stringify(ffz.site.apollo.getQuery('ChannelPage_ChannelInfoBar_User').lastResult.data,null,4))` about an hour after they had switched games, the game in the JSON is the previous game category.

I also confirmed that after refreshing both the info bar and the query returned the correct results. There were no console errors for me as well.

Let me know any other debugging steps you'd like done if it happens again and I'd be happy to gather more info

**Comment by SirStendec** [comment]
I'm not actually sure at this point that this is a bug with FrankerFaceZ. I've heard of users having this issue without FFZ installed. Probably just yet another case of Twitch rushing into React + Apollo and not having a clue how to actually use it properly.

**Comment by BradyThe** [comment]
I can confirm that this bug can occur without having FFZ enabled. I did the unspeakable thing of using Twitch without any addons and stream information just disappeared on me.

**Comment by Jacky1356400** [comment]
To be fair, it was a terrible idea for Twitch to change their JS framework from Ember to React. Twitch could have furtuer optimize their Ember-based legacy site rather than rewriting and breaking the whole site by using React. Features are going to take a good while to add back slowly and some of the features won't be as good as it was for sure.

**Comment by Jacky1356400** [comment]
Can confirm, this was finally fixed on Twitch's side, I'll close the issue now.
