### ISSUE TITLE
Stream Uptime goes Under Chat

### ISSUE THREAD

**Issue by FoxyToaster** [FrankerFaceZ/FrankerFaceZ#32]
**Web Browser**:  Chrome

**Do you use BetterTTV or other Twitch extensions**: No

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:
N/A

**Bug / Idea**:
Highlighting stream uptime outputs everything past the date under the chat box.

**Steps to Reproduce (if Applicable)**:
Just drag mouse over uptime.

**Comment by LawlyPopz** [comment]
You mean this ???
![you mean this](http://pushzz.xyz/img/5ea4a.png)

**Comment by FoxyToaster** [comment]
Hmm, looks like it works now. Sorry for wasting your time!
