### ISSUE TITLE
Separate addons for beta and live

### ISSUE THREAD

**Issue by Kidsheldon** [FrankerFaceZ/FrankerFaceZ#324]
As the addon itself states, version 4 is a beta under heavy development. However, it is a pushed update, so lots of functionality is gone until version 4 is close to exiting beta. Can there be separate addons for FFZ beta and FFZ release?

**Comment by SirStendec** [comment]
FrankerFaceZ v4 is live only because the old version is not compatible with the new version of Twitch. If we had any choice in the matter, we would have delayed its release until it was ready.

You can continue using the old script only via the Legacy Chat Popout.

**Comment by Kidsheldon** [comment]
Oh, okay.

`<sup>I miss the dark theme can I have that back?</sup>`

**Comment by zoton2** [comment]
Enable Twitch's own dark theme. If you don't like the purple, you can remove it using FFZ (control center > theme).
