### ISSUE TITLE
Firefox Quantum chat doesnt stop scrolling

### ISSUE THREAD

**Issue by Maaruis** [FrankerFaceZ/FrankerFaceZ#325]
**Web Browser**: Firefox 58.0b4

**Do you use BetterTTV or other Twitch extensions**: BTTV and uBlock

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: 

**Bug / Idea**: Scrolling up on chat doesn't stop it. Using the chat stop function with buttons on FFZ also doesn't stop it.

**Steps to Reproduce (if Applicable)**: Try scrolling up chat and stopping it in Firefox 58.0b4

**Comment by SirStendec** [comment]
This is an issue with Twitch's chat scrolling. It just breaks completely at times and you have to refresh for it to start working. It happens with or without extensions, and I haven't seen a way to fix it yet.
