### ISSUE TITLE
Resub notifications revert an Unchanged Color Adjustment

### ISSUE THREAD

**Issue by Detrivance** [FrankerFaceZ/FrankerFaceZ#327]
**Web Browser**: Firefox Quantum

**Do you use BetterTTV or other Twitch extensions**: No just FFZ and FFZ:AP

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**: When someone resubs, the resub message will show the unchanged color adjustment even though the rest of the chat is being adjusted 

![firefox_2017-11-21_16-02-39](https://user-images.githubusercontent.com/33882705/33103533-b05b7972-ced7-11e7-860d-8eb5d8333cf3.png)

**Steps to Reproduce (if Applicable)**: Have someone resub when color adjustment setting is turned on

**Comment by XeroOl** [comment]
possibly related to #314

**Comment by SirStendec** [comment]
Yup, that's the same issue as #314. It's fixed in 2e5fe7f17773061ddf16ddfb8773f955ef4d17d5
