### ISSUE TITLE
Highlights in chat not working properly

### ISSUE THREAD

**Issue by Nurga** [FrankerFaceZ/FrankerFaceZ#329]
**Web Browser**: Firefox 57.0

**Do you use BetterTTV or other Twitch extensions**: Only FFZ and AddOn-Pack

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: /

**Bug / Idea**: Highlights like "@Name" or HL-words won't get displayed with red bg anymore, padding of chat line not there, hits the walls.

**Steps to Reproduce (if Applicable)**: /

**Comment by SirStendec** [comment]
Fixed in f66069798db40e11559d35ad63362461c419ded2
