### ISSUE TITLE
Channel Metadata Not Working After Clearing Cookies/Cache

### ISSUE THREAD

**Issue by Slaughterhouserock** [FrankerFaceZ/FrankerFaceZ#33]
**Web Browser**: Chrome

**Do you use BetterTTV or other Twitch extensions**: I use BetterTTV Emotes for FrankerFaceZ

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: http://putco.de/NDc4NQ.log

**Bug / Idea**:  None of the options in the Channel Metadata tab are working.  Everything else is fine.

**Steps to Reproduce (if Applicable)**:  All I did was clear my cookies and cache.

**Comment by SirStendec** [comment]
Are you seeing the old channel layout? FrankerFaceZ no longer supports that to avoid complications from trying to support both old and new.

**Comment by Slaughterhouserock** [comment]
I had the new layout, but it reverted back to the old after clearing everything for some reason.  Guess that's it, though.  Thanks for the quick response!
