### ISSUE TITLE
[Feature Suggestion] Tab-complete emotes (channel-specific, global and FFZ)

### ISSUE THREAD

**Issue by theKKCD** [FrankerFaceZ/FrankerFaceZ#334]
**Web Browser**:
Google Chrome Latest Stable

**Do you use BetterTTV or other Twitch extensions**:
FFZ:AP

**Bug / Idea**:
I'm always misspelling emotes so it would be great if emotes were also tab-completed, similar to how it was pre-v4. Thanks.

**Comment by SirStendec** [comment]
We have had tab completion for ages. It's just not back in yet. We have to rewrite literally everything for v4 and that takes time.
