### ISSUE TITLE
Following button-hover overlay missing & thumbnail uptime missing

### ISSUE THREAD

**Issue by 7CardStud** [FrankerFaceZ/FrankerFaceZ#336]
**Web Browser**:
Chrome

**Bug / Idea**:
Don't think these have been added to V4 yet, just let you know that there is interest in this again.
Also some info on how prioritized this would be?

Thanks.

**Comment by SirStendec** [comment]
These haven't been added to v4 yet. Lordmau5 has been working on them in a fork though, and they're almost done. Soon.
