### ISSUE TITLE
Emotes Glitch on the user sent Message when combined with Emoji

### ISSUE THREAD

**Issue by Meeplee** [FrankerFaceZ/FrankerFaceZ#337]
**Web Browser**: Mozilla Firefox 57

**Do you use BetterTTV or other Twitch extensions**: No

**Bug / Idea**: 
As the title describes, when sending messages with emotes and emoji combined, the emotes will generally glitch if typed after the emoji, for the local display of your message only (messages you sent, but not received).

Do note that the display error only occurs locally, the message goes throught fine, and when received from other users it displays fine. I assume there's a different function handling the messages that are received server side and the ones that are just popped client side.

Example with FFZ enabled: https://i.imgur.com/MNnr0kp.png
Same example but with FFZ disabled: https://i.imgur.com/3eV7qEh.png

**Comment by SirStendec** [comment]
Fixed in cbbe6f3e2027f643ff14b90717bed1fea2d450d8
