### ISSUE TITLE
Twitch Player incorrect sizing 

### ISSUE THREAD

**Issue by mrwhiskersunderscore** [FrankerFaceZ/FrankerFaceZ#343]
**Web Browser**:Chrome

**Do you use BetterTTV or other Twitch extensions**: no

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**:
When using custom width chat, the video player does not size properly in theatre mode. Part of the video is behind the chat including button to exit theatre mode, fullscreen, etc. 

**Steps to Reproduce (if Applicable)**: set custom width chat and enter theatre mode. 

appears to be fixed now

**Comment by BidiBodiBidiBu** [comment]
Web Browser:Chrome

Do you use BetterTTV or other Twitch extensions: only have FFZ extension 

FFZ Logs (via FFZ Menu > About > Logs; if Applicable):

Bug / Idea:
if i have Minimise navigation enabled i lose a small chunk off the top of the stream it seems to move the video up and under the streamers videos/clips/follower buttons

Steps to Reproduce (if Applicable): turned this setting off and video went back to normal

**Comment by Jfamig** [comment]
Example of problem: http://prntscr.com/hhrzlt

**Comment by Dave1456** [comment]
The issue is that the "header" bar (for streams, not Twitch itself, where it says the Streamer name, Videos, Clips, etc tabs) has been moved down. Instead of in between the arrows to minimize both side bars, its underneath that when "Minimize Navigation" is turned on.

It just needs to be moved back up.

**Comment by ALongStringOfNumbers** [comment]
As above with the minimize navigation button. The main bar is minimized, but it looks like the space where it used to be does not get removed. This leads to the header bar with the Streamer name, videos, etc covering the top section of the player. It is worth to note that the arrow to minimize the chat , which is originally on the right side of the header bar, moves up to this blank space that is left when the Navigation bar is minimized. However, all other functions are left on the header bar.

**Comment by SmilesBlue** [comment]
I'm having a similar issue. My chat width (165) was working yesterday but now the player is not expanding to meet the chat bar.

https://prnt.sc/hhv2fu

Web Browser: Google Chrome
Other Twitch extensions: FFZ Addon Pack
