### ISSUE TITLE
annual bttv christmas emotes

### ISSUE THREAD

**Issue by KeppanaD3sti** [FrankerFaceZ/FrankerFaceZ#345]
**Web Browser**:chrome

**Do you use BetterTTV or other Twitch extensions**:bttv,gte,ublockorigin

**Bug / Idea**:betterttv added these annual christmas emotes but they dont really work whit ffz cuz they dont stack on emotes for example SantaHat doesent go on the previous emote FeelsBadMan

**Comment by SirStendec** [comment]
BetterTTV emotes in FFZ are implemented via the FFZ Add-on Pack. Issues involving BTTV emotes in FFZ should go there.

Also, AFAIK, this has been fixed.

**Comment by KeppanaD3sti** [comment]
aight cool thx <3
