### ISSUE TITLE
Auto Completion with emotes

### ISSUE THREAD

**Issue by ReunitedRL** [FrankerFaceZ/FrankerFaceZ#355]
**Web Browser**:
Waterfox(64x version of Firefox)

**Do you use BetterTTV or other Twitch extensions**:
Yes, I use the FFZAP with bttv in it.

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**:
Re-add the auto completion of emotes please <3

**Steps to Reproduce (if Applicable)**:

**Comment by kmslogic** [comment]
I am missing the previous style completion, but I think you can do most of it now by using a colon to start like :kap<tab>.  Is that what you were looking for?  This won't work for bttv or emoticons, but will work for twitch and subscriber emotes.

**Comment by Dgc2002** [comment]
The `:__emote_name__` syntax is driving me nuts but it does the job for now. Hoping to see tab completion return.

**Comment by gempir** [comment]
I agree that atleast there should be an option to change the autocompletion to the classic old style without :
