### ISSUE TITLE
channel bar not going away in theater mode

### ISSUE THREAD

**Issue by CArchetype** [FrankerFaceZ/FrankerFaceZ#36]
**Web Browser**: Firefox 49.0.1

**Do you use BetterTTV or other Twitch extensions**: FFZ4BTTV

**Bug / Idea**: the channel bar does not go away when theater mode is enabled (regardless of whether it is on the bottom or the top)

**Steps to Reproduce (if Applicable)**: turn theater mode on and look at the player

**Comment by SirStendec** [comment]
This bug was already fixed with version 3.5.321. You probably just have the old version cached.

**Comment by SirStendec** [comment]
Disregard me, it's fixed in 3.5.322. I didn't upload the right CSS cause I'm a genius D:
