### ISSUE TITLE
Clip thumbnail preview is missing

### ISSUE THREAD

**Issue by u-C-m** [FrankerFaceZ/FrankerFaceZ#360]
**Web Browser**: Firefox 58 b11

**Do you use BetterTTV or other Twitch extensions**: BTTV and FFZ Addon Pack

**Bug**: 
If I (or someone else) post the link of a clip I only see the bare link. There's no description or thumbnail. And I don't seem to find any option to turn that on or off in the FFZ menu. 
If I deactivate the FFZ userscript the clips appear with desc. and thumbnail again. 
**#Edit** Moving the mouse over the link shows a thumbnail and the description though.
Edit2: after testing around more I can say: 
- turning off BTTV doesn't solve the problem
- unchecking every option in the "link" section under "tooltip" doesn't fix it
- the chat in my dashboard (i dont stream otherwise I would have seen this earlier) shows clips like it should. my guess would be that they use some sort of legacy chat in the dashboard (ffz menu icon is near the emote menu in the bottom right)

**Comment by u-C-m** [comment]
Am I the only one with this bug?

**Comment by winneon** [comment]
I can't reproduce this. Try a fresh install of Firefox 58 and see if it still happens. If it does, try a fresh install on a different PC. A VM will work just fine.

People haven't responded because we're not having the issue.

**Comment by u-C-m** [comment]
I was about to reinstall firefox and also installed chrome. tried the above mentioned addons (bttv, ffz, ffz:ap) and have the exact same issue. Clips only show a thumbnail and info in legacy pop-out chat.
added a screenshot - left is legacy pop out, right is normal chat
![chat](https://user-images.githubusercontent.com/28190506/34644979-9322ea54-f342-11e7-92d4-85368c183ac9.jpg)

**Comment by u-C-m** [comment]
Update:
Got a new laptop, installed firefox with ffz as the **only** addon and it's still bugged (for me).
I don't get it.. FeelsBadMan

**Comment by SirStendec** [comment]
Reimplemented in d1acc9f7cca9df5d653dde7fcb46a8a314237bd9
