### ISSUE TITLE
Ffz not working properly. 

### ISSUE THREAD

**Issue by simplywoolfie** [FrankerFaceZ/FrankerFaceZ#362]
**Web Browser**:
Google chrome Version 63.0.3239.108
**Do you use BetterTTV or other Twitch extensions**:
Just ffz.
**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**:
When I'm watching a stream I'm missing a few ffz features such as, pause chat when scrolling, ffz donators badge emote menu etc.. However, when I'm on the same stream and I click on the "following" tab of the channel the twitch headbar turns purple rather than grey. I can also see my ffz donators badge and all the other settings.
https://gyazo.com/1c9abcfe166457d725bff142bd55c75f watching the stream normally with chat.

https://gyazo.com/5c9ac7b21d8726cc9db4e6abe9dca7dd chat in "following" tab 

**Steps to Reproduce (if Applicable)**:

**Comment by sunkhaskasis** [comment]
Features such as the donor badge and emote menu are still being worked on. If you wish to have old FFZ features, try using "Legacy Popout" by clicking the gear icon below chat.
