### ISSUE TITLE
Sub badge graphical glitch - chrome text size

### ISSUE THREAD

**Issue by Jfamig** [FrankerFaceZ/FrankerFaceZ#364]
**Web Browser**: Chrome

**Do you use BetterTTV or other Twitch extensions**: Yes, did testing and isolated to FFZ

**Bug / Idea**: Sub badges have graphical glitch when chrome font size is set to anything other than normal 

Chrome text size: http://prntscr.com/htl18n

Sub badge graphical bug: http://prntscr.com/htl1kb

**Steps to Reproduce (if Applicable)**: Set font size to anything other than normal in chrome settings. seems to only happen to certain badges.

**Comment by Henryjaw** [comment]
I second this
