### ISSUE TITLE
Missing the FrankerFaceZ button in chat box

### ISSUE THREAD

**Issue by zorkzork** [FrankerFaceZ/FrankerFaceZ#368]
**Web Browser**: Chrome

**Do you use BetterTTV or other Twitch extensions**: Yes, BetterTTV

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: 

**Bug / Idea**: I don't have the FrankerFaceZ button to access the emote box, but it does appear in legacy popout. Is this something that is temporarily gone or should it be appearing?

**Steps to Reproduce (if Applicable)**:

**Comment by TheBaconSpace** [comment]
Same Issue I'm Having

**Comment by TheGloriousArgonaut** [comment]
The FFZ chat emote pop out feature has been broken since the site overhaul. I hope it comes back soon, its been gone for awhile now I miss it allot.

**Comment by TheBaconSpace** [comment]
Same @TheGloriousArgonaut

**Comment by robmonte** [comment]
I'm surprised this hasn't been done yet as I think FFZ emotes is one of the biggest features of the addon. @SirStendec any news or updates on this feature?
