### ISSUE TITLE
"Hide Recent Videos" option unavailable in recent versions

### ISSUE THREAD

**Issue by timeshifter** [FrankerFaceZ/FrankerFaceZ#373]
It used to exist, now I'm having to manually hide that crap with uBlock. Come on guys, don't *remove* functionality, especially not functionality that leads to a cleaner experience.

**Comment by Lordmau5** [comment]
The functionality wasn't *removed*.

It's just that FrankerFaceZ is going through a full rewrite, meaning that features need to be *added back in* again.

Most, if not all, features will be back eventually - it will just take some time.
___
Additionally, as you can see the repository is open source so everyone could in theory do a pull request with fixes / features :)

**Comment by Lordmau5** [comment]
This was implemented in FFZ version 4.9.1 :)
