### ISSUE TITLE
FFZ not loading with Edge

### ISSUE THREAD

**Issue by adamcirillo** [FrankerFaceZ/FrankerFaceZ#374]
**Web Browser**: Edge Windows ver 1709 all updates

**Do you use BetterTTV or other Twitch extensions**: FFZ AP

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: icon not showing to check for logs

**Bug / Idea**:
FFZ won't load on twitch for me I tried without FFZ AP not sure what is wrong.

**Steps to Reproduce (if Applicable)**:

**Comment by Chronophylos** [comment]
Why do you use edge

**Comment by SESNut** [comment]
I also have this issue. 
FFZ only loads in legacy chat. no sign of it anywhere on regular twitch pages

**Comment by SirStendec** [comment]
This has been an issue because of problems with Edge's JavaScript engine. Starting today, we're pushing out special builds on the side for Edge so things should be working again.

**Comment by KyroOW** [comment]
Still having this issue, using Edge on Insider Builds.
