### ISSUE TITLE
[Feature Request] Option to hide "x is new here. Say hello!" system messages.

### ISSUE THREAD

**Issue by akanealw** [FrankerFaceZ/FrankerFaceZ#377]
**Web Browser**:
Chrome
**Do you use BetterTTV or other Twitch extensions**:
Twitch Legacy Chat
**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**:
Just wanted to request the option to hide the (User) is new here. Say hello! message in chat
![image](https://user-images.githubusercontent.com/651352/35538156-7c04c2d4-0512-11e8-9837-b04455d11fac.png)

**Steps to Reproduce (if Applicable)**:

**Comment by SirStendec** [comment]
Added in 5d53dd70710fefaa596e162a059812baf9f343b4
