### ISSUE TITLE
[Bug] Group Hosts feature is broken

### ISSUE THREAD

**Issue by RedSnt** [FrankerFaceZ/FrankerFaceZ#379]
**Web Browser**: Vivaldi (but tested in Firefox as well)

**Do you use BetterTTV or other Twitch extensions**: No.

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: No logs required.

**Bug / Idea**: The feature: "Group Hosts" in Directory >> Following no longer seems to work.

**Steps to Reproduce (if Applicable)**: Go to https://www.twitch.tv/directory/following/hosts and have a gander:  
[![https://gyazo.com/344a84f91da1fa312fc4535f2d43c9ba](https://i.gyazo.com/344a84f91da1fa312fc4535f2d43c9ba.png)](https://gyazo.com/344a84f91da1fa312fc4535f2d43c9ba)

**Comment by SirStendec** [comment]
This is mostly fixed. Twitch upgraded their data library to the latest version, which had several breaking changes for how FFZ interacts with it.

It's not quite perfect as it's still having issues forcing data to reload, but the data *is* getting modified correctly. Switch to another page and back to the directory and it works now.

I'm closing this as it's an issue with Apollo still and not the directory directly.
