### ISSUE TITLE
[Suggestion] Emote size scaling

### ISSUE THREAD

**Issue by RedSnt** [FrankerFaceZ/FrankerFaceZ#38]
**Bug / Idea**: Every emote has a 100% scale version (/1.0) but also has a 200% scale version (/2.0). An easy implementation of this feature would be to just display the 200% scale version and be done with it, but it would be nice if 110%, 120% etc. versions was also possible to select from scaling the 200% version down for quality (maybe add "quality emote scaling" as an option for those that would like to upscale the 100% version).

This would obviously use more bandwidth (? clog the pipes or cached? don't know.)

Just an idea, blatantly stolen from Chatty.

**Comment by SirStendec** [comment]
This is really not trivial to implement, despite seeming like it might be. There is a CSS property to scale things called `zoom`, but it doesn't actually make the browser pull in high-DPI resources even when they're available, and it causes issues with positioning of elements. I tried implementing it before alongside the font-size option to make emotes grow with the text, but it just... didn't go well at all.

Using `transform` to scale the emotes does pull in high-DPI resources, but it doesn't affect the size of the element so the emote ends up overlapping with everything and there is no way to properly correct for that.

This might change in the future, but for now it's just not really feasible to implement.
