### ISSUE TITLE
Cant change chexboxes in settings on/off

### ISSUE THREAD

**Issue by ChaosPaladin** [FrankerFaceZ/FrankerFaceZ#385]
**Web Browser**: Opera 51.0.2830.40

**Do you use BetterTTV or other Twitch extensions**: BetterTV (also same issue with checkboxes on/off

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: Not see this function

**Bug / Idea**: When trying change settings for turn on/off something settings, nothing not happen, checkboxes not change (also this issue with BetterTV, default Twitch site checkboxes work.)

**Steps to Reproduce (if Applicable)**: Go to FFZ settings menu and try change any option on/off

**Comment by SirStendec** [comment]
All I can think is that there's something wrong with your web browser. Have you blocked local storage on Twitch's domain? BTTV and FFZ both use that to store settings and disabling it is the only thing I could think of that would cause issues like that with settings.

**Comment by ChaosPaladin** [comment]
My bad, issue solved self, FFZ conflict with one another addon for Opera.
