### ISSUE TITLE
Ctrl pause seems bugged

### ISSUE THREAD

**Issue by thinkpad4** [FrankerFaceZ/FrankerFaceZ#387]
**Web Browser**:
Slimjet Version 14.0.16.0 (based on Chromium 57.0.2987.98)
**Do you use BetterTTV or other Twitch extensions**:
No
**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**:
When I load a channel I can press ctrl when the mouse is anywhere on the screen and chat will pause, but if I click in the text box like I'm going to type a message ctrl pause stops working unless the mouse cursor is hovering over the chat above the text box.  

**Steps to Reproduce (if Applicable)**:
Load a channel, press ctrl and you will see the chat scrolling pause.  Now click the text box, try ctrl again it won't pause the chat scrolling anymore.  Hover the cursor over the chat above the text box, press ctrl, it pauses the scrolling again but ONLY while the cursor is there, move it somewhere else and ctrl stops pausing.

I hope that explains it well enough
Thanks

**Comment by SirStendec** [comment]
Sorry, I just noticed I never responded to this issue. The behavior you are describing is intended. Hotkeys to pause chat only pause chat when your mouse is over chat. I plan on making this configurable when I write a better input handling system.
