### ISSUE TITLE
Badges

### ISSUE THREAD

**Issue by Khrome-XO** [FrankerFaceZ/FrankerFaceZ#389]
**Web Browser**:Google Chrome

**Do you use BetterTTV or other Twitch extensions**:BetterTTV

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**: I selected 'Rounded' for badges, but some are still default. Like the bit badge.

**Steps to Reproduce (if Applicable)**:

**Comment by SirStendec** [comment]
This is behaving as intended. Custom channel badges, badges from Twitch Crates, and bit badges are not affected by badge settings. We might re-add bit badges in the future, but there are limitations in how we customize badges currently that renders them incorrectly.
