### ISSUE TITLE
Minimized Navigation Bar Appears Atop Player in Theater Mode

### ISSUE THREAD

**Issue by BobbySig** [FrankerFaceZ/FrankerFaceZ#390]
**Web Browser**: Firefox

**Do you use BetterTTV or other Twitch extensions**: Nope

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: N/A

**Bug / Idea**:
When watching a stream in theater mode with navigation collapsed, the purple edge of the menu stays visible atop the player, potentially covering the top of the stream.

**Steps to Reproduce (if Applicable)**:
1. Enable "Minimize Navigation" in FFZ's settings.
2. Open a stream.
3. Turn on Theater Mode.

**Comment by Akibby** [comment]
So I know this was marked as a bug, but I actually really liked this "feature" is it at all possible that this could be an available setting? It is just convenient and turns the two click action of going to your followers from Theater Mode into a one click action.
