### ISSUE TITLE
Navigation no longer expanding while in theater mode

### ISSUE THREAD

**Issue by Dgc2002** [FrankerFaceZ/FrankerFaceZ#392]
**Web Browser**: Chrome  

**Do you use BetterTTV or other Twitch extensions**: No  

**Bug / Idea**:  
Previously while in theater mode moving the mouse to the top edge of the player would cause the navigation to expand, this is no longer the case.

**Comment by SirStendec** [comment]
That happening before was a bug with Minimize Navigation. Navigation is not intended to be visible when in theater mode.
