### ISSUE TITLE
[Feature Request] Ability to enable navigation expansion while in theater mode

### ISSUE THREAD

**Issue by Dgc2002** [FrankerFaceZ/FrankerFaceZ#393]
I previously reported the intended behavior as a bug here: #392 but apparently it's the original behavior that is a bug.  
  
Request:  
  
I'd like to be able to expand the navigation bar by moving my mouse to the top of the player while in theater mode. I use theater mode to have both chat and the video visible while also making use of the available screen real estate. Often when watching a stream I'll want to jump to my following page(either in the same or new tab), with the current behavior I'm required to exit theater mode to do this.

**Comment by SirStendec** [comment]
Implemented in dc358a774df0c8c3af69f375ffba6bc8ed7ef7ba
