### ISSUE TITLE
emote menu

### ISSUE THREAD

**Issue by pepitito0** [FrankerFaceZ/FrankerFaceZ#396]
**Web Browser**:
Google Chrome
**Do you use BetterTTV or other Twitch extensions**:
Yes
**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:
n/a

**Bug / Idea**:
Can't see the emote menu

**Steps to Reproduce (if Applicable)**:

**Comment by pahakalle** [comment]
By the emote menu do you mean the twitch one?

**Comment by pepitito0** [comment]
No I mean there ffz one

**Comment by pahakalle** [comment]
As said in the main screen of the ffz control center the emote menu is still under development
![screen shot 9](https://user-images.githubusercontent.com/1533244/37611587-67074c7a-2bab-11e8-8cca-acaaaccb48b0.png)

**Comment by pepitito0** [comment]
Oh ok so how do I see a list of global emotes for ffz
