### ISSUE TITLE
Channel metadata overlay no longer work in theater mode

### ISSUE THREAD

**Issue by RedSnt** [FrankerFaceZ/FrankerFaceZ#4]
Channel metadata overlay ("Display on Theater Mode Hover") doesn't work in theater mode after latest Twitch update.

Tested in both Firefox and Chrome on Windows 10. I also tested the userscript version to make sure (both browsers as well with grease- and tampermonkey respectively).

![image](https://cloud.githubusercontent.com/assets/6242718/19019092/acf09ede-8879-11e6-8c4a-d70547fc1355.png)

**Comment by LawlyPopz** [comment]
http://pushzz.xyz/img/26429.png

Still doesnt seem to want to work mike

http://pushzz.xyz/img/faad1.png and im on the newest version

**Comment by SirStendec** [comment]
@LawlyPopz Are you in Portrait Mode at the time? There's still a bug with it in portrait mode, trying to display in an off-screen location.

**Comment by SirStendec** [comment]
Also, the new stats bar is wider than it needs to be and it can cover up the settings menu. I need to fix that.

**Comment by LawlyPopz** [comment]
ok the stuff at the top http://pushzz.xyz/img/86e62.png comes back but no buttons at the bottom like the host button and what not like it use to have

**Comment by LawlyPopz** [comment]
Here is a gif on the settings for protrait and metadata http://pushzz.xyz/img/04ff0.gif

**Comment by LawlyPopz** [comment]
ok i worked it out.... doesnt work on hosts Kappa

**Comment by LawlyPopz** [comment]
@RedSnt it stioll doesnt work on hosted channels sadly :(

**Comment by RedSnt** [comment]
@LawlyPopz Well only a little over half the metadata is available like resolution, fps, latency, playback rate and skipped frames and not viewer count, follower count, uptime and total views due to the new implementation.. Stupid twitch ruining shizzle.. 

At least when you open chat pane on the right there is a button that says "go to channel" (I use chatty so hosting doesn't matter much chat wise for me). But I can certainly see how this would be annoying if you hang out on certain channels for the chat while watching another hosted channel using only the integrated twitch chat.
