### ISSUE TITLE
My ideas for Theater Mode

### ISSUE THREAD

**Issue by coleslaw121** [FrankerFaceZ/FrankerFaceZ#40]
Since the bulk of users want to maximize stream size while still allowing for chat, theater mode is a commonly used option. It's primarily useful because it gets rid of that pesky and almost useless left sidebar. However, the black space on the top and bottom, in my opinion, could be utilized for more useful purposes. I've pieced together what I think an ideal twitch stream would look like. This is purely an idea, so feel free to completely ignore it if you like, but I think this would maximize stream size, while keeping all useful and pertinent info and tools at the viewer's disposal with minimal visual noise.

![streamlayout1](https://cloud.githubusercontent.com/assets/22667141/19421032/483b2ad2-93bd-11e6-9778-a707a01ddbc4.png)

For starters, the top bar is always visible in theater mode, unless disabled by the auto-hide option. This allows viewers to see follower count and click on the videos tab without having to disable theater mode. (sure, we're only saving one click, but I'm trying to make this completely optimized.) The stream title and game are always shown below the stream; this way won't require hovering the mouse over the screen. Channel metadata is shown below the screen, and this is especially useful since it's mostly dynamic. I've also added a friends tab, similar to a whisper tab, which shows how many friends the user has online in the red dot notification and should open and work similarly to the whisper tab, showing what your friends are watching and allowing you to whisper them with a click. Relevant follow and subscribe buttons appear in the top right.

![streamlayout2](https://cloud.githubusercontent.com/assets/22667141/19421039/51e01c8c-93bd-11e6-8f19-e7a8acb806e3.png)

Here I've shown what would happen when you hover the mouse over the stream; the channel avatar expands to show detail and the game's cover appears and expands slightly over the stream. The top sidebar and bottom title/game info would shift to the right as the pictures expand.

I'm interested to know what you think. I realize this is starting to get nit-picky as far as how a channel looks but it's been bothering me a little that stream pages don't quite look as perfect as they could. I'm also aware this would be more difficult to dynamically program for people with different screen ratios, who want to auto-hide some of this information, and would be useless for those who don't use theater mode or simply hide chat. These are just ideas! Thanks for taking a look.

**Comment by SirStendec** [comment]
I don't think adding persistent screen elements to theater mode is the solution. Theater mode is ideally a sort of relaxed viewing experience that does away with any distractions from watching and chatting.

Of course, I'm not opposed to adding more information when you hover over the player as you're actively interacting with it then, but there should be limits. My main concern is... does the information you're accessing have immediate relevance concerning the stream or chat?

Statistics about the channel are a level removed, and really not something you need immediately on hand. It's not particularly difficult to disable theater mode for a moment to check, so it's still there. Just not adding needlessly to theater mode.


Moving away from theater mode itself, what this does make me think about is the navigation sidebar. A lot of the time, its presence is unnecessary. You can minimize it down to just icons, of course, but maybe a setting to make it slide out of the way when you're not using it would be even better. I'll need to think about that.

**Comment by coleslaw121** [comment]
Totally understood. I would however like to posit that the friends UI is particularly useful, and at least adding the follower amount to the on-hover channel metadata would be appropriate. Thanks for your consideration, glad to support the project!
