### ISSUE TITLE
Being able to use custom emojicons

### ISSUE THREAD

**Issue by HuntertheWhale** [FrankerFaceZ/FrankerFaceZ#41]
**Bug / Idea**: I want to use my channel emojicons outside of my channel. so do I want to use others emojicons.

You could use a "save emojicon" button so you can use them later

**Comment by SirStendec** [comment]
FrankerFaceZ does not want to let people use arbitrary emoticons everywhere on Twitch. We believe that it should be up to the broadcaster to choose which emotes are used in their chat. We will never add a feature to let you use emotes you upload in channels that haven't specifically added them.

**Comment by HuntertheWhale** [comment]
ok :)  but do u think making emojicons in whispers possible, for instance,
you want to show a friend an emojicon

**Comment by HuntertheWhale** [comment]
if not, then its ok.
