### ISSUE TITLE
[Feature Request] Blacklist Specific Games From Appearing in Following

### ISSUE THREAD

**Issue by Freezinater** [FrankerFaceZ/FrankerFaceZ#411]
**Web Browser**: Google Chrome

**Do you use BetterTTV or other Twitch extensions**: Yes, FFZ:AP

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: N/A

**Bug / Idea**: I would like to be have a blacklist to hide specific games which I do not care to watch. If the streamer is streaming under a game that is blacklisted, they will not show in your following directory until they are within a game that is not blacklisted. There are a couple games I don't care to watch and many streamers I follow have been streaming them for part of their streams as of late and I don't wish to unfollow them.

**Steps to Reproduce (if Applicable)**: N/A

**Comment by SirStendec** [comment]
You can already do that. Go to the game's page on Twitch, and over to the right of the header there should be buttons to Block or Hide Thumbnails for that game.

There are a few things we haven't touched yet. The sidebar and the videos sections of the Following page can still show those videos, but it hides live streamers and hosts. The other stuff is coming as we have time to add more comprehensive directory features.

**Comment by Freezinater** [comment]
Thank you for the heads up. I didn't know about that. I'm making use of it now.
