### ISSUE TITLE
Tab-completion for emotes doesn't work

### ISSUE THREAD

**Issue by Jobinx** [FrankerFaceZ/FrankerFaceZ#415]
**Web Browser**:
Chrome (build 65.0.3325.181 / 64-bit)

**Do you use BetterTTV or other Twitch extensions**:
BetterTTV, FFZ Add-on Pack

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:
N/A

**Bug / Idea**:
Tab-completion of emotes doesn't work for FFZ emotes. But it works for BetterTTV emotes. I've tried disabling BetterTTV, disabling FFZ-AP, and disabling both. But nothin'.

_Also, when will unicode emojis be implemented to the Emote Menu? :-)_

**Steps to Reproduce (if Applicable)**: Start typing in an FFZ emote in a channel that uses FFZ emotes, then press Tab. It's supposed to auto-complete the emote (with proper caps).

**Comment by Jihkie** [comment]
FFZ currently uses twitch's built-in tab complete system, which requires you to put a colon ":" before the emote you wish to autocomplete, and after typing at least 2 characters it will bring up an emote list.
![image](https://user-images.githubusercontent.com/18361844/38585184-ce400c00-3ccd-11e8-8ca6-1a679147230e.png)

**Comment by Minkafighter** [comment]
Hello, Sorry to bring this thread back up, but is there a way to autocomplete emotes without typing a colon first?

If not, is there a way to add that feature?

**Comment by Holdo** [comment]
It's confusing when you tab without the colon it just shows `No matches.` message.

**Comment by slow-down** [comment]
> It's confusing when you tab without the colon it just shows `No matches.` message.

did you find a fix for that? i mean its 2 years.... they could fix it themselves but didnt
