### ISSUE TITLE
"Highlight Messages that mention you." after username change does not work.

### ISSUE THREAD

**Issue by Runkel79** [FrankerFaceZ/FrankerFaceZ#417]
**Web Browser**:
Google Chrome
**Do you use BetterTTV or other Twitch extensions**:
FFZ:AP (The FFZ Add-On Pack)
**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**:

"Highlight Messages that mention you." does no longer word for me after i changed my Twitch username.

**Steps to Reproduce (if Applicable)**:

Change Twitch username

**Comment by SirStendec** [comment]
This happens because Twitch, for some crazy reason, keeps your old username in your session data. Just log out and back in and it'll be fixed.
