### ISSUE TITLE
[Feature Request] Tab-completion without colon

### ISSUE THREAD

**Issue by GreyAsteroid** [FrankerFaceZ/FrankerFaceZ#418]
**Bug / Idea**:
I'd like to be able to tab complete emotes/emoji without using colons. Currently tab complete defaults to usernames when no symbol is specified. 

Usernames, emotes, and emoji could all be tab completed without any symbol and users could adjust the priority of these items in preferences. Another option could be letting users choose which symbols tab complete into which item along with an option to choose no symbol.

**Comment by JoshQuake** [comment]
PLEASE do this. I hate needing the colon.
