### ISSUE TITLE
FrankerFaceZ not loading

### ISSUE THREAD

**Issue by ThibaultVlacich** [FrankerFaceZ/FrankerFaceZ#420]
**Web Browser**:
Firefox 59.0.2

**Do you use BetterTTV or other Twitch extensions**:
BTTV

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

Here's console logs I'm getting:
> FFZ: FrankerFaceZ v4.0.0-beta2.16 (build 9fac4d6cabd486c45f4e)
> FFZ [ settings ]: Using Provider: LocalStorageProvider
> FFZ [ site ]: Using: Twilight
> FFZ [ site.web_munch ]: Found and wrapped webpack's loader after 0ms.
> TypeError: e.tags is undefined
> FFZ [ site.web_munch ]: require() grabbed in 8.00000ms.
> FFZ [ site.web_munch ]: Loaded names for 86 chunks from require().
> FFZ [ settings ]: Initialization complete after 8.00000ms -- Values: 28 -- Profiles: 2

And here's the TypeError stack trace:
```
shouldSendCallback
https://cdn.frankerfacez.com/script/avalon.js:26:28334
_send
https://cdn.frankerfacez.com/script/avalon.js:26:50255
_processException
https://cdn.frankerfacez.com/script/avalon.js:26:47706
_handleStackInfo
https://cdn.frankerfacez.com/script/avalon.js:26:46492
captureException
https://cdn.frankerfacez.com/script/avalon.js:26:36241
captureException
https://cdn.frankerfacez.com/script/avalon.js:26:30069
capture
https://cdn.frankerfacez.com/script/avalon.js:1:40964
populate
https://cdn.frankerfacez.com/script/avalon.js:1:10407
discoverModules
https://cdn.frankerfacez.com/script/avalon.js:26:24989
FrankerFaceZ
https://cdn.frankerfacez.com/script/avalon.js:26:24652
<anonyme>
https://cdn.frankerfacez.com/script/avalon.js:26:25662
__webpack_require__
https://cdn.frankerfacez.com/script/avalon.js:1:397
<anonyme>
https://cdn.frankerfacez.com/script/avalon.js:1:2012
<anonyme>
```

**Bug**:
None of the functionalities of FrankerFaceZ are loading this morning.

**Comment by SirStendec** [comment]
Well, this helped me notice a bug in automated error reporting. Unfortunately, that's likely swallowing the main error. Do you have FFZ:AP installed by chance?

**Comment by ThibaultVlacich** [comment]
I do not. I only have FFZ and BTTV installed. Nothing more.
Disabling BTTV doesn't change anything. Bug is still there.

**Comment by ThibaultVlacich** [comment]
Update: FFZ is still not working with the beta17, but error is now a bit more detailled:

> FFZ [ core ]: An error occurred during initialization. 
> Error: cannot find required module chat when enabling site.chat
> Stack trace:
> ModuleError@https://cdn.frankerfacez.com/script/avalon.js?_=1523700025852:845:19
> __enable/this.__state_promise<@https://cdn.frankerfacez.com/script/avalon.js?_=1523700025852:1:5870
> __enable@https://cdn.frankerfacez.com/script/avalon.js?_=1523700025852:1:5575
> __enable/this.__state_promise<@https://cdn.frankerfacez.com/script/avalon.js?_=1523700025852:1:5948
> __enable@https://cdn.frankerfacez.com/script/avalon.js?_=1523700025852:1:5575
> enable@https://cdn.frankerfacez.com/script/avalon.js?_=1523700025852:1:3141
> enableInitialModules@https://cdn.frankerfacez.com/script/avalon.js?_=1523700025852:26:25244
> FrankerFaceZ/<@https://cdn.frankerfacez.com/script/avalon.js?_=1523700025852:26:24698

And a few lines later:

> TypeError: e is undefined[En savoir plus]
avalon.js:33:189376

**Comment by SirStendec** [comment]
Ah, I've seen that second error before. Unfortunately I don't know what to tell you, because your web browser is wrong. A few people are having that and I have no idea why.

The relevant code is:

```javascript
getUser(e,t,i,n,s=!1){let o;if(e&&"number"==typeof e&&(e=`${e}`),this.user_ids[e]?o=this.user_ids[e]:this.users[t]&&!n&&(o=this.users[t]),o&&o.destroyed&&(o=null),!o){if(i)return null;o=new h.a(this,null,e,t)}if(e&&e!==o.id){if(o.id){if(this.log.warn(`Data mismatch for user #${e} -- Stored ID: ${o.id} -- Login: ${t} -- Stored Login: ${o.login}`),s)throw new Error("id mismatch");this.user_ids[o.id]===o&&(this.user_ids[o.id]=null)}o._id=e,this.user_ids[e]=o}if(t){const e=this.users[t];e?e===this||n||e.id&&(this.users[t]=o):this.users[t]=o}return o}
```

Unminified relevant code:

```javascript
	getUser(id, login, no_create, no_login, error = false) {
		let user;
		if ( id && typeof id === 'number' )
			id = `${id}`;

		if ( this.user_ids[id] )
			user = this.user_ids[id];
```

Your browser is, for some reason, saying "`id` is undefined and that's an exception" when I'm not actually accessing `id` in any way that is unsafe. It's an argument of the function, so it's a declared variable so it shouldn't matter that its contents are `undefined`, and I'm never trying to get a member of `id`.

The fact that your browser also can't locate the chat module doesn't make any sense to me. Are you using a fork or unofficial build of Firefox or anything that might be messing with your JavaScript interpreter?

**Comment by ThibaultVlacich** [comment]
No, it's the official release of Firefox. Version 59.0.2

**Comment by ThibaultVlacich** [comment]
Ok, so I tried to run a dev version, but I can't because I'm running into #340.

**Comment by ThibaultVlacich** [comment]
All right, so I've been able to use the non-minified version of the script by redirecting `cdn.frankerfacez.com` to `localhost` by modifying my host file and I have no error.

So it's definitely the minifying process failing somewhere.

**Comment by ThibaultVlacich** [comment]
Ok, so if I get that right, I have this bug because I'm using the Insider Preview of the Spring Creators Update. I saw that the release of this update has been delayed, probably because a serious bug has been found, maybe this is related.
A new build has been release last night, I should try installing it maybe it contains a fix...

**Comment by ThibaultVlacich** [comment]
Seems like it has been fixed on Firefox's side. Let's hope they'll release this fix soon.
Hopefully before the release of the Spring Creator Update :D

**Comment by SirStendec** [comment]
Alright. I'm going to close this issue for now. Nothing to really do on the FFZ side of things but wait for software updates to be distributed.

**Comment by ThibaultVlacich** [comment]
Just a small update on the issue: a cumulative update for Windows 10 (Build 17134.5) has been released fixing the bug...
