### ISSUE TITLE
Emotes with high DPI versions available, occasionally display at the wrong resolution in Chrome

### ISSUE THREAD

**Issue by CFusion** [FrankerFaceZ/FrankerFaceZ#421]
**Web Browser**:
Chrome 65.0.3325.181 

**Do you use BetterTTV or other Twitch extensions**:
FFZ

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**:
When high DPI versions of an emote are available, (and srcset is used) it will sometimes ignore the resolution of the emote returned by the API and always display it at 28x28 causing a lot of blurr

https://api.frankerfacez.com/v1/emote/151481
https://www.frankerfacez.com/emoticon/151481-nepSmug

It will occasionally show at 32x32 and occasionally at 28x28 both on the frankerfacez site, in the emote menu, and in the chat. I am guessing if chrome has high DPI versions of an emote cached it will  always use that and downscale it to 28x28.

The emote menu explicitly sets the size to 32x32, the browser then takes the highest resolution version, downscales it to 28x28 and then upscales it to 32x32.

https://imgur.com/a/EwVbg

**Steps to Reproduce (if Applicable)**:

**Comment by SirStendec** [comment]
Do you have a non standard font size set in your browser's settings or any sort of zoom applied to Twitch?
