### ISSUE TITLE
Emotes are not showing up in the chat

### ISSUE THREAD

**Issue by Dolbeytwitch** [FrankerFaceZ/FrankerFaceZ#424]
**Web Browser**:
Google Chrome
**Do you use BetterTTV or other Twitch extensions**:

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**:
I have both installed ffz and the addon pack. Menu and all is showin up also the settings i testet all worked but the problem is that the emotes don't show up in the chat only the keywords :/

**Steps to Reproduce (if Applicable)**:

**Comment by pahakalle** [comment]
Hard refresh / check console for possible errors
