### ISSUE TITLE
Chat Prefrences refuse to load in Firefox

### ISSUE THREAD

**Issue by ElectricBee1** [FrankerFaceZ/FrankerFaceZ#429]
**Web Browser**:
Firefox
**Do you use BetterTTV or other Twitch extensions**:
N/A
**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: (Firefox Console Logs)
Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.
Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: call to eval() or related function blocked by CSP.
twitch-ext.min.js:8
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: call to eval() or related function blocked by CSP.
twitch-ext.min.js:8
FFZ: FrankerFaceZ v4.0.0-rc1.3 (build 8d513d37690a974cbc7e)
avalon.js:1:53503
FFZ [ settings ]: Using Provider: LocalStorageProvider
avalon.js:1:53503
FFZ [ site ]: Using: Twilight
avalon.js:1:53503
FFZ [ core ]: 
SyntaxError: invalid regular expression flag ÿ
Stack trace:
Emoji@https://cdn.frankerfacez.com/script/avalon.js?_=1524969987632:33:216920
register@https://cdn.frankerfacez.com/script/avalon.js?_=1524969987632:1:9578
inject@https://cdn.frankerfacez.com/script/avalon.js?_=1524969987632:1:8756
Chat@https://cdn.frankerfacez.com/script/avalon.js?_=1524969987632:33:186209
register@https://cdn.frankerfacez.com/script/avalon.js?_=1524969987632:1:9578
populate@https://cdn.frankerfacez.com/script/avalon.js?_=1524969987632:1:10402
discoverModules@https://cdn.frankerfacez.com/script/avalon.js?_=1524969987632:26:42583
FrankerFaceZ@https://cdn.frankerfacez.com/script/avalon.js?_=1524969987632:26:42246
@https://cdn.frankerfacez.com/script/avalon.js?_=1524969987632:26:43253
__webpack_require__@https://cdn.frankerfacez.com/script/avalon.js?_=1524969987632:1:397
@https://cdn.frankerfacez.com/script/avalon.js?_=1524969987632:1:2038
@https://cdn.frankerfacez.com/script/avalon.js?_=1524969987632:1:2
 Skipping ./chat/index.js
avalon.js:1:53538
FFZ: Unable to find module "chat" that wanted "tooltips".
avalon.js:1:53538
FFZ [ core ]: Loaded descriptions of 4 modules.
avalon.js:1:53503
FFZ [ site.fine ]: Installing MutationObserver.
avalon.js:1:53503
FFZ [ site ]: Loaded descriptions of 12 modules.
avalon.js:1:53503
FFZ [ settings ]: Initialization complete after 46.00000ms -- Values: 13 -- Profiles: 2
avalon.js:1:53503
FFZ [ socket ]: Using Server: wss://andknuckles.frankerfacez.com/
avalon.js:1:53503
FFZ: FrankerFaceZ v4.0.0-rc1.3 (build 8d513d37690a974cbc7e)
avalon.js:1:53503
FFZ [ settings ]: Using Provider: LocalStorageProvider
avalon.js:1:53503
FFZ [ site ]: Using: Twilight
avalon.js:1:53503
FFZ [ site.web_munch ]: Found and wrapped webpack's loader after 0ms.
avalon.js:1:53503
FFZ [ core ]: 
SyntaxError: invalid regular expression flag ÿ
Stack trace:
Emoji@https://cdn.frankerfacez.com/script/avalon.js?_=1524969987908:33:216920
register@https://cdn.frankerfacez.com/script/avalon.js?_=1524969987908:1:9578
inject@https://cdn.frankerfacez.com/script/avalon.js?_=1524969987908:1:8756
Chat@https://cdn.frankerfacez.com/script/avalon.js?_=1524969987908:33:186209
register@https://cdn.frankerfacez.com/script/avalon.js?_=1524969987908:1:9578
populate@https://cdn.frankerfacez.com/script/avalon.js?_=1524969987908:1:10402
discoverModules@https://cdn.frankerfacez.com/script/avalon.js?_=1524969987908:26:42583
FrankerFaceZ@https://cdn.frankerfacez.com/script/avalon.js?_=1524969987908:26:42246
@https://cdn.frankerfacez.com/script/avalon.js?_=1524969987908:26:43253
__webpack_require__@https://cdn.frankerfacez.com/script/avalon.js?_=1524969987908:1:397
@https://cdn.frankerfacez.com/script/avalon.js?_=1524969987908:1:2038
@https://cdn.frankerfacez.com/script/avalon.js?_=1524969987908:1:2
 Skipping ./chat/index.js
avalon.js:1:53538
FFZ: Unable to find module "chat" that wanted "tooltips".
avalon.js:1:53538
FFZ [ core ]: Loaded descriptions of 4 modules.
avalon.js:1:53503
FFZ [ site.web_munch ]: require() grabbed in 10.00000ms.
avalon.js:1:53503
FFZ [ site.web_munch ]: Loaded names for 116 chunks from require().
avalon.js:1:53503
FFZ [ site.fine ]: Installing MutationObserver.
avalon.js:1:53503
FFZ [ site ]: Loaded descriptions of 12 modules.
avalon.js:1:53503
FFZ [ settings ]: Initialization complete after 38.00000ms -- Values: 13 -- Profiles: 2
avalon.js:1:53503
FFZ [ socket ]: Using Server: wss://lilz.frankerfacez.com/
avalon.js:1:53503
FFZ [ socket ]: Connected.
avalon.js:1:53503
FFZ [ socket ]: Connected.
avalon.js:1:53503
FFZ [ experiments ]: Loaded information on 1 experiments.
avalon.js:1:53503
FFZ [ socket ]: Server Time: 2018-04-29T02:46:30.435Z
avalon.js:1:53503
FFZ [ socket ]:  Local Time: 2018-04-29T02:46:29.232Z
avalon.js:1:53503
FFZ [ socket ]:   Est. Ping: 55.00000ms
avalon.js:1:53503
FFZ [ socket ]: Time Offset: -1.25818505859375
avalon.js:1:53503
FFZ [ socket ]: Client ID: 618266dd-9d36-4b37-9870-c3664db78847
avalon.js:1:53503
FFZ [ socket ]: Server Time: 2018-04-29T02:46:30.436Z
avalon.js:1:53503
FFZ [ socket ]:  Local Time: 2018-04-29T02:46:29.234Z
avalon.js:1:53503
FFZ [ socket ]:   Est. Ping: 55.00000ms
avalon.js:1:53503
FFZ [ socket ]: Time Offset: -1.2574150390625
avalon.js:1:53503
FFZ [ socket ]: Client ID: 618266dd-9d36-4b37-9870-c3664db78847
avalon.js:1:53503
FFZ [ experiments ]: Loaded information on 1 experiments.
avalon.js:1:53503
FFZ [ raven ]: Installed error tracking.
avalon.js:1:53503
FFZ [ core ]: An error occurred during initialization. 
Error: cannot find required module chat when enabling site.chat
Stack trace:
ModuleError@https://cdn.frankerfacez.com/script/avalon.js?_=1524969987908:845:19
__enable/this.__state_promise<@https://cdn.frankerfacez.com/script/avalon.js?_=1524969987908:1:5896
__enable@https://cdn.frankerfacez.com/script/avalon.js?_=1524969987908:1:5601
__enable/this.__state_promise<@https://cdn.frankerfacez.com/script/avalon.js?_=1524969987908:1:5974
__enable@https://cdn.frankerfacez.com/script/avalon.js?_=1524969987908:1:5601
enable@https://cdn.frankerfacez.com/script/avalon.js?_=1524969987908:1:3167
enableInitialModules@https://cdn.frankerfacez.com/script/avalon.js?_=1524969987908:26:42838
FrankerFaceZ/<@https://cdn.frankerfacez.com/script/avalon.js?_=1524969987908:26:42292
avalon.js:1:53575
FFZ [ chat.emotes ]: Loaded emote set #3: Global Emotes (11 emotes)
avalon.js:1:53503
FFZ [ chat.emotes ]: Loaded emote set #4330: : Sten's Cheaty Emotes (3 emotes)
avalon.js:1:53503
TypeError: e is undefined[Learn More]
avalon.js:33:191037
FFZ [ chat.emotes ]: Twitch Inventory Sets: 
Set [ 33563 ]
avalon.js:1:53503
FFZ [ site.fine ]: Found class for "chat-line" at depth 3
avalon.js:1:53503
FFZ [ site.fine ]: Found class for "sub-button" at depth 55
avalon.js:1:53503
FFZ [ site.fine ]: Found class for "twitch-player-persistent" at depth 42
avalon.js:1:53503
FFZ [ site.fine ]: Found class for "twitch-player" at depth 52
avalon.js:1:53503
FFZ [ site.fine ]: Found class for "nav-bar" at depth 28
avalon.js:1:53503
FFZ [ site.fine ]: Found class for "chat-picker" at depth 46
avalon.js:1:53503
FFZ [ site.fine ]: Found class for "chat-container" at depth 73
avalon.js:1:53503
FFZ [ site.fine ]: Found class for "chat-controller" at depth 67
avalon.js:1:53503
FFZ [ site.fine ]: Found class for "tab-emote-suggestions" at depth 98
avalon.js:1:53503
FFZ [ site.fine ]: Found class for "chat-input" at depth 87
avalon.js:1:53503
FFZ [ site.fine ]: Found class for "chat-emote-menu" at depth 101
avalon.js:1:53503
FFZ [ site.fine ]: Found class for "chat-scroller" at depth 85
avalon.js:1:53503
FFZ [ site.fine ]: Found class for "host-container" at depth 67
avalon.js:1:53503
FFZ [ site.fine ]: Found class for "channel-bar" at depth 72
avalon.js:1:53503
FFZ [ site.fine ]: Found class for "channel-page" at depth 51
avalon.js:1:53503
FFZ [ main_menu ]: Built Tree in 8.00000ms with 61 structure nodes and 73 settings nodes.
avalon.js:1:53503
HTTP “Content-Type” of “text/html” is not supported. Load of media resource https://imasdk.googleapis.com/js/core/bridge3.205.0_en.html failed.
bridge3.205.0_en.html
Cannot play media. No decoders for requested formats: text/html
bridge3.205.0_en.html
This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features!
ozzycharizard
FFZ [ site.fine ]: Found class for "chat-settings" at depth 10
avalon.js:1:53503
FFZ [ core ]: An error occurred during initialization. Timed out

**Bug / Idea**:
When I attempt to load a chat, FFZ does not load in chat. Attributes outside of the chat load properly, but not properties inside chat. For example, the custom emote menu doesn't load any emotes, and custom badges or emotes do not load. I have attempted to reinstall the extension multiple times, remove extensions.json in the Firefox folder, remove all non-addon store extensions, etc. An example screenshot is supplied to show what I mean.
![capture](https://user-images.githubusercontent.com/24817619/39402785-cf0dacb4-4b37-11e8-94e1-8909b70eedb6.PNG)

**Steps to Reproduce (if Applicable)**:

**Comment by SirStendec** [comment]
This is due to a bug with Firefox running on the latest version of Windows 10. You can read more about the bug at https://bugzilla.mozilla.org/show_bug.cgi?id=1452619 if you're curious. Unfortunately, there's nothing for me to do about it. Just have to wait for the fix to land.
