### ISSUE TITLE
Bookmarking an emote does not work

### ISSUE THREAD

**Issue by Glaived** [FrankerFaceZ/FrankerFaceZ#434]
**Web Browser**: Vivaldi Latest W10 x64

**Do you use BetterTTV or other Twitch extensions**: Yes, BetterTTV

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**: CTRL+Click on an emote does not add it as a favorite emote

**Steps to Reproduce (if Applicable)**:

**Comment by Lordmau5** [comment]
Do you have any other extensions installed in Vivaldi?

I remember someone else had an extension called ["Wikiwand"](https://chrome.google.com/webstore/detail/wikiwand-wikipedia-modern/emffkefkbkpkgpdeeooapgaicgmcbolj) installed and it overwrote the left-click handler on every website...

Maybe one of your extensions causes a similar behaviour?

**Comment by SirStendec** [comment]
Are you trying to favorite a Twitch or FrankerFaceZ emote? You can't favorite those added through BetterTTV (unless you use FFZ:AP to add BTTV emotes directly to FFZ).

**Comment by Glaived** [comment]
@Lordmau5 Yes, Indeed I had the extension with the option `On all other websites` enabled, I have disabled this option and it actually works, this solution satisfies me, thanks 😄
