### ISSUE TITLE
New Account highlight

### ISSUE THREAD

**Issue by WebFreak001** [FrankerFaceZ/FrankerFaceZ#437]
**Idea**:
There could be a moderator option to highlight accounts which have been created in the last X days. For example when banning someone from a chat and that person creates a second account because of that you could quickly see that an account is a new account. There are also lots of scammer accounts just for this.

Combined with #436 you could instantly see new users in chat which are freshly created and could potentially do harm. This is especially useful for smaller streams where legit fresh users are pretty rare.

**Comment by SirStendec** [comment]
We will not implement this feature. We do not have data telling us if an account is new, and there's no way to get this data without hammering Twitch's API with requests. It does not scale.

For checking if an account is new, please wait for the enhanced viewer cards feature to return this week.
