### ISSUE TITLE
Automatic portait mode on unmaximize

### ISSUE THREAD

**Issue by joshuastevenson** [FrankerFaceZ/FrankerFaceZ#44]
**Web Browser**: firefox

**Do you use BetterTTV or other Twitch extensions**: no

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**:

Portrait mode is not triggered when resize is done by unmaximize window button

**Steps to Reproduce (if Applicable)**:
portrait mode automatic
make window narrow
maximize
unmaximize

**Comment by SirStendec** [comment]
I can't reproduce the behavior you're describing. When using Chrome, the window does not return to its initial size when un-maximizing and so portrait mode is rightfully not enabled. When using Firefox, the window returns to its previous size and portrait mode is re-enabled.

**Comment by joshuastevenson** [comment]
reproduction mp4 (some dumb reason github doesn't allow uploading mp4s so its in a zip). I enabled theater mode but it doesn't seem to be required.
[ffz.zip](https://github.com/FrankerFaceZ/FrankerFaceZ/files/546771/ffz.zip)
