### ISSUE TITLE
Update Webpack Hook to handle Webpack 4

### ISSUE THREAD

**Issue by conover** [FrankerFaceZ/FrankerFaceZ#440]
https://github.com/FrankerFaceZ/FrankerFaceZ/blob/master/src/utilities/compat/webmunch.js#L61

Webpack 4 has changed the `webpackJsonp` object from a function to an array. You'll have to update the hooking code to account for this new shape. You can see the new shape by running a Webpack 4  demo: https://github.com/carloluis/webpack-demo. You should allow for hooking using both methods (Webpack 4 and <4) so FFZ can make the transition as smooth as possible. You should be able to do a `Array.isArray(window.webpackJsonp)` to know which hooking code to run. Once you've made this change, I can remove the code blocking access to the `webpackJsonp` object.

**Comment by SirStendec** [comment]
Yes, I'm actually working on this right now. My main concern after this is that Webpack 4 does lazy loading of modules. What I really want access to is webpack's `require()` so I can grab the loaded modules assoc array off of it to find things like React.

I've been doing this before by injecting a fake module with identifiers very, very unlikely to collide with any existing Twitch module. Webpack would execute my fake module right away and hand me require. That won't work any more, and the only solution I've thought up so far is wrapping `webpackJsonp.push` similarly to how I do it now, but also wrapping every module function passing through in a layer so I can grab require if and when that module is used.

(What I'd really, really love is if webpack's require were saved as a global on window.)

**Comment by conover** [comment]
🤔 Yeah, looking at the new way this is done. I think you are going to have to override `.push` as you describe. I don't see any other way to do it.

**Comment by SirStendec** [comment]
I've just pushed a build off of commit 194f93414d5ca745dc5ec0c5961d84138e353da3 with initial support for webpack 4. I haven't been able to test the code in place on Twitch because I have no idea how to opt into the webpack 4 roll-out and the usual tricks to change experiments aren't working.

This doesn't solve the issue of lazy loading, but it should make things a bit less broken at least.

**Comment by conover** [comment]
The experiment has concluded since we gathered all the info that we needed. I'll run a this change against non-hardened copy of Twitch locally and get back to you shortly.

**Comment by SirStendec** [comment]
I'm on Slack if you want a more direct line of contact for this or to discuss anything not appropriate for a public GitHub issue.

---

As for this issue, the only things I'm grabbing from webpack right now are:

1. React, for overriding rendering of chat lines and potentially other content as well.
2. The chat message type enums.
3. The extension service, used for unregistering the current player when destroying and recreating a player to reset its state.
4. A module I've taken to calling `core` that contain a list of all current Twitch experiments as well as code for determining their current state.

I'll have to consider moving away from using require if I can't think up a way to deal with the lazy loading issue. I hope it doesn't come to that. Having to include my own copy of React for access to `createElement` and `Component` seems less than optimal, if that will work at all.

Those other things aren't nearly as big an issue, though I'd like to keep access to the experiments controller for checking state. It's nice for debugging reported errors.

**Comment by conover** [comment]
@TheLarkInn, we were able to resolve this issue outside of this thread. Thanks for offering your expertise.
