### ISSUE TITLE
[Feature] Hiding reruns

### ISSUE THREAD

**Issue by gempir** [FrankerFaceZ/FrankerFaceZ#441]
Reruns are annoying and I don't understand why Twitch would even show them in your following list.
FFZ could have an option to hide reruns from appearing in the following list.

**Comment by SirStendec** [comment]
This is already a feature. Directory > Channels. Do not show reruns in the directory. 
![image](https://user-images.githubusercontent.com/14036657/40274054-92713824-5b9b-11e8-9a3d-b869b2b23a40.png)
