### ISSUE TITLE
[Feature Request] Option to have deleted messages displayed without having to be clicked

### ISSUE THREAD

**Issue by dpython** [FrankerFaceZ/FrankerFaceZ#442]
As the title suggests, would it be possible to add an option that allows deleted messages to be displayed as default like in BTTV instead of me having to click on it every time?
is such an option already implemented?

**Comment by doubledgedboard** [comment]
@SirStendec Can we reopen this?

I'm proposing the removal of the strikethrough.

```
	.message {
		text-decoration: line-through;
```

The request was for BTTV-like behavior. BTTV does not put a line through the message. I prefer the way BTTV does it (does not make it unreadable).

In addition, FFZ is now stomping over the BTTV setting, when previously it left it unaffected, so I could use both in tandem without issues (letting BTTV handle deleted messages and FFZ left it alone).

**Comment by SirStendec** [comment]
Added a new setting to let you remove the strike in 089bc6d715bc5a9819dcd3f4e44731b254bafc40
