### ISSUE TITLE
[Feature Request] Room status indicator.

### ISSUE THREAD

**Issue by androiduser3** [FrankerFaceZ/FrankerFaceZ#443]
Web Browser: Google Chrome.

Do you use BetterTTV or other Twitch extensions: BTTV and FrankerFaceZ Add-On Pack

I would like to request a feature that was in old FFZ, room status indicator.
You know the r9k/sub/slow etc. I like this feature so much now I'm missing it.

Also if possible add pin highlighted messages at top, with a timeout configuration. This is available in BTTV but FFZ overrides(?) the BTTV chat so I can't use it. Maybe just make it available when having BTTV and FFZ installed somehow.

Thanks.

EDIT: I forgot another one, also was in old FFZ, can you bring back notification of duration of timed out/bans? The current one lacks this feature so I don't know who are timed out or banned its just the chatter's message goes dark.

**Comment by Doc94** [comment]
Well i like the "status" to show the actuall rules like the slow,r9k,sub,emoteonly
"this comment its to UP"

**Comment by pointydev** [comment]
If this were to be added back, a way that slow mode could be represented is by putting the total slow time in the chat message placeholder, where the indicator already is:
![](https://pointy.needs-to-s.top/2ThsaUw.png)
