### ISSUE TITLE
BTTV Badges.

### ISSUE THREAD

**Issue by arulas1** [FrankerFaceZ/FrankerFaceZ#447]
**Web Browser**: Chrome

**Do you use BetterTTV or other Twitch extensions**: BTTV.

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**: BTTV Dev badges (Support, Emote Approver) not showing with FFZ Enabled. Would be nice for them to be enabled by default, and have the option to disable, via Settings -> Chat -> Badges down the bottom. The same way FFZ has the option to disable Bot, FFZ Dev and FFZ Supporter tags.

**Steps to Reproduce (if Applicable)**:

**Comment by robsdedude** [comment]
Not seeing BTTV Bot badges is a reason for me to abandon FrankerFaceZ
