### ISSUE TITLE
[Feature Request] Merge Subscribed and Followed Channels on Sidebar

### ISSUE THREAD

**Issue by Freezinater** [FrankerFaceZ/FrankerFaceZ#449]
**Web Browser**: Google Chrome

**Do you use BetterTTV or other Twitch extensions**: FFZ Add-On Pack

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: N/A

**Bug / Idea**: As of late, Twitch as introduced to the left sidebar a section for channels that you are subscribed to that are live, which appears above the original section for live channels you are following. Personally I don't really like it as it clutters it up a bit more than it needs to be and I request that there be a setting that merges these back together essentially reverting it to how it previously was.

**Steps to Reproduce (if Applicable)**: N/A

**Comment by Zoooook** [comment]
Now that Twitch has removed this feature, I'd like to see it re-implemented, even if it means I have to manually maintain my list of subscribed channels.

**Comment by Silvonika** [comment]
It'd be nice to either minimize it all together or allow us to move the friends list above it, as of right now it shows way too many pushing my friend's list off the initial screen that I need to scroll down every time to view the friends list.
