### ISSUE TITLE
Current Stream Uptime No Longer Showing On Channels In The Directory

### ISSUE THREAD

**Issue by Mikeasjkdhfg** [FrankerFaceZ/FrankerFaceZ#450]
**Web Browser**: Version 66.0.3359.181 (Official Build) (64-bit)

**Do you use BetterTTV or other Twitch extensions**:
FFZ AP
**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**:

Title

**Steps to Reproduce (if Applicable)**:

**Comment by Iron-Pangolin** [comment]
I'm having the same issue suddenly.

**Web Browser:** 
Firefox 60.0.2 (64-bit)

**Do you use BetterTTV or other Twitch extensions:**
FFZ:AP

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable):**
NA

**Bug / Idea:**
When changing Directory > Channels > Stream Uptime to enabled it does not show the uptime on the directory page. Toggling this and refreshing does not help.

**Steps to Reproduce (if Applicable):**
Not sure how it was produced, tried restarting web browser as well.
