### ISSUE TITLE
Inline Actions ban button doesnt change to unban button

### ISSUE THREAD

**Issue by mattts1** [FrankerFaceZ/FrankerFaceZ#451]
**Web Browser**: Chrome

**Do you use BetterTTV or other Twitch extensions**: Yes

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**: Having an inline actions ban button setup to change to an unban button when someone is banned doesn't work. It stays a ban button. It also happens when the timeout button is supposed to chance to a untimeout button.

**Steps to Reproduce (if Applicable)**:

**Comment by SirStendec** [comment]
It's working fine here. Please post a screenshot of your In-Line Action configuration.

**Comment by mattts1** [comment]
[https://i.imgur.com/hWUTPDP.png](url)

**Comment by mattts1** [comment]
I opened Chrome today with my customized inline actions reset and when I redid them. This problem ceased to exist.. Works as intended now.
