### ISSUE TITLE
Don't tab complete own username

### ISSUE THREAD

**Issue by freaktechnik** [FrankerFaceZ/FrankerFaceZ#453]
**Web Browser**: Firefox Nightly

**Do you use BetterTTV or other Twitch extensions**: No, FFZ:AP though

**Bug / Idea**:
Currently, your own username will tab complete too. That seems rather unexpected to me. I guess this is in the "fixing Twitch bugs" category. It'd be nice if the tab completion only suggested other's usernames. At least prefer other usernames over your own, because usually you'd reply to other people, not mention yourself.

**Steps to Reproduce (if Applicable)**:
Start typing your username, except that others should also be available. So in my case I'd start typing fre and press tab, expecting to mention the other user starting with fre that is in chat (fredben or similar) but instead it completes to freaktechnik (because a comes before d).

**Comment by Lordmau5** [comment]
Apparently Twitch has removed your own username from the mention tab-completion ever since this issue was opened.

Gonna go ahead and close this then :)

![image](https://user-images.githubusercontent.com/1345036/62993703-30cd4000-be8b-11e9-9075-0b1de5a6d05f.png)
