### ISSUE TITLE
Unwanted Reruns and Missing Boxarts

### ISSUE THREAD

**Issue by Tsunami2069** [FrankerFaceZ/FrankerFaceZ#454]
Hello.

**Bug / Idea**:
Just a little feedback on a possible issue / bug.

Recently, I've been noticing that reruns are showing on my Following list.
I have the option to NOT show them on my FFZ options, as you can see on the screenshot that i'm attaching.

Additionally, I also have the option to show the game boxart on my thumbnails but they aren't showing up.

Screenshot:
![snip1](https://user-images.githubusercontent.com/14236716/41287020-50bb81ae-6e39-11e8-95d7-a5bd5ffefa2b.JPG)

**Web Browser**: Google Chrome

**Do you use BetterTTV or other Twitch extensions**: No

**Comment by gempir** [comment]
I can reproduce this big in only 1 way. When you follow a lot of people and most of them are live you will get a Grey Box to "View All Live Channels" on the following page.

If you click that box also reruns will show up.
