### ISSUE TITLE
Video has a scrollbar and out of frame

### ISSUE THREAD

**Issue by 1ll3g4l** [FrankerFaceZ/FrankerFaceZ#455]
**Web Browser**:
Firefox 61.0b13 64 bit
**Do you use BetterTTV or other Twitch extensions**:
No
**Bug / Idea**:
https://i.imgur.com/Z6QLmvn.png (incorrect, frankz enabled)
https://i.imgur.com/pZ8nEMH.jpg (correct, frankz disabled)
**Steps to Reproduce (if Applicable)**:
Not sure, sorry.
However, it happens on every stream I've checked thus far.

**Comment by SirStendec** [comment]
This is not a FrankerFaceZ specific issue. People are seeing it without any extensions. As far as I know, Twitch is currently deploying a fix for it so try refreshing.
