### ISSUE TITLE
In-Line Actions not showing

### ISSUE THREAD

**Issue by HappyPoison** [FrankerFaceZ/FrankerFaceZ#456]
**Web Browser**:Chrome

**Do you use BetterTTV or other Twitch extensions**: I use "The FFZ Add-on Pack" extension currently but also had this issues with no extension as well as using BetterTTV alongside FFZ

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: Not applicable 

**Bug / Idea**: The In-Line Actions are not showing up (custom)

**Steps to Reproduce (if Applicable)**:
![capture22](https://user-images.githubusercontent.com/40253169/41386562-f34a67e8-6f4f-11e8-9bdf-1b9e98ecab8f.PNG)

**Comment by KSib** [comment]
Did anything ever happen with this?
