### ISSUE TITLE
When clearing history, settings reset to default.

### ISSUE THREAD

**Issue by Zipliopolic** [FrankerFaceZ/FrankerFaceZ#457]
**Web Browser**: Google Chrome

**Do you use BetterTTV or other Twitch extensions**: FFZ addon

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**: When clearing history, settings reset to default. Have to go back & re-do it all. Maybe also give a backup settings option.

**Steps to Reproduce (if Applicable)**:

**Comment by SirStendec** [comment]
Clearing history is not the problem. You are also clearing local storage. You'll need to stop doing that. It's unnecessary and used for legitimate purposes by a lot of websites and tools, including FrankerFaceZ.

We will be bringing backup and restore back in the future, but we currently have no plans to move away from local storage as a method of storing settings.
