### ISSUE TITLE
Safari 12 blocks safariextz extensions

### ISSUE THREAD

**Issue by TheSpyder** [FrankerFaceZ/FrankerFaceZ#458]
Just a quick note in case you weren't aware. Safari 12 is changing how extensions work - they're deprecating `safariextz` completely - and more than that, effective immediately developer-signed extensions don't work :(

https://developer.apple.com/safari/whats-new/
> Support for developer-signed .safariextz Safari Extensions in Safari 12 on macOS has been removed. They no longer appear in Safari preferences and cannot be enabled. On first launch users will receive a warning notification and these extension will not load.

The new restrictions are already active in tech preview:

https://developer.apple.com/safari/download/
<img width="434" alt="ffz safari 12" src="https://user-images.githubusercontent.com/298292/41467605-7f5e5bae-70ea-11e8-8a91-b74b81f97652.png">

This seems like pretty bad news for FrankerFaceZ, and if Apple follow their usual pattern it will be released in September/October.

**Comment by TheSpyder** [comment]
That's not a particularly _good_ workaround, though, because you have to re-apply it every time you restart Safari.

**Comment by SirStendec** [comment]
We don't intend to release a newer extension for Safari at this time. Apple is, quite frankly, ridiculous. I'm not spending a ridiculous amount of money first on another computer, and then on licensing, and then probably more development time on top of that to make sure FFZ fits their guidelines. No.

Safari users should instead use the user script version of FrankerFaceZ with Greasemonkey or any other method of loading user scripts. We'll update the instructions on our website for Safari soon.

**Comment by TheSpyder** [comment]
I disagree with it being ridiculous, but I totally understand it's not worth the investment if you don't already have a mac developer to help. I'd offer myself but I'm not sure I have enough spare time at the moment :)

Thanks for clarifying :)
