### ISSUE TITLE
[Feature Request] Unpair Settings for Following Data

### ISSUE THREAD

**Issue by Anonic** [FrankerFaceZ/FrankerFaceZ#46]
As it stands the feature functions as:

Following Data
Display the number of live channels you're following on the sidebar, and list the channels in a tooltip.

I'd prefer the option for more customization by splitting it in to two settings such as (I'm bad at succinct naming):

Live Channels Followed
Display the number of live channels you're following on the sidebar.

Followed Channels Tooltip
List the live channels you're following in a tooltip.

**Comment by Anonic** [comment]
Or basically I'd prefer if I could have the number but disable the tooltip.

**Comment by SirStendec** [comment]
What's your reasoning for a setting to disable the tooltip? Being that it's a tooltip, it only exists when you're purposefully interacting with that element. It's not like it gets in the way.

Disabling the tooltip only wouldn't even save resources as I'd still be refreshing the followed channels collection to get the number, and that contains the channel information.

**Comment by Anonic** [comment]
Honestly I was pretty hesitant on even posting this one, and probably shouldn't have. It's comically minor and subjective.

Both times I've started to use FFZ its just stood out in my mind as something aesthetically unpleasing and jarring during the initial usage period. It breaks the formatting of the sidebar by creating more than a line of information.

>Disabling the tooltip only wouldn't even save resources as I'd still be refreshing the followed channels collection to get the number, and that contains the channel information.

That's definitely the only realistic reason for the change's nail in the coffin. I'm going to close this one.
