### ISSUE TITLE
FFZ emote menu doesn't work on FireFox 56

### ISSUE THREAD

**Issue by RooTeeM** [FrankerFaceZ/FrankerFaceZ#461]
**Web Browser**: Firefox 56.0.2

**Do you use BetterTTV or other Twitch extensions**: BetterTTV 

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**: FFZ emotes menu doesn't appear.

**Steps to Reproduce (if Applicable)**:

I have tried it on Chrome and it works fine, but in FF it won't work.

**Comment by SirStendec** [comment]
I assume you're using Windows 10? Firefox 56 would be subject to this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1452619

Nothing we can do about that, so you'll need to update your browser.
