### ISSUE TITLE
Overlay Extensions are shown despite being turned off.

### ISSUE THREAD

**Issue by budbutler** [FrankerFaceZ/FrankerFaceZ#463]
**Web Browser**:
Chrome 67.0.3396.87(official 64 bit)
**Do you use BetterTTV or other Twitch extensions**:
No extra addons
**Bug / Idea**:
Show overlay extension is set to Never, but extensions are still shown on stream.
Steps to Reproduce (if Applicable):
ffz control center > Channel >player, set show overlay extensions to never.

**Comment by SirStendec** [comment]
Fixed in 038270d232bd1a70f9d8e0dfc95f9aab9ef8dd07
