### ISSUE TITLE
Settings Under Directory > Channels Not Working

### ISSUE THREAD

**Issue by dastrdly6585** [FrankerFaceZ/FrankerFaceZ#466]
**Web Browser**:
Google Chrome - Version 67.0.3396.87 (Official Build) (64-bit)
Firefox - Version 60.0.2 (64-bit)

**Do you use BetterTTV or other Twitch extensions**:
FFZ: AP

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:
There is no such option to select "About" under the FFZ control panel, so I don't have logs to attach.

**Bug / Idea**:
All the settings under Directory > Channels do not properly affect live channels in the various directories:
1. "Channel Avatars" - Does nothing in all directories
2. "Do not show reruns in the directory" - When active, I can still see reruns listed under the live channels on the Following page and on the Browse page when showing Channels.  Clicking into individual game and community directories, reruns are correctly hidden.
3. "Do not show the Live indicator on channels that are live" - When active, does not work under individual game and community directories (correctly hides indicator on Following page and Browse > Channels)
4. "Show Boxart" - Does nothing in all directories
5. "Stream Uptime" - Does nothing in all directories

**Steps to Reproduce**:
Activate any of the settings above and navigate to a directory which should be affected by the setting change.  Twitch page has not been changed as the FFZ setting indicates.

**Comment by derickso** [comment]
Not fixed
