### ISSUE TITLE
Enable channel hosting setting stopped having an effect

### ISSUE THREAD

**Issue by SaunaCowboy** [FrankerFaceZ/FrankerFaceZ#468]
**Web Browser**: 
Opera 53.0
Chrome 67.0.3396.87

**Do you use BetterTTV or other Twitch extensions**: 
FFZ Add-on pack and The FFZ Enhancing add-on.  No other twitch extensions

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**:
Up until sometime Thursday  June 21st the "Enable Channel Hosting" setting was working as intended with minor bugs.  At some point during the day the setting stopped having any effect.

**Steps to Reproduce (if Applicable)**:

**Comment by SirStendec** [comment]
Fixed in 038270d232bd1a70f9d8e0dfc95f9aab9ef8dd07
