### ISSUE TITLE
Using emotes when typing /me replace wrong parts of text

### ISSUE THREAD

**Issue by lclc98** [FrankerFaceZ/FrankerFaceZ#469]
**Web Browser**: Firefox 61.0

**Do you use BetterTTV or other Twitch extensions**: Yes, Global Twitch Emotes. But tested without and the issue still occurs

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**: When typing /me in front of emotes it doesn't replace, or it replaces the wrong text
https://imgur.com/vzgLYxgl.png
It is affected by how many words are in the sentence. 
It is only /me

**Steps to Reproduce (if Applicable)**:
Typing
1. `/me CurseLit` 
2. `/me CurseLit One` 
3. `/me CurseLit One Two`
4. `/me CurseLit One Two Three`

**Comment by SirStendec** [comment]
This is a bug with Twitch's chat code. I've pushed a temporary fix in 038270d232bd1a70f9d8e0dfc95f9aab9ef8dd07 and also sent an issue up the chain. Thanks for the report.
