### ISSUE TITLE
Turbo emote :> not showing

### ISSUE THREAD

**Issue by Fazh741** [FrankerFaceZ/FrankerFaceZ#472]
**Web Browser**: Chrome

**Do you use BetterTTV or other Twitch extensions**: BTTV + FFZ pack

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**: a turbo monkey emote smiling with a heart flying above :> does not show in chat

**Steps to Reproduce (if Applicable)**:

**Comment by SaunaCowboy** [comment]
Also commented on this but my report was deleted.  They show for other people.  You can see other peoples.  In your own chat you can't see your emote.

**Comment by Fazh741** [comment]
the emote shows in my phone but it doesn't in PC...weird !

**Comment by SaunaCowboy** [comment]
It shows in a browser running no twitch addons or bttv only.  As soon as it's ffz with any other addon it stops working.  I'm guessing your phone isn't running ffz so it's not that weird.

**Comment by SaunaCowboy** [comment]
This seems to be fixed now
