### ISSUE TITLE
Mod option of timeout/ban -slidebar missing

### ISSUE THREAD

**Issue by Peelotar** [FrankerFaceZ/FrankerFaceZ#473]
When using the FrankerFaceZ on Mozilla Firefox, I've had this really useful mod option, where you can rightclick chat-usernames of the channel and it opens a slide-bar of timeout lenght/ban options. 
(Picture of the option mentioned: https://cdn.discordapp.com/attachments/454605888817332234/454607720734261258/unknown.png). 

For some reason this hasn't been available for me the last couple of days and I would want it back. 
Is the option missing because my settings somehow, or is it a bug?

**Comment by Lordmau5** [comment]
That was never, *ever* implemented in FFZ. It was a feature of another extension.

**Comment by Peelotar** [comment]
Oh, I totally thought it came with FrankerFaceZ, my apologies. Thank you for the fast answer ♥
