### ISSUE TITLE
Message of "\o/" isn't appearing

### ISSUE THREAD

**Issue by timeshifter** [FrankerFaceZ/FrankerFaceZ#476]
**Web Browser**:
Chrome

**Do you use BetterTTV or other Twitch extensions**:
FFZ Add-on pack

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**:
The message "\o/" doesn't appear in my chat stream when sent, but it *is* being sent, as seen from the raw IRC stream and a browser in incognito mode.

**Steps to Reproduce (if Applicable)**:
Just type "\o/"

**Comment by SirStendec** [comment]
Twitch chat is broken. The `\` character causes problems on the server. Try sending `\t`. You can't. It literally can't appear in a message.  The handling is also broken in official clients. FrankerFaceZ has nothing to do with the message `\o/` not appearing locally when you send it.
