### ISSUE TITLE
FFZ AP: Chat window locking up (gamewisp error?)

### ISSUE THREAD

**Issue by chozandrias76** [FrankerFaceZ/FrankerFaceZ#477]
**Web Browser**: 
Chrome Version 67.0.3396.99 (Official Build) (64-bit)

**Do you use BetterTTV or other Twitch extensions**: 
Tampermonkey?
Gamewisp?

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:
`logging.js:92 FFZ [addon.ffzap.gamewisp]: Socket: Lost connection to socket server...
invoke @ logging.js:92
error @ logging.js:43
parent.site.getUser._connected._connecting.socket.onclose @ socket.js:69
logging.js:86 FFZ [addon.ffzap.gamewisp]: Socket: Trying to reconnect to socket server...
logging.js:86 FFZ [addon.ffzap.gamewisp]: Socket: Connecting to socket server...
logging.js:92 FFZ [addon.ffzap.gamewisp]: Socket: Error from socket server.
invoke @ logging.js:92
logging.js:86 FFZ [addon.ffzap.gamewisp]: Socket: Trying to reconnect to socket server...
socket.js:28 WebSocket connection to 'wss://emotes.gamewisp.com/' failed: Error during WebSocket handshake: Unexpected response code: 503
connect @ socket.js:28
logging.js:86 FFZ [addon.ffzap.gamewisp]: Socket: Connecting to socket server...
logging.js:92 FFZ [addon.ffzap.gamewisp]: Socket: Error from socket server.
invoke @ logging.js:92
logging.js:86 FFZ [addon.ffzap.gamewisp]: Socket: Trying to reconnect to socket server...
socket.js:28 WebSocket connection to 'wss://emotes.gamewisp.com/' failed: Error during WebSocket handshake: Unexpected response code: 504
connect @ socket.js:28
logging.js:86 FFZ [addon.ffzap.gamewisp]: Socket: Connecting to socket server...
logging.js:86 FFZ [addon.ffzap.gamewisp]: Socket: Connected to socket server.
logging.js:86 FFZ [site.fine]: Found class for "chat-settings" at depth 10
logging.js:86 FFZ [main_menu]: Built Tree in 12.00000ms with 82 structure nodes and 108 settings nodes.
logging.js:86 FFZ [chat.emotes]: Unloaded emote set #addon--ffzap.gamewisp--emotes-global: Global Emotes`

**Bug / Idea**: 

Chat region locking up. Seems to stop bugging out when tabbing away and back, because i've seen my chat bar fill up with queued text.

**Steps to Reproduce (if Applicable)**:

1. Follow all the steps to get FFZAP.
2. Someday your chat randomly locks up.
3. Open console to see gamewisp timing out.

**Comment by chozandrias76** [comment]
Also, I resolved the issue (I think, by disabling gamewisp entirely)

**Comment by Lordmau5** [comment]
Gonna chime in here.

GameWisp's socket errors shouldn't cause anything in regards to the chat locking up...
I say _"shouldn't"_, as I'm not 100% sure if it's really not doing anything. I'll have to investigate that a bit more.

I've personally had several issue reports in regards to chat, or Twitch in general, where they went away after a quick page reload...
So yeah, difficult to reproduce those issues :P

**Comment by chozandrias76** [comment]
Yeah refreshing fixed it temporarily. Disabling it made the issue really go away. Could be a twitch snafu though so who knows.

**Comment by chozandrias76** [comment]
Nevermind, I'm a complete liar.
Colin Swenson-Healey

colin.p.swensonh@gmail.com
chozandrias76@gmail.com
