### ISSUE TITLE
In-Line Actions are not centered properly when "Emote Alignment" is set to "Padded"

### ISSUE THREAD

**Issue by JackyyTV** [FrankerFaceZ/FrankerFaceZ#479]
**Web Browser**: Google Chrome 67.0.3396.99 64-bit on Windows 10

**Do you use BetterTTV or other Twitch extensions**: Yes, FFZ:AP

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: N/A

**Bug / Idea**:
When the "Emote Alignment" setting is set to "Padded", In-Line Actions on messages containing 28x28 (or bigger) emotes gets shifted to the bottom of the message, instead of centered like a regular message should do.

Emote Alignment on Standard:
![image](https://user-images.githubusercontent.com/11830494/42732660-e8ec3dfa-8857-11e8-8a08-0aa2ef20dd96.png)

Emote Alignment on Padded:
![image](https://user-images.githubusercontent.com/11830494/42732650-c3b2af7e-8857-11e8-8245-f03fc9ca726f.png)

Emote Alignment on Baseline:
![image](https://user-images.githubusercontent.com/11830494/42732665-fe033888-8857-11e8-94d7-380c3b3d84df.png)

As you can see, the In-Line Actions are very obviously off-centered when it's on Padded Emote Alignment.

**Steps to Reproduce (if Applicable)**:
1. FFZ Settings -> Chat -> Appearance -> Chat Lines -> Set Emote Alignment to Padded
2. Send a message containing an emote that is 28x28 or bigger

**Comment by mattts1** [comment]
Another example of the the spacing issue:
![2018-07-15_20-38-01](https://user-images.githubusercontent.com/1266711/42740231-3e94ff16-8872-11e8-92ca-073b225c7152.jpg)

**Comment by JackyyTV** [comment]
Can confirm, fixed via c139de9.
