### ISSUE TITLE
[Feature Request] Local Sub/Mod Only Modes

### ISSUE THREAD

**Issue by AwesomeOutcast** [FrankerFaceZ/FrankerFaceZ#48]
**Bug / Idea**:
Local Sub/Mod Only modes
BTTV has a neat little feature to enable a local sub/mod only mode. This is sometimes helpful because I  don't always want to see the spam from viewers, and big channels can get hectic. I thought it might be nice to have that on FFZ.

**Comment by SirStendec** [comment]
Going to fold this into #82 to avoid cluttering up the issues.
