### ISSUE TITLE
Pogs are small in VODs.

### ISSUE THREAD

**Issue by serg06** [FrankerFaceZ/FrankerFaceZ#488]
**Web Browser**:

Chrome 67.0.3396.99 (Official Build) (64-bit)

**Do you use BetterTTV or other Twitch extensions**:

BTTV, FFZ.

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**:

All my Pogs are lidl:

![lidl pogs](https://i.imgur.com/rLMnxR6.png)

**Steps to Reproduce (if Applicable)**:

Watch any vod with POGs, e.g. https://www.twitch.tv/videos/286616599 around 1:02:25 (that's when the ss was taken.)

**Comment by SirStendec** [comment]
FrankerFaceZ hasn't had support for Chat on Videos, so emotes you see there have been added by another extension. However, I just pushed our own Chat on Videos support tonight so this will be "fixed" starting with 5a7a4f3ea9da0af542eb4f8612aacece6956459a
