### ISSUE TITLE
Emotes Menu not responsive when reducing Chat width 

### ISSUE THREAD

**Issue by HekutoruMAC** [FrankerFaceZ/FrankerFaceZ#491]
**Web Browser**: Chrome

**Do you use BetterTTV or other Twitch extensions**: No

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: No

**Bug / Idea**: Make Emotes Menu responsive to Chat width changes.

**Steps to Reproduce (if Applicable)**:
1. Reduce Chat width in Chat Appearance options.
2. Emotes Menu gets chopped.

**Comment by Lordmau5** [comment]
FFZ's emote menu works fine with a smaller chat (tried with 200px width) so I'm going to go ahead and close this issue.
