### ISSUE TITLE
Option to Hide Messages w/ Blocked Terms not Saving

### ISSUE THREAD

**Issue by Freezinater** [FrankerFaceZ/FrankerFaceZ#499]
**Web Browser**: Chrome

**Do you use BetterTTV or other Twitch extensions**: FFZ Add-On Pack

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**: Every time I try to hide messages that have blocked terms, the button will appear to show that it was toggled, but if I close the control center and keep an eye on chat, these messages still show with the blocked terms blocked out. Going back into the control center will show that the button reset back to its previous state.

**Steps to Reproduce (if Applicable)**:
1. Open the Control Center.
2. Go to Chat > Filtering.
3. Add a blocked term if you don't have any already.
4. Toggle visibility for messages with blocked terms so that it appears that they are disabled.
5. Close the Control Center.
6. Open the Control Center and go back to Chat > Filtering.
7. The visibility toggle will be back in its previous state.

**Comment by SirStendec** [comment]
You need to click Save after you toggle visibility. Sorry, I know it's a bit unclear and strange when every *other* setting automatically saves. The next big settings refresh is going to include a warning against unsaved changes.

(PS. If I'm making the wrong assumption here and it really is bugged, reply to this and I'll re-open the issue and look into things.)

**Comment by Freezinater** [comment]
It was even less clear, actually. I thought it was a global toggle for all blocked terms as a whole. I didn't think to edit existing terms to toggle visibility one at a time. Perhaps add a toggle that will modify visibility for all terms at once. I only had 3, but some who may want them all gone may have to go through many more. Regardless, thanks for the heads-up.
