### ISSUE TITLE
[Feature request] Stay in chat on right drawer (chat) close and reopen

### ISSUE THREAD

**Issue by RedSnt** [FrankerFaceZ/FrankerFaceZ#5]
So this one requires a bit of explanation I'm sure:
Currently when you open the right drawer (chat) for the first time all of what has been written in chat (to the scrollback limit, 150 usually) is displayed meaning that you're logged into chat. But as soon as you close it you get logged out of chat, so when you open chat again you won't be able to see what has been written as you would had you just opened chat for the first time on a refresh of the page.  

I'm not sure if this is intentional to reduce traffic for twitch's chat servers or what, but it would be nice if there was a feature to remain logged in to chat when you close it and reopen it multiple times during a stream. 

Also, not sure if this is even possible.

**Comment by SirStendec** [comment]
This is both to reduce traffic, and to reduce load on the client. Even when chat messages aren't being displayed, it has to process them in the background if it's connected to chat. On slower machines it's desirable to prevent all unnecessary work to make the video play as best it can.

I'll look at the code when I have a bit of free time but this probably won't be implemented.
