### ISSUE TITLE
[Feature Request] Disable Features Completely

### ISSUE THREAD

**Issue by doubledgedboard** [FrankerFaceZ/FrankerFaceZ#500]
**Web Browser**: Chrome

**Do you use BetterTTV or other Twitch extensions**: BTTV

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: N\A

**Bug / Idea**:

Currently I'm noticing more and more issues with trying to use BTTV and FFZ together, This appears to be due to FFZ more than BTTV, as FFZ does not allow me to disable many of its features, as it instead 'takes control' of aspects of the page load and blocks BTTV features from working.

I would like to request the ability to actually disable components of FFZ from loading, rather than having them simply default to their normal or default behavior.

An example is that I prefer using BTTV to handle deleted messages, so I would like to completely disable the `Chat->Behavior` section of FFZ.

Currently, as long as FFZ is installed, it takes precedence. (This seems to have changed in the last week or two).

**Steps to Reproduce (if Applicable)**: N\A

**Comment by SirStendec** [comment]
Well, this is a broad request. In short, no. Development time and testing already takes enough of my time. We don't have a big enough team (or any team, it's just me) to add a switch to, say, turn off all of chat processing.

FrankerFaceZ taking priority is not a design goal. It's just loading order or, alternatively, it has to do with having a lower level implementation of certain features. I don't go out of my way to break BetterTTV, just like they don't go out of the way to break FrankerFaceZ. That said, I also don't have time to test everything with BetterTTV. Some features are also inherently more difficult to support with both extensions at once.

As for the specific feature you mentioned, I pushed an initial, basic version of chat filtering two weeks ago as part of allowing people to block messages containing certain words. That is why it was 'changed' in the last week or two, as you say. There are more, related features coming that depend on the same hook.

I won't be adding a way to disable it. That said, I'm fine with your request in that comment on #442 so I'll be adding more configuration for how deleted messages are displayed. Not sure when I'll get it pushed out.
