### ISSUE TITLE
Idea: Don't filter out your own messages

### ISSUE THREAD

**Issue by furai** [FrankerFaceZ/FrankerFaceZ#501]
**Idea**:
I'd like to see an option to be able to not block your own blacklisted words. 
So for example if you block certain keyword like command "!uptime" - all the messages sent by others should be filtered out/blocked but if it's sent by you - you should be able to see them. Would be cool to have an option for that when creating filter.

**Comment by SirStendec** [comment]
Added in 089bc6d715bc5a9819dcd3f4e44731b254bafc40
