### ISSUE TITLE
upstream timer idea

### ISSUE THREAD

**Issue by chief4** [FrankerFaceZ/FrankerFaceZ#502]
I have a idea for the upstream timer, why don't you guys make a custom player with a upstream timer on it, what do you guys think about that idea

**Comment by SirStendec** [comment]
The stream up-time display doesn't currently work with the new channel page layout that 20% of users are experiencing, but we'll be adding support for that soon. It will appear in the sidebar, near where the live viewer count and follower count are.

We don't want to put anything on top of the player. We personally think that putting anything other than controls on the player is just terrible.
