### ISSUE TITLE
Is it possible to have the sub and follow buttons returned to their old places?

### ISSUE THREAD

**Issue by thinkpad4** [FrankerFaceZ/FrankerFaceZ#503]
The latest infinite wisdom of Twitch has placed the sub and follow buttons in the side bar thing.  Since I disable the sidebar thing I can't see the sub or follow buttons anymore.  Is it possible to have a option to return the sub and follow buttons to their old places again?

Thank you very much

**Comment by Morten79** [comment]
Yes that is possible by switching an experiment flag in FFZ.
Open FFZ Control Panel, then on the left side scroll down until you see Debugging. Expand this group (tiny arrow) and under Experiments find the flag channel_page_redesign. The default value is "variant_a (weight: 20)". Change that value too -- Control (weight: 80) -- Finally do a page re-load and the controls should now be on top of the player as before. This "hack" will properly not work forever - enjoy it as long as possible :D

**Comment by thinkpad4** [comment]
@SirStendec would this be possible when the new layout is fully pushed to everyone?

**Comment by SirStendec** [comment]
I don't current plan on this. Really though, it's too early to say. I want to see how Twitch improves their design before they push it out to more people. I'll intervene if the new layout stays completely trash (like it is now), but I'm hoping it gets better.
