### ISSUE TITLE
FFZ installed and loads on TTV, but Control Centre greyed out

### ISSUE THREAD

**Issue by Anon-Nyx** [FrankerFaceZ/FrankerFaceZ#504]
**Web Browser**: Chrome

**Do you use BetterTTV or other Twitch extensions**: just BetterTTV

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: Can't get into menu so ditto.  Clicking the icon either up top or through the chat yield message: "There was an error displaying the menu." from www.twitch.tv.

Was able to find this in the Chrome Dev Tools console:
`Access to Script at 'https://cdn.frankerfacez.com/static/main-menu.adcf5b38c26d619902f8.js' from origin 'https://www.twitch.tv' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.twitch.tv' is therefore not allowed access. The response had HTTP status code 522.`
`console.js:35 FFZ [site.menu_button]: Error enabling main menu. Error: Loading chunk 0 failed.
    at HTMLScriptElement.onScriptComplete (bootstrap 90ae0d30297647f291d3:98)`

**Bug / Idea**: Was working on the initial launch of the Twitch updated UI.  Couple days later it stopped working.  Could be something that changed in Twitch's coding.

**Steps to Reproduce (if Applicable)**:  To be honest I don't know.  The problem persists and I've tried clearing cookies and cache and reinstalling, turning off/removing BTTV.  Searching has no yielded any fixes that I have been able to see.

**Comment by SirStendec** [comment]
Could you please visit https://cdn.frankerfacez.com/cdn-cgi/trace and tell me what you have for `colo=`?

**Comment by Anon-Nyx** [comment]
colo=LAX

**Comment by Anon-Nyx** [comment]
The control centre is now accessible this morning.  Let me know if you need anything else in regard to this (now fixed?) issue.

**Comment by SirStendec** [comment]
It was an issue with our web host. Things seem to be working now, but it might be time to find a new host soon. The problem has been cropping up more and more lately. Anyways, glad it's working for you. Closing this.
