### ISSUE TITLE
FFZ badge not appearing in chat

### ISSUE THREAD

**Issue by kickfliip** [FrankerFaceZ/FrankerFaceZ#506]
**Web Browser**: Chrome

**Do you use BetterTTV or other Twitch extensions**: None

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: 

**Bug / Idea**: Supporter badge isn't appearing after donating

**Steps to Reproduce (if Applicable)**: I supported and it says my badge is visible but I can't seem to get it to show up in chat

**Comment by megadarren** [comment]
hi my ffz badge isn't showing up either
