### ISSUE TITLE
Fullscreen video does not display correctly

### ISSUE THREAD

**Issue by PrgmrAtHrt** [FrankerFaceZ/FrankerFaceZ#508]
**Web Browser**: MS Edge

**Do you use BetterTTV or other Twitch extensions**: Yes (FrankerFaceZ Addon Pack)

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: N/A

**Bug / Idea**:  Refreshing video while in fullscreen causes the page to display improperly
![bug](https://user-images.githubusercontent.com/38510213/44131042-407ec834-a005-11e8-94c2-8f9deb23078c.png)

**Steps to Reproduce (if Applicable)**: Double click the X on the video player to refresh it.

**Comment by Lordmau5** [comment]
Seems like Twitch fixed this over the past year - I'm gonna go ahead and close this issue in that case.
