### ISSUE TITLE
Hosted Metadata the buttons needs more to the right side of the text

### ISSUE THREAD

**Issue by iiNinetales** [FrankerFaceZ/FrankerFaceZ#51]
**Web Browser**:
Google Chrome

**Do you use BetterTTV or other Twitch extensions**:
BTTV4FFZ

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:
N/A

**Bug / Idea**:
the buttons in the image below need to be moved to the other end when hosting like it is for non hosted channels or else it bugs out
![Bug](http://pushzz.xyz/img/c3abb.png)

**Steps to Reproduce (if Applicable)**:
go to any channel thats hosting someone

**Comment by SirStendec** [comment]
Don't close the issue. It's a legitimate issue. Just don't tweet at me too. It's annoying getting more than one notification over such a trivial issue.

**Comment by SirStendec** [comment]
Closed in 3.5.360 c8a7d65732b369b8b325aefc17fe8f8b319f85a6
