### ISSUE TITLE
a update to a feature? 

### ISSUE THREAD

**Issue by gamernation89** [FrankerFaceZ/FrankerFaceZ#511]
**Web Browser**: google chrome

**Do you use BetterTTV or other Twitch extensions**: i use bttv with frankerfacez

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**: can you update the blacklist feature so that i can still see the message in chat like we can now but their is no *** in the message because i rather not know 

**Steps to Reproduce (if Applicable)**:

**Comment by gamernation89** [comment]
![screenshot 1156](https://user-images.githubusercontent.com/19208617/44281247-1d11de00-a225-11e8-9fe5-db5b1c770321.png)
exactly like this but without the ***

**Comment by SirStendec** [comment]
I will not implement a feature like this. I feel that it's important to know that a message *has* been altered, and without the `×××`, there wouldn't be any feedback at all.

If it really bothers you that much, I'd suggest using ad-block or custom CSS to hide elements with the `.ffz--blocked` class.
