### ISSUE TITLE
Alignment issue in the "Reset Player" button

### ISSUE THREAD

**Issue by reaysawa** [FrankerFaceZ/FrankerFaceZ#512]
**Web Browser**: Firefox Quantum 61.0.1

**Do you use BetterTTV or other Twitch extensions**: No

**Bug**:

Currently the style implementation for `.ffz--player-reset` has all kinds of funky stuff to attempt to align the icon to the other buttons' baseline, but it doesn't actually work. The icon is also wrapped in a naked button tag with a pseudo-element, which causes all kinds of unpredictable spacing issues throughout different browsers.

![image](https://user-images.githubusercontent.com/17429390/44292802-5bc38a80-a25d-11e8-95b3-20a5ca7eb712.png)

I have tried to rework everything to flex layout and it aligns as it should, without the need for inner padding or wonky margin values.

Is there some work ongoing on this section or can I submit the PR?

**Comment by Tester798** [comment]
Same in Chrome, but not that obvious though:
![image](https://user-images.githubusercontent.com/8844478/46572931-b2fcf600-c996-11e8-848f-1b24c2c97d6b.png)
