### ISSUE TITLE
The overlay control context menu is partially hidden behind the player controlls.

### ISSUE THREAD

**Issue by Falqun** [FrankerFaceZ/FrankerFaceZ#514]
**Web Browser**: Mozilla/5.0 (X11; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0

**Do you use BetterTTV or other Twitch extensions**: BetterTTV and an overlay extension from Twitch. 

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**: When you set an overlay to be visible while the player controls are, and you want to configure it, the status bar will hide some settings. 
By configuring I mean the context menu you get by clicking the little button centred on the lower side of the player. It is partially hidden by the status bar, like shown in the screenshot.
![ffz_overlay_controll_hidden](https://user-images.githubusercontent.com/28984614/44528188-30bbb980-a6e9-11e8-832a-7cafda17b98d.png)
Id be happy if the menu would appear above the other controls.

**Steps to Reproduce (if Applicable)**: Enable the overlay extension and set to be visible when the controls are. Now click the little configuration thingy for the extension below the controls. The context menu is partially hidden.

**Comment by SirStendec** [comment]
There's no way to make the menu appear above that layer due to how the DOM is structured. The setting just isn't compatible with the new extensions UI. I won't be updating the feature. Just disable it if this is bothering you.
