### ISSUE TITLE
[Feature Request] Option to hide friends activity in chat

### ISSUE THREAD

**Issue by Jacky1356400** [FrankerFaceZ/FrankerFaceZ#52]
**Idea**:
As the title states, it would be great if there is an option to hide friends activity in chat, an annoying feature added by Twitch.
i.e.
Your friend [name] just started watching! HeyGuys
Your friend [name] is also watching! VoHiYo
I know with BTTV, you can hide them, but I don't use BTTV, only standalone FFZ, so it would be great if this feature is available.

**Comment by SirStendec** [comment]
This is already a feature.
![image](https://cloud.githubusercontent.com/assets/14036657/20156229/80163d1e-a69d-11e6-8858-9b9528219905.png)

**Comment by Jacky1356400** [comment]
Oh sorry my bad, didn't see it.
