### ISSUE TITLE
1 Billion views breaks stats alignment.

### ISSUE THREAD

**Issue by brianj64** [FrankerFaceZ/FrankerFaceZ#520]
**Web Browser**: Chrome x64

**Do you use BetterTTV or other Twitch extensions**: No BTTV, but i use FFZ Addon Pack

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**:  On the Riot Games channel, the channel reached 1 billion views(holy moly) and it now breaks the alignment of the FFZ stream stats such as Stream Uptime.

**Steps to Reproduce (if Applicable)**: go to twitch.tv/riotgames with stream stats on

**Comment by vigneshkum01** [comment]
I get misaligned stats on channels that are under 1 billion views. I have stream latency turned on as well and highlighting that pushes stream uptime to the left. I've attached a picture. 
![capture](https://user-images.githubusercontent.com/43321486/45599485-4eafcd80-b9ba-11e8-8816-4e18a248e62b.PNG)

**Comment by 2Head** [comment]
Same problem. Stream latency (number of seconds) also freezes after a while, so you need to reset player to see the correct value.
Also, the emote menu became smaller, so you need to scroll it more.
![image](https://user-images.githubusercontent.com/43323686/45600796-403dd200-ba0b-11e8-8020-9532e5e35cc1.png)
