### ISSUE TITLE
[Feature Request] Going Live Tweet for Streamers

### ISSUE THREAD

**Issue by RedxYeti** [FrankerFaceZ/FrankerFaceZ#529]
**Bug / Idea**:
Twitch used to have an option to automatically tweet when you go live but they removed the option.

if its not too complicated i was hoping you could add this feature back in maybe under a streamer settings drop down.

doesn't need to be too fancy, was thinking just a link account button and a box for the going live message you want.

thanks for all your hard work, been using ffz for i have no idea how long now :)

**Comment by Lordmau5** [comment]
Sending out tweets doesn't really fit into FFZ seeing as it's much more an extension that improves on the look and feel of Twitch. This is out of our scope, really.

Consider having a look at chat bots that offer this feature - I know StreamElements does :)
