### ISSUE TITLE
[Bug] Supporter badge is blank

### ISSUE THREAD

**Issue by lucasn1642** [FrankerFaceZ/FrankerFaceZ#53]
**Web Browser**: Chrome

**Do you use BetterTTV or other Twitch extensions**: BTTV4FFZ

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**: FFZ supporter/FFZ developer badge has no image

**Steps to Reproduce (if Applicable)**: Just find someone with an FFZ supporter or FFZ developer badge. It is just a solid color with no image.

**Comment by SirStendec** [comment]
I totally broke the server cause I'm a smart person. It's fixed now.
