### ISSUE TITLE
[site.compat_emote_menu]: Emote Menu for Twitch was not found after 60 seconds.

### ISSUE THREAD

**Issue by LimEJET** [FrankerFaceZ/FrankerFaceZ#536]
**Web Browser**: Firefox 63.0 x64

**FFZ version**: v4.0.0-rc13.6

**Log file**: [ffzlog.txt](https://gist.github.com/LimEJET/663138e8cc10d882a550d557e9b0b41a)

**Bug**: Emote menu remains in "loading" state forever. After a minute, console displays `FFZ [site.compat_emote_menu]: Emote Menu for Twitch was not found after 60 seconds.`.

**Details**: Tested with all other addons and builtin content blocking disabled.

**Comment by SirStendec** [comment]
That log message has nothing to do with the built-in emote menu. Rather, `Emote Menu for Twitch` is the name of a mildly popular emote menu extension used by some people. It's bundled into BetterTTV. This is just saying that it couldn't find that extension, so it isn't installing the handlers to make FFZ emotes appear in that menu.

If you disable the FFZ emote menu in settings, does the normal Twitch emote menu load correctly?

**Comment by LimEJET** [comment]
It does, yes.
