### ISSUE TITLE
Block button and Hide Thumbnails button for games are gone

### ISSUE THREAD

**Issue by MGLBrian** [FrankerFaceZ/FrankerFaceZ#538]
**Web Browser**: Tested w/ Chrome 69, Chrome 70, Firefox 63

**Do you use BetterTTV or other Twitch extensions**: On Chrome, I used (and tried disabling) FFZ:AP and uBlock Origin. On Firefox I only had core FFZ installed.

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: Sorry, I wasn't able to find any "About" section or any logs

**Bug / Idea**: There used to be a Block button and a Hide Thumbnails button on directory pages for specific games, next to the Follow button. They're not there anymore.
Notes:
- Disabling FFZ:AP and uBlock Origin doesn't fix this.
- FFZ still remembers all of the games I've blocked previously.

**Steps to Reproduce (if Applicable)**:
1. Open the Directory
2. Click any game to go to its directory page
3. There is only a Follow button

While I'm here, I'd like to add that I'd be interested in the feature requested in this other issue, which is to access a list of games I've blocked: https://github.com/FrankerFaceZ/FrankerFaceZ/issues/460 For me, it would suffice for such list to be as simple as a text blob that I could edit manually, so that I could adjust blocked games even if the buttons don't appear, and so that I could bring such list over to another computer (since profiles aren't ready yet).

Sorry if this is a known issue; I tried my best to see if it was. Thanks for your hard work.

**Comment by leandor** [comment]
I can confirm the same is happening to me on Vivaldi.

The functionality still works (games already blocked are hidden) but I can no longer hide games since some time ago.

Here's how it looks for a random game I'd had wanted to block these last past days:

![image](https://user-images.githubusercontent.com/1095373/48242513-5a1be580-e3ba-11e8-8fc1-996451cb28f5.png)

**Comment by leandor** [comment]
Thank you! I just noticed it is working again! :)
