### ISSUE TITLE
Automatic Theater Mode is broken (again)

### ISSUE THREAD

**Issue by CArchetype** [FrankerFaceZ/FrankerFaceZ#54]
**Web Browser**: Firefox 49.0.2

**Do you use BetterTTV or other Twitch extensions**: BTTV4FFZ

**Bug / Idea**: Automatic Theater Mode is broken

**Steps to Reproduce (if Applicable)**: enable automatic theater mode, go to stream, it doesn't go in theater mode. using FFZ 3.5.368

**Comment by SirStendec** [comment]
Looks like Twitch actually updated the player to exit theater mode when the page is set up. ... for reasons. (The also broke the player teardown code so it'll spam the console and cause slowdowns after enough time without refreshing...)

I'll have to investigate this more to figure out how to fix this.

**Comment by SirStendec** [comment]
This seems to have been fixed by Twitch code changes.
