### ISSUE TITLE
Emote Menu not opening

### ISSUE THREAD

**Issue by TetraxZ** [FrankerFaceZ/FrankerFaceZ#542]
**Web Browser**:
Google Chrome
**Do you use BetterTTV or other Twitch extensions**:
FFZ:AP

**Bug**:
Clicking the Emote Menu button does not open the emote menu, but it does glow like it was opened.

**Comment by SirStendec** [comment]
If you disable the FFZ emote menu in settings, does the normal Twitch emote menu load correctly?

**Comment by TetraxZ** [comment]
No it does not, the normal Twitch Emote Menu and the FFZ Emote Menu both have the same issue of glowing but not actually opening.

**Comment by SfSuicune** [comment]
Experienced the same problem in the latest Waterfox version. The solution is to delete Twitch related cookies/cache. In Firefox/Waterfox you can open the history, right click on a Twitch entry and tell it to forget the whole page. (Make sure you know your password.)
It's not that easy in chrome though, you have to dig deeper there. Dunno how it was there.

**Comment by eccccco** [comment]
had the same issue. deleting all twitch cookies alone did not help. deleting all twitch relating cache as SfSuicune described, did work after all. all my FFZ setting were gone though and I had no backup. Better make a backup of your ffz settings before you delete that cache.

**Comment by Gamertech** [comment]
This is coming back on Opera. Clearing Twitch cache and cookies fixes it, but it keeps returning.

Firefox only needed it once.

**Comment by SirStendec** [comment]
I've pushed out some changes that should address the emote menu not opening as of v4.0.0-rc13.14, which was released on the 9th.

Have any of you had problems with your emote menus since then?

**Comment by Gamertech** [comment]
Seems to be working for me since around then. Thanks for that mate!

**Comment by churine** [comment]
As of february and redownloading the last update, the bug seems to be occuring still on Firefox.

**Comment by xellosmetallum** [comment]
Problem has cropped back up for me. Can't open the emote menu at all. Disabled the ffz icon for the menu with no help, tried clearing cache and cookies also. 
Log is here: https://putco.de/MTA4MDk

**Comment by Lordmau5** [comment]
Seeing as the last report of this issue was around 5 months ago, we consider this resolved.

If something like this does come up again, don't hesitate to open up another issue though :)
