### ISSUE TITLE
Metadata not visible without scrolling down.

### ISSUE THREAD

**Issue by thinkpad4** [FrankerFaceZ/FrankerFaceZ#545]
**Web Browser**:
Chrome 70
**Do you use BetterTTV or other Twitch extensions**:
No
**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**:
The metadata used to be visible under the player without having to scroll down the page to see it, now I have to scroll down to see it 

**Steps to Reproduce (if Applicable)**:
Enable metadata Playback stats and you will have to scroll down to see the info everytime

https://i.imgur.com/aeITla4.jpg

It WAS showing without scrolling down on version 4.0.0-rc13.9 of FFZ and before, but starting with version 4.0.0-rc13.10 you need to scroll down to see the metadata

**Comment by pahakalle** [comment]
It does not seem to be a ffz issue. Still "broken" when disabling ffz

**Comment by pahakalle** [comment]
Seems like twitch decided to add it to the same section/div as the stream tags hence moving it down

**Comment by SirStendec** [comment]
Addressed in 49bcfaebeda79b948c6451800baf13fb1fc5c090 with the inclusion of a setting to re-order the channel info box to put the metadata line on top. 
![image](https://user-images.githubusercontent.com/14036657/49857713-3d137180-fdc1-11e8-8b14-8d9a3346158e.png)


I considered using CSS grid to make both the title and the metadata appear at the top, but I'm a bit worried that CSS for that would end up breaking when Twitch ends up inevitably making changes to the area again as part of them not realizing their channel page already looks fine. Or... *did* look fine at least.

I expect this setting to be more resilient against those changes.
