### ISSUE TITLE
Emote "D:" not working 

### ISSUE THREAD

**Issue by deelong87** [FrankerFaceZ/FrankerFaceZ#546]
**Web Browser**:
Chrome 
**Do you use BetterTTV or other Twitch extensions**:
No only FFZ with BTTV emote add on 
**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**:
D: does not show up in chat, all other emotes work 

**Steps to Reproduce (if Applicable)**:

**Comment by Lordmau5** [comment]
That's an issue with FFZ:AP and it's the default behaviour.

To enable `D:` and other BTTV Global Emotes that use non-alphanumeric characters, make sure this option in the FFZ:AP -> BetterTTV settings is enabled
![image](https://user-images.githubusercontent.com/1345036/49196808-bd32e380-f38c-11e8-8073-ba40c2811a5f.png)

**Comment by pahakalle** [comment]
@Lordmau5 With high usage of those emotes can it be made on by default

**Comment by Lordmau5** [comment]
Sure, can do.
Initially I wasn't too keen about that but seeing as a couple people brought it up already and also thought it was a bug, I might as well make it default from now on :)
