### ISSUE TITLE
Settings Export Missing

### ISSUE THREAD

**Issue by ToxiClay** [FrankerFaceZ/FrankerFaceZ#548]
**Web Browser**:

Chrome.

**Do you use BetterTTV or other Twitch extensions**:

Nope. FFZ and the Addon Pack.

**Bug / Idea**:

I can't seem to find any option to Export the current settings from FFZ for later re-importation. Is this a feature that's been permanently axed, or are there plans to re-include it later on in the dev cycle?

**Comment by wassereimer86** [comment]
+1

**Comment by pahakalle** [comment]
I think it will be added to the profile system when its finished.
