### ISSUE TITLE
Featured Channels Wont Disappear

### ISSUE THREAD

**Issue by FunkyPixie** [FrankerFaceZ/FrankerFaceZ#550]
**Web Browser**:

**Do you use BetterTTV or other Twitch extensions**:
I have The FFZ Addon Pack
**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**:
When I set Display Recommended Channels to Never the featured channels are still there in the side bar even if I refresh the page

**Steps to Reproduce (if Applicable)**:
Go to FFZ settings
Go to the layout section
set Display Recommended Channels to never
thats it

**Comment by EdC94** [comment]
Can confirm, got the same bug on Firefox

**Comment by starzonmyarmz** [comment]
Ditto

**Comment by Lordmau5** [comment]
Seems this has been fixed with one of the updates of FFZ that came out after the last message.

If this issue does come up again, please don't hesitate to open another issue for it :)
