### ISSUE TITLE
Emotes overlap

### ISSUE THREAD

**Issue by stefazenon** [FrankerFaceZ/FrankerFaceZ#555]
**Web Browser**: Chrome

**Do you use BetterTTV or other Twitch extensions**: No only FFZ + Addon Pack

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log; if Applicable)**: https://putco.de/OTczMg.brainfuck

**Bug / Idea**: The latest version seems to have broken emotes as they overlap now underneath each other instead of being padded and separated neatly.

**Steps to Reproduce (if Applicable)**: When I spam a lot of emotes around 12+ the emote overlaps.

**Comment by SirStendec** [comment]
Looks like I need to update the Emote Alignment CSS to go with the changed emote DOM. I'll get this fixed tomorrow. Thanks for the report.
