### ISSUE TITLE
Tooltip Location / Tooltip Flickering

### ISSUE THREAD

**Issue by PopGen33** [FrankerFaceZ/FrankerFaceZ#559]
Sorry if this is addressed elsewhere or if this is a 'just me' issue, but the location of the mouse-over tootips for emotes, badges, etc. seems to be incorrect. I often end up with the tooltips spawning on top of whatever I've moused-over causing them to flicker (e.g. mouse-over emote -> tooltip dislayed -> mouse is now over tooltip -> tooltip disappears -> repeat multiple times per second). 

I don't know if this is a bug or if tooltips are intended to spawn that way. If the later is true, it might be nice to add an x / y offset setting to the tooltip menu in FFZ settings to we can adjust this ourselves. 

I have a couple of screencaps showing this issue here: [https://imgur.com/a/cKC7rhQ](https://imgur.com/a/cKC7rhQ)
Descriptions for each image in that album explain what each image is trying to show.

Log/Settings: [https://putco.de/OTc2MA](https://putco.de/OTc2MA)

I'm using Chrome Version 71.0.3578.98 on Windows 10.

Also, if this is a 'just me' thing, I'd really appreciate any advice on fixing it. Thanks for your time.

**Comment by Lordmau5** [comment]
Do you have any other extensions installed that could potentially cause issues by changing certain aspects of Chrome? (Stylish / Stylus for custom styles, BTTV, something else, ...)

**Comment by PopGen33** [comment]
Sorry, it is an interaction with another extension. I had turned Stylish and Tampermonkey on and off while testing, but the extension that was actually the culprit was FoxClocks. I hadn't even thought about that one. Again, sorry about this. Thanks for your help.
