### ISSUE TITLE
[Bug report] Regex for filtering case insensitive

### ISSUE THREAD

**Issue by laagone** [FrankerFaceZ/FrankerFaceZ#561]
**Web Browser**:
Google Chrome 71.0.3578.98

**Do you use BetterTTV or other Twitch extensions**:
Yes (BTTV and FFZ:AP), but the problem persists when they're turned off.

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log; if Applicable)**:
https://putco.de/OTg1NA

**Bug / Idea**:
The option of using regex for filtering chat (banned and highlighted words) seems to be case insensitive. When the filtered word is `test` it also matches `TEST`, when it's `[A-C]` it also matches `a`, when it's `\u0058` it also matches `x`, and so on.

I use this feature to block emotes I'd rather not see from a certain streamer (relying on `[A-Z0-9]` because the first character after the prefix can't be lowercase), but regular words constantly get falsely matched.

**Steps to Reproduce (if Applicable)**:
I use the "Regex (Word)" option but I also see it happening with "Regex". From there it's pretty easy to reproduce with practically any keyword in a fast chat or when own messages are filtered.

**Comment by Gallion** [comment]
I am running into a similar issue when trying to filter out long stings of spam in caps. The following : (?=.{70})[A-Z ]{5} will also match "This is a test message This is a test message This is a test message This is a test message". The expression behaves as expected in regxr.
