### ISSUE TITLE
Recommended Channels dissapear once you are in one

### ISSUE THREAD

**Issue by C0BZ** [FrankerFaceZ/FrankerFaceZ#562]
**Web Browser**:
Google Chrome
**Do you use BetterTTV or other Twitch extensions**:
BetterTTV
**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log; if Applicable)**:
https://putco.de/OTg2Mw
**Bug / Idea**:
Recommended channels disappear after a while or refreshing stream in a recommended channel.
**Steps to Reproduce (if Applicable)**:
1. Open a stream from your recommended channels
2. 2a. Refresh the page
2b. Wait a while.
3. Recommended channels are gone.

**Comment by Lordmau5** [comment]
I can't seem to be able to reproduce this - my assumption is that this was an issue on Twitch's end that was fixed ever since December of 2018.
