### ISSUE TITLE
FFZ emote icon bug

### ISSUE THREAD

**Issue by stefazenon** [FrankerFaceZ/FrankerFaceZ#565]
**Web Browser**: Google Chrome

**Do you use BetterTTV or other Twitch extensions**: No only FFZ addon pack

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log; if Applicable)**:
https://putco.de/OTk5NQ

**Bug / Idea**: A small bug "Replace the emote menu icon with the FFZ icon for that classic feel." when this is checked it doesn't switch to the classic FFZ icon.

**Steps to Reproduce (if Applicable)**: Select the checkbox and it only displays the default icon and moves it down.

![screenshot 7](https://user-images.githubusercontent.com/24326065/51070189-100ee480-1635-11e9-98f8-b332b598e0b6.png)
![screenshot 8](https://user-images.githubusercontent.com/24326065/51070190-100ee480-1635-11e9-81e4-e72a3efb6416.png)

**Comment by pahakalle** [comment]
Nevermind that does not seem to fix it
