### ISSUE TITLE
[Feature Request] Option to hide (gifted/normal) sub notifications/messages

### ISSUE THREAD

**Issue by 1bakedpotato** [FrankerFaceZ/FrankerFaceZ#570]
**Is your feature request related to a problem? Please describe.**
On popular Twitch channels, the chat can easily become filled with other users' subscription notifications and/or resub messages. This makes the chat quite busy and can be difficult for a user to keep up with.

The "Blocked Terms" chat filtering already provides a solution to hide standard "welcome" / "thanks for subscribing!" type bot messages, however no current solution exists to hide the (typically) multi-line subscription notification and optionally the user-provided resub message as well.

**Describe the solution you'd like**
I propose a new option be added to the Chat > Filtering >> Apearance section that allows one of three options to be selected:

1. Show notification and user message (default - current behavior)
2. Show notification only
3. Don't show notification or message

The final option should suppress all output in the chat when a user subscribes.

**NOTE:** While the "message" portion of the above wouldn't apply, I would also suggest that individual gifted subscription notifications be included within the scope of the final option. In other words, the in-chat notifications of "User X gifted a Tier # subscription to user Y" would be suppressed for each gifted sub, however the single "User X is gifting out # subscriptions!" banner above chat and notification in chat would not be affected.

Additionally, all of the filtering would be ignored if the target (or recipient, in case of gifted subs) matches the current user.

**Describe alternatives you've considered**
Alternatives would be to allow the status quo; large swaths of manual/gifted (re)subs are allowed to render the chat unreadable.

**Comment by SirStendec** [comment]
Implemented in 24a5cd512f076f25c2570287f59967fa29cbd270

As I noted in the PR, I was silly and didn't notice the PR so I ended up developing a similar feature myself. Got quite a few people asking for controls for subscriber messages.

Thanks for your interest!
