### ISSUE TITLE
Bits menu width is affected by chat width

### ISSUE THREAD

**Issue by jnki** [FrankerFaceZ/FrankerFaceZ#574]
**Describe the bug**
Bits menu is width is changed when you change the width of chat.
**To Reproduce**
1. Set chat width to something wide (I use 500px)
2. Click on the bits button.
3. Look how wide bits menu is

**Expected behavior**
Bits menu width shouldn't be changed by chat width

**Screenshots**
![image](https://user-images.githubusercontent.com/17442109/52356081-7e27ab00-2a2b-11e9-95fe-5b63b6b81f65.png)

**Environment (please complete the following information):**
 - OS: Windows 10 64bit 1809
 - Browser: Brave Browser (Chromium 72.0.3626.81)

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**: https://putco.de/MTA0MDU

**Comment by Lordmau5** [comment]
This is intended behavior from Twitch's end - the wider the chat, the wider the popout menu.

This will also apply to the upcoming restyling of the tab-completion and whatnot, as can be seen here
![image](https://user-images.githubusercontent.com/1345036/62829800-f5850400-bc33-11e9-9c65-c0f0898b7e78.png)
