### ISSUE TITLE
Display Subscriber Loyalty Badges -- Subscriber badge not visible in Chat Replay

### ISSUE THREAD

**Issue by connorkidd** [FrankerFaceZ/FrankerFaceZ#58]
**Web Browser**: Chrome

**Do you use BetterTTV or other Twitch extensions**: No

**Bug / Idea**: With Display Subscriber Loyalty Badges disabled, no subscriber badge is visible in Chat Replay (in past broadcasts/highlights).

**Comment by SirStendec** [comment]
This should be fixed now as of a version ago. Forgot to close this.
