### ISSUE TITLE
Badges icons not showing up

### ISSUE THREAD

**Issue by ghost** [FrankerFaceZ/FrankerFaceZ#582]
**Describe the bug**
Badges icons not showing up.

**To Reproduce**
1. Go to 'channel stream chat'

**Expected behavior**
Badges icons like moderator sword.

**Screenshots**
![image](https://user-images.githubusercontent.com/42117486/53839140-8533d180-3f75-11e9-8158-abd83bdc58f9.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 4.0.0-rc14.2
 - Other Extensions: BetterTTV, The FFZ Add-On Pack, Nano Defender, Nano Adblocker

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**: https://putco.de/MTA3Mjk

**Additional information**
When i disable ffz the icons show normally.

**Comment by ThibaultVlacich** [comment]
Yes, happening to me frequently also.
