### ISSUE TITLE
Disable clips timestamps on default

### ISSUE THREAD

**Issue by holndonner** [FrankerFaceZ/FrankerFaceZ#583]
I would really appreciate an option to disable your custom clips page timestamp or a general option to hide timestamps on all clips by default.
I have an highlights channel and if I want to record the chat properly I always have to turn the timestamps off / adjusting the capture window, which consumes a lot of time over the days.

**Comment by Lordmau5** [comment]
Twitch already offers a setting in the clips **and** vod chat to hide timestamps so there's no need for us to implement something like this.

I'd assume that feature isn't that old, meaning it was not implemented back in March.
