### ISSUE TITLE
Line/Chat history with up/down arrows

### ISSUE THREAD

**Issue by Tyr808** [FrankerFaceZ/FrankerFaceZ#586]
Browser: Brave

BTTV or other Twitch extension: Only FFZ and FFZAP

The one and only feature I'm missing with FFZ that I liked on BTTV is being able to press the up arrow in the chat box to access previous submissions.

**Comment by tonijarjour** [comment]
Please add this.

**Comment by SirStendec** [comment]
Added in ef827352bb863804a45b7c2880db493d17659857
