### ISSUE TITLE
Extension no longer works at all

### ISSUE THREAD

**Issue by Nickoladze** [FrankerFaceZ/FrankerFaceZ#594]
**Describe the bug**
No FFZ menu in header bar, no FFZ dark mode, no auto theater mode, no bit hiding. Extension is not working at all.

**To Reproduce**
Go to any stream.
Example I can reproduce every time: https://www.twitch.tv/distortion2

**Screenshots**
https://i.imgur.com/zLwCqUL.png

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 73.0.3683.103 (Official Build) (64-bit)
 - Other Extensions: Tested in Incognito with only FFZ allowed to run

Happy to provide any other data required.

**Comment by kojul** [comment]
Seems to be fixed now but I was in the middle of writing this, so...

Same issue all of a sudden starting today. Screenshot is of the error message in the console.

Screenshots
https://gyazo.com/3e2cf493ab396491665a9fc76adce3fa

Environment (please complete the following information):

    OS: Windows 10
    Browser: Firefox
    Version: 66.0.3 (64-bit)
    Other Extensions: FFZ AP

**Comment by Nickoladze** [comment]
Can confirm that it's suddenly fixed for me as well.

Leaving this open in case there's something that needs to be fixed.

**Comment by Nickoladze** [comment]
https://twitter.com/SirStendec/status/1116812459996786688

**Comment by Nickoladze** [comment]
Closing
