### ISSUE TITLE
Highlight chat messages of followed streamers

### ISSUE THREAD

**Issue by Andiasn** [FrankerFaceZ/FrankerFaceZ#598]
**Is your feature request related to a problem? Please describe.**
Not a problem, just an extra feature that could improve chat experience in bigger streams.

**Describe the solution you'd like**
Highlight of all followed streamers the same way you can set badges/keywords to highlight

**Describe alternatives you've considered**
Using the filtering option for Verified Badges. A lot of streamers don't use it to not seem like they're seeking attention in other's chat rooms. 

Manually typing in  followed streamers 

**Additional context**

**Comment by SirStendec** [comment]
This isn't really viable as the client never requests a full list of your followed streamers during normal operations, and it isn't something I would want to trigger myself.
