### ISSUE TITLE
Twitch chat settings/Viewer list with minimal chat input 

### ISSUE THREAD

**Issue by Linkviii** [FrankerFaceZ/FrankerFaceZ#60]
**Idea**:
An interface for the viewer list while using minimal chat would be nice.

**Comment by SirStendec** [comment]
This has been brought up before. Where exactly would you put the UI when the input is in minimal mode?

**Comment by Linkviii** [comment]
![option](https://cloud.githubusercontent.com/assets/12771000/20993582/41c039c0-bcb9-11e6-9cf1-78a86fe53a65.png)
I'm no good at designing but the two immediate obvious options- A: next to the ffz button or B: next to the whisper menu. 
I'd prefer A. As it is I'm sometimes annoyed by the whisper button when in theater mode.

**Comment by BlacRyu** [comment]
Hey, just got FFZ recently, it's really nice. I am also enjoying the minimal chat and was hoping to be able to see the viewer list without disabling it. I noticed that when you mouse over the stream in theater mode there is a little window that pops up in the bottom left which includes the viewer count. I thought maybe clicking on that number would bring up the viewer list but at the moment it does nothing. Maybe that could be implemented as an alternate way to let us access the viewer list. This could of course be added for the normal viewer count under the stream as well.

**Comment by Lordmau5** [comment]
Seeing as `Minimal Chat` is not a feature in v4 anymore and will also not be seeing a comeback, this issue is now considered resolved.
