### ISSUE TITLE
The extension doesn't load in Chrome Beta

### ISSUE THREAD

**Issue by RoqueDeicide** [FrankerFaceZ/FrankerFaceZ#600]
**Describe the bug**
The extension is among installed, but has no effect on Twitch whatsoever.

The console contains the following message:
> Access to script at 'https://cdn.frankerfacez.com/script/avalon.js?_=1558631689380' from origin 'https://www.twitch.tv' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.

**Environment (please complete the following information):**
 - OS: Windows 7
 - Browser: Chrome Beta
 - Version: 75
 - Other Extensions: BetterTTV, uBlock Origin

**Additional context**
Everything seems to work fine in normal Chrome, the above message doesn't appear in the console. Also the same message doesn't appear for BetterTTV in either browser.

**Comment by RoqueDeicide** [comment]
Looks like this issue can be resolved by disabling CORS by adding  --disable-web-security --user-data-dir="" command line arguments to Chrome Beta shortcut. However this solution prevents me from sending comments on Github.

**Comment by RoqueDeicide** [comment]
Apparently this issue relates to this:
[Changes to Cross-Origin Requests in Chrome Extension Content Scripts](https://www.chromium.org/Home/chromium-security/extension-content-script-fetches)

**Comment by SirStendec** [comment]
FrankerFaceZ works fine in Chrome Beta as far as I can determine. You are likely using a third party extension that is interfering with web requests.

We do not use fetch or XMLHttpRequest to load avalon.js. We inject a <script> tag into the page header to trigger that load. Simply put, loading a script from a script tag does not generate a CORS pre-flight request.

The fact that you're seeing one tells me something else is doing screwy things.

**Comment by RoqueDeicide** [comment]
I found it, it's friGate extension that has been causing an issue, weird that it's only on Beta. I can't tell if there is any way to fix this, so just a warning to everyone else.
