### ISSUE TITLE
Option to disable and/or change the border color of the Get Bits Button

### ISSUE THREAD

**Issue by SephirothWS** [FrankerFaceZ/FrankerFaceZ#603]
**Is your feature request related to a problem? Please describe.**
The border for the Get Bits button in the site header kind of sticks out like a sore thumb. Giving us an option to change the border of the Get Bits button to be similar to the ... menu on the left side of the overall header navigation would make it look better. Right now we have nice little icons that sit off on their own, then the bits button that sits there with a box around it kinda making it look more important than the notifications icon, the FFZ control panel icon, as well as the user avatar menu.

**Describe the solution you'd like**
An option to set the border of the button to a color of our choosing, or to hide the border of the button entirely.

**Additional context**
![Screenshot](https://i.imgur.com/TtNcJsB.png)

**Comment by SephirothWS** [comment]
@SirStendec Why "wontfix"?

**Comment by SirStendec** [comment]
I will not be implementing this feature. While I try to make FrankerFaceZ very flexible, some features that users request are, to put it bluntly, considered too minor or not worth implementing. I suggest using a custom style extension for minor tweaks such as this.

The selector for the button, if you want to mess with that, is `button[data-a-target="top-nav-get-bits-button"]`
