### ISSUE TITLE
Incorrect tool-tips for images on i.stack.imgur

### ISSUE THREAD

**Issue by micsthepick** [FrankerFaceZ/FrankerFaceZ#604]
**Describe the bug**
i.stack.imgur (and probably other) links treated like normal imgur links. When posting an image from that site, it pulls a totally unrelated image for the preview

**To Reproduce**
View preview of an i.stack.imgur link such in twitch chat such as https://i.stack.imgur.com/pHG6E.png

**Expected behavior**
Showing the correct image is preferred, but at the very least don't show an incorrect preview

**Screenshots**
![image](https://user-images.githubusercontent.com/11528421/58700265-e6d3d280-83e2-11e9-84b2-d630466865f3.png)

**Comment by micsthepick** [comment]
@SirStendec I noticed that you closed this issue. Is the bug fixed? Is there a relevant commit?

**Comment by SirStendec** [comment]
The bug is fixed. There is no relevant commit as the fix was in a back-end service that is not currently open-source.
