### ISSUE TITLE
Small side bar feature gone?

### ISSUE THREAD

**Issue by Ovicron** [FrankerFaceZ/FrankerFaceZ#612]
i used to be able to only view the sidebar in a small column with only profile picture of the streamer but now i cant?

https://i.imgur.com/Zr74hHw.png it only gives me an option to display side bar or not display sidebar. HELP

**Comment by SirStendec** [comment]
Click the arrow to expand or collapse the sidebar. This is not a FFZ feature at all.
![image](https://user-images.githubusercontent.com/14036657/60136438-28e9fd00-9772-11e9-83a9-dac646bff99f.png)
