### ISSUE TITLE
Column for autocomplete not working

### ISSUE THREAD

**Issue by Tralexium** [FrankerFaceZ/FrankerFaceZ#614]
**Describe the bug**
When typing a column the autocomplete box shows only Twitch related emotes

**To Reproduce**
1. Type a column, done.

**Expected behavior**
Show BTTV or FFZ emotes in the autocomplete emote box.

**Environment (please complete the following information):**
 - OS: win10
 - Browser: Chrome
 - Version:  75.0.3770.100 (Official Build) (64-bit)
 - Other Extensions: BetterTTV, uBlock, FFZ Add-on pack.

**FFZ Logs**:
https://putco.de/MTE4NjU

**Comment by mackoz** [comment]
Getting the same error on both Mac and Windows

Logs: https://putco.de/MTE4NjY

**Comment by csrapr** [comment]
Same, tab completion also not working.

http://putco.de/MTE4Njc.brainfuck

**Comment by Yokutto** [comment]
+1
