### ISSUE TITLE
Opening the FrankerFaceZ Control Center in an Embedded Browser instead opens a different chat.

### ISSUE THREAD

**Issue by Krutonium** [FrankerFaceZ/FrankerFaceZ#616]
**Describe the bug**
Basically, I am using CefSharp (Embedded Google Chrome) in C#, and injecting the FrankerFaceZ via the userscript (executed as raw javascript, which seems to work). The problem comes with trying to access the FrankerFaceZ Control Center, where instead of opening the panel like it does in most browsers, it instead opens an entirely new Window, to https://twitch.tv/FrankerFaceZ, and continues to present no options.

**To Reproduce**
1. Create a CefSharp Application
2. Load a Twitch Chat (Using popout url)
3. Load FrankerFaceZ (After the chat has finished loading)
4. Attempt to open FFZ CC.

**Expected behavior**
It opens the FFZ CC.

**Screenshots**
![IssueFFZ](https://user-images.githubusercontent.com/3945538/60380472-36261680-9a14-11e9-9584-c91c3fafc58b.PNG)

**Environment (please complete the following information):**
 - OS: Windows 10 1903 
 - Browser: CEF (Chromium Embedded)
 - Version: 73.1.130
 - Other Extensions: Absolutely None

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:

That's not really doable, considering.

**Additional context**
I am trying to add FFZ Support to my bot, https://github.com/Krutonium/KruBot

**Comment by SirStendec** [comment]
The way our control center works when opened from embedded or pop-out chat is it opens a new window to https://www.twitch.tv/popout/frankerfacez/chat?ffz-settings

When the script loads into that page, it detects the `ffz-settings` query parameter on the URL and it automatically opens the FFZ Control Center in exclusive mode. I assume what's happening in your example is FFZ's script is not being injected into the pop-up window. You'll have to address that in your application. It isn't a bug with FFZ.
