### ISSUE TITLE
Set custom nickname for other users

### ISSUE THREAD

**Issue by Vivelin** [FrankerFaceZ/FrankerFaceZ#618]
**Is your feature request related to a problem? Please describe.**
Some of my friends have completely different usernames on Twitch than what I know them by. This would cause me to skip past messages I otherwise would've wanted to see.

**Describe the solution you'd like**
I'd like to be able to set custom nicknames (like Steam chat) for certain users so that I can more easily recognize them. Twitch already has some support for setting a separate display name, so these could be displayed the same way.

**Describe alternatives you've considered**
Highlighting messages by certain users could work to, well, highlight messages that might be important, but it would still take me a while to figure out _who_ the message is from.

**Comment by MaxSilvesterQWE** [comment]
If you are looking for the custom nickname feature, it is a chat action called "Change Name & Color" and can be added in the settings in Chat > Actions (e.g. Message Hover)
