### ISSUE TITLE
Whitelist/Blacklist for Tab-completion

### ISSUE THREAD

**Issue by WRPBeater** [FrankerFaceZ/FrankerFaceZ#621]
**Is your feature request related to a problem? Please describe.**
With more and more emotes added to Twitch, there can be plenty of garbage to scroll / tap through while trying to tab-complete a particular emote (with colon). Many emotes have many of the same letters, so you'd have to type almost the whole emote to single it out, defeating the point of tab-completion.

**Describe the solution you'd like**
The ability to use some kind of whitelist/blacklist system for emotes; ideally, you'd whitelist emotes that you want to appear at the top of tab-completion, and blacklist emotes that you don't want shown in tab-completion (since you'll never use them). This could be done using the already existing favorites system. At present, it doesn't seem like favoriting emotes does anything but let you find them in the favorites menu.

**Describe alternatives you've considered**
The blacklist stuff might be redundant if a whitelist is implemented, but ideas / opinions on that are welcome.

Log, if needed: https://putco.de/MTE5MTg

**Comment by WRPBeater** [comment]
This has been added as of 4.7.0. Thanks for adding it! However, it seems not to work for BTTV emotes with the BTTV add-on (ffzap-bttv).

**Comment by Lordmau5** [comment]
Version 4.9.0 fixed favored add-on emotes (e.g. BTTV) in the tab-complete menu :)

Seeing as you're satisfied with this implementation, I'm going to go ahead and close this issue.
