### ISSUE TITLE
Extension doesn't install properly on Opera

### ISSUE THREAD

**Issue by fourst4r** [FrankerFaceZ/FrankerFaceZ#622]
**Describe the bug**
When you go to https://www.frankerfacez.com/ and click the "Download for Opera" button, it will download a .nex file, not invoking any installation process.

**Expected behavior**
The extension will install.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser: Opera
 - Version: 62.0.3331.43
 - Other Extensions: Privacy Badger, uBlock Origin

**Comment by Lordmau5** [comment]
This is actually intended behavior by Opera - other websites are telling users to open the `.nex` file with Opera after downloading them, unless they are in the Opera Extension Store.
