### ISSUE TITLE
[Feature Request] Be able to tweak the highlight color of messages than mention me

### ISSUE THREAD

**Issue by Blaxou** [FrankerFaceZ/FrankerFaceZ#627]
**Is your feature request related to a problem? Please describe.**

When someone mentions you and you have the **_Highlight messages that mention you_** option enabled, the message is automatically highlighted in red with no way to change it.

**Describe the solution you'd like**

Have an option to tweak the color under **_Highlight messages that mention you_**

**Describe alternatives you've considered**

Matching my username via regex/filtering, but that's not very user friendly

**Additional context**
None

**Comment by SirStendec** [comment]
Added in ef827352bb863804a45b7c2880db493d17659857
