### ISSUE TITLE
Option to use minimal chat input only when chat is below video

### ISSUE THREAD

**Issue by dominiklohmann** [FrankerFaceZ/FrankerFaceZ#63]
I have set the chat position to be aspect ratio dependent, and would like to use minimal chat input only when the chat is below the video. 

Reasoning is that minimal chat input hides information like chat room settings (r9k, sub/slow mode) and there usually is no need for the extra chat lines when the chat uses the full window height.

**Comment by RenaKunisaki** [comment]
I wish there were an "in-between" setting, that gets rid of all the extra whitespace at the bottom of the chat, but still shows the slow/batch/etc labels and the buttons. Just not so much padding, and maybe smaller entry field (especially if it grows when typing enough to fill it).

**Comment by Lordmau5** [comment]
Seeing as `Minimal Chat` is not a feature in v4 anymore and will also not be seeing a comeback, this issue is now considered resolved.
