### ISSUE TITLE
Settings from JSON File Not Importing

### ISSUE THREAD

**Issue by ntriley** [FrankerFaceZ/FrankerFaceZ#632]
**Describe the bug:**
When trying to import saved settings, nothing happens after selecting which profile to import from the JSON file.

**To Reproduce:**
1. Open FFZ Settings
2. Click **Default Profile>Configure>Import...**
3. Select .JSON file **[ENCLOSED, see end]**
4. Choose profile to import.
5. See error.

**Expected Behavior**
After selection I expected the profile to import automatically.

**Environment (please complete the following information):**
-OS: Windows 10
-Browser: Chrome
-Version: 75.0.3770.142
-Extensions: FFZ, FFZ:AP, AdBlock, Netflix Party, Picture in Picture (by Google), Honey

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log):** 
https://putco.de/MTIyMDg

**Additional Context:**
Problem persists after a fresh install of both the FFZ & FFZ:AP extensions, regardless of popup menu or seperate window. Log is from fresh install.

**.JSON File (converted to .txt):**
[ffz-settings.txt](https://github.com/FrankerFaceZ/FrankerFaceZ/files/3464566/ffz-settings.txt)

**Comment by SirStendec** [comment]
Fixed in 9ab57897efa5632f6bc4820b7fce5711b48edbe4

**Comment by ntriley** [comment]
Thank you so much!
-NTR
