### ISSUE TITLE
[Bug] Chat message highlights using custom colours conflicts with alternating chat line colours in dark mode

### ISSUE THREAD

**Issue by tornado-ii** [FrankerFaceZ/FrankerFaceZ#633]
**Issue:**
When dark mode is enabled on Twitch and alternating chat background colours is enabled in FFZ, applying a custom colour to chat highlights will be nullified by the alternating chat line background colour.

**To Reproduce:**
1. Enable Dark Theme through Twitch's standard settings drop-down menu.
2. Enable `Display lines with alternating background colors` in FFZ Control Center>Chat>Appearance>Chat Lines
3. Add a custom highlight colour in FFZ Control Center>Chat>Filtering>Appearance
4. Enable `Highlight messages that mention you` in FFZ Control Center>Chat>Filtering>Appearance AND/OR Add terms to FFZ>Chat>Filtering>Highlight Terms AND/OR Add terms to FFZ Control Center>Chat>Filtering>Highlight Users

**Expected Behavior:**
Chat lines of alternating background colours should inherit the custom highlight colour when highlight conditions are met.

**Screenshots:**
![Default highlight colour in Light theme with alternating chat lines](https://user-images.githubusercontent.com/25275680/62541115-f7069480-b80d-11e9-861a-49b4ecbb3163.png) ![Default highlight colour in Dark theme with alternating chat lines](https://user-images.githubusercontent.com/25275680/62541147-0980ce00-b80e-11e9-9df1-19d343cb79f5.png)
![Custom highlight colour in Light theme with alternating chat lines](https://user-images.githubusercontent.com/25275680/62541179-1bfb0780-b80e-11e9-9d68-c76bea15115e.png) ![Custom highlight colour in Dark theme with alternating chat lines](https://user-images.githubusercontent.com/25275680/62541191-261d0600-b80e-11e9-8a6e-d5f77279e927.png)

**Environment:**
 - OS: Windows 7 Professional, Service Pack 1
 - Browser: Firefox Quantum 68.0.1 (64-bit)
 - FrankerFaceZ Version: 4.7.2 (9ab5789)
 - Other Extensions: BetterTTVEmotes (via FFZ Control Center>Add-Ons), FFZ:AP Core (via FFZ Control Center>Add-Ons), HTTPS Everywhere, Privacy Badger, Stylus (No themes installed for Twitch), uBlock Origin 1.21.2, Greasemonkey (No scripts installed for Twitch), Ecosia Search, View Image

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log):**
https://putco.de/MTIyNDE

**Comment by SirStendec** [comment]
Fixed in 3583dd8fe7b7786763d4387fdfba534a0f878db6
