### ISSUE TITLE
Option to pin messages with specific keywords

### ISSUE THREAD

**Issue by TimeBomb** [FrankerFaceZ/FrankerFaceZ#64]
**Idea:** New setting that makes messages containing specified keywords (e.g. mentions of your own name) pinned to the top of the chat for X seconds. Similar to pinning of cheers.
Potentially able to manually remove a pinned message as well, rather than wait for the specified time to pass.

**Potential use case:** Keep better track of messages where you're mentioned. So you don't miss them and can reply to them.

**Comment by Zeoxsys** [comment]
Yes, I would love to have this added in, this was in BTTV and I loved it, very useful

**Comment by faiizow** [comment]
I would LOVE this.

**Comment by shelterx** [comment]
Please add this ASAP, it's very useful in crowded channels.
