### ISSUE TITLE
FFZ Debug Server connection problem

### ISSUE THREAD

**Issue by MrSnowman** [FrankerFaceZ/FrankerFaceZ#644]
**Describe the bug**
After following the instructions in the readme for setting up the development server FFZ addon doesn't load from the server.

**To Reproduce**
Follow the "Developing" instructions in order.

**Expected behavior**
After having written localStorage.ffzDebugMode = true; in console and reloading the console shouldn't say "FFZ: Development Server is not present. Using CDN."

**Environment (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Chrome and Firefox have similar issues and no effective development server use.
 - Version: Cloned directly from repo. Most recent commit: 2142f132f5aaf4031e11c0a253ed023e5a3af2c6
 - Other Extensions: BetterTTV, Adblock, Privacybadger, Violentmonkey (no twitch related scripts running) on Firefox. Chrome was installed when I found the bug. FFZ addon installed from Chrome web store.

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:
https://putco.de/MTIzNDk

**Additional context**
Browsing to https://localhost:8000/webpack-dev-server/ usually gives the "Disconnected"-page. Sometimes it loads right and might end up saying hello world as it should after a while.
In Firefox I get console log messages like:

> FFZ [socket]: Disconnected. (1006:) logging.js:99:11
> FFZ [socket]: Using Server: wss://127.0.0.1:8003/ logging.js:99:11
> Firefox can’t establish a connection to the server at wss://127.0.0.1:8003/. socket.js:186:23

In Chrome I just get this console output https://putco.de/MTIzNTE.log
Since I got the error I've also changed the server cluster under in the FFZ control center » Debugging » Socket to development just to try. Didn't change anything.
Both browsers have FFZ functional as expected.

**Update**
Firefox still has the exact same problems. Chrome had the same problems after server restart but now that I restarted it a second time Chrome seems fine. Doesn't have any problems I can see and I see a console.log I added to one of the files.
Disabling all addons on Firefox and switching standard content blocking to didn't change anything.

**Comment by SirStendec** [comment]
Make sure you have the dev certificate trusted in your browser. Visiting https://127.0.0.1:8000/dev_server should show you JSON straight away and not a certificate warning.

Do not set the Socket Server to Development. That will do nothing but make things that rely on the socket server cluster not work for you. The socket server is not emulated by the webpack development server.

**Comment by MrSnowman** [comment]
I've added localhost and 127.0.0.1 as exceptions in Firefox. I don't get the certificate warning.
