### ISSUE TITLE
[Feature Request] Reducing Visual Noise and/or Eliminating Visual Noise ENTIRELY from channel points feature

### ISSUE THREAD

**Issue by SephirothWS** [FrankerFaceZ/FrankerFaceZ#654]
This has already been suggested over on the BTTV side, would love to see the same thing over here with FrankerFaceZ.

https://github.com/night/BetterTTV/issues/3563

The guy that made the request explains it perfectly.

**Comment by SirStendec** [comment]
Closed by 89d243a26953d193935e9155ef67fa5d534c25aa
