### ISSUE TITLE
New UI "Live" view scroll load is broken

### ISSUE THREAD

**Issue by FinalDoom** [FrankerFaceZ/FrankerFaceZ#662]
It appears maybe twitch changed some of the calls that were being hooked for the new live view display. FFZ Chrome 76.0.3809.132

Without extension, scroll/load operates as expected, page loads first 50 streams, on scrolling to the bottom, it loads more.

With extension, the loading seems to happen, but instead of adding to the list, the page is reloaded and only the original 50 streams are displayed. Scrolling to load then does not do anything.

**Comment by SirStendec** [comment]
This should be fixed, I believe? Please comment if you're still experiencing it and I'll re-open.

**Comment by FinalDoom** [comment]
Yup, looks good. Thanks :D
