### ISSUE TITLE
Player specific settings do not seem to be working

### ISSUE THREAD

**Issue by simoniz0r** [FrankerFaceZ/FrankerFaceZ#667]
**Describe the bug**
Player specific settings such as the option to add a button to reset the stream, automatic theater mode, etc do not seem to be working at all.  I first noticed this yesterday.

**To Reproduce**
1. Enable a player specific setting such as the option to add a button to reset the stream (Player -> General -> Click 'Add a `Reset Player` button to the player controls.')
2. See that no button is added to reset the stream as it was in the past even after refreshing the page

**Expected behavior**
Player specific settings should work as they did less than a week ago.

**Environment (please complete the following information):**
 - OS: openSUSE Tumbleweed (Linux)
 - Browser: Electron
 - Version v6.0.11
 
**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:
https://putco.de/MTI4MDk

**Additional context**
I am running FrakerFaceZ by injecting the javascript version into an Electron wrapper created using Nativefier.  Everything was working normally until a couple of days ago.  It would seem like something might have changed with Twitch's player as none of the player specific settings work as far as I can tell.

**Comment by martinsstuff** [comment]
I can confirm I have the same issue since around yesterday, interestingly it works when allowing FFZ in incognito and visiting a Twitch stream (some A/B testing going on?).

**Comment by Doorstop2** [comment]
Yeah it's this new highwind player buttons and player features are missing - firefox

**Comment by curs0n** [comment]
It's definitely due the new Highwind player.
No metadata (latency) showing, I'm forced in Normal Latency mode, lost the ability for the custom buttons, and the player doesn't seem to be able to automatically open in Theatre mode.

**Comment by Emilgardis** [comment]
6547497 removes the button temporarily, hopefully a way to implement it is found

**Comment by martinsstuff** [comment]
Just in case it might be relevant: When I got this bug: https://github.com/FrankerFaceZ/FrankerFaceZ/issues/674 I was able to see the player reset button (and I believe it worked) until I restarted Chrome entirely which fixed the issue but also removed the button.

Could this be an indication on how to force it to use the old player?
