### ISSUE TITLE
Tab auto complete display name / aliases doesn't work with /me or other commands

### ISSUE THREAD

**Issue by Jacky1356400** [FrankerFaceZ/FrankerFaceZ#67]
**Web Browser**: Google Chrome 55.0.2883.87 m (64-bit)

**Do you use BetterTTV or other Twitch extensions**: No

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: N/A

**Bug / Idea**: Tab auto complete is supposed to be able to complete display name and aliases, but apparently, when I put /me or other commands like /timeout and tried to tab auto complete a name, it completes the username (full lowercase name) instead of the display name, even though the autocomplete tooltip shows the display name / aliases (e.g. "/me hugs SomeOne" will becomes "/me hugs someone"). That really bugs me when I tried to use /me and tab autocomplete names.

**Steps to Reproduce (if Applicable)**: In any chatrooms, do /me (or something like /timeout, /ban, /purge) and then tab a name.

**Comment by zoton2** [comment]
SirStendec explained this to me once before: commands that do something like /timeout need "English" usernames to work and of course won't work with an Asian display name. Of course with /me this technically doesn't matter but it has something to do with how it's a command and it's not differentiated from the rest for some good reason that I can't remember.

**Comment by Jacky1356400** [comment]
I mean, /timeout or other chat moderation commands doesn't really matter but what really bugs me is /me doesn't work with tab auto complete, and I had to tab in the name first and then put /me before sending messages.
