### ISSUE TITLE
"Auto-play featured broadcasters on the front page" setting not working

### ISSUE THREAD

**Issue by kevzor** [FrankerFaceZ/FrankerFaceZ#676]
**Describe the bug**
Streams are autoplaying on the front page even though the "Auto-play featured broadcasters on the front page" setting is disabled.

**To Reproduce**
Toggle the setting and go to the front page.

**Expected behavior**
Annoying people not screaming at me when I open Twitch.

**Comment by blueYOSHI9000** [comment]
This still seems to be an issue for me, Stream autoplays regardless if the setting is on or off.

**Comment by thrwKappu** [comment]
Still happens for me too
log: https://putco.de/MTMwNzU
