### ISSUE TITLE
Stream delay no longer shown in metadata

### ISSUE THREAD

**Issue by Gamertech** [FrankerFaceZ/FrankerFaceZ#677]
**Describe the bug**
As of today, Twitch has changed something so FFZ no longer displays the stream delay in the metadata section under the player. Just viewers, views and uptime.

**To Reproduce**
1. Go to any live channel and see no delay data shown
2. Toggling Playback Statistics in FFZ has zero effect

**Expected behavior**
Stream delay info to display as normal

**Environment (please complete the following information):**
 - OS: Win10
 - Browser: Opera
 - Version: 64
 - Other Extensions: uMatrix, uBlock Origin (whitelisted)

**Comment by GeekBoyMN** [comment]
I am having this same issue in Chrome and FireFox browsers running on Windows 8.1 64bit.

**Comment by restcure** [comment]
Same issue on MacOS 10.10: for browsers Firefox 70.0, Opera 63.0, Opera 64.0, Chrome 79.0

**Comment by Gamertech** [comment]
Delay working again with today's update.

Cheers SirStendec

**Comment by GeekBoyMN** [comment]
This is still an issue for me on FireFox, Windows 8.1 and latest FF update. The latency display works fine in Chrome.
