### ISSUE TITLE
Reset player by doubling click X? MISSING???

### ISSUE THREAD

**Issue by Ovicron** [FrankerFaceZ/FrankerFaceZ#678]
Where is this? I never disabled it, I don't see it anywhere. Someone help? Is it a bug? What happened?

**Comment by SirStendec** [comment]
> The Reset Player button has been removed because implementing it with the new player is infeasible to the best of our knowledge.
> 
> The new player is more integrated into the web application, so destroying it and recreating it is not trivial as it was before.

**Comment by Ovicron** [comment]
oh damn... it was one of the best features, imo. 

hopefully there is a workaround for it. thx

**Comment by Ovicron** [comment]
THANKS A LOT!!! for bringing it back!!!
