### ISSUE TITLE
Setting that allows FFZ to press claim points button when it appears

### ISSUE THREAD

**Issue by TETYYS** [FrankerFaceZ/FrankerFaceZ#681]
In new points feature, there is a button that appears after some watch time below the chat that gives you more points (https://help.twitch.tv/s/article/channel-points-guide?language=en_US#viewers). FFZ could press this button automatically.

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to manually press the button for more points

**Describe the solution you'd like**
Addon automatically presses the button when it appears

**Describe alternatives you've considered**
Pressing the button manually

**Comment by 33kk** [comment]
Here is userscript to do this
```
// ==UserScript==
// @name        Points Autoclicker
// @namespace   33kk
// @match       *://*.twitch.tv/*
// @grant       none
// @version     1.0
// @author      33kk
// @description yes
// ==/UserScript==

setInterval(()=>{
  let e = document.querySelector(".community-points-summary .tw-button--success");
  if (e !== undefined)
   e.click()
}, 5000);
```

**Comment by stephanrenggli** [comment]
This feature is already in FFZ but there is no visible setting.

While on twitch.tv, paste the following into the console of your browser to enable this feature:
`localStorage["FFZ:setting:p:0:chat.points.auto-rewards"] = true`
