### ISSUE TITLE
Disable Picture in Picture

### ISSUE THREAD

**Issue by Zoooook** [FrankerFaceZ/FrankerFaceZ#682]
When I'm watching a channel and I click the Videos or Clips tab at the top, the stream keeps playing in a tiny player. I want it to not do that.

**Comment by SirStendec** [comment]
That's a Twitch thing called Mini Player. They already have a setting for it.
![image](https://user-images.githubusercontent.com/14036657/67166369-9a227100-f35c-11e9-8431-8e374b276ff3.png)
