### ISSUE TITLE
(poolparty), :'( are not emotes anymore

### ISSUE THREAD

**Issue by cinemassacres** [FrankerFaceZ/FrankerFaceZ#688]
**Describe the bug**
in the bttv addon you have this line, the Enable to show arbitrary emoticons (like D:, :tf:, (poolparty), :'( and similar).  (poolparty), :'( are gone and are not emotes anymore
**To Reproduce**
1. Go to 'addons'
2. Click on 'bttv'
3. Scroll down to rbitrary Emotes
Enable to show arbitrary emoticons (like D:, :tf:, (poolparty), :'( and similar).'
(poolparty), :'( and similar) are not emotes anymore
**Expected behavior**
that line to be edited to say the Enable to show arbitrary emoticons D: :tf:
**Screenshots**
https://i.imgur.com/ehrxsaR.png
**Environment (please complete the following information):**
N/A
**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:

**Additional context**
those emotes where removed year(s) ago

**Comment by Lordmau5** [comment]
The BetterTTV Emotes Add-On isn't using the v2 API of BTTV anymore as that one's soon to be disabled.
Instead, I've switched it over to v3, which doesn't list those 2 emotes mentioned.
Nothing I can do about it.

https://api.betterttv.net/3/cached/emotes/global

**Comment by cinemassacres** [comment]
@Lordmau5 https://i.imgur.com/ynD9GDN.png

**Comment by SirStendec** [comment]
I'm not going to close this as Lordmau5 is already interacting here (and apparently totally missed your point), but in the future issues related to Add-ons for FrankerFaceZ should be opened on the https://github.com/FrankerFaceZ/Add-Ons repository and not the main client repository.

**Comment by SirStendec** [comment]
Or I can just close this one since you opened one on the Add-Ons repo.
