### ISSUE TITLE
showing bttv "pro" emotes

### ISSUE THREAD

**Issue by cinemassacres** [FrankerFaceZ/FrankerFaceZ#689]
**Describe the bug**
showing "bttv pro" emotes when they really aren't global emote and will show up for web chat users when in reality the are bttv pro emotes that normal bttv/ffz people wouldn't be able to see except if you are a "bttv pro" user .
**To Reproduce**
type Kaged and you should not be able to see it [example ](https://i.imgur.com/4GmdPVr.png)

**Expected behavior**

not to see the emotes [example](https://i.imgur.com/eA1zyRf.png
**Screenshots**
https://i.imgur.com/eA1zyRf.png
https://i.imgur.com/4GmdPVr.png
**Environment (please complete the following information):**
N/A

**Additional context**
you show "bttv pro" emotes in the emote picker as there listed in the bttv api as shown [here ](https://api.betterttv.net/2/emotes)  emote listed in the bttv api like  BlackKappa motnahP, DogeWitIt, BadAss,  Kaged,  SoSerious, (chompy),  BatKappa,  normal bttv/ffz people wouldn't be able to see except if you are a "bttv pro" user . [example ](https://i.imgur.com/ADgaQSM.jpg)  The global API endpoint specifies a number of sets (54faa50d01e468494b85b578, 55288e390fa35376704a4c7a, 54faa52f01e468494b85b579, 54faa4f101e468494b85b577, 54fbf11001abde735115de66, 5514afe362e6bd0027aede8, 550b225fff8ecee922d2a3b2, 550b6b07ff8ecee922d2a3e7 ) but all of them are bttv pro as explained by this [archived link ](http://web.archive.org/web/20160305071910/https://nightdev.com/betterttv/faces.php)  all are global as specified by the "global" array. For example this causes the Kaged emote to be shown in web browser when it really isn't a global emote and will not show up for web chat users except if you are a bttv pro user .

**Comment by SirStendec** [comment]
Issues related to Add-ons for FrankerFaceZ should be opened on the https://github.com/FrankerFaceZ/Add-Ons repository and not the main client repository.
