### ISSUE TITLE
Whispers displaying wall of spaces

### ISSUE THREAD

**Issue by danintheclub** [FrankerFaceZ/FrankerFaceZ#69]
**Web Browser**: 
Chrome

**Do you use BetterTTV or other Twitch extensions**: 
FFZ

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:
none

**Bug / Idea**:
when whispering a cbenni multi chat, massive wall of spaces are displayed after the sent whisper message (see photos)

![ffzdisabled](https://cloud.githubusercontent.com/assets/24618411/21284945/9b933cea-c3df-11e6-96e5-c24c5fcb501a.png)

![ffzenabled](https://cloud.githubusercontent.com/assets/24618411/21284944/9b92c4c2-c3df-11e6-85aa-e4a49638ddf3.png)

**Steps to Reproduce (if Applicable)**:
install FFZ extension
send whisper to cbenni multi chat

**Comment by SirStendec** [comment]
Fixed in 3.5.403.
