### ISSUE TITLE
Recommended Channels

### ISSUE THREAD

**Issue by Sacobrt** [FrankerFaceZ/FrankerFaceZ#699]
**Screenshots**
Recommended channels still active: https://i.imgur.com/VxMWLZc.png

**Environment (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Opera
 - Version: 4.15.3 0fdb988
 - Other Extensions: AdBlock, BetterTTV

**Comment by SirStendec** [comment]
The setting you are showing is for the directory following page, not the side bar. There is a separate setting to control the visibility of recommended channels in the sidebar in: Appearance > Layout >> Side Navigation
