### ISSUE TITLE
frankerfacez.com is DOWN

### ISSUE THREAD

**Issue by petercunha** [FrankerFaceZ/FrankerFaceZ#701]
**Describe the bug**
The FrankerFacez official website is down and returns HTTP 522.

> A 522 error occurs because CloudFlare could not make a TCP connection to your origin server before the attempts timed out. This means that CloudFlare was unable to send the HTTP request to the origin because a network connection to the origin server could not be established.

**To Reproduce**
1. Go to https://frankerfacez.com
2. Go to https://downforeveryoneorjustme.com/frankerfacez.com

**Screenshot**
![FFZ is offline](https://i.imgur.com/YQH1v9R.png)

**Comment by SirStendec** [comment]
As we tweeted, we were performing a server migration to more powerful hardware today. This was normal. Things are back up and running now.
