### ISSUE TITLE
FFZ not working in Firefox

### ISSUE THREAD

**Issue by tharos96** [FrankerFaceZ/FrankerFaceZ#702]
**Describe the bug**
FFZ does not work/show up at all in Firefox since a few days.
Reinstalling doesn't fix it.

**Expected behavior**
FFZ menu appears and works as intended

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 70.0.1 (64-Bit)
 - Other Extensions: Bitwarden, Decentraleyes, DuckDuckGo Privacy Essentials, Privacy Badger, Pushbullet, Reddit Enhancement Suite, uBlock Origin, YouTube Classic

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**: Can't access

**Comment by SirStendec** [comment]
Privacy Badger is most likely blocking our domains. It likes doing that. We can only assume it does because of Cloudflare. Whitelist FFZ in Privacy Badger.

**Comment by tharos96** [comment]
That was it, thank you!
