### ISSUE TITLE
Picture in Picture mode no longer rendering

### ISSUE THREAD

**Issue by Ian-Avallo** [FrankerFaceZ/FrankerFaceZ#703]
**Describe the bug**
Picture in picture mode is no longer working. When I activate the window, it opens up a transparent chrome window that is not intractable. Occasionally this window renders as a black box instead of a transparent box. The issue started about a month ago. I've tried to reinstall the chrome extension and disabling all my other extensions. I have been unable to fix the issue.

**To Reproduce**
1. Open up twitch.tv and go to any stream
2. Click the picture in picture button on bottom of stream UI

**Expected behavior**
The picture in picture window would correctly render and display the twitch stream
 
**Screenshots**
![PicinPicTest](https://user-images.githubusercontent.com/38537720/68997921-6f4f0e00-0871-11ea-9f0b-e5aa41c6279c.png)
![unknown](https://user-images.githubusercontent.com/38537720/68997922-6f4f0e00-0871-11ea-9752-045bfa337008.png)

**Environment (please complete the following information):**
 - OS: Windows 10 Home, 17763.864
 - Browser Chrome Version 78.0.3904.97 (Official Build) (64-bit)

 - Version 4.15.5347919c
 - Other Extensions: Issue persists when only FrankerFaceZ extension is running

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:
https://putco.de/MTMxNzk

**Comment by SirStendec** [comment]
FrankerFaceZ doesn't have anything to do with the actual rendering of the picture-in-picture window. We only add the button to trigger it, and use native browser API calls to tell it to play the video via picture-in-picture.

A rendering error such as you've described can only be an issue with your web browser and/or other software running on your computer.
