### ISSUE TITLE
Remove themed emotes (christmas hat on emotes???? lol)

### ISSUE THREAD

**Issue by EdmirMid** [FrankerFaceZ/FrankerFaceZ#705]
No way to disable it seems. Every emote with a christmas hat on is just bad, looks small and ruining the chat experience. Please remove.

**Comment by SirStendec** [comment]
People are specifically replacing emotes with holiday themed versions of them. They are effectively a different emote with the same name.

There's no bug. Nothing for us to fix. We aren't removing them.
