### ISSUE TITLE
Add follows list on users channel back

### ISSUE THREAD

**Issue by lyfeme** [FrankerFaceZ/FrankerFaceZ#708]
Hi,

**Is your feature request related to a problem? Please describe.**
There used to be a button on users channels to show who he follows. But twitch removed it.

**Describe the solution you'd like**
Add the button back. There are websites that list follows like https://twitchfollowing.com/ for example, but it'd really cool if it'd be directly on twitch website.

**Describe alternatives you've considered**
using https://twitchfollowing.com/

**Additional context**
You may consider it's not really meaningful. But in my opinion having an easy possibility to find who a friend or a streamer is following allow us to find new streamers.
"I like this person, let's see what streamers he watches, maybe I'll find new good streamers",

Thank you.

**Comment by SirStendec** [comment]
I'm not interested in adding an entire page like that back to the site that Twitch removed. Building that and making it act like people would expect, without access to certain pre-made components that Twitch uses, would be a pain.

As you pointed out, there are external tools for accomplishing that already.  Please just use those tools.
