### ISSUE TITLE
Ban offenses logged within FFZ

### ISSUE THREAD

**Issue by foxotic** [FrankerFaceZ/FrankerFaceZ#71]
**Idea**

It would be great to help organize which ban offense a user is on. For example if a viewer has been timed out for a second offense. it would show user has been timed out on , eg. 12/13/2016 @ 3:23PM by MOD. and the second one with the same type of data. That way if a viewer has a policy for how timeouts are handled, they can take action accordingly.

**Comment by foxotic** [comment]
to extend on this, it could add some mod card buttons to show that a viewer is on a certain teir of timeout that you can setup within FFZ. So when they do hit a certain offense you could simply hit a button to time them out for the proper amount of time

**Comment by SirStendec** [comment]
Get logviewer. https://cbenni.com/ This already has integration with FFZ and shows a user's previous chat activity, including bans, and allows moderators to keep notes on users.
