### ISSUE TITLE
[Feature Request] Highlight term only in channels you mod

### ISSUE THREAD

**Issue by BoCentury** [FrankerFaceZ/FrankerFaceZ#711]
**Is your feature request related to a problem? Please describe.**
As a moderator, it is quite convenient to have the words 'mod' and 'mods' highlighted in chat. It would be lovely to be able to only highlight certain terms in chats that you moderate, especially if you have highlight sounds on.

**Describe the solution you'd like**
A simple checkbox next to each term that says 'mod only' or something similar would work.

**Describe alternatives you've considered**
The alternative is to manually delete and add the 'mod' and 'mods' terms every time you leave and join a chat you moderate, which I can't imagine anyone actually does. Otherwise you just deal with 'mods' being highlighted in all chats (as well as the potential highlight sound playing).

**Additional context**
N/A

**Comment by SirStendec** [comment]
This is already possible by using multiple settings profiles. By default there is an additional setting profile that is only active in channels where you are a moderator. Select that profile using the profile selector in the upper left of the control center, and then add the relevant terms to that profile.
