### ISSUE TITLE
Highlight own messages

### ISSUE THREAD

**Issue by A-UNDERSCORE-D** [FrankerFaceZ/FrankerFaceZ#712]
**Is your feature request related to a problem? Please describe.**
In other chat platforms (and with BTTV) I find it very helpful to be able to have my own messages highlighted a different colour.

**Describe the solution you'd like**
A simple checkbox for adding a colour to my own messages

**Describe alternatives you've considered**
Higlighting my nickname with the existing system and enabling matching my own messages. This *works* but really isn't clean--First off, it hits my notification sound. And secondly, its the same colour as regular highlights, which is something I dont want.

**Comment by Lordmau5** [comment]
You can add your own username into the `Highlight Users` section within `Chat > Filtering` like this
![image](https://user-images.githubusercontent.com/1345036/70957849-b2bab900-2077-11ea-8722-e457463eff15.png)

Then you can set a custom color for that.

**Comment by A-UNDERSCORE-D** [comment]
That does work, however every message triggers the notification noise, as mentioned in "Considered alternatives"

**Comment by SirStendec** [comment]
The notification sound isn't a FrankerFaceZ feature. It's an add-on. Everything else here is already part of core FrankerFaceZ.
