### ISSUE TITLE
[Feature Request|Quality of Life] Auto-claim "Active watching reward"

### ISSUE THREAD

**Issue by BradyThe** [FrankerFaceZ/FrankerFaceZ#713]
**Is your feature request related to a problem? Please describe.**
The new 'Channel points' feature includes a reward for every [15 minutes watched](https://help.twitch.tv/s/article/channel-points-guide?language=en_US#viewers), which need to be claimed manually by clicking on the respective button. This moves the focus from watching a stream to playing a clicker game.

**Describe the solution you'd like**
Auto-claiming the reward would solve this problem.

**Comment by SirStendec** [comment]
Duplicate #681
