### ISSUE TITLE
Metadata not visible when hovering over the player in theater mode

### ISSUE THREAD

**Issue by UnknownSoldier9865** [FrankerFaceZ/FrankerFaceZ#72]
**Web Browser**: Chrome 

**Do you use BetterTTV or other Twitch extensions?**: BTTV, FFZ, Hide Unwanted Streams, KappaEverywhere

I always Twitch in theater mode; and when you mouse over onto the stream, you'll see this [example](http://i.imgur.com/geoNBtB.jpg); It's been the stream name and game displayed up top, and in the bottom left it was number if viewers, uptime, latency and host. and as of the last couple days, it seems to have diapered... I've gone through both BTTV's, and FFZ's setting and couldn't find anything related to it... Is there any way to bring it back?

I know there is always [this option](http://i.imgur.com/0i7OQy2.png) but unlike the other feature, this is always displayed on the screen.

I've been previously told that this is not a feature with BTTV, so the only other option is FFZ...

**Comment by SirStendec** [comment]
This feature can be effectively considered removed at this time. The changes Twitch recently made to the player to support their mini player feature put it in another layer separate from other channel content and, as such, makes rendering over it much more effort than the feature took before.

At this point I'm considering it more trouble than it's worth to fix when people can just use a button of keyboard shortcut to briefly exit theater mode and then re-enable it after seeing what they need. It's unfortunate but it's also very low priority.
