### ISSUE TITLE
[Feature Request] Prevent Hype Train box from appearing.

### ISSUE THREAD

**Issue by Tinase-nau** [FrankerFaceZ/FrankerFaceZ#721]
**Is your feature request related to a problem? Please describe.**
Twitch added obnoxious Hype Train box to top of chat which appears several times a day.

**Describe the solution you'd like**
We need a function to hide that abomination from sight.

**Comment by thegamerx1** [comment]
maybe just make it smaller

**Comment by thegamerx1** [comment]
closed why?

**Comment by Tinase-nau** [comment]
Feature has been implemented into FFZ as option to hide abomination train box. Check your FFZ's settings.

**Comment by thegamerx1** [comment]
expected something like this..
![image](https://user-images.githubusercontent.com/34986564/76128629-24662b80-6005-11ea-821b-b6f8dbe4555b.png)
