### ISSUE TITLE
the api shows emotes that are not global

### ISSUE THREAD

**Issue by cinemassacres** [FrankerFaceZ/FrankerFaceZ#723]
**Describe the bug**
the api shows emotes that are not global they cause a problem for third party apps like Chatterino
**To Reproduce**
1. Go to https://api.frankerfacez.com/v1/set/global
4. See AndKnuckles OiMinna OBOY 

**Expected behavior**
them not to be there
**Screenshots**
N/A
**Environment (please complete the following information):**
N/A

**Additional context**

**Comment by SirStendec** [comment]
The bug is with third party apps that do not properly handle our API response.

Documentation from https://www.frankerfacez.com/developers :

## GET `/set/global`
> Fetch all sets that could be used globally. That is, sets that aren't associated with specific chat rooms.
> 
> Not all users should be able to use all of the sets provided. The `default_sets` key of the returned object contains a list of set IDs that should be available for all users to use.
> 
> A mapping of emote sets to users that should be allowed to use them globally is provided.
