### ISSUE TITLE
Auto clicker for channel points

### ISSUE THREAD

**Issue by Alimao1905** [FrankerFaceZ/FrankerFaceZ#724]
Auto click the channel points
![Opera Snapshot_2020-01-15_112910_www twitch tv](https://user-images.githubusercontent.com/59922544/72441932-53d98400-378a-11ea-8ace-ced379dd9b7e.png)

**Comment by zoton2** [comment]
Duplicate of #681

**Comment by Alimao1905** [comment]
> Duplicate of #681

sorry, I tried to edit and unintentionally create another one.
