### ISSUE TITLE
Rewind like Youtube

### ISSUE THREAD

**Issue by Alimao1905** [FrankerFaceZ/FrankerFaceZ#728]
**Is your feature request related to a problem? Please describe.**
I'm just upset that I can't rewind like Youtube LiveStreaming that you can rewind 5 secs or so when you press the left arrow on your keyboard

**Additional context**
I know it may be hard but I'm just saying I'd like a feature like that

**Comment by SirStendec** [comment]
I am not touching the player, sorry. You're asking for something that would literally take hundreds of hours of work. If not more. And it still wouldn't work well without native support from Twitch.
