### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by Alimao1905** [FrankerFaceZ/FrankerFaceZ#729]
**Describe the bug**
Everytime I put the mouse in the chat it goes to the very top of the chat

**To Reproduce**
1. Go to Twitch
2. Hold the mouse to the chat
3. And when I scroll just a little bit it goes to the top of the chat

**Expected behavior**
It should go the same as I scroll but it goes to the top.

**Environment (please complete the following information):**
 - OS: Windows
 - Browser: Opera GX
 - Other Extensions: Install Chrome Extensions, Opera Ad Blocker and Social Blade.

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**: settings
-------------------------------------------------------------------------------
socket.use-cluster: "Production"
i18n.debug.capture: false
i18n.debug.transform: null
i18n.locale: "en"
addons.dev.server: false
chat.bits.show: true
layout.display-bits-button: true
theme.can-dark: true
theme.is-dark: true
theme.dark: false
theme.color.background: ""
theme.color.text: ""
layout.swap-sidebars: false
layout.theatre-navigation: false
layout.minimal-navigation: false
layout.side-nav.show-avatars: true
layout.side-nav.show: true
layout.side-nav.show-rec-friends: true
layout.side-nav.hide-offline: false
layout.prime-offers: true
layout.discover: true
channel.round-avatars: true
channel.hide-not-live-bar: true
channel.hide-live-indicator: true
layout.side-nav.rerun-style: 1
layout.side-nav.show-rec-channels: 1
layout.side-nav.show-friends: 1
whispers.show: true
layout.theme.global-font: ""
metadata.host-button: false
channel.hosting.enable: true
channel.metadata.force-above: true
metadata.featured-follow: true
layout.portrait-invert: false
layout.portrait: false
layout.portrait-threshold: 1.25
layout.use-portrait: false
layout.inject-portrait: false
layout.use-portrait-swapped: false
player.theatre.metadata: true
layout.use-portrait-meta: false
layout.use-portrait-meta-top: false
layout.portrait-extra-width: 24
player.theatre.no-whispers: false
layout.portrait-extra-height: 14
player.volume-always-shown: false
player.ext-interaction: true
player.hide-mouse: true
player.hide-event-bar: false
player.hide-rerun-bar: false
player.captions.font-size: ""
player.captions.font-family: ""
player.ext-hide: 0
player.no-autoplay: true
player.button.reset: true
player.allow-catchup: true
player.theatre.auto-enter: false
metadata.uptime: 2
metadata.player-stats: true
directory.show-channel-avatars: true
directory.hide-live: false
ffz.show-new-settings: true
chat.width: 340
chat.use-width: false
sub-button.prime-notice: true
player.hide-squad-banner: false
metadata.stream-delay-warning: 10

**Comment by SirStendec** [comment]
I am unable to reproduce any scrolling issues with Opera GX, with or without Social Blade also installed.
