### ISSUE TITLE
blocked terms

### ISSUE THREAD

**Issue by Alimao1905** [FrankerFaceZ/FrankerFaceZ#731]
**Is your feature request related to a problem? Please describe.**
yes, I put some blocked terms and it just remove the term and not the full message

**Describe the solution you'd like**
I'd like to remove the whole message from the chat and not just the word

**Comment by Lordmau5** [comment]
That's already implemented - make sure that if you add a blocked term that this is clicked so the eye is striked through (as seen in the 2nd screenshot)
![image](https://user-images.githubusercontent.com/1345036/72682797-637e0300-3ad1-11ea-9d69-37beac306f5d.png)

![image](https://user-images.githubusercontent.com/1345036/72682801-7395e280-3ad1-11ea-8183-a83a4910fecb.png)
