### ISSUE TITLE
Emotes in titles

### ISSUE THREAD

**Issue by Alimao1905** [FrankerFaceZ/FrankerFaceZ#733]
**Is your feature request related to a problem? Please describe.**
I see sometimes streamers putting like: WeirdChamp, Pog, etc in the title.

**Describe alternatives you've considered**
Put the emotes that the channel has in bttv and ffz.

**Comment by SirStendec** [comment]
No. Primarily because we don't always have emote data loaded in contexts where we need to render a channel title, so it would be inconsistent.
