### ISSUE TITLE
Minimize Navigation doesn't work

### ISSUE THREAD

**Issue by Taizunz** [FrankerFaceZ/FrankerFaceZ#735]
**Describe the bug**
Minimize Navigation no longer works as expected. The top navigation bar stays in place.

**To Reproduce**
1. Enable "Minimize Navigation" in FFZ Control Panel
2. Notice that the top navigation bar doesn't minimize.

**Expected behavior**
I expected the top navigation bar to slide out of view when not hovering my mouse over it.

**Screenshots**
GIF of expected behavior: https://gfycat.com/anothermilkydrafthorse
GIF of bug: https://gfycat.com/bothunawarechrysalis

**Environment (please complete the following information):**
 - OS: Windows 10 Pro N, 1809
 - Browser: Tested in Chrome 71.0.3578.80 (Official Build) (64-bit) and in Firefox 71.0 (64-bit)
 - Other Extensions:
 In Chrome: Too many to list.
 In Firefox: Just FFZ.

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:
(The uploader in the Feedback menu either takes ages or isn't working for me, so I've uploaded it to pastebin myself)
Firefox log: https://pastebin.com/x7W89AuF
Chrome log: https://pastebin.com/fsQaw5Ue

**Comment by ApocalypsePlease0** [comment]
Same thing happening to me.

**Comment by Taizunz** [comment]
Looks like it's been fixed. Closing this.
