### ISSUE TITLE
VERY IMPORTANT issue regarding FRAUD, BITS, and Kappa420

### ISSUE THREAD

**Issue by hawkjameses** [FrankerFaceZ/FrankerFaceZ#74]
**Web Browser**:
Chrome
**Do you use BetterTTV or other Twitch extensions**:
I use BTTV, irrelevant.
**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:
N/A

**Bug / Idea**:
The following is regarding the new bits feature in chat, and a few emotes on FFZ that directly clash with the new processes, and more importantly, how it STEALS MONEY FROM UNKNOWING USERS.  This feature is new, and the emotes in questions are old... in this way, many channels with this emote are stealing this money on ACCIDENT, I should make that clear, however the potential to take advantage of the situation currently exists.

The feature that said emotes are clashing with is the new "cheer" function in which you can cheer with an emote attached to it, by using Kappa, Kreygasm, or SwiftRage before the number you want to cheer.  THEREFOR, any emote that starts with "cheer", "kappa", "kreygasm", or "swiftrage", which then continues with numbers, such as the only example I have "Kappa420", will proceed to spend the unknowing user's bits, instead of portraying the Kappa420 emote they are trying to generate.

You get it, right?  OK so I'm actually going to search through each one, because I realize its sort of easy.  The emotes that breach this boundary are as follows.

Kappa1, Kappa2, Kappa420 (there are 4 called Kappa420, 3 public, 1 private)

and as far as I can tell, there are no more.  none for "cheer", "kreygasm", or "swiftrage" that breaches the boundaries.

**Steps to Reproduce (if Applicable)**:
Go to a twitch.tv channel that accepts bits as donations.  type in Kappa420 as if you are trying to generate the Kappa420 emote.

![image](https://cloud.githubusercontent.com/assets/18111729/21478100/2e7013fe-caec-11e6-8bc2-f9703781d0f4.png)

**Comment by SirStendec** [comment]
The FrankerFaceZ emoticons with names that have become invalid thanks to the recent Twitch changes have been renamed to include underscores in an effort to reduce confusion. Thank you for bringing the bad names to my attention.
