### ISSUE TITLE
Reset Player Enhancement

### ISSUE THREAD

**Issue by SephirothWS** [FrankerFaceZ/FrankerFaceZ#745]
For the button to reset the video player, can we get an option to have it show up when the dreaded error 2000 hits? I'm getting so tired of error 2000 completely disabling the video player controls and forcing me to refresh the entire page just to get a stream back. I would love to be able to reload the video stream without refreshing the page and LOSING chat, specially as a moderator in some channels.

**Comment by SirStendec** [comment]
I already try to do that, but the player is very finnicky and it doesn't always catch the errors. There is, however, already a way to reset a player without access to the controls and without refreshing the page.

If you open the profile selector by right-clicking the FFZ menu button, there's a Reset All Players button in the upper left of the profile selector:

![image](https://user-images.githubusercontent.com/14036657/73312132-029faa80-41f6-11ea-8548-65ab94a49514.png)

**Comment by SephirothWS** [comment]
"If you open the profile selector by right-clicking the FFZ menu button," ... I did not even know this menu was even a thing. Thanks for the heads-up.
