### ISSUE TITLE
Disable the stream latency in reruns

### ISSUE THREAD

**Issue by Alimao1905** [FrankerFaceZ/FrankerFaceZ#752]
![2020-02-03 (3)](https://user-images.githubusercontent.com/59922544/73675227-c86c5800-4690-11ea-9e97-1f622193c423.png)
**Is your feature request related to a problem? Please describe.**
I think it doesn't make sense to show stream latency in a rerun.

**Describe alternatives you've considered**
Have an option to hide the "playback statistics" in reruns.

**Comment by SirStendec** [comment]
Reruns aren't new content, but they *are* live content. They are delivered in the same way that other live content is delivered. They are live as far as the player is concerned, so they're live as far as I'm concerned. You can fall behind watching a rerun, and that's what the Stream Latency display is there for.

This is working as intended.
