### ISSUE TITLE
colored mentions

### ISSUE THREAD

**Issue by chneau** [FrankerFaceZ/FrankerFaceZ#753]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated with following conversation between **other** users, spending half the time looking up usernames and scrolling up to understand why someone said something to someone.

**Describe the solution you'd like**
Mentions (eg `@otheruser` ) will have the color of the username color.

**Describe alternatives you've considered**
The option to click on a mention and highlight the user message is good enough but it requires to click.

**Additional context**
![image](https://user-images.githubusercontent.com/5753629/74087630-3c8a6f80-4a86-11ea-86f4-b10f00f84e51.png)

![image](https://user-images.githubusercontent.com/5753629/74087658-6fccfe80-4a86-11ea-91f1-dcb26f9cff46.png)
So for example here:
the chat text color "@isoidiki" from torkoax message becomes red because isoidiki pseudo is red.

I know different users can have the same color, it could be a very good QoL feature.

**Comment by Lordmau5** [comment]
You can already change the background color for highlighted words - it's in Chat -> Filtering -> Appearance
![image](https://user-images.githubusercontent.com/1345036/74088552-f63e0c00-4a97-11ea-8a4a-687eeebc2e6d.png)

Additionally, you can set the global highlight color, too
![image](https://user-images.githubusercontent.com/1345036/74088584-40bf8880-4a98-11ea-8431-fa68dd5ac0a4.png)

The idea of a username-based highlight color option isn't bad per-se, but it would cause the text to not be readable anymore from what I can tell...

**Comment by chneau** [comment]
Hello,

Here is another screenshot of what it could look like:

![image](https://user-images.githubusercontent.com/5753629/74088756-98a6c100-4a91-11ea-9238-51ff84b0aac9.png)

As you said it could be less readable for some, but I truly like it. It makes it way easier if you follow an interesting conversation between a few people.

Similarly, another idea I had and which could be a nice compromise would be to highlight the messages of an user when you mouse over a mention (which is slightly different than the already existing option to highlight messages of an user when you click on the name/mention).

I might try to implement it.

**Comment by chneau** [comment]
So far I could produce the result I wanted with this:

```js
function getColor(recipient) {
	let usernames = [...document.querySelectorAll(".chat-line__username")];
	return usernames.reduce((acc, cur) => {
		acc[cur.innerText.toLowerCase()] = cur.style.color;
		return acc;
	}, {})[recipient] || "#AAAAAA";
}
```
^^^ of course this is the worst way to get the color of an username, after a few minutes searching I couldn't find anything I decided to implement this little hack to go forward.

and modifying the `export const Mentions` from `tokenizers.jsx` to have a style color

```jsx
	render(token, createElement) {
		return (<strong
			class={`chat-line__message-mention${token.me ? ' ffz--mention-me' : ''}`}
			style={{ color: getColor(token.recipient) }}
			data-login={token.recipient}
			onClick={this.handleMentionClick}
		>
			{token.text}
		</strong>)
	},
```
![image](https://user-images.githubusercontent.com/5753629/74090689-2ee4e200-4aa6-11ea-9450-1b14d4bd38e0.png)


let me know what you think of that, and if you know a better way to get the color of a username in the chat from the module chat.
