### ISSUE TITLE
Reset Player Enchancement (Take 2)

### ISSUE THREAD

**Issue by SephirothWS** [FrankerFaceZ/FrankerFaceZ#754]
**Is your feature request related to a problem? Please describe.**
So I get frustrated when I get "There was a Network Error. Please try again. (Error 2000)" which removes video controls from the page. I created #745 inquiring about the addition of the reset player button to the player area when this happens. Was told it's in the right-click menu for FFZ when you go to switch profiles. Well, turns out that button doesn't actually reset the player when Error 2000 happens despite double-clicking it.

**Describe the solution you'd like**
I would like double-clicking the reset player button during a Network Error (2000) to actually reset the video player.

**Additional context**
As a moderator of various channels, having to **REFRESH** the entire page (Thus losing chat history and losing an eye on chat) the *entire page* is just counterproductive to moderating chat. I'd love for a way to get Error 2000 to go away without losing chat history.

**Comment by SirStendec** [comment]
This has been fixed now.
