### ISSUE TITLE
Image thumbnail for imgur and youtube not working 

### ISSUE THREAD

**Issue by JordanDi123** [FrankerFaceZ/FrankerFaceZ#76]
**Web Browser**: Google Chrome

**Do you use BetterTTV or other Twitch extensions**: I use BTTV4FFZ

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: http://putco.de/NTI5MA.log

**Bug / Idea**: Not displaying the thumbnail

**Steps to Reproduce (if Applicable)**: Try to hover over the links and it will not show any image

**Comment by SirStendec** [comment]
Duplicate of #15.
