### ISSUE TITLE
Badge categories are collapsed/do not show individual badges besides in the FrankerFaceZ/Add-on sections.

### ISSUE THREAD

**Issue by M1ch431** [FrankerFaceZ/FrankerFaceZ#761]
**Description:**
Badge categories are collapsed/do not show individual badges besides in the FrankerFaceZ/Add-on sections.

**To Reproduce:**
1. Go to the Chat >> Badges subsection.
2. Click on the visibility tab.
3. See error.

**Expected behavior:**
All badges should be listed with a toggle next to them.

**Screenshot:**
![https://i.imgur.com/X1P92i3.png](https://i.imgur.com/X1P92i3.png)

**Environment:**
 - OS: Windows 10 LTSC 2019 (1809).
 - Browser: Firefox Nightly v75.0a1.
 - Version: 4.19.0.

**Comment by M1ch431** [comment]
Seems fine now.

**Comment by SirStendec** [comment]
Just to clarify: this happens when the client hasn't yet loaded the actual Twitch badge data. That only happens the first time you view a page with chat. I should probably display a message about that, but it's a pretty small issue so it's hard to devote time to it.
