### ISSUE TITLE
Settings missing in Chrome

### ISSUE THREAD

**Issue by Gamerbiomek2** [FrankerFaceZ/FrankerFaceZ#762]
Not seeing the FFZ settings menu where it's supposed to be

**Comment by SirStendec** [comment]
This is not a valid bug report. You haven't filled out an issue template. You haven't provided any actual details about what's going on. You just said "It's not working."

1. Make sure the script isn't being blocked by Privacy Badger or other extensions you have installed.
2. Make sure you have the actual FFZ extension or user-script installed and not only "FFZ Add-on Pack" or "FFZ Enhancing Addon" or something.
3. If you're still having an issue at that point, please provide actual details about your setup. Installed extensions, versions of things, things you've tried. Just saying it doesn't work doesn't help at all.

**Comment by Gamerbiomek2** [comment]
I guess privacy badger was blocking it when I told not lol
