### ISSUE TITLE
Chat filter

### ISSUE THREAD

**Issue by thegamerx1** [FrankerFaceZ/FrankerFaceZ#764]
a chat filter like chitchat.ma.pe that can be easily disabled or enabled, some streamers with thousands of viewers have sub mode disabled and chat is unreadable

![image](https://user-images.githubusercontent.com/34986564/76167196-3c54c100-6165-11ea-815d-86f70ad9daa6.png)
spam 90% (got up to 96%)
actual chat 10%

**Comment by yontekh** [comment]
I will like this, either that or make FFZ emotes work on that domain (chitchat.ma.pe) aswell.
