### ISSUE TITLE
Stream Uptime on the following page are missing and not displaying

### ISSUE THREAD

**Issue by Morten79** [FrankerFaceZ/FrankerFaceZ#765]
After the recent FFZ update the stream uptime for each stream at the directory are not displaying anymore on the upper right corner. Both Live channels and Live hosts channels further down on the following page aren't showing any uptime info anymore.
Additionally all options like "Display channel avatars." under  Settings » Directory » Channels seems to have no effect.

1. https://www.twitch.tv/directory/following
2. navigate to Settings -> Directory -> Channels 
3. ... and make sure "Display the stream uptime on the channel cards" are set to Enabled.

**Expected behavior**
FFZ with it's default settings should be able too display the uptime of any streams the user are following.

 - OS: Windows 10 64bit Home Ed.
 - Browser: Google Chrome 80
 - I haven't installed any other extension that run / or modify Twitch.

My FFZ Logs:
`https://pastebin.com/B0NiTC0C`

**Comment by Morten79** [comment]
Please try and fix this little issue and I'll be very grateful.

**Comment by tbergeron** [comment]
Been having the same issue for the past week+ as well.
I can see uptime on stream page but not on followin page.
Same config as OP.

**Comment by milofeC1** [comment]
I'm having a similar issue but I can't see the uptime on any channel card anywhere on twitch (Stream uptime is enabled).

**Comment by DuhMe** [comment]
On the FrankerFaceZ Discord it was said that this feature broke due to changes Twitch made which is pretty apparent. They also said that due to those changes Twitch made it harder to get to the information that's needed to make it work again.
