### ISSUE TITLE
Option to move FFZ settings button from top nav to user menu

### ISSUE THREAD

**Issue by pointydev** [FrankerFaceZ/FrankerFaceZ#773]
**Is your feature request related to a problem? Please describe.**
Recently I installed FFZ and noticed that the Control Center button is prominently positioned in the top navigation. I find it partially annoying as my pre-existing BTTV installed puts it's settings button in the "user menu" (see additional context), making the FFZ button seem out of place.

**Describe the solution you'd like**
I think an *option* that allows users to move the FFZ to a position similar to how BTTV handles it, putting it more out of the way. This would, personally, streamline my extension management.

**Describe alternatives you've considered**
On the [creator dashboard](https://dashboard.twitch.tv/), BTTV doesn't continue this behaviour, however like FFZ, it does allow access to it's settings via the Chat Settings menu in chat. In this situation, the option I described could be disabled, or this situation could be ignored entirely.

**Additional context**
![](https://pointy.needs-to-s.top/9zRUutD.png)

Thanks,
Elliott

**Comment by SirStendec** [comment]
No.

Reasoning:

1. Branding. Displaying the FFZ Control Center button prominently makes it obvious that the extension is installed. This is, I think, a good thing. Users don't forget they have it. Anyone seeing their browser sees they have it.

2. Notifications. The FFZ Control Center button can be used to display FFZ related notifications to the user. Currently, this is mainly limited to grabbing user attention when new settings are added to the extension. In the future, once the new website is complete, this will also be used to notify users when their submissions have been reviewed.

3. The FFZ Control Center button serves as an obvious indicator that the extension has loaded. When users are having trouble with the extension, often the button does not appear, making it obvious that something is wrong. Hiding it within the user menu would make it more annoying. From a coding perspective, it is more prone to failure if it's within a dynamic menu.

4. It's literally only 30 by 30 pixels, next to three other buttons that are 30 by 30 pixels. It doesn't exactly stand out.
