### ISSUE TITLE
[Feature request] Ability to open settings when watching VODs (using ReChat)

### ISSUE THREAD

**Issue by RedSnt** [FrankerFaceZ/FrankerFaceZ#78]
No way to access FFZ settings when watching VODs. Would like the ability to.

Personally I'd like this feature mostly to be able to use the "Swap Sidebar Positions" feature while watching VOD's but I'm sure other users would have different preferences.

**Comment by SirStendec** [comment]
This will be taken care of when the settings UI rewrite comes in the next month or two. Settings UI is going to be accessed via the sidebar rather than chat.
