### ISSUE TITLE
Mouse wheel volume control issue.

### ISSUE THREAD

**Issue by Rupthya** [FrankerFaceZ/FrankerFaceZ#783]
**Describe the bug**
Mouse wheel volume control sets the volume to max after certain behaviour.

**To Reproduce**
1. Adjust volume by scrolling with the mouse wheel option enabled,
2. View any channel then go to any other channel at same tab without refresh.
3. mouse wheel down to lower volume,
4. **Volume jumps to max.**

**Expected behavior**
the volume should be lower and not set to max.

**Environment (please complete the following information):**

- OS: Windows 10
- Browser: Microsoft Edge
- Version: 81.0.416.53
- Other Extensions: BetterTTV, UBlock Origin, Stylus

**Additional context**
Also reprodue issue at Incognito mode with FFZ only.
Issue similar to this one https://github.com/FrankerFaceZ/FrankerFaceZ/issues/781

**Comment by whtft** [comment]
Just FYI, those logs are exposing sensitive personal data, if you care at all you should redact them.  
Tried to warn you via PM on twitch but your privacy settings didn't allow me ¯\\\_(ツ)_/¯

**Comment by Rupthya** [comment]
> Just FYI, those logs are exposing sensitive personal data, if you care at all you should redact them.
> Tried to warn you via PM on twitch but your privacy settings didn't allow me ¯\_(ツ)_/¯
> 
> FWIW I also have this bug. Same env. as before.

Thank you i already removed the log.

**Comment by SirStendec** [comment]
Closed in 13af2f304697b9e71d5abfcd79561815059e6994
