### ISSUE TITLE
Whisper chat unusable (only when FFZ enabled)

### ISSUE THREAD

**Issue by NRN1337** [FrankerFaceZ/FrankerFaceZ#784]
**Describe the bug**
I use whisper a lot because we don't wanna spam normal chat and we usually talk over whispers so we don't spam as much in chat but sometimes I have issue(s) such as not being able to re-open their chat and having to open another tab just to whisper them again (don't wanna do this because of obvious reason-chat log for the channel). 

**To Reproduce**
1. Go to whisper icon 
2. Click on the person's name you whispered
3. Nothing happens,chat doesn't open nor you can do anything about it.

**Expected behavior**
When clicking person's name on whisper,should open chat and be able to reply back.

**Screenshots**
Dual monitors as an example. On 2nd tab I can open the message and reply back but on the "original" one,I can't. 
https://i.imgur.com/bY9aUDE.png - Right monitor is main. 

**Environment (please complete the following information):**
 - OS: Win10x64Pro1909
 - Browser: Chrome&Opera
 - Version: 
  Tested on: Chrome 80.0.3987.132 and 81.0.4044.113 (it's bugged on both) 
  Opera: 67.0.3575.137
 - Other Extensions: uBlock Origin,BTTV

**Comment by solidmoose** [comment]
We might be having the same issue - I am unable to open whisper chatboxes when on a stream but I can do it on the front Twitch page or directory. This seems to be a problem with the "Hide whispers when Theatre Mode is enabled" setting. (Found under Player > General > Theatre Mode.) Try unchecking that for now and see if it fixes your issue.

**Comment by NRN1337** [comment]
> We might be having the same issue - I am unable to open whisper chatboxes when on a stream but I can do it on the front Twitch page or directory. This seems to be a problem with the "Hide whispers when Theatre Mode is enabled" setting. (Found under Player > General > Theatre Mode.) Try unchecking that for now and see if it fixes your issue.

I didn't had it on.
