### ISSUE TITLE
Highlight Messages with User Card Open Not Working

### ISSUE THREAD

**Issue by StingerPA** [FrankerFaceZ/FrankerFaceZ#785]
**Describe the bug**
When I open a user card to highlight a user's messages in chat, it does not highlight user messages in chat.

**To Reproduce**
1. Go to "Chat -> Viewer Cards"
2. Turn on "Highlight Messages from users with open viewer cards"
3. Open a user card in chat by clicking someone's name
4. User messages are not highlighted

**Expected behavior**
When opening a user card, all messages from that user in chat are to be highlighted.

**Screenshots**
https://i.imgur.com/jBpu5fx.png

**Environment (please complete the following information):**
 - OS: Windows 10 Home
 - Browser: Chrome
 - Version: 81.0.4044.113 (Official Build) (64-bit)
 - Other Extensions:: uBlock Origin, Stylish (not enabled on Twitch)

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**
https://pastebin.com/bF4csJnv

**Additional Context**
Similar issue to #780, although that report is specific to mod view

**Comment by SirStendec** [comment]
Closed in 13af2f304697b9e71d5abfcd79561815059e6994
