### ISSUE TITLE
Font Size chat box bug

### ISSUE THREAD

**Issue by Bloodhit** [FrankerFaceZ/FrankerFaceZ#788]
**Describe the bug**
When Font Size under Chat>Appearance set bigger than 12(Default value) first 3 symbols expand chat box by 3 lines

**To Reproduce**
1. Go to 'Chat>Appearance'
2. Set 'Font Size' to 13 or bigger
3. Type in chat
4. First 3 symbols expand chat upwards by 1 line each.

**Expected behavior**
Chat box doesn't expands with font size change.

**Screenshots**
https://imgur.com/nam9ZJx

**Environment (please complete the following information):**
 - OS: Win10
 - Browser Chrome
 - Version  80.0.3987.163 
 - Other Extensions: Ublock Origin

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:
https://pastebin.com/HRmdJUJm

**Comment by SirStendec** [comment]
This is a bug with Twitch, triggered by having a different font size as you've pointed out. It can also happen without extensions, so I've submitted it to Twitch to fix themselves.

Hopefully they fix it within a day or two. If it takes too long, then I'll consider fixing it myself.
