### ISSUE TITLE
Toggle message filters

### ISSUE THREAD

**Issue by gr3ger** [FrankerFaceZ/FrankerFaceZ#792]
**Is your feature request related to a problem? Please describe.**
When I'm modding for certain streams I would like to highlight specific things in chat with the Chat Filtering -> Highlight Terms, but for other streams I would rather not have this filter enabled.

**Describe the solution you'd like**
One option would be to simply have an enabled/disabled toggle on each filter so you can easily manage them.

**Describe alternatives you've considered**
I considered using different profiles, but since I in general like to keep my FFZ settings uniform I have to manually change the settings in every profile if I want them to be the same except for the filters.

**Comment by SirStendec** [comment]
You seem to be misunderstanding how profiles work. You do not have to change settings in every profile to keep them in sync.

Multiple profiles can be active at one time. They cascade. If a setting isn't set in the first active profile, then the next ones are checked until the setting is found or, if it isn't set, the default value is used.

So, as an example, you would make profiles that *only* contain filters and no other settings.


Aside from that, I do plan on eventually having toggles for filtering rules whenever I finally have time to work on a more advance filtering system.

**Comment by gr3ger** [comment]
Oh wow, didn't realize they worked that way, I just assumed they were mutually exclusive.
Thanks for the help!

I'll use profiles in the meantime then :)

**Comment by gr3ger** [comment]
Closing since it was me misunderstanding how profiles work.
