### ISSUE TITLE
Incompatibilities with New Twitch Layout

### ISSUE THREAD

**Issue by MakoSDV** [FrankerFaceZ/FrankerFaceZ#794]
**Describe the bug**
When enabling the _Appearance>Layout>Swap Sidebars_ option, the Stream Chat panel is replaced with an empty blank space instead of swapping to the left side.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 76.0
 - Other Extensions: uBlock Origin, NoScript

**Screenshots:**
![image](https://user-images.githubusercontent.com/26930776/81353770-f8643680-9097-11ea-9851-825a1cf33f9a.png)
![image](https://user-images.githubusercontent.com/26930776/81353792-07e37f80-9098-11ea-94ed-19bbb8dc3147.png)

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:
The Upload option in FFZ didn't complete, so I copied the log to a file and attached it.
[FFZ.log](https://github.com/FrankerFaceZ/FrankerFaceZ/files/4596247/FFZ.log)

**Comment by SirStendec** [comment]
You're experiencing a Twitch experiment at 2% roll-out. It's probably going to become the new layout, but I can't really support it yet when 98% of users are on the old layout still.

The experiment controlling this is called `watch_stunt_double_user`. I'll be watching it and adding support later.

**Comment by MakoSDV** [comment]
OK, thanks.  Lucky me...  I can see the `watch_stunt_double_user` references in the core js from twitch.

I totally understand that you can't easily support Twitch experiments like this.  I'm glad you're already aware of it.

I assume this also causes the _Chat>Appearance>Width_ to no longer work properly and for the _Player>General>Show metadata when mousing over the player_ to no longer show up.

I'll keep an eye out for any other things that misbehave with this experimental layout.  Let me know if I can provide anything helpful related to it.

**Comment by embrsword** [comment]
Same story for me but a few more details
With FFZ enabled the layout seems to switch to a more 4:3 arrangement and pinned to the left leaving an empty region on the right
Swapping side panels makes the chat disappear off the left of the screen.

Was not seeing the issue reproduced in Chrome suggesting its possibly controlled by cookies rather than per user. I was signed in on both FF and Chrome

**Comment by SirStendec** [comment]
Just to note for anyone stumbling across this, it is also known that metadata such as FFZ's custom uptime display, player latency, and the hosting button aren't working on the new layout.

**Comment by CyBeRoni** [comment]
When you don't have the chat swapped to the other side, there's a huge empty area.

![image](https://user-images.githubusercontent.com/5394358/81666397-4a171300-9442-11ea-9ac6-50b3293b9dd1.png)

I do believe this will be the new layout going forward, they're just rolling it out slowly. Thanks for telling us the experiment name to disable it, I couldn't find it myself.

**Comment by tbodt** [comment]
It's now at 32%, should probably add support soon

**Comment by cmd430** [comment]
now at 50% rollout

**Comment by brandinarsenault** [comment]
- Channel -> Metadata -> Stream Uptime: Uptime counter is currently broken and uses Twitch's new native, consider allowing option to modify (based on FFZ settings including toggle off) or removing the setting all together
- Channel -> Metadata -> Playback Statistics -> Playback Statistics: Latency data below player is broken
- Channel -> Metadata -> Host Button: Button does not show 
- Channel -> Behavior -> Enable Channel Hosting: Toggle doesn't work with new hosting method (which is the worst thing Twitch has updated btw)
- Channel -> Appearance -> Hide the "LIVE" Indicator: This toggle seems to not work anymore, the LIVE badge is now under the player so likely had some modified elements 

I haven't tested the "Event", "Rerun" or "Squad Streaming" bar

**Comment by cmd430** [comment]
I have a working CSS fix for Swap Sidebars Pref for the new Layout
For now you can use this with a style injector i.e Stylus

```css
.channel-root__player--with-chat {
  left: 34rem;
}
.channel-root__right-column--expanded,
.toggle-visibility__right-column--expanded {
  transform: translateX(0rem);
}
.channel-root__info--with-chat {
  position: relative;
  left: 34rem;
}
```

**Comment by SirStendec** [comment]
Swap Sidebars, chat width, and portrait mode are all working now.

Hosting control and metadata are still not working.

**Comment by Khurzol** [comment]
Chat width doesn't seem to work still on Chromium Edge. Here's a screenshot. I made sure to re-install the add-on as well as clearing cache.
![ffz](https://user-images.githubusercontent.com/33005531/83090230-98f6b680-a098-11ea-870b-f71f61b9a900.png)

**Comment by Techjar** [comment]
Dunno if this has been reported, but "Automatically open Theatre Mode when visiting a channel." is also horribly busted with the new layout.

**Comment by ceresse** [comment]
I've been trying to figure this out as to why the following navigation panel won't go to the right side when I use Swap Sidebars.

![5db494be1141a03af355ad2c36117383](https://user-images.githubusercontent.com/47435219/84201344-efd79500-aa75-11ea-8bb7-63017ca014f1.jpg)

**Comment by Californ1a** [comment]
Just to add since it's very minor and might be glossed over otherwise - when swapping between regular and theater mode, the chat background color gets brighter in theater mode with the new layout. There's less contrast between the text and background, making it a bit harder to read.

**Comment by Techjar** [comment]
Looks like the new layout is now at 100% rollout.

**Comment by ifonefox** [comment]
I'm also not seeing highlighted messages like #821. However, it's still working correctly if you pop out the chat. It looks like the the css for `.ffz--points-highlight` sets the background color to the variable  `--ffz-channel-color-20`. This variable is supposed to be defined in the `style#ffz--managed-style--1` style sheet, but isn't.

![Screenshot](https://user-images.githubusercontent.com/517314/85077910-54d76d00-b191-11ea-9044-f507c3c0f202.png)

**Comment by fouram** [comment]
In the new layout, I've still got no luck with Swap Sidebars or the enhanced info overlay. Also as an FYI, even at 100% rollout, you seem to still be able to switch the stunt double experiments over to control and the old layout comes up. Not sure how long it'll last, of course.

**Comment by Khurzol** [comment]
As of 4.20 (nice), which fixes a bunch of issues here, these are some incompatibilities I could find:

* Metadata/info overlay doesn't currently show. (#818)
* Bit/gift-subs Leaderboard on top of chat overflows when chat in under default size (off-screen when swap bars is off).
* Channel Rewards menu overflows when chat is under default size (off-screen when swap bars is off).
* Portrait mode doesn't work.
* Disabling Display Channel Avatar (navigation sidebar layout) doesn't do anything.
* The stream player that displays in the background of live channel pages (when you click on someone avatar while they are live) displays on the foreground when “Automatically open Theatre Mode when visiting a channel“ is on.

This isn't an exhaustive list, but that's what I found, poking around with the settings and twitch.
Thank you for your amazing work!

**Comment by embrsword** [comment]
When you swap sidebars, if you try to minimize the followed channels list it minimizes on the left instead of the right

**Comment by SirStendec** [comment]
Portrait Mode, disabling channel avatars in sidebar, and Swap Sidebars are definitely working as intended for me. Are you experiencing the experiment that makes the sidebar pop out when you hover over it?

I'm not sure I can fix the leaderboard overflowing when chat is smaller, so I'm probably going to just leave that be. Maybe throw a width on it just so it cuts itself off when swap sidebars is on.

**Comment by Khurzol** [comment]
Turns out my config of Ublock Origin was blocking "Twitch Polyfill", which was making portrait mode not work (and some non-ffz related bugs here and there). My bad.

I'm not experiencing this experiment, but maybe I'm misunderstanding the function itself. Here is what I see :
![Annotation 2020-06-25 135157](https://user-images.githubusercontent.com/33005531/85714827-1854c580-b6eb-11ea-81a9-5eae836d0a49.png)
I'm not sure if what I see is normal or not. (I usually disable the nav bar personally, I just noticed it didn't change anything when poking around)
Also, I made sure to disable any addon aside ffz for testing :p

**Comment by Techjar** [comment]
It looks like a lot of the issues have been fixed, though the "disable channel hosting" option is still not working on the new layout.

**Comment by SirStendec** [comment]
Today's update has accomplished two things. First, metadata is now working on the new layout. Second, support for the old layout was removed to make room for that.

**Comment by Techjar** [comment]
Automatic theater mode seems to be broken again. Also, why was the disable hosting option removed?

**Comment by SirStendec** [comment]
Automatic Theater Mode has been broken. This latest update did not fix it. The option to disable hosting has not yet been rewritten to work on the new layout, as I'm not sure how to go about it yet. Support for the old layout, where that feature continued to work if you somehow had the old layout, was removed in this update. Cutting out dead code is important to keep the project healthy.

From the sounds of your complaints, you're probably using an experiment override. The feature for overriding experiments is intended for developer use only and we won't support any issues that arise from using it. I can't continue supporting code that Twitch intends to drop and that normal users don't ever see. I just don't have the time.

**Comment by Techjar** [comment]
Yeah I figured support for the old layout would be dropped, just not quite so soon. I thought support for the new layout would be finished first. I'm aware that using experiment overrides isn't necessarily supported, but it was only to revert to the old layout so it worked fine for a while. I thought I saw automatic theater mode working on the new layout, but maybe the page just didn't refresh correctly clearing the experiment override.

Ah well, I guess I shall wait until all the options are ported over. Hosting is especially stupid on the new layout since the background stream cannot be paused (thanks Twitch for your genius website design), so I hope that can be fixed.

**Comment by SESNut** [comment]
automatic theater mode is working in bttv in the new layout but not disable hosting

**Comment by tbodt** [comment]
The one thing that's still broken that I care about is metadata on top of the stream in theater mode.

**Comment by btmcgeev** [comment]
"Show metadata when mousing over the player" doesn't seem to work while the stream/chat layout is in portrait mode. It works if chat is along the side, but as soon as chat moves beneath the player the metadata box stops showing up again on hover.
