### ISSUE TITLE
Popular emotes reach the "int limit" of 32767

### ISSUE THREAD

**Issue by 13ace37** [FrankerFaceZ/FrankerFaceZ#798]
**Describe the bug**
The most subscribed emotes reached the [int limit](https://stackoverflow.com/a/18558328) of 32767. It's not critical but kinda irritating.

**To Reproduce**
1. Go to [Emote Libary](https://www.frankerfacez.com/emoticons/?sort=count-desc) and sort by `count-desc`
2. See the "32767" limit for the top emotes.

**Expected behavior**
Either the number should be limited at 32000+ or stored into another var type.

**Screenshots**
![image](https://user-images.githubusercontent.com/29045525/82027496-9eb1cc80-9694-11ea-9c84-942fa2fdce71.png)

**Environment (please complete the following information):**
 - OS: Win 10
 - Browser Chrome, Chromium, Edge

**Comment by SirStendec** [comment]
This is known and fixed on the in-development APIv2. It will not be fixed on the current website because there is no good time to take the website offline to run the query necessary to update the database column type.
