### ISSUE TITLE
Channel Metadata in Theatre Mode crosses the middle of the screen.

### ISSUE THREAD

**Issue by Luggs123** [FrankerFaceZ/FrankerFaceZ#8]
**Web Browser**: Google Chrome v 53.0.2785.143 m

**Do you use BetterTTV**: Yes.
**Do you use other Twitch extensions**: Yes, Crowdcast. Disabling Crowdcast does not resolve this bug.
**Do you use PrivacyBadger**: No.

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: Could not locate.

**Bug / Idea**: Channel metadata in Theatre Mode is placed across the middle of the screen.

**Steps to Reproduce (if Applicable)**: Occurs consistently and whenever a stream is opened, especially given that BTTV is set to automatically open Theatre Mode.

 [Here](http://i.imgur.com/Xzc6ThO.png) is a link to a screenshot for the bug in question.

**Comment by Devexer** [comment]
This bug is also persistent without BTTV enabled. 
Web Browser: Opera - 40.0.2308.62
Do you use other Twitch extensions: No.
Do you use PrivacyBadger: No.
FFZ Logs: http://putco.de/NDc0Mg.log
