### ISSUE TITLE
Emote parsing bug

### ISSUE THREAD

**Issue by TETYYS** [FrankerFaceZ/FrankerFaceZ#808]
**Describe the bug**
There seems to be some issues when parsing emotes, behavior differs when FFZ extension is disabled

**To Reproduce**
1. Write `TriHard..FFZUSERSDONTSEETHISLULW..` in chat
2. ![chrome_SPtTRRvdh8](https://user-images.githubusercontent.com/3091645/83064463-7cdc2080-a06a-11ea-8b17-27d96452b20b.png)

**Expected behavior**
![chrome_bZ1Ka4gBpd](https://user-images.githubusercontent.com/3091645/83064512-8f565a00-a06a-11ea-8422-117ac08f19b4.png)

**Environment (please complete the following information):**
 - OS: Windows
 - Browser: Chrome 81.0.4044.129
 - FFZ Version 4.19.11 b3266a2
 - Other Extensions: probably not relevant but uBlock, etc., this bug occurs for others as well

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**: 
[log.log](https://github.com/FrankerFaceZ/FrankerFaceZ/files/4691326/log.log)

**Comment by SirStendec** [comment]
Fixed in 261c461481a5eb14e27b57336ef5c907c1c63e14

**Comment by TETYYS** [comment]
Still happens when using commas instead of dots

**Comment by SirStendec** [comment]
Oops, I accidentally typed a `+` instead of a `,` in the fix. Really fixed now.
