### ISSUE TITLE
Optionally configure Visibility of Room Actions based on current Channel

### ISSUE THREAD

**Issue by MakoSDV** [FrankerFaceZ/FrankerFaceZ#810]
**Is your feature request related to a problem? Please describe.**
I have several different room actions defined, but some are only relevant in specific Twitch channels.  For example, a channel specific Hype action.  As a result, I make less use of Room Actions than I would like to.

**Describe the solution you'd like**
Under the Visibility options for a Room Action, have an optional Channel Filter field.  If a channel name is specified, the Room Action will only be visible in the chat for the specified channel.  A list of channels could be used as well, but specifying a single channel name would meet my current needs.

**Describe alternatives you've considered**
An alternative could be to somehow use some logic conditions in the Chat Command to allow one command to have different behavior on different channels.  This sounds harder to implement and harder for users to make use of though.

**Comment by SirStendec** [comment]
This problem is solved by creating multiple settings profiles, with different profiles for different channels. Create a few extra profiles, then use the drop-down in the upper left of the control center to change which profile you're editing.
