### ISSUE TITLE
Compact side navigation option

### ISSUE THREAD

**Issue by drakari** [FrankerFaceZ/FrankerFaceZ#813]
Recently, Twitch changed the behavior of the side navigation to expand when you mouse over it, rather than just giving a small summary when you mouse over a specific channel. I often used the side navigation to see who else is streaming without needing to open a separate tab or leave the stream I was already watching, but I don't find the expanded version useful; I usually look at the titles of streams to make decisions, but the expanded view only shows the streamer's name and the game they're playing. Additionally, I sometimes accidentally mouse over the side navigation when I am attempting to click the mute button, and then it expands to cover the mute button which is annoying.

I would like an option under Appearance > Layout > Side Navigation to prevent the "expand on mouseover" behavior. It could be listed just like that as "Expand on mouseover" checked by default, or something else such as "Compact side navigation" as I wrote in the title.

My annoyances with overshooting the mute button could be improved if expand on mouseover were disabled only for the empty parts of the side navigation, or if the empty parts stayed collapsed even if the rest expanded when any of it is moused over. The functionality of the expanded side navigation could also be improved by including the stream's title in addition or instead of the current information, which would be useful and mitigate my frustration with the feature.

**Comment by drakari** [comment]
After trying another browser, I am unable to replicate the "expand on mouseover" behavior in Chrome. I'm not certain why that would be the case, but it initially appeared in Firefox.

**Comment by SirStendec** [comment]
You're experiencing a Twitch experiment. A/B testing, in other words. It's currently at a relatively low percentage roll-out. I am personally hoping they realize, like they did the last time this was tried, that people don't like it and they remove it.

Please provide feedback directly to Twitch when they make changes that you feel strongly about.

In the future, if this becomes the new norm, I will be looking into a FFZ feature to revert it. For now, I do nothing.
