### ISSUE TITLE
Side Nav Bar Doesn't Auto-Expand

### ISSUE THREAD

**Issue by TheRightScript** [FrankerFaceZ/FrankerFaceZ#815]
**Describe the bug**
Side navigation bar won't expand on mouse hover.

My twitch profile currently has their new layout, however the issue persists even when I logout and am on the old layout. I have tried reinstalling FFZ, resetting the FFZ profile to default settings and have tried the extension in multiple browsers, yet I can't get the side navigation to auto-expand.

When using FFZ on my Laptop the feature works perfectly regardless of profile, account or twitch layout.

**To Reproduce**
1. Open Twitch with FFZ Enabled.
2. Mouse over collapsed side navigation bar.
3. Nothing happens.

**Expected behavior**
Auto expansion of side bar.

**Environment (please complete the following information):**

 - OS: Windows 10 - 1909 
 - Browser Chrome and Vivaldi
 - Version: Chrome: 83.0.4103.97  Vivaldi: 3.0.1874.38
 - Other Extensions: FFZ:AP Core, BetterTTV (through FFZ), Ublock Origin

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:
Upload function not working. Logs attached in txt file.
[ffz logs.txt](https://github.com/FrankerFaceZ/FrankerFaceZ/files/4740025/ffz.logs.txt)

**Comment by SirStendec** [comment]
This is not a bug. This is not a FFZ feature. The side bar expanding on mouse hover is a Twitch experiment.

**Comment by TheRightScript** [comment]
Now I feel like a moron. I could have sworn I saw it as a FFZ feature somewhere. Sorry for the trouble, and thanks for getting back to me.

**Comment by alkaris2** [comment]
Why can't this just be an option that can be toggled in **Appearance > Layout**? It's annoying it's hidden away under Experiments, because every so often I have to in there and set it on because it resets and defaults to 100 instead of 0 which is what I set it to.
