### ISSUE TITLE
More chat filtering options

### ISSUE THREAD

**Issue by RenaKunisaki** [FrankerFaceZ/FrankerFaceZ#82]
**Web Browser**: Chromium

**Do you use BetterTTV or other Twitch extensions**: No

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: http://putco.de/NTMyOQ.log

**Bug / Idea**: More options for chat message filtering:

- Filter messages with more than N emotes
- Filter messages that are all-caps (excluding emotes) - regex filtering can't be used for this because it uses `i` flag
- An API for custom filtering scripts (pass each message in, accept possibly-modified message(s) out)
- Per-channel filters and/or a quick setting to turn individual filters on/off
- Be able to specify that a given filter should not apply to (mods|bots|broadcaster|...) or in channels where you're a moderator
- Per-filter setting for what to do with the message (mark as deleted/remove entirely)

**Comment by SirStendec** [comment]
I've been working on filtering updates for ages now that handles all of these cases. Just waiting on the settings overhaul so it's actually configurable by someone without way too much time on their hands and working knowledge of their browser's JS console.

**Comment by SirStendec** [comment]
Moving to #299
