### ISSUE TITLE
Blocking/Hiding a thumbnail doesn't work

### ISSUE THREAD

**Issue by jorcip** [FrankerFaceZ/FrankerFaceZ#824]
**Web Browser:** Google Chrome 83.0.4103.106 (64-bit)

**Do you use BetterTTV or other Twitch extensions:** Yes (BetterTTV v7.2.81)

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable):** Not Applicable

**Bug / Idea:** Blocking a category or hiding a thumbnail doesn't hide streams that play blocked category.

**Steps to Reproduce (if Applicable):**

1. Go to https://www.twitch.tv/directory
2. Set to "Categories"
3. Pick any category
4. Click "Block" or "Hide thumbnail" button
5. Return to https://www.twitch.tv/directory
6. Set to "Live Channels"
7. You can see that xQc's stream is still shown to me even though I blocked the category

![image](https://user-images.githubusercontent.com/38240056/85065833-287e1980-b1ae-11ea-9f0d-e1d0604fc991.png)

![image](https://user-images.githubusercontent.com/38240056/85065874-36339f00-b1ae-11ea-87ae-2caea4c6d514.png)

**Comment by bantu88** [comment]
Same issue for me with the same Chrome and BTTV version.
Also doesn't work in other browsers such as Firefox.
