### ISSUE TITLE
Maximized dialog goes under chat when chat-fix not applied on channel pages

### ISSUE THREAD

**Issue by ChaosPaladin** [FrankerFaceZ/FrankerFaceZ#833]
**Describe the bug**
Inability to see experiment settings in the new Twitch design, they are hiding under the chat box

**To Reproduce**
Open FFZ control center
Goto Debugging » Experiments

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/10120702/86330403-505e8a00-bc50-11ea-9ffd-d2b0bf1bcbc8.png)
![image](https://user-images.githubusercontent.com/10120702/86330638-a2071480-bc50-11ea-9d03-1181700de817.png)

Old twitch UI enabled by watch_stunt_double_user = control (weight: 0) experiment:
![image](https://user-images.githubusercontent.com/10120702/86330504-72f0a300-bc50-11ea-8ad2-393d49bb8439.png)

**Environment (please complete the following information):**
 - OS: Windows
 - Browser: Opera / Firefox
 - Version: 58.0.3135.90 / 78.0.1
 - Other Extensions: BetterTTV

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**: https://gist.github.com/ChaosPaladin/8d9f591e13a6d53004c59fbc4b0893e4

**Additional context**

**Comment by Lordmau5** [comment]
This appears to be happening only in theater mode as I personally can't reproduce it otherwise. (To add a bit more info to it)

**Comment by ChaosPaladin** [comment]
It's happen if expand window size by button, with small window size all fine
![image](https://user-images.githubusercontent.com/10120702/86346531-bbff2200-bc65-11ea-9f09-247230318442.png)
