### ISSUE TITLE
Stream Uptime and Latency to Streamer no longer showing up

### ISSUE THREAD

**Issue by Darxide23** [FrankerFaceZ/FrankerFaceZ#838]
As the title says, this info is no longer visible anywhere even when forcing the old Twitch layout.

Chrome Version 83.0.4103.116 (Official Build) (64-bit)

**Comment by SirStendec** [comment]
They're working on the new layout. The old layout is not supported anymore.

**Comment by Darxide23** [comment]
Does not work on the new layout, either.
