### ISSUE TITLE
Chat Replay's chat scrolling is inaccurate

### ISSUE THREAD

**Issue by connorkidd** [FrankerFaceZ/FrankerFaceZ#84]
**Web Browser**: Chrome

**Do you use BetterTTV or other Twitch extensions**: No

[FFZ Logs](https://putco.de/NTM0Mw.log)

**Bug**: Chat Replay's chat scrolling is inaccurate (doesn't scroll enough), causing last few chat messages to be obscured.

[Image example](https://i.imgur.com/CDd7DQp.png)

Tested at exact same time in past broadcast with & without FFZ and FFZ is indeed causing it. Tested with no configurations made to FFZ (fresh install), still occurs.

**Comment by connorkidd** [comment]
**(2017-01-13) Fixed: Twitch broke Chat Replay handling of chat timeouts and bans somehow.**

Guess this is related. Still lags behind though.

**Comment by blaenk** [comment]
I experienced this as well when watching a VOD just yesterday.
