### ISSUE TITLE
Stream title should be above info

### ISSUE THREAD

**Issue by ashkitten** [FrankerFaceZ/FrankerFaceZ#85]
**Web Browser**: Chrome 57

**Do you use BetterTTV or other Twitch extensions**: No

**Bug / Idea**: When there is lots of information below the stream (all info settings turned on) the stream title does not have enough width so it gets all bunched up. This should be fixed by putting the stream title above the information.

![2017-01-13-20 02 30](https://cloud.githubusercontent.com/assets/9281956/21950698/9e075248-d9cb-11e6-8c4b-ea5cb499bfab.png)

**Comment by SirStendec** [comment]
This can be mitigated somewhat by enabling the FFZ setting to display the title above the player, but I definitely agree that this is ridiculous. Unfortunately, I still haven't thought of a good way to actually accomplish that with how Twitch implements flexbox to position those elements.

Might be something to try tackling as I rewrite all my CSS.
