### ISSUE TITLE
 watch_stunt_double_user experiment now gone, want it back

### ISSUE THREAD

**Issue by insaneredeye** [FrankerFaceZ/FrankerFaceZ#851]
**Is your feature request related to a problem? Please describe.**

I'm frustrated that the watch_stunt_double_user experiment is gone when i've been using that experiment to switch twitch from the new layout to the old layout which I prefer.

**Describe the solution you'd like**

I would like the watch_stunt_double_user to come back in the experiments as a used experiment and not a unused experiment as it is right now because I'm sure I'm not the only one who liked the old twitch layout and was using this experimental feature to get the old layout back.
**Describe alternatives you've considered**

Anything that lets the user switch the twitch layout to the old one would be a solution to this problem.
**Additional context**

**Comment by insaneredeye** [comment]
![image](https://user-images.githubusercontent.com/68666217/88229180-8ed2dd80-cc2d-11ea-9641-20614a684b22.png)

**Comment by SirStendec** [comment]
Experiment control is an advanced feature intended for developer use only, as the setting screen itself tells you. We do not have control over what experiments Twitch is offering, and we do not support end users changing their experiments.

**Comment by insaneredeye** [comment]
okay thanks for the response and informing me how the experiments work
