### ISSUE TITLE
Pre-redesign esque channel "bar" above stream

### ISSUE THREAD

**Issue by DorCoMaNdO** [FrankerFaceZ/FrankerFaceZ#852]
**Is your feature request related to a problem? Please describe.**
Not really, just disliking the redesign

**Describe the solution you'd like**
To undo the content shift that the redesign implemented by moving content from the bottom of the stream (streamer profile icon and name and the follow/bell/subscribe buttons) as well as readding the home/videos/clips/followers links as well as the game directory icon and the stream tags, ideally as similar as possible to how it used to be before the redesign (size, spacing) and perhaps some customization options (maybe the option to adjust the links above the stream).

**Describe alternatives you've considered**
Used the experiment to revert the redesign until it became inactive.

**Additional context**
I think I've covered it all, I have a few screenshots of the pre-redesign page, some with element sizes if needed.

**Comment by SirStendec** [comment]
I am not at all interested in the amount of work this would take for such a minor change. The old layout isn't coming back. I am considering adding a few direct links to the live channel page, for things like Videos, etc, but they would not be at the top.
