### ISSUE TITLE
 watch_stunt_double_user gone 

### ISSUE THREAD

**Issue by LGPxD** [FrankerFaceZ/FrankerFaceZ#854]
watch_stunt_double_user has gone from my list under experiments in FFZ settings , this was the only way to keep the old twitch layout and for disable host mode to work. Is there a reason for this to not be there anymore ?

**Comment by SirStendec** [comment]
Experiment control is an advanced feature intended for developer use only, as the setting screen itself tells you. We do not have control over what experiments Twitch is offering, and we do not support end users changing their experiments.
