### ISSUE TITLE
Video Player Options Don't Scale

### ISSUE THREAD

**Issue by Outsanity** [FrankerFaceZ/FrankerFaceZ#86]
**Web Browser**: Chrome

**Do you use BetterTTV or other Twitch extensions**: No

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**:
Not too sure if this is a bug or possible to fix but I use a custom width of the chat with FFZ and, in turn, it makes the video player smaller. The issue is it seems the options (when you click the gear icon on the player) don't scale to the video. The only part that gets cut off of the options is the "Video Quality" option at the top.

Screenshot: https://puu.sh/tmUmz.png 

EDIT: Forgot to say this was on the HTML5 player.

**Steps to Reproduce (if Applicable)**:

**Comment by SirStendec** [comment]
So, the only solution for this is forcing a max-height onto the element and allowing it to scroll. This will need to be a special hook for the player. It shouldn't be too hard.

**Comment by Lordmau5** [comment]
Closing this because it's fixed on Twitch's end for a long while already.
