### ISSUE TITLE
ModView Session Widget Show Latency

### ISSUE THREAD

**Issue by cmd430** [FrankerFaceZ/FrankerFaceZ#862]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to easily see what my delay is to the stream I'm moderating when in mod view so that I can make sure I don't get too far behind the stream.

**Describe the solution you'd like**
Show the Latency to Broadcaster info in the Session Widget, below the viewer count.

**Describe alternatives you've considered**
I have created a user script that adds it myself but it would be nice if it was built into FFZ.

**Additional context**
![image](https://user-images.githubusercontent.com/2668906/88923466-e58f8580-d2c5-11ea-924c-8ae2c71d9a8c.png)

**Comment by SebVFX** [comment]
Hey cmd430, would you like to share your script with me? i have given up hope that ffz implements such feature themself and I am not skilled enough to make one myself. Would be awesome to use mod view permanently without having to look into the advanced infoscreen or via normal view.

Best greetings!
