### ISSUE TITLE
Highlight messages from new users in chat.

### ISSUE THREAD

**Issue by Norryn** [FrankerFaceZ/FrankerFaceZ#869]
**Is your feature request related to a problem? Please describe.**
I mod a channel and most of the people we have to timeout/ban are new to the channel and have sent fewer than 2 or 3 messages in chat. I would like a method to more easily keep track of these users.

**Describe the solution you'd like**
I would like a way to use the highlight users function or similar to automatically highlight the first X number of messages any user sends in a chat. 

**Describe alternatives you've considered**
I have looked at chat bots that point out new users however i would prefer a method that does not show up in chat. 

**Additional context**
Account age could also be something i would like to see as an option for highlighting messages.

**Comment by SirStendec** [comment]
No. That information isn't available and there's no reasonable way to keep track of it.
