### ISSUE TITLE
Extensive Console Logging should be reduced

### ISSUE THREAD

**Issue by Kissaki** [FrankerFaceZ/FrankerFaceZ#87]
**Web Browser**: Firefox

**Do you use BetterTTV or other Twitch extensions**: Yes, BTTV

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: http://putco.de/NTM0OA.log

**Bug / Idea**: I see the FFZ addon does a ton of information and error logging (despite it working). I would appreciate if that could be reduced.

404s, ember errors, ember cache clearing errors (logged not typed as error), information

**Steps to Reproduce (if Applicable)**:
Load a twitchtv stream page, open developer/browser console

I can’t even take a screenshot of it as it is more than 3 pages long of logs.

I can see extensive logs being useful for debugging, but that should not be the default. It should be enable-able in the FFZ about settings -> debug. And the errors should not exist either. Even with them, FFZ seems to work, so I wonder if it "just works"/just happens to work.

As it is, it makes working on anything else than FFZ more bothersome.

* Various FFZ: There was an error creating and destroying an instance of the Ember class "component:[…]" to clear its cache.
* Trace-verbose FFZ: Added "[…]" badge to […] users. logging
* Various 404 to https://api.frankerfacez.com/v1/room[…]
* Various FFZ: Socket Reply to […] - SUCCESS I don't get
* FFZ Error: There was an unknown error within Ember. [[object Object]]
script.min.js:11 FFZ Error: There was an error within an Ember RSVP. [[object Object]]

**Comment by SirStendec** [comment]
You can filter logs via your browser's console. As such, I see no reason to disable FFZ's logging.
