### ISSUE TITLE
Profile Current Channel Rule does not work in Mod View

### ISSUE THREAD

**Issue by cmd430** [FrankerFaceZ/FrankerFaceZ#872]
**Describe the bug**

**To Reproduce**
1. Go to Channel in ModView
2. Click on FFZ button
3. Scroll down to profiles
4. Edit Channel Specific Profile
5. See error (image included below)

**Expected behavior**
The channel should be matched by the rule

**Screenshots**
Issue with Mod View
![image](https://user-images.githubusercontent.com/2668906/89363997-9dd58780-d725-11ea-83dd-84300a81b5c1.png)

Works fine in Normal View
![image](https://user-images.githubusercontent.com/2668906/89364035-ba71bf80-d725-11ea-9d16-30a718a84082.png)

**Environment (please complete the following information):**
 - OS: Windows 10 (2004)
 - Browser Firefox 
 - Version 79 (x64)
 - Other Extensions: uBlock Origin

**Comment by fouram** [comment]
You can use Current Page "Mod View" and the name of the streamer to activate a profile under Mod View. Use the "Or" rule to put both Channel and Mod View for that same Channel together and it'll work in both places.

I found this issue as I am having problems with any Profiles with channel rules working at all (both regular and Mod View). Looks like I'll be opening a separate ticket as this is the only one that even comes close to the issue I'm seeing.
