### ISSUE TITLE
Setting your own buffer per stream

### ISSUE THREAD

**Issue by StoneColeQ** [FrankerFaceZ/FrankerFaceZ#878]
**Is your feature request related to a problem? Please describe.**
When watching multiple streams at the same time they aren't in sync.

**Describe the solution you'd like**
Setting our own buffer on a per stream basis. Ex setting 5.33s to be the target. Other extensions have sped up the player to reduce buffer so this should be possible.

**Describe alternatives you've considered**
Refreshing the streams and hope you get lucky? Only for them to no longer be sync'd in 5 minutes.

**Additional context**
Important for this setting to be as granular as possible. Maybe steps of 0.01s. Also the buffer changes per second so that may be a bit tricky to deal with. Maybe average over 5s?

**Comment by SirStendec** [comment]
I am not interested in implementing this. I try to avoid digging into the player internals when possible, aside from extracting information. Those other extensions that you've mentioned can try this.
