### ISSUE TITLE
middle clicking to mute/unmute randomly stops working

### ISSUE THREAD

**Issue by RepulsiveDoor2798** [FrankerFaceZ/FrankerFaceZ#879]
middle clicking won't mute or unmute the player randomly

**To Reproduce**
1. Go to a stream on twitch.tv
2. try to middle click to mute/unmute a stream
3. stream won't mute/unmute
4. i have to manually click the mute button or press the 'M' key to mute/unmute

**Expected behavior**
when i middle click the stream should mute/unmute

**Screenshots**
i can't really screenshot me middle clicking the mouse

**Environment (please complete the following information):**
 - OS: windows 10
 - Browser: chrome
 - Version i don't know
 - Other Extensions: BetterTTV, AdBlock, honey, ublock origin, AHA music

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:

**Additional context**

**Comment by SirStendec** [comment]
Are you viewing streams with overlay extensions? The player doesn't receive click events if there is an overlay extension unless you use the FFZ setting to prevent mouse interaction with extensions.
