### ISSUE TITLE
Viewer Count should be pulled from the number of names in the Viewer List

### ISSUE THREAD

**Issue by Bombycon** [FrankerFaceZ/FrankerFaceZ#88]
**Bug / Idea**: Viewer Count should be pulled from the number of names in the Viewer List. 

Since the Viewer List doesn't display Viewer Bots, it's more accurate then the actual Watching Now number.

Or maybe just have a thing that shows the number of bots? Seems that some streamers have no idea they are getting view botted.

**Comment by SirStendec** [comment]
Nope. Users connected to chat is not at all related to viewer count. It does not account for users viewing the player by itself on embedded platforms or the front page, users with chat closed, viewers who are not logged in, viewers on other platforms without chat...
