### ISSUE TITLE
error #2000 auto reload

### ISSUE THREAD

**Issue by JoLong** [FrankerFaceZ/FrankerFaceZ#884]
**Is your feature request related to a problem? Please describe.**
there was an option to auto reload the player when an error 2000 occured, but i can't find it anymore, same as the one for the autoclaim of channel points.

**Describe the solution you'd like**
i might not notice the option anymore, should be there (?)

**Describe alternatives you've considered**
there is a command to enable the auto click for the points, not for the reload.

**Additional context**
i remember there was one, can't find it now, the feature was shut down?

**Comment by SirStendec** [comment]
FrankerFaceZ never had an option to automatically reload the player. You are likely thinking of another extension. I don't plan on adding one at this time. If you are actively watching a stream, there is a reset control to do so manually. If you are not watching a stream, reloading it is harmful.

**Comment by JoLong** [comment]
thank you for the response, i found it, was the FFZ:AP/FFZ Enhancing add-on.
