### ISSUE TITLE
New reply feature doesn't work

### ISSUE THREAD

**Issue by yobson1** [FrankerFaceZ/FrankerFaceZ#886]
**Describe the bug**
The new reply feature doesn't work with FFZ enabled.

**To Reproduce**
Try to use the new reply feature, you can't.

**Expected behavior**
To be able to use it.

**Environment (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 84
 - Other Extensions: Honey, Dark Reader, uBlock Origin

**Additional context**
I am aware that there is the option to enable FFZ's reply button in the in-line chat settings but that is not what I'm looking for. I just want to be able to use the default Twitch implementation.

**Comment by SirStendec** [comment]
The feature is an implementation of a Twitch experiment. Availability varies by channel and user.
