### ISSUE TITLE
Accent color change not allowing for messages to be highlighted for copy/paste

### ISSUE THREAD

**Issue by Zeltys** [FrankerFaceZ/FrankerFaceZ#888]
**Describe the bug**
After setting a custom accent color (Appearance > Theme > Accent color) I was unable to highlight messages either in chat or on the pop out mod cards, which is something mods do often.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g. chrome, firefox]
 - Version [e.g. 70]
 - Other Extensions: [e.g. BetterTTV, Privacy Badger, AdBlock, etc.]

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:

**Additional context**

**Comment by Taizunz** [comment]
I tried reproducing your issue without results.
Are you sure you're not currently using the vanilla Twitch replies style? The new "Reply"-experiment that Twitch is running makes messages function as one big button that you can't select any text from, FFZ has a setting to override this style with a more mod-friendly one.
Please check: FFZ Control Panel -> Chat -> Appearance -> Style

**Comment by Zeltys** [comment]
I have the style set to FFZ, I changed the accent color and tried
highlighting messages again, it worked, however it seems that some
highlight colors don't show, I tried #0F3F3E and when highlighting messages
it doesn't show up, I'm using a black background #000000 and the highlight
appears to be the same color. I changed background to white so you can see
that highlight color does not match custom accent color in the screenshot
below.

[image: image.png]

**Comment by SirStendec** [comment]
Yeah, the way it works, there's no brightness limitation currently. As a result, you can set colors that don't work great for certain page elements. This isn't really a bug, just something a bit unfriendly. Maybe something to look into for the future, but for now I'm not concerned about it.
