### ISSUE TITLE
[Feature Request] One-click ignore

### ISSUE THREAD

**Issue by just-a-bird** [FrankerFaceZ/FrankerFaceZ#89]
**Web Browser**: N/A

**Do you use BetterTTV or other Twitch extensions**: N/A

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: N/A

**Bug / Idea**:
Currently, moderators can script a `/ignore` button, but this doesn't work unless you're a mod in the chat. Would like to see an inline ignore button that also bypasses the "ignore reason" popup dialog (if possible).

The absolute ideal would be the ability to click a button and then FFZ automatically ignores anyone who matches a custom filter (that includes emotes), until it's toggled off.

**Steps to Reproduce (if Applicable)**: N/A

**Comment by SirStendec** [comment]
When the new settings UI comes, it should become possible to set "mod icons" that are always there, even in rooms where you're not a moderator.

As for ignoring anyone, that belongs with the enhanced filtering system over at #82.
