### ISSUE TITLE
FFZ emote menu not loading

### ISSUE THREAD

**Issue by Voczi** [FrankerFaceZ/FrankerFaceZ#891]
**Describe the bug**
FFZ emote menu does not load, gets stuck on FFZ logo.

**To Reproduce**
1. Enable FFZ's custom emote menu (Chat -> Emote Menu -> Use the FrankerFaceZ Emote Menu).
2. Go to a channel's chat.
3. Open emote menu.

**Expected behavior**
FFZ emote menu to load successfully.

**Screenshots**
https://user-images.githubusercontent.com/62214162/90320883-0d791d00-df45-11ea-804a-5bca1a889445.png

**Environment (please complete the following information):**
OS: Ubuntu 20.04.1 LTS
Browser: Firefox
Version: Firefox 68.0esr
Other Extensions: None

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:
https://gist.github.com/Voczi/979436648d805c614e226371e5a56e84

**Additional context**
I think the error has to do with "TypeError: e is undefined". Appears in developer console too, after opening the emote menu.

**Comment by SirStendec** [comment]
Please provide the full error, not just "TypeError: e is undefined". I need the stack trace to know what is happening. The error wasn't captured in the log you uploaded.

**Comment by Voczi** [comment]
The console wasn't really giving me a stack trace, just printed a TypeError like the one in the FFZ log (line 15). Not sure if they're related though.
Anyways, the TypeError occurred at emote_menu.jsx:2290:20. Screenshot of the code:
![Screenshot from 2020-08-15 22-54-35](https://user-images.githubusercontent.com/62214162/90321488-99da0e80-df4a-11ea-824d-c76f37bd762f.png)
Point of error is after "const product =".

**Comment by SirStendec** [comment]
Interesting. Twitch is outputting garbage data, then. I'll add a check to that line in the next release.
