### ISSUE TITLE
Left chat and Watch Party

### ISSUE THREAD

**Issue by Manerr** [FrankerFaceZ/FrankerFaceZ#898]
**Describe the bug**  
Twitch's Watch Party system has display problems when the chat is set to display on the left side of the screen

**To Reproduce**  
1. Enable the left chat option
2. Go to a stream broadcasting a watch party
3. See error

**Expected behavior**  
The streamer camera should be placed on the left side, above the chat.

**Screenshots**  
[https://i.imgur.com/qVW8lmR.jpg](https://i.imgur.com/qVW8lmR.jpg)

**Environment (please complete the following information):**  
 - OS: Windows
 - Browser: Firefox
 - Version: 80.0.1
 - Other Extensions: BetterTTV (but no appearance modification option enabled), uBlock Origin

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**: [https://hasteb.in/adusewep.makefile](https://hasteb.in/adusewep.makefile)

**Comment by Luzifer** [comment]
Sadly the original screenshot is gone but I'm right now seeing issues with `Appearance -> Layout -> Swap Sidebars` feature and a WatchParty…

Reloading after the WatchParty was started (missing login) breaks the whole layout, chat is gone, streamer cam is hidden in a collapsible full-screen to the left (opening hides the movie)…

Looks like a regression?

- Chromium Version 90.0.4430.85 (Official Build) Arch Linux (64-bit)
- FFZ Version 4.21.1 2f41f52
