### ISSUE TITLE
Some channels disappear from the following list depending on the category they're streaming

### ISSUE THREAD

**Issue by tesence** [FrankerFaceZ/FrankerFaceZ#899]
**Describe the bug**
As the pages finishes to load, any followed channel under a specific category (category name: "Dofus") just disappears from my list (both from the side panel and the home page)

**To Reproduce**
1. Follow a channel that is currently streaming the game "Dofus"
2. Reload the page
3. See the said channel channel in the list of followed channels for a second or two, then see it disappear as the page finishes to load

**Expected behavior**
The channel is not supposed to disappear from the list

**Screenshots**
Not really applicable, but I can record a video if necessary

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 80.0.1
 - Other Extensions: BetterTTV, Stylish, uBlock Origin, Tampermonkey (no script running)

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:
I unfortunately can't get the log upload feature to work

**Additional context**
I can safely say that it comes from FFZ because I get the issue after disabling every extension but FFZ. Disabling FFZ makes the issue not occur

**Comment by SirStendec** [comment]
You probably have that category blocked, using the Block button we add to category pages. (Appears next to the Hide Thumbnails button.) This is not a bug and is intended behavior.

If you do not have the category blocked and channels are still disappearing, let me know and I can re-open this.
