### ISSUE TITLE
Google Chrome is asking for permissions to edit websites after the last update? 

### ISSUE THREAD

**Issue by babbelnedd** [FrankerFaceZ/FrankerFaceZ#91]
Im confused  -  were there any changes to the needed permissions in the last patch? Why did Chrome ask for permissions? Iirc or already did on installation.

**Comment by SirStendec** [comment]
FrankerFaceZ has not recently released any updates that change the required permissions. It's likely you're talking about BTTV4FFZ, which is currently re-branding itself to "The FFZ Add-on Pack" and gearing up to add support for a few more services.

Lordmau5 gave more details on what permissions are required in this issue on his own project: https://github.com/Lordmau5/BTTV4FFZ/issues/18

**Comment by babbelnedd** [comment]
ooops. I did not realize they changed the name. I appreciate your answer. Thank you
