### ISSUE TITLE
Whispers no longer have highlight when a new one is received

### ISSUE THREAD

**Issue by JimmyBoyHalpert** [FrankerFaceZ/FrankerFaceZ#912]
**Describe the bug**
Previously, when a whisper was received there would be a purple highlight of the whisper to show a new, unread message was present. Currently, when a whisper is received, this distinction is no longer there and makes it harder to see a whisper has been received. Whether you are already communicating with a person or its a new whisper popping up, neither will show a highlight.

**To Reproduce**
1. Create a second account on Twitch
2. Send a whisper to yourself from one account to another

OR

1. Whisper someone and have them whisper you back 

**Expected behavior**
When a whisper is received, the element on the page where you click to respond back should be highlighted with purple to show an unread message is waiting for the user.

**Screenshots**
![a_ffz_issue](https://user-images.githubusercontent.com/71977902/94368604-f7698b00-00b2-11eb-8653-e8839b2025e8.PNG)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser: Opera
 - Version: 70.0.3728.189
 - Other Extensions: Test was run with only FFZ and FFZ Add-On Pack enabled

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:

**Additional context**

**Comment by techop2000** [comment]
New on FFZ. I and a few friends are encountering this as well. With FFZ disabled, new unread whispers show purple at bottom of screen. With FFZ enabled, they do not. Using Chrome on windows 10.

**Comment by techop2000** [comment]
Fixed today with 4.22.1
