### ISSUE TITLE
"Allow the player to speed up to reduce delay." stopped working

### ISSUE THREAD

**Issue by Techjar** [FrankerFaceZ/FrankerFaceZ#915]
**Describe the bug**
Disabling this setting no longer seems to have any effect, as I am getting the audio warble issue again.

**To Reproduce**
1. Disable "Allow the player to speed up to reduce delay."
2. Watch a stream on a poor connection with lots of buffering.

**Expected behavior**
The player should not speed up and no audio warble should be observed.

**Environment (please complete the following information):**
 - OS: Arch Linux
 - Browser: Google Chrome
 - Version: 78
 - Other Extensions: uBlock Origin

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:
https://gist.github.com/Techjar/1f2b89da827f2df6f730ff1c44953b49

**Comment by Mangos02** [comment]
i also want this to be fixed as i get stream with over 30 seconds delay now and it slowly go up over time

**Comment by FireFingertips** [comment]
For now, you can use a chrome extension by the name of Video Speed Controller and pressing G when focused on the video player (might have to set the key-bind G to 1.0 speed in the settings of the extension first). Also enable "Remember playback speed" though keep in mind this option only reduces how often the video speed is back to 1.03 so you still gonna have to press G every once in a while.

**Comment by orion78fr** [comment]
The option have been removed from version 4.20.47 #b7a2ce3 it seems. Pretty annoying sound distortions

**Comment by Lordmau5** [comment]
From my understanding Twitch removed the way for us to modify the player internals so we could disable the speed-up, so that's the reason why it was removed.

I'm sure it'll come back eventually, just that nobody can give an ETA on *when* that'll be, sadly.

**Comment by yalanyali** [comment]
We could just override the video element's `playbackRate` attribute on load. Not as elegant as the now-deprecated solution but hey, it'd work. That's what I do personally. Just hijack the `playbackRate` setter using `Object.defineProperty` on video element and let Twitch think it's setting the `playbackRate` with success.

**Comment by yalanyali** [comment]
> We could just override the video element's `playbackRate` attribute on load. Not as elegant as the now-deprecated solution but hey, it'd work. That's what I do personally. Just hijack the `playbackRate` setter using `Object.defineProperty` on video element and let Twitch think it's setting the `playbackRate` with success.

It seems this has just been implemented. Can close this issue now.

**Comment by SirStendec** [comment]
Yup, I ended up going with that after a bit of testing. It doesn't really feel elegant at all, especially since there are legitimate reasons to change playback rate that need to be supported. But, it's working.
