### ISSUE TITLE
Notification Sound

### ISSUE THREAD

**Issue by FloridaSky** [FrankerFaceZ/FrankerFaceZ#92]
**Web Browser**: 
Chrome

**Do you use BetterTTV or other Twitch extensions**:
Just FFZ now.

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**:
Play a notification sound, a little 'tick' noise. When a highlighted word is presented in chat. Such as your twitch username. 

**Steps to Reproduce (if Applicable)**:

**Comment by SirStendec** [comment]
I want to support sounds for messages that match filters. That's planned with the filtering update I'm working on to come out shortly after the settings update... whenever that is. Chat filtering discussion should go in #82.
