### ISSUE TITLE
Option to hide Community Challenge notifications in chat

### ISSUE THREAD

**Issue by lallaria** [FrankerFaceZ/FrankerFaceZ#929]
This can be very spammy if many people contribute at once.  I cannot find a FFZ or twitch way to turn it off/hide it, and it doesn't look like Community Challenge is anywhere in the community settings list here (also searched with no hits)
![community challenge](https://user-images.githubusercontent.com/10296974/97109994-f6754a80-16ac-11eb-94bf-24bb2fe89f22.png)

**Comment by SirStendec** [comment]
You can do this by using the setting to block messages by type in Chat > Filtering. Specifically, you'll want to block "CommunityChallengeContribution".
