### ISSUE TITLE
Allow to resize chat below 250

### ISSUE THREAD

**Issue by Barteks2x** [FrankerFaceZ/FrankerFaceZ#93]
**Web Browser**: Firefox

**Do you use BetterTTV or other Twitch extensions**: No

**Bug / Idea**: In some streams that show text the chat makes video resolution smaller so the text becomes very hard to read. I usually use browser inspect functionality to change the size to 200 to workaround that. It looks very ugly but it works. Would it be possible to add a feature to resize below it below 250?

**Comment by SirStendec** [comment]
I will not remove the limit from the UI. People would make chat too narrow and not have a good way to fix it. If you wish to set it manually, you can use the JavaScript console to make that sidebar narrower.

To do so, open your browser's JavaScript console and run the following:

`ffz.settings.set("right_column_width", 200)`

**Comment by Barteks2x** [comment]
Would it be possible to at least make it work correctly when used from console by changing the min width property on the single thing that has it set to 250 and prevents the change from working?
