### ISSUE TITLE
Add an option to activate the "Reset Player" button with 1 click

### ISSUE THREAD

**Issue by asdsadsaasd12312132** [FrankerFaceZ/FrankerFaceZ#936]
**Is your feature request related to a problem? Please describe.**
As you may know, Twitch has been inserting pre-roll ads that sometimes do not get blocked. I have been bypassing this by spamming the reset player button until the ad disappears. Currently, the button requires 2 clicks to work. Considering I have to spam the button fairly often, it would be more convenient if only 1 click was required.

**Describe the solution you'd like**
Add an option to allow the button to work with 1 click instead of 2.

**Comment by SirStendec** [comment]
No.

Using this feature to bypass ads is not intended and will not be supported. FrankerFaceZ is not an adblocker and is remaining neutral. The last thing we need is Twitch getting annoyed with us over something so stupid as playing catch up with the adblocker extensions.

While I am not doing anything to impact the behavior of the Reset Player button, I will also not be making changes to it that make it more convenient to circumvent ads.
