### ISSUE TITLE
Chat UI optimisation in theater/portrait mode

### ISSUE THREAD

**Issue by tmarti2** [FrankerFaceZ/FrankerFaceZ#937]
Is your feature request related to a problem? Please describe.
Don't know if this can be called a problem, but when iin theater mode and/or portrait mode, a lot of space is wasted by 2 things :
- Chat banner "Strem chat" at the top of the chat
- Send textbox / buttons /etc at the bottom

Describe the solution you'd like
It would be great if it was possible to reduce the banner at the top of the chat for my first point. For my 2nd point, a solution could be to place buttons à the right/left of the text box to reduce its height.
I did a quick paint to illustrate this :
![image](https://user-images.githubusercontent.com/32908972/98285126-5ff53300-1fa2-11eb-8b8d-7a81efd8bdc7.png)

I don't know if it's possible or not, but it would be great !
Nice work anyway, great plugin.

Describe alternatives you've considered
None

Additional context
Increasing your window width further increase this problem to a point where this 2 points take 50% of chat space.

**Comment by SirStendec** [comment]
Closed in 5e5b3280762678201973f45f605ade90a8ddba5e
