### ISSUE TITLE
Audio compressor option to enable/disable by default says "Enable" but acts like disable

### ISSUE THREAD

**Issue by nodthenbow** [FrankerFaceZ/FrankerFaceZ#939]
**Describe the bug**
The audio compressor option that says "Enable the compressor by default." but behaves like it says disable.

**To Reproduce**
You can see it by changing that option like normal. It'll turn off the compressor if you make it true and then default the compressor to off and all the other stuff it should do. The description just is has the truth inverted.

**Expected behavior**
https://github.com/FrankerFaceZ/FrankerFaceZ/blob/a95c2ebccda54146fdab0d5d084731a0b0e58ef0/src/sites/twitch-twilight/modules/player.jsx#L109 should say
`title: 'Disable the compressor by default.',`
Or the logic should be the other way round.

**Comment by SirStendec** [comment]
The description is not incorrect. You appear to have a misunderstanding about which state is enabled for the compressor.
