### ISSUE TITLE
[Feature Request] Desktop notifications when channels go live.

### ISSUE THREAD

**Issue by jnki** [FrankerFaceZ/FrankerFaceZ#94]
**Web Browser**: Vivaldi / Chrome

**Do you use BetterTTV or other Twitch extensions**: Twitch Giveaways

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: n/a

**Idea**: It would be neat if FFZ could give a desktop/browser notification when a channel you're following goes live. 

**Steps to Reproduce (if Applicable)**: n/a

**Comment by SirStendec** [comment]
FrankerFaceZ is not a good platform for this feature. The extension lives in the context of a Twitch page, meaning that it is only running when you are already on Twitch. You would potentially be missing a lot of channels going live if you relied on such an extension to provide notifications.

Instead, you should also grab an existing extension such as Twitch Now that is always running in the background and use it for your notification needs.
