### ISSUE TITLE
Chat Timestamp doesn't appear on Opera GX

### ISSUE THREAD

**Issue by TheRealRazbi** [FrankerFaceZ/FrankerFaceZ#944]
**Describe the bug**
The timestamp before messages doesn't show on Opera GX.

**To Reproduce**
1. Use FFZ [make sure you're on Opera GX]
2. Make sure timestamps for messages are enabled [not sure if you can disable them, I just loaded my old settings which work on my older browser, "work" as in, they display the timestamp]
3. Observe that no message on the chat has timestamp

**Expected behavior**
A timestamp should appear before each message.

**Screenshots**
https://cdn.discordapp.com/attachments/587668028771270697/780570146581512202/ffz_bug_report.PNG
^ this is just a screenshot of how it looks like with the extension, but without the timestamp

**Environment (please complete the following information):**
 - OS: Windows
 - Browser Opera GX
 - Version 4.20.49
 - Other Extensions: uBlock origin, Dark Reader

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:
I'm sorry, but the "Upload" loads in indefinitely, so I've uploaded it somewhere else and here's a link:
https://cdn.discordapp.com/attachments/587668028771270697/780568849304649739/ffz_bug_report.log

**Additional context**
Thanks for maintaining this great extension.

**Comment by SirStendec** [comment]
Timestamp visibility is not controlled by FFZ settings nor is it restored along with an FFZ setting backup.

Click the gear in chat. Non-mod settings (if you're a mod). Chat Appearance. Turn on timestamps there.

**Comment by TheRealRazbi** [comment]
I am sorry for wasting your time.
