### ISSUE TITLE
Highlight colours suddenly darker than configured

### ISSUE THREAD

**Issue by CyBeRoni** [FrankerFaceZ/FrankerFaceZ#947]
**Describe the bug**
The custom highlight colours for mentions and users that you're highlighting (by having their user card open) are suddenly a lot darker than configured.

**To Reproduce**
Go to settings -> chat -> filtering, set a custom highlight colour, wait for someone to mention you.

**Expected behavior**
Message is highlighted with the colour configured.

**Screenshots**
![Screenshot 2020-11-26 at 11 05 50](https://user-images.githubusercontent.com/5394358/100337397-9d644380-2fd7-11eb-92a4-9c93f454604d.png)

**Environment (please complete the following information):**
 - OS: macOS 10.14
 - Browser Safari
 - Version 14.0
 - Other Extensions: BTTV but no highlighting configured there

**Additional context**
This problem seems to have started happening in the last day or maybe two.

**Comment by IamMeWasTaken** [comment]
And now they are much lighter than expected [https://i.imgur.com/Nr4LMaZ.png](url)

**Comment by CyBeRoni** [comment]
For me it went back to normal today.
