### ISSUE TITLE
Youtube Vanced keeps getting uninstalled

### ISSUE THREAD

**Issue by asdsadsaasd12312132** [FrankerFaceZ/FrankerFaceZ#951]
**Describe the bug**
Ever since the Vanced 2 Manager, I have had my Youtube Vanced get uninstalled randomly over 10 times. I have to go back into Vanced Manager and reinstall it. Sometimes I lost all of my settings too.

**To Reproduce**
Occurs randomly.

**Comment by SirStendec** [comment]
Hi, we aren't YouTube Vanced.
