### ISSUE TITLE
Chat polls do not display correctly.

### ISSUE THREAD

**Issue by pirate1337** [FrankerFaceZ/FrankerFaceZ#956]
**Describe the bug**
When a poll is done during stream, the popup does not display correctly and is just a black box.

**To Reproduce**
1. Activate a poll during stream.
2. See error at the top of chat.

**Expected behavior**
The poll popup is supposed to be displayed correctly.

**Screenshots**
https://imgur.com/7F6pCsY

**Environment (please complete the following information):**
 - OS: W10
 - Browser: Ungoogled-Chromium
 - Version: 4.20.55
 - Other Extensions: Ublock, Alternative Twitch Player (yes I have checked without it), HTTPSEverywhere, Twitch Now.
**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**: https://pastebin.com/Z431zJKz

**Additional context**
- Yes I have tested it with FFZ disabled. It is definitley FFZ.

**Comment by furai** [comment]
It's for community highlights. If you disable hiding community highlights then poll should show up correctly.

For me it's the other way around. I don't want anything displayed at all, so I have community highlights hidden - but for polls still the empty box shows up. I'd love that to be hidden completely.
