### ISSUE TITLE
Profile Rule "Current Channel" does not match when it should be

### ISSUE THREAD

**Issue by fouram** [FrankerFaceZ/FrankerFaceZ#957]
**Describe the bug**
The Profile rule for Current Channel does not correctly detect the current channel

**To Reproduce**
0. Open a channel on Twitch for which you've created a Profile for using the Current Channel rule
1. Go to Data Management
2. Click on Profiles
3. Scroll down to the profile that depends on the Current Channel rule
4. Click on "Configure"
5. See error: Current Channel does not match, shows red X

**Expected behavior**
Current Channel rule matches when the current channel is the same as the rule expects

**Screenshots**
![FFZ Profiles - Current Channel not working](https://user-images.githubusercontent.com/533951/102084543-505bdc00-3de3-11eb-9fe3-addbfdcf16e0.png)
![FFZ Profiles - Current Page - Mod View IS working](https://user-images.githubusercontent.com/533951/102084541-4fc34580-3de3-11eb-9ed4-d33d2cd28be3.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 83
 - Other Extensions: BTTV, uBlock origin, Privacy Badger, HTTPS Everywhere

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:
(My logs wouldn't upload this morning, I will try to recreate this later)

**Additional context**
When I add a channel, the channel name is converted to all lowercase. Is it possible that this is causing the issue (i.e. being case-sensitive compared against another variable with capitals in it)?

**Comment by Nicolasdiaz17** [comment]
I have the same problem right here. I am a moderator of this channel but the rule never works even when I have the mod view turned on. I hope someone replies with the solution.

**Comment by fouram** [comment]
I've discovered a workaround (which, interestingly, worked for me but not for a friend; more on that later):

Use Current Page with the "User" type OR'd with Current Page with type "Mod View", behavior mimics that expected of "Current Channel", where being in either view matches the profile:
![Screenshot 2021-01-13 095947 - FFZ Profile Current Page User](https://user-images.githubusercontent.com/533951/104469045-26363f00-5586-11eb-801c-591599884d42.png)
(Note: It's possible I'm understanding "Current Channel" wrong, but I'd imagine it's there as a convenience so that one doesn't need to set up an OR with all the different page possibilities for a given channel)

I am a Firefox user, and I advised a friend to do this to correct this issue - his rules show Current Page User matching, but the rule itself (even after a confirmed Save from the top of this configurator page) does NOT match. It;s possible something else is going on with his installation (and he is also using Chrome).

**Comment by fouram** [comment]
Many thanks for the fix!
