### ISSUE TITLE
Verified account being asked to verify

### ISSUE THREAD

**Issue by IshtarScorpio** [FrankerFaceZ/FrankerFaceZ#958]
**Describe the bug**
Twitch is asking me to verify my account. I already had done that. Attempts to get it verified by sending an email to my account result in no email being sent. I can not comment in chat. When I down load the app on my phone (a platform I am NOT interested in using), it works. I had the stream on earlier in the day, it worked. I got a Sea of Thieves drop by watching a streamer in the morning.

**Expected behavior**
I want to be able to comment in chat with my already verified account. I can not un-verify it either.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 83

**Comment by SirStendec** [comment]
Twitch was having internal issues regarding verification today.
