### ISSUE TITLE
Add auto-mute to stream ads

### ISSUE THREAD

**Issue by acdvs** [FrankerFaceZ/FrankerFaceZ#959]
**Is your feature request related to a problem? Please describe.**
Pre-roll and mid-roll ads are mostly unavoidable now.

**Describe the solution you'd like**
Add an option to auto-mute the stream when ads start playing. I have no idea if FFZ even has the functionality to detect ads, so this may be a futile issue.

**Describe alternatives you've considered**
Manually muting streams every time an ad plays

**Additional context**
n/a

**Comment by SirStendec** [comment]
I am staying firmly away from the issue of ads within FrankerFaceZ, and consider this something that other scripts focusing specifically on ads should address.
