### ISSUE TITLE
cheer1 badge not appearing

### ISSUE THREAD

**Issue by TrampolineTales** [FrankerFaceZ/FrankerFaceZ#96]
**Web Browser**:
Chromium 55.0.2883.87

**Do you use BetterTTV or other Twitch extensions**:
No.

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:
http://putco.de/NTQwNg.log

**Bug / Idea**:
Cheered 40 bits in a channel and the cheer1 badge does not appear next to my name. I cheered Kappas though if that matters (Kappa1 x40 instead of cheer1 x40).

**Steps to Reproduce (if Applicable)**:
1. Type Kappa1 40 times in [twitch.tv/fuzzyness](https://www.twitch.tv/fuzzyness).
2. Bits appear in alert.
3. Badge does not appear next to name in chat.

**Comment by SirStendec** [comment]
This is an issue with Twitch's chat cluster not updating badges immediately and not FrankerFaceZ.
