### ISSUE TITLE
Bug: Emote menu upsets the layout

### ISSUE THREAD

**Issue by InzeNL** [FrankerFaceZ/FrankerFaceZ#962]
**Describe the bug**
Since a very recent update to the Twitch layout, when opening the emote menu, it opens up *below* the chatbox, thus moving the rest of the page up.

**To Reproduce**
1. Go to any Twitch Channel
2. Click on the emote menu
3. See error

**Expected behavior**
The emote menu shows up over the existing chat, and not under it.

**Screenshots**
![Emote menu](https://i.gyazo.com/ecea5f545e2511a4a0210e3182365618.png)

**Environment:**
 - OS: Windows 10 (Build 18363)
 - Browser: Chrome
 - Version: 87
 - Other Extensions: FFZ:AP

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:
Upload button in the add-on didn't work, but:
https://pastebin.com/fcMPYsb4

**Comment by SirStendec** [comment]
Fixed in 9a2a6f2acf90164e22f6a1e58128da69681bfe86
