### ISSUE TITLE
Bug: Button colours are inverted

### ISSUE THREAD

**Issue by InzeNL** [FrankerFaceZ/FrankerFaceZ#963]
**Describe the bug**
Since a very recent update to the Twitch layout, when loading any Twitch page, the FFZ buttons will show up as white when in Dark mode, and as black when in Bright mode.

**To Reproduce**
1. Go to any Twitch page
2. See error

**Expected behavior**
When loading any Twitch page, the FFZ buttons will show up as black when in Dark mode, and as white when in Bright mode.

**Screenshots**
![Buttons](https://i.gyazo.com/294f41e090e84e583e5f8d02e293d69b.png)

**Environment:**
- OS: Windows 10 (Build 18363)
- Browser: Chrome
- Version: 87
- Other Extensions: FFZ:AP

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:
Upload button in the add-on didn't work, but:
https://pastebin.com/fcMPYsb4

**Comment by SirStendec** [comment]
Fixed in 9a2a6f2acf90164e22f6a1e58128da69681bfe86
