### ISSUE TITLE
Emote Features

### ISSUE THREAD

**Issue by kevzor** [FrankerFaceZ/FrankerFaceZ#970]
I'd like a feature to upload my own custom images to replace the ones shown in chat locally.
Also, a feature to block specific streamers' emotes from appearing in chat.

**Comment by SirStendec** [comment]
You can use Blocked Terms to filter specific emotes by their name. To block all potential emotes from a channel, you can add a Glob-type filter matching their emote prefix. Note, however, that this may block other words starting with that sequence of letters.

For example, blocking `sten*` would block all of my sub emotes. Things like `stenNope` and `stenGlasses`.

Implementing a more precise filter is not practical at this time. I am not interested in adding a feature for overriding local emote image overrides.
