### ISSUE TITLE
Websocket errors

### ISSUE THREAD

**Issue by Yemtex** [FrankerFaceZ/FrankerFaceZ#976]
**Describe the bug**
As can be seen in the log, the websocket connections are denied or run into a timeout or have other errors.

**To Reproduce**
Leider habe ich zu wenig Information, wie man diesen Fehler reproduzieren kann.

**Expected behavior**
A stable websocket connection

**Screenshots**
![image](https://user-images.githubusercontent.com/55879864/105260645-72890c80-5b8e-11eb-8c36-b2cceae0f226.png)

**Environment (please complete the following information):**
 - OS: Windows 10 Version 2004 (Build 19041.685)
 - Browser: Chrome
 - Version: 87.0.4280.141
 - Other Extensions: Add-Ons active in FrankerFaceZ Control Panel ffzap-bttv, ffzap-core

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:
[FFZ Log.txt](https://github.com/FrankerFaceZ/FrankerFaceZ/files/5846185/FFZ.Log.txt)

**Additional context**
Chrome Console
[Chrome Console.log](https://github.com/FrankerFaceZ/FrankerFaceZ/files/5846186/Chrome.Console.log)

**Comment by Osahashi** [comment]
I noticed the same with Firefox, couldn't find any reason for the issue on my side, I test it with https://www.websocket.org/echo.html and other connections are working

![websocket](https://user-images.githubusercontent.com/22057956/105876538-5c040a80-5fff-11eb-9b36-7eb120ae50f3.JPG)
![Test 1](https://user-images.githubusercontent.com/22057956/105876539-5c9ca100-5fff-11eb-82ab-b53fe46001c3.JPG)
![Test 2](https://user-images.githubusercontent.com/22057956/105876540-5d353780-5fff-11eb-8a90-c604a4bd4b52.JPG)

**Comment by SirStendec** [comment]
It's entirely an issue with the FFZ socket server cluster. We have too many users for the current capacity, and adding capacity doesn't work well with the current design.

I've been working on a new backend for PubSub but it is not ready at this time.
