### ISSUE TITLE
More granular channel hosting options

### ISSUE THREAD

**Issue by brian6932** [FrankerFaceZ/FrankerFaceZ#977]
**Is your feature request related to a problem? Please describe.**
If enable channel hosting is disabled, there is no option to view who is being hosted or to jump to said channel

**Describe the solution you'd like**
Enable an option to keep the channel info column host details, while still having hosting disabled
This is what it currently looks like with hosts enabled:
![image](https://user-images.githubusercontent.com/18603393/105274974-51172900-5b6c-11eb-8f82-a2fb33eb32f8.png)
And this is disabled:
![image](https://user-images.githubusercontent.com/18603393/105275349-1eb9fb80-5b6d-11eb-80f1-b5e0a30497c0.png)

**Comment by SirStendec** [comment]
This would be problematic to pull off. Twitch is using features of React that make it difficult to access and modify data, let alone to extend granular control over which parts of the website receive which parts of the data.

It's frankly not worth the effort.
