### ISSUE TITLE
Chat identity button

### ISSUE THREAD

**Issue by NoTraceFound** [FrankerFaceZ/FrankerFaceZ#986]
Could we get an option to either hide the button or move it somewhere that's not taking up space in the text field? 

It's been an annoyance since twitch implemented it and I thought there would be an issue started on this already but here I am.

The way it doesn't even clip correctly... 
![image](https://user-images.githubusercontent.com/33948468/107152403-ecc7d800-6967-11eb-9227-9738afa9e8ce.png)

**Comment by SirStendec** [comment]
This is still an experiment. I am waiting for Twitch to make a final decision on the feature before I do anything about it. (Though, I admit I was expecting them to have decided by now.)

**Comment by Lego6245** [comment]
Want to re-raise this issue, as I believe the experiment has graduated (or if it hasn't, it's changed names, as the experiment is missing from the list in FFZ). +1ing the ask for a toggle for this particular feature. Looks like (to me) you'd have to both hide the button and tweak the style attribute on the text area to re-adjust the left padding.
