### ISSUE TITLE
Highlight newly created accounts

### ISSUE THREAD

**Issue by MCAaronIce** [FrankerFaceZ/FrankerFaceZ#99]
If possible, it would be a really helpful moderation tool to be able to highlight users in chat whose accounts have been recently created (either within the hour or maybe up to 24 hours) to help easily identify potential troll accounts. I know you can click on the name to get this information, but it would be much easier to have it visible without clicking.

**Comment by SirStendec** [comment]
This is not possible. The amount of API requests this would generate to load account age information would create unacceptable load on Twitch's service.

**Comment by MCAaronIce** [comment]
Was afraid of that. Thanks for the reply.
