### ISSUE TITLE
Option to disable being notified about new FrankerFaceZ features

### ISSUE THREAD

**Issue by asdsadsaasd12312132** [FrankerFaceZ/FrankerFaceZ#996]
**Is your feature request related to a problem? Please describe.**
When FrankerFaceZ adds a new feature, a number appears on the icon indicating this. I find it annoying because it is a notification I do not need. I am content with the setup I have, so I am not concerned with changing it and hence, do not need to be notified about new features.

![image](https://user-images.githubusercontent.com/51249734/109405146-a8a58180-79c1-11eb-9c64-d700887dfed2.png)

**Describe the solution you'd like**
An option to disable the number from appearing.

**Describe alternatives you've considered**
Hiding or blocking the FrankerFaceZ icon.

**Comment by SirStendec** [comment]
Already exists.

Appearance > Layout >> Top Navigation
[x] Display an indicator on the FFZ Control Center button whenever there are new settings added to FrankerFaceZ.
