### ISSUE TITLE
Emote tab complete behavior: Function of the <Tab> key

### ISSUE THREAD

**Issue by Munzu** [FrankerFaceZ/FrankerFaceZ#999]
**Is your feature request related to a problem? Please describe.**

![image](https://user-images.githubusercontent.com/31477160/109435062-b0dcdb80-7a18-11eb-94c6-fc22ee83d9b2.png)

Currently, when I type e.g. `pepe` and press `<Tab>`, it will only show the suggestion list; I still have to select one of those suggestions with the arrow keys and confirm my selection with a second `<Tab>` or `<Enter>` press. 
This also happens when there's only one possible emote in the suggestions, in which case I have to press `<Tab>` twice:

![image](https://user-images.githubusercontent.com/31477160/109434691-ca7d2380-7a16-11eb-9a2f-dda05d7f40f2.png)

**Describe the solution you'd like**
I'd like the first `<Tab>` press to already fill in the top suggestion, but still show the list of the other suggestions so that I can iterate over them with more `<Tab>` presses. In my opinion, this is faster and more comfortable since I can just iterate over the list with `<Tab>` instead of reaching for the arrow keys and confirm with another `<Tab>`.

**Describe alternatives you've considered**
Since this is basically how BTTV's does it, I could of course just use BTTV for this. However, I really like the suggestion list that FFZ implements. BTTV has no such suggestion list as far as I'm aware.

I hope you can consider implementing this behavior. Thanks in advance for any reply.

**Comment by SirStendec** [comment]
There is an add-on for inline tab completion now. It does not feature the full suggestion list, but does have a tooltip showing you the current item and what position in the list it is. I might add more options for the add-on's tooltip going forward, depending on what people want.

Further discussion of that alternative style of tool-tips should happen in an issue on the https://github.com/FrankerFaceZ/Add-Ons repository.
